Repository Mbed-TLS/mbedtls, pull requests merged in 2018-10, with the labels that each got.

#1990 Disable interop tests without a working OpenSSL version
  tests/ssl-opt.sh
Labels: bug, component: TLS, mbed TLS team, ready for merge

#1806 Adds a filter to run-test-suites.pl to exclude source code and data files
  tests/scripts/run-test-suites.pl
Labels: enhancement, mbed TLS team, ready for merge

#2037 Backport 2.7: Adds a filter to run-test-suites.pl to exclude source code and data files
  tests/scripts/run-test-suites.pl
Labels: enhancement, mbed TLS team, ready for merge

#1618 Improve bignum speed on ARM with DSP instructions
  include/mbedtls/bn_mul.h
Labels: CLA valid, component: Crypto, enhancement, ready for merge

#2107 Add missing return value check in ECDSA test suite
  tests/suites/test_suite_ecdsa.function
Labels: bug, component: TLS, mbed TLS team, ready for merge

#2109 Backport 2.7: Add missing return value check in ECDSA test suite
  tests/suites/test_suite_ecdsa.function
Labels: bug, component: TLS, mbed TLS team, ready for merge
