Repository Mbed-TLS/mbedtls, pull requests merged in 2018-06, with the labels that each got.

#1402 Redundant declaration of mbedtls_ssl_list_ciphersuites
  ChangeLog
  include/mbedtls/ssl.h
Labels: Arm Contribution, bug, ready for merge

#1654 Fix MicroBlaze register typo.
  include/mbedtls/bn_mul.h
Labels: CLA valid, bug, component: Crypto, ready for merge

#1404 Backport 2.7: Redundant declaration of mbedtls_ssl_list_ciphersuites
  ChangeLog
  include/mbedtls/ssl.h
Labels: Arm Contribution, bug, ready for merge

#1403 Backport 2.1: Redundant declaration of mbedtls_ssl_list_ciphersuites
  ChangeLog
  include/mbedtls/ssl.h
Labels: Arm Contribution, bug, ready for merge

#1683 Fix file permissions for ssl.h
  include/mbedtls/ssl.h
Labels: bug, component: TLS, mbed TLS team, needs review

#1693 Add a disabled CMAC define in the no-entropy configuration
  configs/config-no-entropy.h
Labels: enhancement, mbed TLS team, needs design approval, ready for merge

#1699 Fix out-of-tree testing symlinks on Windows
  CMakeLists.txt
Labels: approved for design, component: Platform, mbed TLS team, ready for merge

#795 check matching issuer crt and key for all algs
  programs/x509/cert_write.c
Labels: approved for design, bug, mbed TLS team, ready for merge

#1646 Treat warnings as errors for IAR
  CMakeLists.txt
  include/mbedtls/ssl_internal.h
  library/asn1write.c
  library/pkcs5.c
Labels: approved for design, bug, component: Platform, mbed TLS team, ready for merge

#1668 Correct and clarify the documentation of GCM whole-message functions
  include/mbedtls/gcm.h
Labels: bug, component: Crypto, mbed TLS team, ready for merge

#1692 Fix coverity defects
  programs/test/zeroize.c
Labels: approved for design, bug, component: Crypto, mbed TLS team, ready for merge

#1655 Backport 2.7: Treat warnings as errors for IAR
  CMakeLists.txt
  include/mbedtls/ssl_internal.h
  library/asn1write.c
  library/pkcs5.c
Labels: bug, component: Platform, mbed TLS team, ready for merge

#1670 Backport 2.7: Correct and clarify the documentation of GCM whole-message functions
  include/mbedtls/gcm.h
Labels: bug, component: Crypto, mbed TLS team, ready for merge

#1709 Fix multiple issues in the source code of mbedtls-2.7 found by check-files.py
  ChangeLog
  Makefile
  include/mbedtls/ecp_internal.h
  include/mbedtls/ssl.h
  include/mbedtls/ssl_ciphersuites.h
  library/asn1write.c
  library/ecjpake.c
  library/net_sockets.c
  library/ssl_cli.c
  library/ssl_srv.c
  library/ssl_tls.c
  programs/ssl/ssl_client1.c
  programs/ssl/ssl_mail_client.c
  programs/ssl/ssl_server.c
  tests/compat.sh
  tests/scripts/gen_ctr_drbg.pl
  tests/scripts/gen_pkcs1_v21_sign_verify.pl
  tests/suites/test_suite_gcm.function
  tests/suites/test_suite_mpi.data
  tests/suites/test_suite_pkcs1_v15.data
  tests/suites/test_suite_ssl.function
  yotta/data/example-authcrypt/README.md
  yotta/data/example-benchmark/README.md
  yotta/data/example-hashing/README.md
  yotta/data/example-selftest/README.md
Labels: approved for design, bug, component: Crypto, component: Platform, component: TLS, component: X.509, mbed TLS team, ready for merge

#1671 Backport 2.1: Correct and clarify the documentation of GCM whole-message functions
  include/mbedtls/gcm.h
Labels: bug, component: Crypto, mbed TLS team, ready for merge

#1075 Suport clang version 3.8
  CMakeLists.txt
Labels: approved for design, bug, mbed TLS team, ready for merge

#1182 Fix braces in mbedtls_memory_buffer_alloc_status()
  ChangeLog
  library/memory_buffer_alloc.c
Labels: approved for design, bug, component: Platform, mbed TLS team, ready for merge

#1555 Only redefine _WIN32_WINNT macro when < 0x0501
  library/net_sockets.c
Labels: CLA valid, approved for design, bug, component: Platform, ready for merge

#1672 Fix MSan build without MBEDTLS_TIMING_C
  library/entropy_poll.c
Labels: approved for design, bug, component: Platform, mbed TLS team, ready for merge

#1730 Fix missing preprocessor condition in AES self-test
  library/aes.c
Labels: bug, component: Crypto, mbed TLS team, ready for merge

#1581 Backport 2.7: Fix braces in mbedtls_memory_buffer_alloc_status()
  ChangeLog
  library/memory_buffer_alloc.c
Labels: approved for design, bug, component: Platform, mbed TLS team, ready for merge

#1647 Backport 2.7: Suport clang version 3.8
  CMakeLists.txt
Labels: approved for design, bug, component: Platform, mbed TLS team, ready for merge

#1664 Backport 2.7: Add SNI with DTLS tests to ssl-opt.sh script
  tests/ssl-opt.sh
Labels: enhancement, mbed TLS team, ready for merge

#1728 Backport 2.7: Compilation warning fix on 32-bit platform with IAR
  ChangeLog
  library/ssl_srv.c
Labels: approved for design, bug, component: TLS, mbed TLS team, ready for merge

#710 Add SNI with DTLS tests to ssl-opt.sh script
  tests/ssl-opt.sh
Labels: component: TLS, enhancement, mbed TLS team, ready for merge

#1681 Convert mbedtls_free and mbedtls_calloc into functions
  include/mbedtls/platform.h
  library/platform.c
Labels: Arm Contribution, approved for design, component: Platform, enhancement, ready for merge

#1727 Compilation warning fix on 32-bit platform with IAR
  ChangeLog
  library/ssl_srv.c
Labels: approved for design, bug, component: TLS, mbed TLS team, ready for merge

#1735 Revert "Turn on MBEDTLS_SSL_ASYNC_PRIVATE by default"
  include/mbedtls/config.h
  tests/scripts/all.sh
Labels: component: TLS, mbed TLS team, ready for merge

#1736 Fix for undeclared len variable used in AES-XTS self-test
  library/aes.c
Labels: bug, component: Crypto, mbed TLS team, ready for merge

#1648 Backport 2.1: Support clang version 3.8
  CMakeLists.txt
Labels: approved for design, bug, component: Platform, mbed TLS team, ready for merge

#1665 Backport 2.1: Add SNI with DTLS tests to ssl-opt.sh script
  tests/ssl-opt.sh
Labels: enhancement, mbed TLS team, ready for merge

#1673 Backport 2.1: Fix MSan build without MBEDTLS_TIMING_C
  library/entropy_poll.c
Labels: approved for design, bug, component: Platform, mbed TLS team, ready for merge

#1533 Use "#!/usr/bin/env perl" as shebang line.
  ChangeLog
  scripts/config.pl
  scripts/generate_errors.pl
  scripts/generate_features.pl
  scripts/generate_visualc_files.pl
  scripts/massif_max.pl
  scripts/rename.pl
  tests/scripts/check-doxy-blocks.pl
  tests/scripts/curves.pl
  tests/scripts/depends-hashes.pl
  tests/scripts/depends-pkalgs.pl
  tests/scripts/gen_ctr_drbg.pl
  tests/scripts/gen_gcm_decrypt.pl
  tests/scripts/gen_gcm_encrypt.pl
  tests/scripts/gen_pkcs1_v21_sign_verify.pl
  tests/scripts/key-exchanges.pl
  tests/scripts/list-enum-consts.pl
  tests/scripts/recursion.pl
  tests/scripts/run-test-suites.pl
  tests/scripts/test-ref-configs.pl
Labels: CLA valid, bug, ready for merge

#1557 Backport 2.7: Use "#!/usr/bin/env perl" as shebang line.
  ChangeLog
  scripts/config.pl
  scripts/generate_errors.pl
  scripts/generate_features.pl
  scripts/generate_visualc_files.pl
  scripts/massif_max.pl
  scripts/rename.pl
  tests/scripts/check-doxy-blocks.pl
  tests/scripts/curves.pl
  tests/scripts/depends-hashes.pl
  tests/scripts/depends-pkalgs.pl
  tests/scripts/gen_ctr_drbg.pl
  tests/scripts/gen_gcm_decrypt.pl
  tests/scripts/gen_gcm_encrypt.pl
  tests/scripts/gen_pkcs1_v21_sign_verify.pl
  tests/scripts/key-exchanges.pl
  tests/scripts/list-enum-consts.pl
  tests/scripts/recursion.pl
  tests/scripts/run-test-suites.pl
  tests/scripts/test-ref-configs.pl
Labels: CLA valid, bug, component: Platform, ready for merge

#1391 2.1 only: all.sh: add test with MBEDTLS_DEPRECATED_REMOVED
  tests/scripts/all.sh
Labels: enhancement, mbed TLS team, ready for merge

#1558 Backport 2.1: Use "#!/usr/bin/env perl" as shebang line.
  ChangeLog
  scripts/config.pl
  scripts/generate_errors.pl
  scripts/generate_features.pl
  scripts/generate_visualc_files.pl
  scripts/massif_max.pl
  scripts/rename.pl
  tests/scripts/check-doxy-blocks.pl
  tests/scripts/curves.pl
  tests/scripts/depends-hashes.pl
  tests/scripts/depends-pkalgs.pl
  tests/scripts/gen_ctr_drbg.pl
  tests/scripts/gen_gcm_decrypt.pl
  tests/scripts/gen_gcm_encrypt.pl
  tests/scripts/gen_pkcs1_v21_sign_verify.pl
  tests/scripts/key-exchanges.pl
  tests/scripts/list-enum-consts.pl
  tests/scripts/recursion.pl
  tests/scripts/run-test-suites.pl
  tests/scripts/test-ref-configs.pl
Labels: CLA valid, bug, component: Platform, ready for merge

#1258 remove additional zero byte when writing pub der
  programs/pkey/key_app_writer.c
Labels: bug, component: X.509, mbed TLS team, ready for merge

#1621 Fix memory leak in mbedtls_x509_csr_parse
  library/x509_csr.c
Labels: CLA valid, approved for design, bug, component: X.509, ready for merge

#1794 Backport 2.7: remove additional zero byte when writing pub der
  programs/pkey/key_app_writer.c
Labels: bug, component: X.509, mbed TLS team, ready for merge

#1771 Fix multiple issues in the source code of mbedtls-2.1 found by check-files.py
  ChangeLog
  Makefile
  include/mbedtls/rsa.h
  include/mbedtls/ssl.h
  library/asn1write.c
  library/net.c
  library/ssl_cli.c
  library/ssl_srv.c
  library/ssl_tls.c
  library/x509_crt.c
  library/x509_csr.c
  tests/scripts/gen_ctr_drbg.pl
  tests/scripts/gen_pkcs1_v21_sign_verify.pl
  tests/scripts/run-test-suites.pl
  tests/suites/test_suite_gcm.function
  tests/suites/test_suite_mpi.data
  tests/suites/test_suite_pkcs1_v15.data
  tests/suites/test_suite_ssl.function
  yotta/data/example-authcrypt/README.md
  yotta/data/example-benchmark/README.md
  yotta/data/example-hashing/README.md
  yotta/data/example-selftest/README.md
  yotta/data/example-tls-client/README.md
Labels: bug, component: Crypto, component: Platform, component: TLS, component: X.509, mbed TLS team, ready for merge

#1795 Backport 2.1: remove additional zero byte when writing pub der
  programs/pkey/key_app_writer.c
Labels: bug, component: X.509, mbed TLS team, ready for merge

#1801 Backport2.1: update forum link
  README.md
Labels: bug, mbed TLS team, ready for merge
