Repository Mbed-TLS/mbedtls, pull requests merged in 2018-12, with the labels that each got.

#2208 Change ecdsa hash buf size to a valid hash length
  tests/suites/test_suite_ecdsa.function
Labels: bug, component: Crypto, mbed TLS team, ready for merge

#2223 check-files: Don't check same-named files
  tests/scripts/check-files.py
Labels: component: Platform, mbed TLS team, ready for merge

#1721 Clear pk context and other minor changes in *_free() procedures
  library/dhm.c
  library/pem.c
  library/pk.c
  library/rsa.c
Labels: CLA valid, bug, component: Crypto, ready for merge

#2126 Clarify documentation of MBEDTLS_SSL_{MAX/IN/OUT}_CONTENT_LEN
  include/mbedtls/config.h
Labels: bug, component: TLS, mbed TLS team, ready for merge

#2134 Clarify documentation of ssl_set_own_cert()
  ChangeLog
  include/mbedtls/ssl.h
Labels: bug, component: TLS, mbed TLS team, ready for merge

#2171 Add ARIA and ChachaPoly to basic-build-test
  tests/scripts/basic-build-test.sh
Labels: bug, component: Platform, mbed TLS team, ready for merge

#2209 PSA: support: Disable test that trigger bug in old GnuTLS
  tests/ssl-opt.sh
Labels: bug, component: TLS, mbed TLS team, ready for merge

#2145 Backport 2.1: Clarify documentation of ssl_set_own_cert()
  ChangeLog
  include/mbedtls/ssl.h
Labels: bug, component: TLS, mbed TLS team, ready for merge

#2144 Backport 2.7: Clarify documentation of ssl_set_own_cert()
  ChangeLog
  include/mbedtls/ssl.h
Labels: bug, component: TLS, mbed TLS team, ready for merge
