Repository Mbed-TLS/mbedtls, pull requests merged in 2018-04, with the labels that each got.

#1541 Backport 2.7: Improve documentation of mbedtls_ssl_write()
  ChangeLog
  include/mbedtls/ssl.h
Labels: CLA valid, mbed TLS team, ready for merge

#1542 Backport 2.1: Improve documentation of mbedtls_ssl_write()
  ChangeLog
  include/mbedtls/ssl.h
Labels: CLA valid, mbed TLS team, ready for merge

#1539 Improve documentation of mbedtls_ssl_write()
  ChangeLog
  include/mbedtls/ssl.h
Labels: CLA valid, mbed TLS team, ready for merge

#348 Support for Curve448
  include/mbedtls/config.h
  include/mbedtls/ecp.h
  library/ecp.c
  library/ecp_curves.c
  library/version_features.c
  programs/test/benchmark.c
  tests/suites/test_suite_ecp.data
Labels: CLA valid, approved for design, enhancement, ready for merge, runCI

#1458 Backport 2.7: Add clarity to use of the rsa_internal.h interface
  include/mbedtls/rsa_internal.h
Labels: mbed TLS team, ready for merge

#1552 Backport 2.7: Enable SSL test scripts to dump logs on stdout #1535
  tests/compat.sh
  tests/ssl-opt.sh
Labels: enhancement, mbed TLS team, ready for merge

#1457 Add clarity to use of the rsa_internal.h interface
  include/mbedtls/rsa_internal.h
Labels: mbed TLS team, ready for merge

#1553 Backport 2.1: Enable SSL test scripts to dump logs on stdout #1535
  tests/compat.sh
  tests/ssl-opt.sh
Labels: enhancement, mbed TLS team, ready for merge

#1554 Backport 2.1: Fix for returning correct error code
  ChangeLog
  programs/pkey/pk_sign.c
Labels: CLA valid, bug, mbed TLS team, ready for merge

#1535 Enable SSL test scripts to dump logs on stdout
  tests/compat.sh
  tests/ssl-opt.sh
Labels: enhancement, mbed TLS team, ready for merge

#1559 Make the memset call prior to FD_ZERO conditional to needing it
  library/net_sockets.c
Labels: approved for design, enhancement, mbed TLS team, ready for merge

#1560 Warn if using a memory sanitizer on AESNI
  library/aesni.c
Labels: approved for design, enhancement, mbed TLS team, ready for merge

#1234 Doxygen: don't traverse symbolic links
  doxygen/mbedtls.doxyfile
Labels: approved for design, enhancement, mbed TLS team, ready for merge

#1503 Update aes.h
  include/mbedtls/aes.h
Labels: Arm Contribution, enhancement, ready for merge

#1507 Update cmac.h
  include/mbedtls/cmac.h
Labels: Arm Contribution, enhancement, ready for merge

#1508 Update ctr_drbg.h
  include/mbedtls/ctr_drbg.h
Labels: Arm Contribution, enhancement, ready for merge

#1509 Update ecdh.h
  include/mbedtls/ecdh.h
Labels: Arm Contribution, enhancement, ready for merge

#1512 Update md.h
  include/mbedtls/md.h
Labels: Arm Contribution, enhancement, ready for merge

#1513 Update rsa.h
  include/mbedtls/rsa.h
Labels: Arm Contribution, enhancement, ready for merge

#1514 Update sha1.h
  include/mbedtls/sha1.h
Labels: Arm Contribution, enhancement, ready for merge

#1515 Update sha256.h
  include/mbedtls/sha256.h
Labels: Arm Contribution, enhancement, ready for merge

#1516 Update sha512.h
  include/mbedtls/sha512.h
Labels: Arm Contribution, enhancement, ready for merge

#1518 Update platform.h
  include/mbedtls/platform.h
Labels: Arm Contribution, enhancement, ready for merge

#1577 Backport 2.1: Doxygen: don't traverse symbolic links
  doxygen/mbedtls.doxyfile
Labels: enhancement, mbed TLS team, ready for merge

#1505 Update ccm.h
  include/mbedtls/ccm.h
Labels: Arm Contribution, enhancement, ready for merge

#1506 Update cipher.h
  include/mbedtls/cipher.h
Labels: Arm Contribution, enhancement, ready for merge

#1510 Update ecdsa.h
  include/mbedtls/ecdsa.h
Labels: Arm Contribution, enhancement, ready for merge

#1511 Update gcm.h
  include/mbedtls/gcm.h
Labels: Arm Contribution, enhancement, ready for merge

#1580 Update dhm.h
  include/mbedtls/dhm.h
Labels: Arm Contribution, enhancement, ready for merge
