Repository Mbed-TLS/mbedtls, pull requests merged in 2018-07, with the labels that each got.

#1567 library: Port to Haiku.
  library/CMakeLists.txt
  library/entropy_poll.c
  library/net_sockets.c
  library/timing.c
Labels: CLA valid, approved for design, component: Platform, enhancement, ready for merge

#1788 Enable ARIA self test in the unit testing
  tests/suites/test_suite_aria.data
Labels: approved for design, component: Crypto, mbed TLS team, ready for merge

#1821 Fix ssl-opt.sh not starting when lsof is not available
  tests/ssl-opt.sh
Labels: approved for design, bug, mbed TLS team, ready for merge

#1822 Backport 2.7: Fix ssl-opt.sh not starting when lsof is not available
  tests/ssl-opt.sh
Labels: approved for design, bug, mbed TLS team, ready for merge

#1663 Fixes different off by ones
  ChangeLog
  library/ssl_cli.c
  library/ssl_srv.c
  library/ssl_tls.c
Labels: CLA valid, bug, component: TLS, ready for merge

#1836 tests: dhm: Rename Hallman to Hellman
  tests/suites/test_suite_dhm.data
Labels: component: Crypto, mbed TLS team, ready for merge

#1838 Backport 2.7: tests: dhm: Rename Hallman to Hellman
  tests/suites/test_suite_dhm.data
Labels: component: Crypto, mbed TLS team, ready for merge

#1847 Backport 2.7: Fixes different off by ones
  ChangeLog
  library/ssl_cli.c
  library/ssl_srv.c
  library/ssl_tls.c
Labels: CLA valid, bug, component: TLS, ready for merge

#1837 Backport 2.1: tests: dhm: Rename Hallman to Hellman
  tests/suites/test_suite_dhm.data
Labels: component: Crypto, mbed TLS team, ready for merge

#1846 Backport 2.1: Fixes different off by ones
  ChangeLog
  library/ssl_cli.c
  library/ssl_srv.c
  library/ssl_tls.c
Labels: CLA valid, bug, component: TLS, ready for merge

#779 Fix all.sh check_tools function to handle paths
  tests/scripts/all.sh
Labels: bug, mbed TLS team, ready for merge

#919 Show error message only if there was an error
  programs/pkey/key_app.c
Labels: bug, component: Crypto, mbed TLS team, ready for merge

#1724 Reliably detect GDB script failures in all.sh for zeroize test.
  tests/scripts/all.sh
Labels: bug, component: Platform, mbed TLS team, ready for merge, runCI

#1832 Update the CONTRIBUTING.md file for LTS branches
  CONTRIBUTING.md
  README.md
Labels: bug, mbed TLS team, ready for merge

#1868 Add to the networking module header a definition of the purpose and use of the module
  include/mbedtls/net_sockets.h
Labels: component: Platform, enhancement, mbed TLS team, ready for merge

#1871 all.sh: Return error on keep-going failure
  tests/scripts/all.sh
Labels: bug, component: Platform, mbed TLS team, ready for merge

#1875 Increase the memory buffer size for ssl_server2.c
  programs/ssl/ssl_server2.c
Labels: CLA not applicable, approved for design, bug, component: TLS, ready for merge

#1800 Backport2.7: Show error message only if there was an error
  programs/pkey/key_app.c
Labels: approved for design, bug, component: Crypto, mbed TLS team, ready for merge

#1877 Backport 2.7: all.sh: Return error on keep-going failure
  tests/scripts/all.sh
Labels: approved for design, bug, component: Platform, mbed TLS team, ready for merge

#1799 Backport2.1: Show error message only if there was an error
  programs/pkey/key_app.c
Labels: bug, component: Crypto, mbed TLS team, ready for merge

#1876 Backport 2.1: all.sh: Return error on keep-going failure
  tests/scripts/all.sh
Labels: approved for design, bug, component: Platform, mbed TLS team, ready for merge

#1893 Backport 2.7: Fix RC4 dependencies
  tests/suites/test_suite_pkparse.data
Labels: bug, component: Crypto, mbed TLS team, ready for merge

#1894 Backport 2.1: Fix RC4 dependencies
  tests/suites/test_suite_pkparse.data
Labels: bug, component: Crypto, mbed TLS team, ready for merge
