Repository Mbed-TLS/mbedtls, pull requests merged in 2018-08, with the labels that each got.

#1598 enforce input and output of ccm selftest on stack
  library/ccm.c
Labels: approved for design, bug, component: Crypto, mbed TLS team, ready for merge

#1816 Use preserve mode to copy headers.
  Makefile
Labels: CLA valid, component: Platform, enhancement, ready for merge

#1834 Fix memory leak in ecp_mul_comb() if ecp_precompute_comb() fails
  ChangeLog
  library/ecp.c
Labels: CLA valid, bug, component: Crypto, ready for merge

#1861 Allow to forward declare of mbedtls_blowfish_context #1215
  include/mbedtls/aes.h
  include/mbedtls/arc4.h
  include/mbedtls/aria.h
  include/mbedtls/bignum.h
  include/mbedtls/blowfish.h
  include/mbedtls/camellia.h
  include/mbedtls/ccm.h
  include/mbedtls/chacha20.h
  include/mbedtls/chachapoly.h
  include/mbedtls/cipher.h
  include/mbedtls/ctr_drbg.h
  include/mbedtls/des.h
  include/mbedtls/dhm.h
  include/mbedtls/ecdh.h
  include/mbedtls/ecjpake.h
  include/mbedtls/ecp.h
  include/mbedtls/entropy.h
  include/mbedtls/gcm.h
  include/mbedtls/havege.h
  include/mbedtls/hmac_drbg.h
  include/mbedtls/md.h
  include/mbedtls/md2.h
  include/mbedtls/md4.h
  include/mbedtls/md5.h
  include/mbedtls/net_sockets.h
  include/mbedtls/oid.h
  include/mbedtls/pem.h
  include/mbedtls/pk.h
  include/mbedtls/pkcs11.h
  include/mbedtls/platform.h
  include/mbedtls/poly1305.h
  include/mbedtls/ripemd160.h
  include/mbedtls/rsa.h
  include/mbedtls/sha1.h
  include/mbedtls/sha256.h
  include/mbedtls/sha512.h
  include/mbedtls/ssl_cookie.h
  include/mbedtls/ssl_ticket.h
  include/mbedtls/threading.h
  include/mbedtls/timing.h
  include/mbedtls/x509_crt.h
  include/mbedtls/xtea.h
Labels: CLA valid, component: Crypto, enhancement, ready for merge

#1887 Backport 2.1: Fix memory leak in ecp_mul_comb() if ecp_precompute_comb() fails
  ChangeLog
  library/ecp.c
Labels: CLA valid, bug, component: Crypto, ready for merge

#1886 Backport 2.7: Fix memory leak in ecp_mul_comb() if ecp_precompute_comb() fails
  ChangeLog
  library/ecp.c
Labels: CLA valid, bug, component: Crypto, ready for merge

#1900 Backport 2.7: enforce input and output of ccm selftest on stack
  library/ccm.c
Labels: bug, component: Crypto, mbed TLS team, ready for merge

#1932 Fix Wformat-overflow warning in ssl_mail_client.c
  programs/ssl/ssl_mail_client.c
Labels: component: TLS, mbed TLS team, ready for merge

#1938 Use mbedtls_printf instead of printf
  ChangeLog
  library/aria.c
Labels: bug, component: Crypto, mbed TLS team, ready for merge

#1952 Backport 2.1: Fix Wformat-overflow warning in ssl_mail_client.c
  programs/ssl/ssl_mail_client.c
Labels: ready for merge

#1953 Backport 2.7: Fix Wformat-overflow warning in ssl_mail_client.c
  programs/ssl/ssl_mail_client.c
Labels: ready for merge

#1625 Fix undefined shift in x509_profile_check_pk_alg
  ChangeLog
  library/ssl_cli.c
  library/x509_crt.c
Labels: CLA valid, bug, component: X.509, ready for merge

#1965 Remove redundant `else` statement
  ChangeLog
  library/ecp.c
Labels: bug, component: Crypto, mbed TLS team, ready for merge

#1967 ssl-opt.sh: Preserve proxy log if --preserve-logs is specified
  tests/ssl-opt.sh
Labels: bug, component: TLS, mbed TLS team, ready for merge

#1979 Fix typos in programs/x509/cert_write.c
  programs/x509/cert_write.c
Labels: component: TLS, enhancement, mbed TLS team, ready for merge

#1888 Backport 2.7: Fix undefined shift in x509_profile_check_pk_alg
  ChangeLog
  library/ssl_cli.c
  library/x509_crt.c
Labels: CLA valid, bug, component: X.509, ready for merge

#1974 Backport 2.7: ssl-opt.sh: Preserve proxy log if --preserve-logs is specified
  tests/ssl-opt.sh
Labels: bug, component: TLS, mbed TLS team, ready for merge

#1981 Backport 2.7: Fix typos in programs/x509/cert_write.c
  programs/x509/cert_write.c
Labels: component: TLS, enhancement, mbed TLS team, ready for merge

#1889 Backport 2.1: Fix undefined shift in x509_profile_check_pk_alg
  ChangeLog
  library/ssl_cli.c
  library/x509_crt.c
Labels: CLA valid, bug, component: X.509, ready for merge

#1980 Backport 2.1: Fix typos in programs/x509/cert_write.c
  programs/x509/cert_write.c
Labels: component: TLS, enhancement, mbed TLS team, ready for merge
