Repository Mbed-TLS/mbedtls, pull requests merged in 2018-03, with the labels that each got.

#953 Backport 2.1: Set correct minimal versions in default conf
  ChangeLog
  include/mbedtls/ssl_internal.h
  library/ssl_tls.c
Labels: bug, mbed TLS team, ready for merge

#1250 Backport 2.1: all.sh --keep-going: work if TERM is unset
  tests/scripts/all.sh
Labels: bug, mbed TLS team, ready for merge

#1297 Backport 2.1: Fix typo and bracketing in macro args
  library/net.c
Labels: bug, mbed TLS team, ready for merge

#1409 Backport 2.1: Test suite test_suite_pk test pk_rsa_overflow passes valid parameters
  ChangeLog
  tests/suites/test_suite_pk.function
Labels: Arm Contribution, bug, ready for merge

#1408 Backport 2.7: Test suite test_suite_pk test pk_rsa_overflow passes valid parameters
  ChangeLog
  tests/suites/test_suite_pk.function
Labels: Arm Contribution, bug, ready for merge

#1012 Fix typo and bracketing in macro args
  library/net_sockets.c
Labels: bug, mbed TLS team, ready for merge

#1249 all.sh --keep-going: work if TERM is unset
  tests/scripts/all.sh
Labels: bug, mbed TLS team, ready for merge

#1407 Test suite test_suite_pk test pk_rsa_overflow passes valid parameters
  ChangeLog
  tests/suites/test_suite_pk.function
Labels: Arm Contribution, bug, ready for merge

#679 Fix missing void argument declarations #678
  library/memory_buffer_alloc.c
  library/version.c
Labels: CLA valid, approved for design, enhancement, ready for merge

#922 Remove Yotta module from footprint.sh script
  scripts/footprint.sh
Labels: bug, mbed TLS team, ready for merge

#1241 Improve cmake usage notes in Readme
  README.md
Labels: enhancement, mbed TLS team, ready for merge

#1431 Backport 2.1: Improve cmake usage notes in Readme
  README.md
Labels: enhancement, mbed TLS team, needs review, ready for merge

#1423 Deprecate support for record compression
  include/mbedtls/check_config.h
  include/mbedtls/config.h
  include/mbedtls/ssl.h
Labels: approved for design, enhancement, mbed TLS team, ready for merge

#1448 Add missing MBEDTLS_DEPRECATED_REMOVED guards
  ChangeLog
  library/aes.c
Labels: bug, mbed TLS team, ready for merge

#403 Remove redundant i increments
  library/bignum.c
Labels: CLA valid, enhancement, ready for merge

#726 Workaround for GCC Bug
  library/cmac.c
Labels: CLA valid, bug, ready for merge

#1442 Add a missing bracket in ifdef for __cplusplus - 2.7
  include/mbedtls/rsa_internal.h
Labels: bug, mbed TLS team, ready for merge

#1073 Use current source paths for config file creation command
  CMakeLists.txt
Labels: CLA valid, approved for design, enhancement, ready for merge

#1256 corrected a typo in a comment
  library/ssl_cli.c
Labels: CLA valid, bug, ready for merge

#1406 fix typo in pem.c
  library/pem.c
Labels: CLA valid, bug, ready for merge

#1441 Add a missing bracket in ifdef for __cplusplus
  include/mbedtls/rsa_internal.h
Labels: bug, mbed TLS team, ready for merge

#572 Added checking for QNX operating system to make mbedtls build on QNX
  library/entropy_poll.c
  library/net.c
  library/timing.c
Labels: CLA valid, enhancement, ready for merge

#1134 Change generate_errors.pl to call perl grep
  scripts/generate_errors.pl
Labels: approved for design, bug, mbed TLS team, ready for merge

#1379 Fix parsing of PKCS#8 encoded Elliptic Curve keys.
  ChangeLog
  library/pkparse.c
  tests/data_files/Makefile
  tests/data_files/ec_prv.pk8nopub.der
  tests/data_files/ec_prv.pk8nopub.pem
  tests/data_files/ec_prv.pk8nopubparam.der
  tests/data_files/ec_prv.pk8nopubparam.pem
  tests/data_files/ec_prv.pk8param.der
  tests/data_files/ec_prv.pk8param.pem
  tests/suites/test_suite_pkparse.data
Labels: CLA valid, approved for design, bug, ready for merge

#1493 Backport 2.1: Change generate_errors.pl to call perl grep
  scripts/generate_errors.pl
Labels: bug, mbed TLS team, ready for merge

#1494 Backport 2.1: Fix parsing of PKCS#8 encoded Elliptic Curve keys.
  ChangeLog
  library/pkparse.c
  tests/data_files/Makefile
  tests/data_files/ec_prv.pk8nopub.der
  tests/data_files/ec_prv.pk8nopub.pem
  tests/data_files/ec_prv.pk8nopubparam.der
  tests/data_files/ec_prv.pk8nopubparam.pem
  tests/data_files/ec_prv.pk8param.der
  tests/data_files/ec_prv.pk8param.pem
  tests/suites/test_suite_pkparse.data
Labels: CLA valid, bug, ready for merge

#1529 Backport 2.7: Fix parsing of PKCS#8 encoded Elliptic Curve keys.
  ChangeLog
  library/pkparse.c
  tests/data_files/Makefile
  tests/data_files/ec_prv.pk8nopub.der
  tests/data_files/ec_prv.pk8nopub.pem
  tests/data_files/ec_prv.pk8nopubparam.der
  tests/data_files/ec_prv.pk8nopubparam.pem
  tests/data_files/ec_prv.pk8param.der
  tests/data_files/ec_prv.pk8param.pem
  tests/suites/test_suite_pkparse.data
Labels: CLA valid, bug, mbed TLS team, ready for merge
