Repository Mbed-TLS/mbedtls, pull requests merged in 2019-08, with the labels that each got.

#2760 Change worktree_rev to HEAD for rev-parse
  scripts/abi_check.py
Labels: component: Platform, mbed TLS team, ready for merge

#2761 Backport 2.16: Change worktree_rev to HEAD for rev-parse
  scripts/abi_check.py
Labels: component: Platform, mbed TLS team, ready for merge

#2762 Backport 2.7: Change worktree_rev to HEAD for rev-parse
  scripts/abi_check.py
Labels: component: Platform, mbed TLS team, ready for merge

#2734 Add TEST_ASSUME macro to allow skipping tests at runtime
  tests/suites/helpers.function
  tests/suites/host_test.function
  tests/suites/main_test.function
Labels: enhancement, mbed TLS team, ready for merge

#2735 2.16: Add TEST_ASSUME macro to allow skipping tests at runtime
  tests/suites/helpers.function
  tests/suites/host_test.function
  tests/suites/main_test.function
Labels: enhancement, mbed TLS team, ready for merge

#2417 Update soon to be expired crl
  library/certs.c
  programs/x509/cert_write.c
  tests/data_files/Makefile
  tests/data_files/cert_example_multi.crt
  tests/data_files/cert_example_wildcard.crt
  tests/data_files/cert_sha1.crt
  tests/data_files/cert_sha224.crt
  tests/data_files/cert_sha256.crt
  tests/data_files/cert_sha384.crt
  tests/data_files/cert_sha512.crt
  tests/data_files/cli-rsa-sha1.crt
  tests/data_files/cli-rsa-sha256.crt
  tests/data_files/cli-rsa-sha256.crt.der
  tests/data_files/cli2.crt
  tests/data_files/cli2.crt.der
  tests/data_files/crl.pem
  tests/data_files/crl_cat_ecfut-rsa.pem
  tests/data_files/enco-ca-prstr.pem
  tests/data_files/enco-cert-utf8str.pem
  tests/data_files/rsa_pkcs1_1024_clear.pem
  tests/data_files/server1.cert_type.crt
  tests/data_files/server1.cert_type_noauthid.crt
  tests/data_files/server1.crt
  tests/data_files/server1.crt.der
  tests/data_files/server1.key_usage.crt
  tests/data_files/server1.key_usage_noauthid.crt
  tests/data_files/server1.noauthid.crt
  tests/data_files/server1.v1.crt
  tests/data_files/server1_ca.crt
  tests/data_files/server2-badsign.crt
  tests/data_files/server2-sha256.crt
  tests/data_files/server2-sha256.crt.der
  tests/data_files/server2.crt
  tests/data_files/server2.crt.der
  tests/data_files/server5-ss-forgeca.crt
  tests/data_files/test-ca-alt-good.crt
  tests/data_files/test-ca-alt.crt
  tests/data_files/test-ca-alt.csr
  tests/data_files/test-ca-alt.key
  tests/data_files/test-ca-good-alt.crt
  tests/data_files/test-ca-sha1.crt
  tests/data_files/test-ca-sha1.crt.der
  tests/data_files/test-ca-sha256.crt
  tests/data_files/test-ca-sha256.crt.der
  tests/data_files/test-ca.crt
  tests/data_files/test-ca.crt.der
  tests/data_files/test-ca.opensslconf
  tests/data_files/test-ca.server1.db
  tests/data_files/test-ca2.crt
  tests/data_files/test-ca2.crt.der
  tests/data_files/test-ca_cat12.crt
  tests/data_files/test-ca_cat21.crt
  tests/data_files/test-ca_printable.crt
  tests/data_files/test-ca_uppercase.crt
  tests/data_files/test-ca_utf8.crt
  tests/suites/test_suite_debug.data
  tests/suites/test_suite_x509parse.data
  tests/suites/test_suite_x509write.data
Labels: bug, component: X.509, mbed TLS team, ready for merge

#2418 Backport 2.7: Update soon to be expired crl
  library/certs.c
  tests/data_files/Makefile
  tests/data_files/cert_example_multi.crt
  tests/data_files/cert_example_wildcard.crt
  tests/data_files/cert_md5.crt
  tests/data_files/cert_sha1.crt
  tests/data_files/cert_sha224.crt
  tests/data_files/cert_sha256.crt
  tests/data_files/cert_sha384.crt
  tests/data_files/cert_sha512.crt
  tests/data_files/cli-rsa-sha1.crt
  tests/data_files/cli-rsa-sha256.crt
  tests/data_files/crl.pem
  tests/data_files/crl_cat_ecfut-rsa.pem
  tests/data_files/enco-ca-prstr.pem
  tests/data_files/enco-cert-utf8str.pem
  tests/data_files/rsa_pkcs1_1024_clear.pem
  tests/data_files/server1.cert_type.crt
  tests/data_files/server1.cert_type_noauthid.crt
  tests/data_files/server1.crt
  tests/data_files/server1.key_usage.crt
  tests/data_files/server1.key_usage_noauthid.crt
  tests/data_files/server1.noauthid.crt
  tests/data_files/server1.v1.crt
  tests/data_files/server1_ca.crt
  tests/data_files/server2-badsign.crt
  tests/data_files/server2-sha256.crt
  tests/data_files/server2.crt
  tests/data_files/server5-ss-forgeca.crt
  tests/data_files/test-ca-alt-good.crt
  tests/data_files/test-ca-alt.crt
  tests/data_files/test-ca-alt.csr
  tests/data_files/test-ca-alt.key
  tests/data_files/test-ca-good-alt.crt
  tests/data_files/test-ca-sha1.crt
  tests/data_files/test-ca-sha256.crt
  tests/data_files/test-ca.crt
  tests/data_files/test-ca.server1.db
  tests/data_files/test-ca_cat12.crt
  tests/data_files/test-ca_cat21.crt
  tests/data_files/test-ca_printable.crt
  tests/data_files/test-ca_uppercase.crt
  tests/data_files/test-ca_utf8.crt
  tests/suites/test_suite_debug.data
  tests/suites/test_suite_x509parse.data
  tests/suites/test_suite_x509write.data
Labels: bug, component: X.509, mbed TLS team, ready for merge

#2773 Changelog entry for test certificates update
  ChangeLog
Labels: mbed TLS team, ready for merge

#2774 Backport 2.7: Changelog entry for test certificates update
  ChangeLog
Labels: mbed TLS team, ready for merge

#2775 Backport 2.16: Changelog entry for test certificates update
  ChangeLog
Labels: mbed TLS team, ready for merge

#2779 Don't exclude DTLS1.2 in OpenSSL
  tests/compat.sh
Labels: component: TLS, enhancement, mbed TLS team, ready for merge

#2736 Backport 2.16: Test documented builds
  tests/scripts/all.sh
Labels: component: Platform, enhancement, mbed TLS team, ready for merge

#2786 Backport 2.16: Don't exclude DTLS1.2 in OpenSSL
  tests/compat.sh
Labels: component: TLS, enhancement, mbed TLS team, ready for merge

#2737 Backport 2.7: Test documented builds
  tests/scripts/all.sh
Labels: component: Platform, enhancement, mbed TLS team, ready for merge

#2787 Backport 2.7: Don't exclude DTLS1.2 in OpenSSL
  tests/compat.sh
Labels: component: TLS, enhancement, mbed TLS team, ready for merge

#2807 Update with changes from the mbedtls-2.18 release branch
  ChangeLog
  doxygen/input/doc_mainpage.h
  doxygen/mbedtls.doxyfile
  include/mbedtls/version.h
  library/CMakeLists.txt
  library/Makefile
  tests/suites/test_suite_version.data
Labels: component: Platform, mbed TLS team, needs: ci, needs: review

#2812 Backport 2.7: HMAC DRBG: Split entropy-gathering requests to reduce request sizes
  library/hmac_drbg.c
Labels: bug, mbed TLS team, ready for merge

#2811 Backport 2.16: HMAC DRBG: Split entropy-gathering requests to reduce request sizes
  library/hmac_drbg.c
Labels: bug, mbed TLS team, ready for merge

#2814 Update library version to 2.19.0
  ChangeLog
  doxygen/input/doc_mainpage.h
  doxygen/mbedtls.doxyfile
  include/mbedtls/version.h
  library/CMakeLists.txt
  tests/suites/test_suite_version.data
Labels: enhancement, mbed TLS team, ready for merge
