Repository Mbed-TLS/mbedtls, pull requests merged in 2019-06, with the labels that each got.

#2664 test: Always use `make clean` by itself
  tests/scripts/list-symbols.sh
Labels: bug, component: Platform, mbed TLS team, ready for merge

#2665 Backport 2.7: test: Always use `make clean` by itself
  tests/scripts/list-symbols.sh
Labels: bug, component: Platform, mbed TLS team, ready for merge

#2666 Backport 2.16: test: Always use `make clean` by itself
  tests/scripts/list-symbols.sh
Labels: bug, component: Platform, mbed TLS team, ready for merge

#2654 Create symbolic links only when ENABLE_TESTING is ON
  CMakeLists.txt
  include/CMakeLists.txt
Labels: CLA valid, component: Platform, enhancement, ready for merge

#2658 Backport 2.7: Create symbolic links only when ENABLE_TESTING is ON
  CMakeLists.txt
  include/CMakeLists.txt
Labels: CLA valid, bug, component: Platform, ready for merge

#2657 Backport 2.16: Create symbolic links only when ENABLE_TESTING is ON
  CMakeLists.txt
  include/CMakeLists.txt
Labels: CLA valid, bug, component: Platform, ready for merge

#2674 Backport 2.7: Remove all abi dumps, not just ones shared between versions
  scripts/abi_check.py
Labels: component: Platform, mbed TLS team, ready for merge

#2677 Backport 2.7: abi check show removed symbols
  scripts/abi_check.py
Labels: component: Platform, mbed TLS team, ready for merge

#2696 Backport 2.7: Fix UDP proxy incorrectly dissecting CID-based datagrams into records
  programs/test/udp_proxy.c
Labels: bug, mbed TLS team, ready for merge

#2673 Backport 2.16: Remove all abi dumps, not just ones shared between versions
  scripts/abi_check.py
Labels: component: Platform, mbed TLS team, ready for merge

#2676 Backport 2.16: abi check show removed symbols
  scripts/abi_check.py
Labels: component: Platform, mbed TLS team, ready for merge

#2695 Backport 2.16: Fix UDP proxy incorrectly dissecting CID-based datagrams into records
  programs/test/udp_proxy.c
Labels: bug, mbed TLS team, ready for merge

#2661 Remove all abi dumps, not just ones shared between versions
  scripts/abi_check.py
Labels: component: Platform, mbed TLS team, ready for merge

#2675 Show removed symbols in abi check
  scripts/abi_check.py
Labels: component: Platform, mbed TLS team, ready for merge

#2694 Fix UDP proxy incorrectly dissecting CID-based datagrams into records
  programs/test/udp_proxy.c
Labels: bug, component: TLS, ready for merge

#2686 Update library version to 2.18.0
  ChangeLog
  doxygen/input/doc_mainpage.h
  doxygen/mbedtls.doxyfile
  include/mbedtls/version.h
  library/CMakeLists.txt
  library/Makefile
  tests/suites/test_suite_version.data
Labels: component: Platform, mbed TLS team, needs: review

#2688 Update library version to 2.7.11
  ChangeLog
  doxygen/input/doc_mainpage.h
  doxygen/mbedtls.doxyfile
  include/mbedtls/version.h
  library/CMakeLists.txt
  tests/suites/test_suite_version.data
Labels: component: Platform, mbed TLS team

#2687 Update library to 2.16.2
  ChangeLog
  doxygen/input/doc_mainpage.h
  doxygen/mbedtls.doxyfile
  include/mbedtls/version.h
  library/CMakeLists.txt
  tests/suites/test_suite_version.data
Labels: component: Platform, mbed TLS team

#2451 Backport 2.7: Fix minor typos and spelling mistakes
  ChangeLog
  README.md
  include/mbedtls/check_config.h
  include/mbedtls/config.h
  include/mbedtls/hmac_drbg.h
  include/mbedtls/rsa.h
  include/mbedtls/ssl.h
  include/mbedtls/ssl_ticket.h
  include/mbedtls/x509.h
  include/mbedtls/x509_crl.h
  library/Makefile
  library/ecjpake.c
  library/error.c
  library/ssl_srv.c
  library/ssl_tls.c
  library/x509.c
  tests/compat.sh
  tests/scripts/all.sh
  tests/ssl-opt.sh
  tests/suites/test_suite_ccm.data
  tests/suites/test_suite_ecdh.function
  tests/suites/test_suite_rsa.data
Labels: CLA valid, ready for merge

#2616 [Backport 2.7] Use 'config.pl baremetal' in all.sh
  tests/scripts/all.sh
Labels: component: Platform, enhancement, mbed TLS team, ready for merge

#2702 2.7 only: Pass -m32 to the linker as well
  tests/scripts/all.sh
Labels: bug, component: Platform, mbed TLS team, ready for merge

#2450 Backport 2.16: Fix minor typos and spelling mistakes
  CONTRIBUTING.md
  ChangeLog
  README.md
  include/mbedtls/check_config.h
  include/mbedtls/config.h
  include/mbedtls/hmac_drbg.h
  include/mbedtls/rsa.h
  include/mbedtls/ssl.h
  include/mbedtls/ssl_ticket.h
  include/mbedtls/x509.h
  include/mbedtls/x509_crl.h
  library/Makefile
  library/ecjpake.c
  library/error.c
  library/ssl_srv.c
  library/ssl_tls.c
  library/x509.c
  library/x509_crt.c
  tests/compat.sh
  tests/scripts/all.sh
  tests/scripts/test_zeroize.gdb
  tests/ssl-opt.sh
  tests/suites/test_suite_ccm.data
  tests/suites/test_suite_ecdh.function
  tests/suites/test_suite_nist_kw.function
  tests/suites/test_suite_rsa.data
Labels: CLA valid, ready for merge

#2615 [Backport 2.16] Use 'config.pl baremetal' in all.sh
  tests/scripts/all.sh
Labels: component: Platform, enhancement, mbed TLS team, ready for merge

#2614 Use 'config.pl baremetal' in all.sh
  tests/scripts/all.sh
Labels: component: Platform, enhancement, mbed TLS team, ready for merge

#2681 SSL reproducible test mode
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
Labels: CLA valid, component: Platform, ready for merge

#2690 Making version features easily ROM-able when using Arm C compiler.
  library/version_features.c
  scripts/data_files/version_features.fmt
Labels: Arm Contribution, component: Platform, enhancement, ready for merge
