Repository Mbed-TLS/mbedtls, pull requests merged in 2019-12, with the labels that each got.

#2940 [baremetal] Fix basic-build-test.sh to work in different env
  scripts/config.pl
  tests/scripts/basic-build-test.sh
Labels: branch: baremetal, component: TLS, ready for merge

#2935 config.pl: If python3 fails, make it clear that this isn't fatal
  scripts/config.pl
Labels: component: Platform, enhancement, mbed TLS team, ready for merge

#2841 Improve clarity of a memory operation call
  library/ssl_tls.c
Labels: enhancement, mbed TLS team

#2938 Mock TCP sockets and callbacks for SSL unit tests
  tests/suites/helpers.function
  tests/suites/target_test.function
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: component: TLS, enhancement, mbed TLS team, needs: review

#2952 [baremetal] Re-enable hardened SCA mem functions
  library/platform_util.c
Labels: branch: baremetal, mbed TLS team, ready for merge

#2961 Update the VS version in the Readme file
  README.md
Labels: bug
