Repository Mbed-TLS/mbedtls, pull requests merged in 2019-10, with the labels that each got.

#2488 Change X.509 test case to not rely on asn1parse limitation
  tests/suites/test_suite_x509parse.data
Labels: component: X.509, enhancement, mbed TLS team, ready for merge

#2578 Backport 2.16: Remove a redundant function call
  ChangeLog
  library/bignum.c
Labels: bug, component: Crypto, mbed TLS team, ready for merge

#2884 Fix parallel make jobs for shared target
  library/Makefile
  programs/Makefile
  tests/Makefile
  tests/scripts/all.sh
Labels: bug, component: TLS, enhancement, mbed TLS team, ready for merge

#2881 [baremetal] Merge mbedtls-2.16 (2019-10-04)
  ChangeLog
  include/mbedtls/check_config.h
  library/bignum.c
  scripts/config.pl
  tests/scripts/all.sh
  tests/suites/target_test.function
  tests/suites/test_suite_cipher.gcm.data
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_pkcs1_v15.function
  tests/suites/test_suite_pkcs1_v21.function
  tests/suites/test_suite_rsa.data
  tests/suites/test_suite_rsa.function
Labels: branch: baremetal, mbed TLS team, ready for merge

#2865 [Baremetal] Harmonize static function compiler flags
  library/ssl_srv.c
Labels: branch: baremetal, bug, mbed TLS team, ready for merge

#2872 Backport 2.7: Test the library when malloc(0) returns NULL
  programs/test/selftest.c
  tests/configs/config-wrapper-malloc-0-null.h
  tests/scripts/all.sh
Labels: component: Platform, mbed TLS team

#2871 Backport 2.16: Test the library when malloc(0) returns NULL
  programs/test/selftest.c
  tests/configs/config-wrapper-malloc-0-null.h
  tests/scripts/all.sh
Labels: component: Platform, mbed TLS team

#2898 Make sure Asan failures are detected in 'make test'
  tests/scripts/all.sh
  tests/scripts/run-test-suites.pl
Labels: bug, component: Platform, mbed TLS team

#2900 Backport 2.7: Make sure Asan failures are detected in 'make test'
  tests/scripts/all.sh
  tests/scripts/run-test-suites.pl
Labels: bug, component: Platform, mbed TLS team

#2899 Backport 2.16: Make sure Asan failures are detected in 'make test'
  tests/scripts/all.sh
  tests/scripts/run-test-suites.pl
Labels: bug, component: Platform, mbed TLS team

#2904 [baremetal] Fix tests to work in Mbed OS test environment
  tests/Makefile
  tests/suites/test_suite_x509parse.function
  tests/suites/test_suite_x509write.function
Labels: branch: baremetal, mbed TLS team, ready for merge

#2907 [baremetal] Fix mbedtls_ssl_check_record usage with ext buf
  library/ssl_tls.c
Labels: branch: baremetal, mbed TLS team, ready for merge
