Repository Mbed-TLS/mbedtls, pull requests merged in 2019-01, with the labels that each got.

#975 Add `MBEDTLS_SELF_TEST` check in header files
  ChangeLog
  include/mbedtls/aes.h
  include/mbedtls/arc4.h
  include/mbedtls/base64.h
  include/mbedtls/bignum.h
  include/mbedtls/camellia.h
  include/mbedtls/ctr_drbg.h
  include/mbedtls/des.h
  include/mbedtls/dhm.h
  include/mbedtls/gcm.h
  include/mbedtls/md2.h
  include/mbedtls/md4.h
  include/mbedtls/md5.h
  include/mbedtls/pkcs5.h
  include/mbedtls/ripemd160.h
  include/mbedtls/rsa.h
  include/mbedtls/sha1.h
  include/mbedtls/sha256.h
  include/mbedtls/sha512.h
  include/mbedtls/x509.h
  include/mbedtls/xtea.h
Labels: component: Crypto, component: Platform, mbed TLS team, ready for merge

#2232 Fix resource leak of file desc in test code
  tests/suites/helpers.function
Labels: bug, component: Platform, mbed TLS team, ready for merge

#2321 Update the LTS branch list in the contributing doc
  CONTRIBUTING.md
Labels: component: Platform, enhancement, mbed TLS team, ready for merge

#2233 Backport 2.7: Fix resource leak of file desc in test code
  tests/suites/helpers.function
Labels: bug, component: Platform, mbed TLS team, ready for merge

#2326 Remove duplicate #include
  ChangeLog
  programs/pkey/rsa_sign_pss.c
Labels: CLA valid, bug, component: Crypto, ready for merge

#2341 Backport 2.7: Remove duplicate #include
  ChangeLog
  programs/pkey/rsa_sign_pss.c
Labels: CLA valid, bug, component: Crypto, ready for merge

#2055 Remove lines above 80 characters in library/ctr_drbg.c
  library/ctr_drbg.c
Labels: enhancement, mbed TLS team, ready for merge

#2137 Document `psk_list` parameter of ssl_server2 example program
  programs/ssl/ssl_server2.c
Labels: component: TLS, enhancement, mbed TLS team, ready for merge

#2191 Fix false positive result when on Target Tests should fail
  tests/scripts/mbedtls_test.py
Labels: bug, component: Platform, mbed TLS team, ready for merge

#2207 Fix parsing error of test data
  tests/scripts/mbedtls_test.py
Labels: bug, component: Platform, mbed TLS team, ready for merge

#2371 Fix minor typos and spelling mistakes
  CONTRIBUTING.md
  ChangeLog
  README.md
  include/mbedtls/check_config.h
  include/mbedtls/config.h
  include/mbedtls/hmac_drbg.h
  include/mbedtls/rsa.h
  include/mbedtls/ssl.h
  include/mbedtls/ssl_ticket.h
  include/mbedtls/x509.h
  include/mbedtls/x509_crl.h
  library/Makefile
  library/ecjpake.c
  library/error.c
  library/ssl_srv.c
  library/ssl_tls.c
  library/x509.c
  library/x509_crt.c
  tests/compat.sh
  tests/scripts/all.sh
  tests/scripts/test_zeroize.gdb
  tests/ssl-opt.sh
  tests/suites/test_suite_ccm.data
  tests/suites/test_suite_ecdh.function
  tests/suites/test_suite_nist_kw.function
  tests/suites/test_suite_rsa.data
Labels: CLA valid, bug, needs: backports, ready for merge

#2356 Backport 2.7: Document `psk_list` parameter of ssl_server2 example program
  programs/ssl/ssl_server2.c
Labels: component: TLS, enhancement, mbed TLS team, ready for merge
