Repository Mbed-TLS/mbedtls, pull requests merged in 2020-11, with the labels that each got.

#3780 Add validate_key hooks and tests
  library/psa_crypto.c
  library/psa_crypto_core.h
  library/psa_crypto_driver_wrappers.c
  library/psa_crypto_driver_wrappers.h
  library/psa_crypto_slot_management.c
  library/psa_crypto_storage.h
  tests/include/test/drivers/key_management.h
  tests/include/test/drivers/signature.h
  tests/include/test/drivers/test_driver.h
  tests/src/drivers/key_management.c
  tests/src/drivers/keygen.c
  tests/suites/test_suite_psa_crypto_driver_wrappers.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
  visualc/VS2010/mbedTLS.vcxproj
Labels: Community, HwDrivers, needs: review

#3815 [baremetal] ssl_tls.c: Fix unchecked memory allocation
  library/ssl_tls.c
Labels: branch: baremetal, needs: ci, needs: review

#3826 PSA Crypto: Add zero-length input test vectors for ChaChaPoly
  tests/suites/test_suite_psa_crypto.data
Labels: Community, ready for merge

#3829 Backport 2.7: Fix printf escape errors in shell scripts
  tests/compat.sh
  tests/scripts/check-names.sh
  tests/ssl-opt.sh
Labels: component: Platform, component: TLS, needs: review, needs: reviewer

#3828 Backport 2.16: Fix printf escape errors in shell scripts
  tests/compat.sh
  tests/scripts/check-names.sh
  tests/ssl-opt.sh
Labels: bug, component: Platform, component: TLS, needs: review, needs: reviewer

#3614 Fix printf escape errors in shell scripts
  tests/compat.sh
  tests/context-info.sh
  tests/scripts/check-names.sh
  tests/ssl-opt.sh
Labels: bug, component: Platform, component: TLS, needs: backports

#3813 Backport 2.7: Remove a useless zeroization
  ChangeLog.d/aes-zeroize-pointer.txt
  library/aes.c
Labels: component: Crypto, enhancement

#3812 Backport 2.16: Remove a useless zeroization
  ChangeLog.d/aes-zeroize-pointer.txt
  library/aes.c
Labels: component: Crypto, enhancement

#3609 Remove a useless zeroization
  ChangeLog.d/aes-zeroize-pointer.txt
  library/aes.c
Labels: component: Crypto, enhancement

#3827 [baremetal] ssl_server2: move memory allocation to the beginning
  programs/ssl/ssl_server2.c
Labels: branch: baremetal, bug, component: TLS, enhancement, needs: ci, needs: review

#3851 cmake: Avoid using target_properties for old cmake
  programs/ssl/CMakeLists.txt
  programs/test/CMakeLists.txt
Labels: component: Platform

#3845 cmake: Avoid using target_properties for old cmake
  programs/fuzz/CMakeLists.txt
  programs/ssl/CMakeLists.txt
  programs/test/CMakeLists.txt
Labels: ready for merge

#3862 Backport 2.7: Do not set IV size for ECB mode ciphers
  ChangeLog.d/ecb_iv_fix.txt
  library/cipher_wrap.c
Labels: bug, component: TLS, mbed TLS team

#3861 Backport 2.16: Do not set IV size for ECB mode ciphers
  ChangeLog.d/ecb_iv_fix.txt
  library/cipher_wrap.c
Labels: bug, component: TLS, mbed TLS team

#3836 Do not set iv size for ECB mode ciphers
  ChangeLog.d/ecb_iv_fix.txt
  library/cipher_wrap.c
Labels: bug, component: TLS, mbed TLS team, ready for merge

#3853 [baremetal] Avoid narrow loop counters etc
  library/aes.c
  library/ccm.c
  library/cipher.c
  library/ecp.c
  library/ssl_tls.c
  tinycrypt/ecc.c
Labels: branch: baremetal, needs: ci, needs: review

#3823 Make the aes xts methods independent from MBEDTLS_AES_SETKEY_DEC_ALT
  library/aes.c
Labels: bug, component: Crypto, ready for merge

#3863 [Backport 2.16] Make the aes xts methods independent from MBEDTLS_AES_SETKEY_DEC_ALT
  library/aes.c
Labels: bug, component: Crypto, needs: ci, ready for merge

#3602 [Backport 2.16] NetBSD/OpenBSD symbol availability fix
  ChangeLog.d/arc4random_buf-implicit.txt
  tests/suites/main_test.function
Labels: Community, needs: work

#3571 NetBSD/OpenBSD symbol availability fix
  ChangeLog.d/arc4random_buf-implicit.txt
  tests/src/random.c
Labels: Community, bug, needs: backports, needs: review, needs: reviewer

#3888 Backport 2.7: Fix several configuration-related issues
  library/error.c
  scripts/data_files/error.fmt
  tests/scripts/all.sh
  tests/scripts/test-ref-configs.pl
Labels: component: Platform, enhancement, ready for merge

#3867 Fix several configuration-related issues
  ChangeLog.d/error-include-string.txt
  include/mbedtls/config.h
  include/psa/crypto_platform.h
  library/error.c
  programs/ssl/ssl_context_info.c
  scripts/data_files/error.fmt
  tests/scripts/all.sh
  tests/scripts/test-ref-configs.pl
Labels: Product Backlog, bug, component: Crypto, component: Platform, ready for merge

#3886 Backport 2.16: Fix several configuration-related issues
  library/error.c
  scripts/data_files/error.fmt
  tests/scripts/all.sh
  tests/scripts/test-ref-configs.pl
Labels: component: Platform, enhancement, ready for merge

#3876 Fix another use of uinitialized memory in ssl_parse_encrypted_pms
  library/ssl_srv.c
Labels: Community, bug, component: TLS, needs: backports, ready for merge

#3893 Backport 2.16: Fix another use of uinitialized memory in ssl_parse_encrypted_pms
  library/ssl_srv.c
Labels: Community, bug, component: TLS, ready for merge

#3894 Backport 2.7: Fix use of uinitialized memory in ssl_parse_encrypted_pms
  library/ssl_srv.c
Labels: Community, bug, component: TLS, ready for merge

#3830 Phase 2 support for MBDTLS_PSA_CRYPTO_CONFIG
  configs/config-symmetric-only.h
  include/mbedtls/config_psa.h
  include/mbedtls/ssl.h
  include/mbedtls/ssl_internal.h
  include/psa/crypto_config.h
  library/check_crypto_config.h
  library/psa_crypto.c
  tests/scripts/all.sh
  tests/src/drivers/key_management.c
  visualc/VS2010/mbedTLS.vcxproj
Labels: Community, HwDrivers, component: Crypto, needs: ci, ready for merge

#3697 PSA C configuration: more concrete information
  docs/proposed/psa-conditional-inclusion-c.md
Labels: HwDrivers, component: Crypto, enhancement, needs: review

#3844 [minor] Added Cscope to .gitignore
  .gitignore
Labels: Community, needs: backports

#3869 Backport 2.16: Add makefile target for cscope.out + .gitignore
  .gitignore
  Makefile
Labels: component: Platform, enhancement, needs: review, needs: reviewer

#3870 Backport 2.7: Add makefile target for cscope.out + .gitignore
  .gitignore
  Makefile
Labels: component: Platform, enhancement, needs: review, needs: reviewer

#3868 Add makefile target for cscope.out
  Makefile
Labels: component: Platform, enhancement, needs: backports, needs: review, needs: reviewer

#3547 Openless PSA crypto APIs implementation
  ChangeLog.d/psa-openless.txt
  README.md
  docs/architecture/testing/invasive-testing.md
  docs/getting_started.md
  docs/proposed/psa-driver-developer-guide.md
  docs/proposed/psa-driver-interface.md
  include/mbedtls/check_config.h
  include/mbedtls/cipher_internal.h
  include/mbedtls/config.h
  include/mbedtls/pk.h
  include/mbedtls/ssl.h
  include/mbedtls/ssl_internal.h
  include/psa/crypto.h
  include/psa/crypto_accel_driver.h
  include/psa/crypto_compat.h
  include/psa/crypto_entropy_driver.h
  include/psa/crypto_extra.h
  include/psa/crypto_platform.h
  include/psa/crypto_se_driver.h
  include/psa/crypto_struct.h
  include/psa/crypto_types.h
  include/psa/crypto_values.h
  library/pk.c
  library/pk_wrap.c
  library/pkwrite.c
  library/psa_crypto.c
  library/psa_crypto_core.h
  library/psa_crypto_invasive.h
  library/psa_crypto_its.h
  library/psa_crypto_slot_management.c
  library/psa_crypto_slot_management.h
  library/psa_crypto_storage.c
  library/psa_crypto_storage.h
  library/ssl_cli.c
  library/ssl_srv.c
  library/ssl_tls.c
  programs/psa/crypto_examples.c
  programs/psa/key_ladder_demo.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  scripts/config.py
  tests/include/test/psa_crypto_helpers.h
  tests/scripts/all.sh
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
  tests/suites/test_suite_psa_crypto_init.function
  tests/suites/test_suite_psa_crypto_persistent_key.data
  tests/suites/test_suite_psa_crypto_persistent_key.function
  tests/suites/test_suite_psa_crypto_se_driver_hal.data
  tests/suites/test_suite_psa_crypto_se_driver_hal.function
  tests/suites/test_suite_psa_crypto_se_driver_hal_mocks.function
  tests/suites/test_suite_psa_crypto_slot_management.data
  tests/suites/test_suite_psa_crypto_slot_management.function
  tests/suites/test_suite_x509write.function
Labels: HwDrivers, enhancement, mbed TLS team, ready for merge

#3786 Add export_public_key entry point for drivers
  ChangeLog.d/add_export_public_key_driver.txt
  library/psa_crypto.c
  library/psa_crypto_driver_wrappers.c
  library/psa_crypto_driver_wrappers.h
  tests/include/test/drivers/key_management.h
  tests/src/drivers/key_management.c
  tests/suites/test_suite_psa_crypto_driver_wrappers.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
Labels: Community, HwDrivers, ready for merge

#3877 Fix _POSIX_C_SOURCE typos
  library/platform_util.c
  library/threading.c
Labels: needs: ci, ready for merge

#3879 Backport 2.16: Fix _POSIX_C_SOURCE typos
  library/platform_util.c
  library/threading.c
Labels: ready for merge

#3900 Fix uninitialized variables
  library/ssl_tls.c
Labels: branch: baremetal, needs: ci, needs: review

#3840 [Baremetal] CCM countermeasures - shuffling and masking
  library/ccm.c
Labels: branch: baremetal, needs: ci, needs: review

#3841 [baremetal] Move size checks outside of mbedtls_platform_random_in_range
  include/mbedtls/platform_util.h
  library/platform_util.c
Labels: branch: baremetal, needs: ci, needs: review

#3913 Fix possible memory leak when MBEDTLS_SSL_VARIABLE_BUFFER_LENGTH defined
  library/ssl_tls.c
Labels: branch: baremetal, bug, component: TLS, needs: ci

#3890 [baremetal] Add a callback for platform faults in platform_util.c
  include/mbedtls/config.h
  library/platform_util.c
  library/version_features.c
  programs/ssl/query_config.c
  scripts/config.pl
Labels: branch: baremetal, enhancement

#3850 [baremetal] ccm - clean temp data
  library/ccm.c
Labels: branch: baremetal, needs: ci, needs: review

#3880 [baremetal] Add random delays to sha256 to protect against fault injection
  library/sha256.c
Labels: branch: baremetal, component: Crypto, needs: ci, needs: review

#3919 [baremetal] Make CCM shuffling an masking optional
  configs/baremetal.h
  include/mbedtls/config.h
  library/ccm.c
  library/version_features.c
  programs/ssl/query_config.c
Labels: branch: baremetal, component: Crypto, needs: ci, needs: review

#3907 Move "internal use" sentence attached to the wrong function
  include/mbedtls/sha512.h
Labels: bug, component: Crypto, needs: ci, ready for merge

#3908 Backport 2.16: Move "internal use" sentence attached to the wrong function
  include/mbedtls/sha512.h
Labels: bug, component: Crypto, ready for merge

#3920 Backport 2.7: Move "internal use" sentence attached to the wrong function
  include/mbedtls/sha512.h
Labels: bug, component: Crypto, needs: ci, ready for merge

#3918 PSA conditional inclusion spec: formatting fix
  docs/proposed/psa-conditional-inclusion-c.md
Labels: enhancement

#3917 Remove psa header files in uninstall part
  Makefile
Labels: Community, enhancement, ready for merge

#3899 Masked AES 128 bit, encrypt only (boolean mask technique)
  configs/baremetal.h
  include/mbedtls/aes.h
  include/mbedtls/check_config.h
  include/mbedtls/config.h
  library/aes.c
  library/version_features.c
  programs/ssl/query_config.c
  scripts/config.pl
Labels: branch: baremetal, needs: ci, needs: review

#3924 Fix removal of deprecated PSA constants
  include/psa/crypto_compat.h
Labels: bug, component: Crypto, mbed TLS team, needs: ci, ready for merge

#3695 PSA unified driver specification: key validation and transparent key import
  docs/proposed/psa-driver-interface.md
Labels: HwDrivers, PSA compliance, enhancement, needs: review, needs: reviewer
