Repository Mbed-TLS/mbedtls, pull requests merged in 2020-05, with the labels that each got.

#3219 Remove error_description variable from strerr functions
  library/error.c
  scripts/data_files/error.fmt
  scripts/generate_errors.pl
Labels: component: Platform, enhancement, ready for merge

#3295 Backport 2.7: Clarify that the full config enables everything that can be tested together
  programs/aes/crypt_and_hash.c
  programs/pkey/pk_decrypt.c
  programs/pkey/rsa_decrypt.c
  programs/pkey/rsa_verify.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  scripts/config.pl
  tests/scripts/all.sh
  tests/suites/test_suite_entropy.function
Labels: component: Platform, mbed TLS team, ready for merge

#3286 Backport 2.16: Clarify that the full config enables everything that can be tested together
  programs/aes/crypt_and_hash.c
  programs/pkey/pk_decrypt.c
  programs/pkey/rsa_decrypt.c
  programs/pkey/rsa_verify.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  scripts/config.pl
  tests/scripts/all.sh
  tests/suites/main_test.function
  tests/suites/test_suite_entropy.function
Labels: component: Platform, mbed TLS team, ready for merge

#3218 Rationalize Travis builds
  .travis.yml
  scripts/windows_msbuild.bat
  tests/scripts/all.sh
  tests/scripts/check-files.py
Labels: component: Platform, mbed TLS team, ready for merge

#3247 Backport 2.16: Rationalize Travis builds
  .travis.yml
  scripts/windows_msbuild.bat
  tests/scripts/all.sh
  tests/scripts/check-files.py
Labels: component: Platform, mbed TLS team, ready for merge

#3248 Backport 2.7: Rationalize Travis builds
  .travis.yml
  scripts/windows_msbuild.bat
  tests/scripts/all.sh
  tests/scripts/check-files.py
Labels: component: Platform, mbed TLS team, ready for merge

#3239 add support for win2k
  library/net_sockets.c
Labels: enhancement, ready for merge

#3190 Clarify that the full config enables everything that can be tested together
  library/psa_crypto_se.c
  programs/aes/crypt_and_hash.c
  programs/pkey/pk_decrypt.c
  programs/pkey/rsa_decrypt.c
  programs/pkey/rsa_verify.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  scripts/config.py
  tests/scripts/all.sh
  tests/scripts/basic-build-test.sh
  tests/suites/main_test.function
  tests/suites/test_suite_entropy.function
  tests/suites/test_suite_x509parse.data
Labels: component: Platform, mbed TLS team, ready for merge

#3308 Backport 2.7: Update link in contributing guide
  CONTRIBUTING.md
Labels: mbed TLS team

#3307 Backport 2.16: Update link in contributing guide
  CONTRIBUTING.md
Labels: mbed TLS team

#3306 Update link in contributing guide
  CONTRIBUTING.md
Labels: mbed TLS team

#3310 Expose SSL HW record acceleration error.
  ChangeLog.d/fix-masked-hw-record-init-error.txt
  library/ssl_tls.c
Labels: bug, component: TLS

#3311 Add variable initialization to large SSL TLS function
  library/ssl_tls.c
Labels: component: TLS, enhancement, needs: review

#3312 Scope reduction to enable NULL check to protect dereferencing.
  ChangeLog.d/fix-null-ptr-deref-in-mbedtls_ssl_free.txt
  library/ssl_tls.c
Labels: bug, component: TLS, good first issue, ready for merge

#2710 Backport 2.16: Unify the example programs' termination
  ChangeLog.d/unified-exit-in-examples.txt
  programs/aes/aescrypt2.c
  programs/aes/crypt_and_hash.c
  programs/hash/generic_sum.c
  programs/hash/hello.c
  programs/pkey/dh_client.c
  programs/pkey/dh_genprime.c
  programs/pkey/dh_server.c
  programs/pkey/ecdh_curve25519.c
  programs/pkey/ecdsa.c
  programs/pkey/gen_key.c
  programs/pkey/key_app.c
  programs/pkey/key_app_writer.c
  programs/pkey/mpi_demo.c
  programs/pkey/pk_decrypt.c
  programs/pkey/pk_encrypt.c
  programs/pkey/pk_sign.c
  programs/pkey/pk_verify.c
  programs/pkey/rsa_decrypt.c
  programs/pkey/rsa_encrypt.c
  programs/pkey/rsa_genkey.c
  programs/pkey/rsa_sign.c
  programs/pkey/rsa_sign_pss.c
  programs/pkey/rsa_verify.c
  programs/pkey/rsa_verify_pss.c
  programs/random/gen_entropy.c
  programs/random/gen_random_ctr_drbg.c
  programs/random/gen_random_havege.c
  programs/ssl/dtls_client.c
  programs/ssl/dtls_server.c
  programs/ssl/mini_client.c
  programs/ssl/ssl_client1.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_fork_server.c
  programs/ssl/ssl_mail_client.c
  programs/ssl/ssl_pthread_server.c
  programs/ssl/ssl_server.c
  programs/ssl/ssl_server2.c
  programs/test/benchmark.c
  programs/test/selftest.c
  programs/test/udp_proxy.c
  programs/test/zeroize.c
  programs/util/pem2der.c
  programs/util/strerror.c
  programs/x509/cert_app.c
  programs/x509/cert_req.c
  programs/x509/cert_write.c
  programs/x509/crl_app.c
  programs/x509/req_app.c
  tests/scripts/test_zeroize.gdb
Labels: component: Platform, enhancement, mbed TLS team, ready for merge

#2595 Unify the example programs' termination
  ChangeLog.d/unified-exit-in-examples.txt
  programs/aes/aescrypt2.c
  programs/aes/crypt_and_hash.c
  programs/hash/generic_sum.c
  programs/hash/hello.c
  programs/pkey/dh_client.c
  programs/pkey/dh_genprime.c
  programs/pkey/dh_server.c
  programs/pkey/ecdh_curve25519.c
  programs/pkey/ecdsa.c
  programs/pkey/gen_key.c
  programs/pkey/key_app.c
  programs/pkey/key_app_writer.c
  programs/pkey/mpi_demo.c
  programs/pkey/pk_decrypt.c
  programs/pkey/pk_encrypt.c
  programs/pkey/pk_sign.c
  programs/pkey/pk_verify.c
  programs/pkey/rsa_decrypt.c
  programs/pkey/rsa_encrypt.c
  programs/pkey/rsa_genkey.c
  programs/pkey/rsa_sign.c
  programs/pkey/rsa_sign_pss.c
  programs/pkey/rsa_verify.c
  programs/pkey/rsa_verify_pss.c
  programs/random/gen_entropy.c
  programs/random/gen_random_ctr_drbg.c
  programs/random/gen_random_havege.c
  programs/ssl/dtls_client.c
  programs/ssl/dtls_server.c
  programs/ssl/mini_client.c
  programs/ssl/ssl_client1.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_fork_server.c
  programs/ssl/ssl_mail_client.c
  programs/ssl/ssl_pthread_server.c
  programs/ssl/ssl_server.c
  programs/ssl/ssl_server2.c
  programs/test/benchmark.c
  programs/test/selftest.c
  programs/test/udp_proxy.c
  programs/test/zeroize.c
  programs/util/pem2der.c
  programs/util/strerror.c
  programs/x509/cert_app.c
  programs/x509/cert_req.c
  programs/x509/cert_write.c
  programs/x509/crl_app.c
  programs/x509/req_app.c
Labels: approved for design, component: Platform, enhancement, mbed TLS team, ready for merge

#2705 Backport 2.7: Unify the example programs' termination
  ChangeLog.d/unified-exit-in-examples.txt
  programs/aes/aescrypt2.c
  programs/aes/crypt_and_hash.c
  programs/hash/generic_sum.c
  programs/hash/hello.c
  programs/pkey/dh_client.c
  programs/pkey/dh_genprime.c
  programs/pkey/dh_server.c
  programs/pkey/ecdh_curve25519.c
  programs/pkey/ecdsa.c
  programs/pkey/gen_key.c
  programs/pkey/key_app.c
  programs/pkey/key_app_writer.c
  programs/pkey/mpi_demo.c
  programs/pkey/pk_decrypt.c
  programs/pkey/pk_encrypt.c
  programs/pkey/pk_sign.c
  programs/pkey/pk_verify.c
  programs/pkey/rsa_decrypt.c
  programs/pkey/rsa_encrypt.c
  programs/pkey/rsa_genkey.c
  programs/pkey/rsa_sign.c
  programs/pkey/rsa_sign_pss.c
  programs/pkey/rsa_verify.c
  programs/pkey/rsa_verify_pss.c
  programs/random/gen_entropy.c
  programs/random/gen_random_ctr_drbg.c
  programs/random/gen_random_havege.c
  programs/ssl/dtls_client.c
  programs/ssl/dtls_server.c
  programs/ssl/mini_client.c
  programs/ssl/ssl_client1.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_fork_server.c
  programs/ssl/ssl_mail_client.c
  programs/ssl/ssl_pthread_server.c
  programs/ssl/ssl_server.c
  programs/ssl/ssl_server2.c
  programs/test/benchmark.c
  programs/test/selftest.c
  programs/test/udp_proxy.c
  programs/util/pem2der.c
  programs/util/strerror.c
  programs/x509/cert_app.c
  programs/x509/cert_req.c
  programs/x509/cert_write.c
  programs/x509/crl_app.c
  programs/x509/req_app.c
Labels: component: Platform, enhancement, mbed TLS team, ready for merge

#3302 Define some structure for lifetime values
  ChangeLog.d/psa-lifetime-locations.txt
  include/psa/crypto_se_driver.h
  include/psa/crypto_types.h
  include/psa/crypto_values.h
  library/psa_crypto_se.c
  library/psa_crypto_se.h
  tests/suites/test_suite_psa_crypto_se_driver_hal.data
  tests/suites/test_suite_psa_crypto_se_driver_hal.function
  tests/suites/test_suite_psa_crypto_se_driver_hal_mocks.data
  tests/suites/test_suite_psa_crypto_se_driver_hal_mocks.function
Labels: approved for design, component: Crypto, enhancement, mbed TLS team, ready for merge

#3319 Fix typo in program benchmark.
  programs/test/benchmark.c
Labels: enhancement

#3301 psa: Define mbedtls_ecc_group_to_psa() inline
  ChangeLog.d/inline-mbedtls_gcc_group_to_psa.txt
  include/psa/crypto_extra.h
  library/psa_crypto.c
Labels: Arm Contribution, component: Crypto, component: Platform, ready for merge

#3335 midipix platform support
  ChangeLog.d/midipix-support.txt
  library/entropy_poll.c
  library/net_sockets.c
  library/timing.c
Labels: enhancement, ready for merge

#3326 fix mbedtls_x509_dn_gets to show non-ASCII string properly
  ChangeLog.d/fix-print-non-ascii-string-in-mbedtls_x509_dn_gets.txt
  library/x509.c
  tests/data_files/non-ascii-string-in-issuer.crt
  tests/suites/test_suite_x509parse.data
Labels: enhancement

#2855 Remove non-working check from x509_get_subject_alt_name
  ChangeLog.d/bugfix_PR2855.txt
  library/x509_crt.c
Labels: CLA valid, bug, component: X.509

#3341 Fix contributing link to changelog howto
  CONTRIBUTING.md
Labels: component: Platform, mbed TLS team, ready for merge

#3362 Backport 2.16: Fix contributing link to changelog howto
  CONTRIBUTING.md
Labels: mbed TLS team, ready for merge

#3361 Backport 2.7: Fix contributing link to changelog howto
  CONTRIBUTING.md
Labels: mbed TLS team, ready for merge

#3351 Add output of make, cmake and python3 versions
  scripts/output_env.sh
Labels: component: Platform, enhancement, mbed TLS team, needs: review

#3358 Backport 2.16: Add output of make, cmake and python3 versions
  scripts/output_env.sh
Labels: component: Platform, enhancement, mbed TLS team, needs: review

#3359 Backport 2.7: Add output of make, cmake and python3 versions
  scripts/output_env.sh
Labels: component: Platform, enhancement, mbed TLS team, needs: review

#3350 Include asn1.h in error.c
  ChangeLog.d/error-asn1.txt
  library/error.c
  scripts/generate_errors.pl
Labels: bug, component: Crypto, mbed TLS team, ready for merge

#3368 Backport 2.16: Include asn1.h in error.c
  ChangeLog.d/error-asn1.txt
  library/error.c
  scripts/generate_errors.pl
Labels: bug, component: Crypto, mbed TLS team, ready for merge

#3369 Backport 2.7: Include asn1.h in error.c
  ChangeLog.d/error-asn1.txt
  library/error.c
  scripts/generate_errors.pl
Labels: bug, component: Crypto, mbed TLS team, ready for merge

#3305 PSA: Fix copypasta and align terminology about asymmetric encryption
  include/psa/crypto_sizes.h
  include/psa/crypto_values.h
Labels: component: Crypto, mbed TLS team, ready for merge
