Repository Mbed-TLS/mbedtls, pull requests merged in 2020-12, with the labels that each got.

#3926 Backport 2.7: Fix build failure on gcc-11
  ChangeLog.d/bugfix_3782.txt
  library/cmac.c
  library/ssl_tls.c
  programs/test/selftest.c
  tests/suites/main_test.function
Labels: Community, component: Platform, ready for merge

#3925 Backport 2.16: Fix build failure on gcc-11
  ChangeLog.d/bugfix_3782.txt
  library/cmac.c
  library/ssl_tls.c
  programs/test/selftest.c
  tests/suites/host_test.function
Labels: Community, component: Platform, ready for merge

#3848 Fix build failure on gcc-11
  ChangeLog.d/bugfix_3782.txt
  library/cmac.c
  library/ssl_tls.c
  programs/test/selftest.c
  tests/suites/host_test.function
Labels: Community, component: Platform, ready for merge

#3931 Platform random buf FI mitigation added
  include/mbedtls/config.h
  library/platform_util.c
Labels: branch: baremetal

#3932 [baremetal] Tinycrypt - ecdh test vectors
  tests/suites/test_suite_tinycrypt.data
  tests/suites/test_suite_tinycrypt.function
Labels: branch: baremetal, needs: ci, needs: review

#3930 Fix: Add missing arguments to debug message.
  ChangeLog.d/missing-debug-message-arguments_mbedtls_ssl_decrypt_buf.txt
  library/ssl_msg.c
Labels: Community, bug, needs: ci, ready for merge

#3934 [Baremetal] Add NIST CAVP FIPS 186-4 test vectors for tinycrypt ecdsa
  tests/suites/test_suite_tinycrypt.data
  tests/suites/test_suite_tinycrypt.function
Labels: branch: baremetal, needs: ci, needs: review

#3725 Backport 2.7: add missing some error checks in ECP and bignum
  ChangeLog.d/ecp-bignum-error-checks.txt
  library/bignum.c
  library/ecp_curves.c
  tests/suites/test_suite_mpi.data
  tests/suites/test_suite_mpi.function
Labels: bug, component: Crypto

#3513 Backport 2.16: add missing some error checks in ECP and bignum
  ChangeLog.d/ecp-bignum-error-checks.txt
  library/bignum.c
  library/ecp_curves.c
  tests/suites/test_suite_mpi.data
  tests/suites/test_suite_mpi.function
Labels: bug, component: Crypto

#3942 Add missing some error checks in ECP and bignum
  ChangeLog.d/ecp-bignum-error-checks.txt
  library/bignum.c
  library/ecp_curves.c
  tests/suites/test_suite_mpi.data
  tests/suites/test_suite_mpi.function
Labels: bug, component: Crypto, ready for merge

#3916 Add support to crypto config for hashes
  include/mbedtls/config_psa.h
  include/psa/crypto_config.h
  library/psa_crypto.c
  tests/scripts/all.sh
Labels: HwDrivers, PSA compliance, component: Crypto, enhancement, ready for merge

#3393 Support set *_drbg reseed interval before seed
  ChangeLog.d/bugfix-2927.txt
  include/mbedtls/ctr_drbg.h
  include/mbedtls/hmac_drbg.h
  library/ctr_drbg.c
  library/hmac_drbg.c
  tests/suites/test_suite_ctr_drbg.function
  tests/suites/test_suite_hmac_drbg.function
Labels: Community, bug, component: Crypto

#3937 Backport to Mbedtls 2.7: Support set *_drbg reseed interval before seed
  ChangeLog.d/bugfix-2927.txt
  include/mbedtls/ctr_drbg.h
  include/mbedtls/hmac_drbg.h
  library/ctr_drbg.c
  library/hmac_drbg.c
  tests/suites/test_suite_ctr_drbg.function
  tests/suites/test_suite_hmac_drbg.function
Labels: Community, bug, component: Crypto, ready for merge

#3938 Backport to Mbedtls 2.16: Support set *_drbg reseed interval before seed
  ChangeLog.d/bugfix-2927.txt
  include/mbedtls/ctr_drbg.h
  include/mbedtls/hmac_drbg.h
  library/ctr_drbg.c
  library/hmac_drbg.c
  tests/suites/test_suite_ctr_drbg.function
  tests/suites/test_suite_hmac_drbg.function
Labels: Community, bug, component: Crypto, ready for merge

#3948 Update the values of PSA Crypto API macros to version 1.0.0
  ChangeLog.d/psa-crypto-api-values-1.0.0.txt
  include/psa/crypto_compat.h
  include/psa/crypto_extra.h
  include/psa/crypto_sizes.h
  include/psa/crypto_values.h
  library/psa_crypto.c
  programs/psa/psa_constant_names_generated.c
  scripts/generate_psa_constants.py
  tests/scripts/test_psa_constant_names.py
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto_metadata.data
  tests/suites/test_suite_psa_crypto_persistent_key.data
Labels: PSA compliance, component: Crypto, mbed TLS team

#3941 [baremetal] Add ECDSA signature generation tests to tinycrypt
  include/tinycrypt/ecc_dsa.h
  scripts/baremetal.sh
  tests/scripts/all.sh
  tests/suites/test_suite_tinycrypt.data
  tests/suites/test_suite_tinycrypt.function
Labels: branch: baremetal

#3898 Remove Extraneous bytes from buffer post pem write
  ChangeLog.d/clean_pem_buffers.txt
  library/pem.c
  tests/suites/test_suite_pkwrite.function
  tests/suites/test_suite_x509write.function
Labels: bug, component: X.509, needs: ci, ready for merge

#3935 Backport 2.16: Remove Extraneous bytes from buffer post pem write
  ChangeLog.d/clean_pem_buffers.txt
  library/pem.c
  tests/suites/test_suite_pkwrite.function
  tests/suites/test_suite_x509write.function
Labels: bug, component: X.509, ready for merge

#3945 Backport 2.7: Add tests for buffer corruption after PEM write
  library/pem.c
  tests/suites/test_suite_pkwrite.function
  tests/suites/test_suite_x509write.function
Labels: component: Crypto, enhancement, needs: ci, ready for merge

#3949 Improve documentation in test_psa_constant_names.py
  tests/scripts/test_psa_constant_names.py
Labels: component: Crypto, enhancement, mbed TLS team, ready for merge

#3929 Remove old proposed accelerator interfaces
  docs/architecture/testing/driver-interface-test-strategy.md
  include/psa/crypto_accel_driver.h
  include/psa/crypto_driver_common.h
  include/psa/crypto_entropy_driver.h
  programs/test/cpp_dummy_build.cpp
  visualc/VS2010/mbedTLS.vcxproj
Labels: PSA compliance, enhancement, ready for merge

#3882 PSA: Specification for random generation and entropy drivers
  docs/proposed/psa-driver-interface.md
Labels: HwDrivers, PSA compliance, Product Backlog, approved for design, component: Crypto, enhancement

#3576 Tweak documentation about lifetimes
  include/psa/crypto_types.h
  include/psa/crypto_values.h
Labels: component: Crypto, enhancement, ready for merge

#3691 Set CMake Max Version
  CMakeLists.txt
Labels: Arm Contribution, bug, needs: review

#3946 [baremetal] Key exchange optimizations
  configs/baremetal.h
  include/mbedtls/check_config.h
  include/mbedtls/config.h
  include/mbedtls/ssl_internal.h
  library/ssl_cli.c
  library/ssl_srv.c
  library/ssl_tls.c
  library/version_features.c
  programs/ssl/query_config.c
  scripts/config.pl
  tests/scripts/all.sh
  tests/ssl-opt.sh
Labels: branch: baremetal

#3965 Fix use-after-scope error in programs/ssl
  ChangeLog.d/programs-ssl-use-after-scope.txt
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
Labels: bug, mbed TLS team, ready for merge
