Repository Mbed-TLS/mbedtls, pull requests merged in 2020-02, with the labels that each got.

#2236 Deprecate SSLv2 parsing and SSLv3
  ChangeLog
  include/mbedtls/check_config.h
  include/mbedtls/config.h
  scripts/config.py
  tests/scripts/all.sh
Labels: component: TLS, mbed TLS team, ready for merge

#3018 Fix ssl-opt.sh for GnuTLS versions rejecting SHA-1
  tests/ssl-opt.sh
Labels: bug, component: TLS, mbed TLS team, ready for merge

#3019 [backport 2.16] Fix ssl-opt.sh for GnuTLS versions rejecting SHA-1
  tests/ssl-opt.sh
Labels: bug, component: TLS, mbed TLS team, ready for merge

#3020 [backport 2.7] Fix ssl-opt.sh for GnuTLS versions rejecting SHA-1
  library/certs.c
  tests/data_files/Makefile
  tests/data_files/test-ca_cat12u.crt
  tests/ssl-opt.sh
Labels: bug, component: TLS, mbed TLS team, ready for merge

#3023 Add crypto-only preset configurations
  scripts/config.py
  tests/scripts/all.sh
  tests/suites/test_suite_x509write.function
Labels: component: Crypto, mbed TLS team, ready for merge

#3021 Handshake tests with mocked I/O callbacks
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: component: TLS, mbed TLS team, ready for merge

#3033 Revert "Merge pull request #3008 from jp-bennett/development"
  ChangeLog
  library/x509_crt.c
Labels: bug, mbed TLS team, ready for merge

#3034 Revert "Merge pull request #3012 from Patater/dev/jp-bennett/developm…
  ChangeLog
  library/x509_crt.c
Labels: bug, mbed TLS team, ready for merge

#3035 Revert "Merge pull request #3011 from Patater/dev/jp-bennett/developm…
  ChangeLog
  library/x509_crt.c
Labels: bug, mbed TLS team, ready for merge

#3027 Backport 2.16: Improve robustness and testing of mbedtls_mpi_copy
  library/bignum.c
  tests/suites/test_suite_mpi.data
  tests/suites/test_suite_mpi.function
Labels: component: Crypto, enhancement, mbed TLS team, ready for merge

#3028 Backport 2.7: Improve robustness and testing of mbedtls_mpi_copy
  library/bignum.c
  tests/suites/test_suite_mpi.data
  tests/suites/test_suite_mpi.function
Labels: component: Crypto, enhancement, mbed TLS team, ready for merge

#3022 Add tests for data transfer to test suites
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: component: TLS, mbed TLS team, needs: review

#2852 Fix and test the full config with gcc and clang
  programs/ssl/ssl_server2.c
  tests/scripts/all.sh
Labels: bug, component: Platform, enhancement, mbed TLS team, ready for merge

#3029 Backport 2.16: Fix and test the full config with gcc and clang
  tests/scripts/all.sh
Labels: component: Platform, enhancement, mbed TLS team, ready for merge

#3030 Backport 2.7: Fix and test the full config with gcc and clang
  tests/scripts/all.sh
Labels: component: Platform, enhancement, mbed TLS team, needs: review, ready for merge

#2873 Fix some possibly-undefined variable warnings
  ChangeLog
  library/x509_crl.c
  library/x509_crt.c
Labels: CLA not applicable, bug, component: X.509, ready for merge

#3010 Introduce separate source file for SSL messaging layer
  include/mbedtls/ssl_internal.h
  library/CMakeLists.txt
  library/Makefile
  library/ssl_msg.c
  library/ssl_tls.c
  visualc/VS2010/mbedTLS.vcxproj
Labels: component: TLS, enhancement, needs: review, ready for merge

#3048 [backport 2.16] Fix pk_parse_key()'s use of rsa_complete()
  ChangeLog
  library/pkparse.c
  tests/suites/test_suite_pkparse.data
  tests/suites/test_suite_pkparse.function
Labels: bug, component: Crypto, mbed TLS team, ready for merge

#3049 [backport 2.7] Fix pk_parse_key()'s use of rsa_complete()
  ChangeLog
  library/pkparse.c
  tests/suites/test_suite_pkparse.data
  tests/suites/test_suite_pkparse.function
Labels: bug, component: Crypto, mbed TLS team, ready for merge

#3052 Bump version 2.7.14
  ChangeLog
  doxygen/input/doc_mainpage.h
  doxygen/mbedtls.doxyfile
  include/mbedtls/version.h
  library/CMakeLists.txt
  tests/suites/test_suite_version.data
Labels: mbed TLS team, ready for merge

#3053 Bump version 2.16.5
  ChangeLog
  doxygen/input/doc_mainpage.h
  doxygen/mbedtls.doxyfile
  include/mbedtls/version.h
  library/CMakeLists.txt
  tests/suites/test_suite_version.data
Labels: mbed TLS team, ready for merge

#3036 DTLS handshake tests
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: component: TLS, mbed TLS team, ready for merge

#3038 Side-port from crypto: programs/
  programs/Makefile
  programs/aes/CMakeLists.txt
  programs/hash/CMakeLists.txt
  programs/pkey/CMakeLists.txt
  programs/pkey/key_app.c
  programs/pkey/rsa_genkey.c
  programs/pkey/rsa_sign_pss.c
  programs/pkey/rsa_verify_pss.c
  programs/random/CMakeLists.txt
  programs/ssl/CMakeLists.txt
  programs/test/CMakeLists.txt
  programs/test/benchmark.c
  programs/test/query_config.c
  programs/test/selftest.c
  programs/util/CMakeLists.txt
  programs/x509/CMakeLists.txt
  scripts/bump_version.sh
  scripts/generate_query_config.pl
  scripts/generate_visualc_files.pl
  tests/configs/config-wrapper-malloc-0-null.h
  tests/scripts/all.sh
  tests/scripts/check-generated-files.sh
  visualc/VS2010/query_compile_time_config.vcxproj
  visualc/VS2010/ssl_client2.vcxproj
  visualc/VS2010/ssl_server2.vcxproj
Labels: component: Crypto, component: Platform, enhancement, mbed TLS team, ready for merge

#3042 Dtls handshake serialization test
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: component: TLS, mbed TLS team

#3043 DTLS application data
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: component: TLS, mbed TLS team

#3046 DTLS renegotiation
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: mbed TLS team, needs: ci, needs: review, needs: work

#2263 Deprecate feature MBEDTLS_SSL_HW_RECORD_ACCEL
  ChangeLog
  include/mbedtls/check_config.h
  include/mbedtls/config.h
  include/mbedtls/ssl.h
Labels: component: TLS, mbed TLS team, ready for merge

#3069 Handshake tests refactor
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: component: TLS, mbed TLS team, needs: review

#3074 Add a DTLS handshake fragmentation test
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: component: TLS, enhancement, mbed TLS team, ready for merge
