Repository Mbed-TLS/mbedtls, pull requests merged in 2020-08, with the labels that each got.

#3509 x509.c: Remove one unnecessary cast
  library/x509.c
Labels: Arm Contribution, branch: baremetal, needs: ci, needs: review

#3500 Introduce sha256 security review fixes
  include/mbedtls/sha256.h
  library/sha256.c
Labels: Arm Contribution, DO NOT MERGE, branch: baremetal, needs: ci, needs: review

#3510 pk.c FI-related fixes
  include/tinycrypt/ecc.h
  library/pk.c
Labels: Arm Contribution, DO NOT MERGE, branch: baremetal, needs: ci, needs: review

#3516 FI-related pkparse.c fixes
  library/pkparse.c
Labels: Arm Contribution, DO NOT MERGE, branch: baremetal, needs: ci, needs: review

#3492 Rework PSA Crypto core to store keys in export representation
  ChangeLog.d/psa_curve25519_public_key_import.txt
  library/psa_crypto.c
  library/psa_crypto_core.h
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: component: Crypto, enhancement, needs: ci

#3514 Fi write user data
  configs/baremetal.h
  include/mbedtls/config.h
  include/mbedtls/ssl.h
  library/ssl_tls.c
  library/version_features.c
  programs/ssl/query_config.c
Labels: branch: baremetal, needs: review

#3493 PSA unified driver specification
  docs/.gitignore
  docs/architecture/.gitignore
  docs/proposed/Makefile
  docs/proposed/README
  docs/proposed/psa-driver-developer-guide.md
  docs/proposed/psa-driver-integration-guide.md
  docs/proposed/psa-driver-interface.md
Labels: PSA compliance, component: Crypto, mbed TLS team, needs: review

#3477 Use a fake random key in AES calculations
  include/mbedtls/aes.h
  library/aes.c
Labels: Arm Contribution, branch: baremetal, component: Crypto, needs: ci, needs: review

#3532 Fi-related hmac_drbg fixes
  include/mbedtls/hmac_drbg.h
  library/ecdsa.c
  library/hmac_drbg.c
  tests/suites/test_suite_hmac_drbg.function
Labels: Arm Contribution, branch: baremetal, needs: ci, needs: review

#3488 Backport 2.16: PR #2632 Avoid use of large stack buffers in CRT writing
  ChangeLog.d/bugfix_PR_2632.txt
  include/mbedtls/pem.h
  library/x509write_crt.c
Labels: bug, component: X.509, ready for merge

#3448 Renamed mbedtls_platform_memcmp() to mbedtls_platform_memequal()
  include/mbedtls/asn1.h
  include/mbedtls/compat-1.3.h
  include/mbedtls/platform_util.h
  library/asn1parse.c
  library/asn1write.c
  library/des.c
  library/oid.c
  library/pem.c
  library/pk.c
  library/pkparse.c
  library/platform_util.c
  library/rsa.c
  library/ssl_cache.c
  library/ssl_cli.c
  library/ssl_cookie.c
  library/ssl_srv.c
  library/ssl_ticket.c
  library/ssl_tls.c
  library/x509.c
  library/x509_crl.c
  library/x509_crt.c
Labels: branch: baremetal, needs: review

#3537 Expanded the random number generator in the `platform_util.c` file
  include/mbedtls/platform_util.h
  library/platform_util.c
Labels: branch: baremetal

#3489 Backport 2.16: PR #3464 Dynamically allocate requested CSR write buffer size
  ChangeLog.d/x509write_csr_heap_alloc.txt
  library/x509write_csr.c
Labels: component: X.509

#3468 Add flow monitor for memory block operations
  include/mbedtls/platform_util.h
  library/entropy.c
  library/pkparse.c
  library/platform_util.c
  library/rsa.c
  library/ssl_tls.c
  tinycrypt/ecc_dh.c
Labels: branch: baremetal

#3495 Add update option to check-generated-files
  tests/git-scripts/pre-commit.sh
  tests/scripts/check-generated-files.sh
Labels: component: Platform, enhancement, good first issue, mbed TLS team

#3548 [Backport 2.16] Add update option to check-generated-files
  tests/git-scripts/pre-commit.sh
  tests/scripts/check-generated-files.sh
Labels: component: Platform, enhancement, mbed TLS team

#3549 [Backport 2.7] Add update option to check-generated-files
  tests/git-scripts/pre-commit.sh
  tests/scripts/check-generated-files.sh
Labels: component: Platform, enhancement

#3553 Validate AES keys after each use checking CRC
  configs/baremetal.h
  include/mbedtls/aes.h
  include/mbedtls/check_config.h
  include/mbedtls/config.h
  include/mbedtls/crc.h
  library/CMakeLists.txt
  library/Makefile
  library/aes.c
  library/crc.c
  library/version_features.c
  programs/ssl/query_config.c
  tests/CMakeLists.txt
  tests/suites/test_suite_aes.ecb.crc.data
  tests/suites/test_suite_aes.function
  tests/suites/test_suite_crc.data
  tests/suites/test_suite_crc.function
  visualc/VS2010/mbedTLS.vcxproj
Labels: Arm Contribution, DO NOT MERGE, branch: baremetal, component: Crypto, enhancement, needs: ci, needs: review

#3540 Use arc4random_buf instead of rand on NetBSD
  ChangeLog.d/netbsd-rand-arc4random_buf.txt
  library/rsa.c
  tests/src/random.c
Labels: bug, component: Crypto

#3560 [Backport 2.16] Use arc4random_buf instead of rand on NetBSD
  ChangeLog.d/netbsd-rand-arc4random_buf.txt
  library/rsa.c
  tests/suites/helpers.function
Labels: bug, component: Crypto

#3559 [Backport 2.7] Use arc4random_buf instead of rand on NetBSD
  ChangeLog.d/netbsd-rand-arc4random_buf.txt
  library/rsa.c
  tests/suites/helpers.function
Labels: bug, component: Crypto

#3554 X509 verify non-DNS SANs
  ChangeLog.d/x509-verify-non-dns-san.txt
  include/mbedtls/x509_crt.h
  library/x509_crt.c
  tests/data_files/Makefile
  tests/data_files/server5-tricky-ip-san.crt
  tests/data_files/test-ca.opensslconf
  tests/suites/test_suite_x509parse.data
Labels: bug, component: X.509, mbed TLS team, needs: backports

#3557 Ensure that only one definition of ASSERT is present
  library/chacha20.c
  library/chachapoly.c
  library/poly1305.c
  undef_assert_before_defining_it.txt
Labels: component: Platform, enhancement

#3404 Improve ssl-opt.sh logs
  tests/compat.sh
  tests/ssl-opt.sh
Labels: component: TLS, enhancement, good first issue, mbed TLS team

#3566 [Backport 2.7] Improve ssl-opt.sh logs
  tests/compat.sh
  tests/ssl-opt.sh
Labels: component: TLS, enhancement, mbed TLS team

#3565 [Backport 2.16] Improve ssl-opt.sh logs
  tests/compat.sh
  tests/ssl-opt.sh
Labels: component: TLS, enhancement, mbed TLS team

#3558 [Backport 2.16] NetBSD 9.0 build fixes
  ChangeLog.d/fix-build-netbsd.txt
  library/net_sockets.c
  programs/ssl/ssl_mail_client.c
Labels: bug, component: Platform

#3555 [Backport 2.16] X509 verify non-DNS SANs
  tests/data_files/Makefile
  tests/data_files/server5-tricky-ip-san.crt
  tests/data_files/test-ca.opensslconf
  tests/suites/test_suite_x509parse.data
Labels: bug, component: X.509, mbed TLS team

#3556 [Backport 2.7] X509 verify non-DNS SANs
  tests/data_files/Makefile
  tests/data_files/server5-tricky-ip-san.crt
  tests/data_files/test-ca.opensslconf
  tests/suites/test_suite_x509parse.data
Labels: bug, component: X.509, mbed TLS team

#3582 2.16 only: Fix license header in pre-commit hook
  tests/git-scripts/pre-commit.sh
Labels: enhancement, mbed TLS team

#3583 Backport 2.7: Fix license header in pre-commit hook
  tests/git-scripts/pre-commit.sh
Labels: enhancement, mbed TLS team, needs: ci

#3584 Fix location of a ChangeLog entry file
  ChangeLog.d/undef_assert_before_defining_it.txt
Labels: bug, mbed TLS team

#3578 Fix memory leak in mbedtls_md_setup with HMAC
  ChangeLog.d/md_setup-leak.txt
  library/md.c
Labels: bug, component: Crypto

#2182 Add support for password protected key files to ssl_server2 and ssl_client2
  ChangeLog.d/pw_protected_key_file_ssl_clisrv2.txt
  library/ssl_cli.c
  library/ssl_srv.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  tests/data_files/Makefile
  tests/data_files/server2.key.enc
  tests/data_files/server5.key.enc
  tests/ssl-opt.sh
Labels: component: TLS, enhancement, mbed TLS team, ready for merge

#3528 Fix bug in redirection of unit test outputs
  ChangeLog.d/stdout-macro.txt
  tests/suites/helpers.function
  tests/suites/host_test.function
Labels: bug, component: Platform

#3601 [Backport 2.16] Fix bug in redirection of unit test outputs
  ChangeLog.d/stdout-macro.txt
  tests/suites/helpers.function
  tests/suites/host_test.function
Labels: bug, component: Platform

#3600 [Backport 2.7] Fix bug in redirection of unit test outputs
  ChangeLog.d/stdout-macro.txt
  tests/suites/helpers.function
  tests/suites/main_test.function
Labels: bug, component: Platform

#3604 Add a deprecated version of mbedtls_platform_memcmp.
  include/mbedtls/platform_util.h
  library/platform_util.c
Labels: Arm Contribution, branch: baremetal, component: Platform, enhancement, needs: ci, needs: review

#3574 Support building on e2k (Elbrus) architecture
  CMakeLists.txt
  ChangeLog.d/e2k-support.txt
  library/ssl_msg.c
  programs/pkey/dh_genprime.c
  tests/include/test/macros.h
Labels: component: Platform, enhancement, ready for merge

#3598 Backport 2.16: Support building on e2k (Elbrus) architecture
  ChangeLog.d/e2k-support.txt
  library/ssl_tls.c
  programs/pkey/dh_genprime.c
  tests/suites/helpers.function
Labels: component: Crypto, component: TLS, ready for merge

#3599 Backport 2.7: Support building on e2k (Elbrus) architecture
  ChangeLog.d/e2k-support.txt
  library/ssl_tls.c
  programs/pkey/dh_genprime.c
  tests/suites/helpers.function
Labels: component: Crypto, component: TLS, ready for merge

#3594 Backport 2.7: Fix compat.sh with ubuntu 16.04 gnutls 2.7
  library/certs.c
  programs/x509/cert_write.c
  tests/compat.sh
  tests/data_files/Makefile
  tests/data_files/cert_md2.crt
  tests/data_files/cert_md4.crt
  tests/data_files/cert_md5.crt
  tests/data_files/cert_sha1.crt
  tests/data_files/cert_sha224.crt
  tests/data_files/cert_sha256.crt
  tests/data_files/cert_sha384.crt
  tests/data_files/cert_sha512.crt
  tests/data_files/server2-sha256.crt
  tests/suites/test_suite_x509parse.data
Labels: bug, component: TLS, component: X.509

#3612 PSA: add negative MAC tests
  tests/suites/test_suite_psa_crypto.function
Labels: component: Crypto, enhancement, ready for merge

#3433 Always revoke certificate on CRL
  ChangeLog.d/crl-revocationDate.txt
  library/x509_crt.c
  tests/data_files/Makefile
  tests/data_files/Readme-x509.txt
  tests/data_files/crl-futureRevocationDate.pem
  tests/data_files/test-ca.server1.future-crl.db
  tests/data_files/test-ca.server1.future-crl.opensslconf
  tests/scripts/all.sh
  tests/suites/test_suite_x509parse.data
Labels: bug, component: X.509, ready for merge

#3562 Backport 2.16: Always revoke certificate on CRL
  ChangeLog.d/crl-revocationDate.txt
  library/x509_crt.c
  tests/data_files/Makefile
  tests/data_files/Readme-x509.txt
  tests/data_files/crl-futureRevocationDate.pem
  tests/data_files/test-ca.server1.future-crl.db
  tests/data_files/test-ca.server1.future-crl.opensslconf
  tests/scripts/all.sh
  tests/suites/test_suite_x509parse.data
Labels: bug, component: X.509, ready for merge

#3561 Backport 2.7: Always revoke certificate on CRL
  ChangeLog.d/crl-revocationDate.txt
  library/x509_crt.c
  tests/data_files/Makefile
  tests/data_files/Readme-x509.txt
  tests/data_files/crl-futureRevocationDate.pem
  tests/data_files/test-ca.server1.future-crl.db
  tests/data_files/test-ca.server1.future-crl.opensslconf
  tests/scripts/all.sh
  tests/suites/test_suite_x509parse.data
Labels: bug, component: X.509, ready for merge

#3611 Minor fixes in PSA code and tests
  library/psa_crypto_storage.c
  library/psa_its_file.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_hash.function
  tests/suites/test_suite_psa_crypto_metadata.function
  tests/suites/test_suite_psa_its.function
Labels: bug, component: Crypto, needs: ci

#3619 [Baremetal] Change the UECC_SUCCESS return value to 0xCC
  include/tinycrypt/ecc.h
Labels: Arm Contribution, branch: baremetal, needs: ci, needs: review
