Repository Mbed-TLS/mbedtls, pull requests merged in 2020-03, with the labels that each got.

#3050 Fix possible close_notify/ClientHello confusion
  programs/ssl/ssl_client2.c
  tests/ssl-opt.sh
Labels: bug, component: TLS, mbed TLS team, ready for merge

#3060 [backport 2.16] Fix possible close_notify/ClientHello confusion
  programs/ssl/ssl_client2.c
  tests/ssl-opt.sh
Labels: bug, component: TLS, mbed TLS team, ready for merge

#3061 [backport 2.7] Fix possible close_notify/ClientHello confusion
  programs/ssl/ssl_client2.c
  tests/ssl-opt.sh
Labels: bug, component: TLS, mbed TLS team, ready for merge

#3051 Drop requirement for a CLA
  .github/pull_request_template.md
  CONTRIBUTING.md
  LICENSE
  README.md
  apache-2.0.txt
  dco.txt
Labels: enhancement, mbed TLS team, ready for merge

#3062 [backport 2.7] Drop requirement for a CLA
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
  dco.txt
Labels: mbed TLS team, ready for merge

#3063 [backport 2.16] Drop requirement for a CLA
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
  dco.txt
Labels: mbed TLS team, ready for merge

#3067 Fix fuzz_pubkey on valid RSA keys
  programs/fuzz/fuzz_privkey.c
  programs/fuzz/fuzz_pubkey.c
Labels: bug, component: Crypto, mbed TLS team, needs: work

#3082 Fix remaining occurrences of config.pl in all.sh
  tests/scripts/all.sh
Labels: enhancement, mbed TLS team, ready for merge

#3072 Enhance the `output_env.sh` script with GBD and Distro version
  scripts/output_env.sh
Labels: enhancement, mbed TLS team, ready for merge

#3083 Backport 2.16: Enhance the `output_env.sh` script with GBD and Distro version
  scripts/output_env.sh
Labels: enhancement, ready for merge

#3084 Backport 2.7: Enhance the `output_env.sh` script with GBD and Distro version
  scripts/output_env.sh
Labels: enhancement

#3092 test_suite_ssl: check for errors during queue setup
  tests/suites/test_suite_ssl.function
Labels: component: TLS, enhancement, mbed TLS team

#3088 test_suite_ssl: fix coverity issues with uninitialized members
  tests/suites/test_suite_ssl.function
Labels: component: TLS, mbed TLS team, ready for merge

#3086 Add Python, Perl and Pylint to output_env.sh
  scripts/output_env.sh
Labels: enhancement, ready for merge

#3090 Backport 2.16: Add Python, Perl and Pylint to output_env.sh
  scripts/output_env.sh
Labels: enhancement, ready for merge

#3091 Backport 2.7: Add Python, Perl and Pylint to output_env.sh
  scripts/output_env.sh
Labels: enhancement, ready for merge

#3075 Variable buffer size
  include/mbedtls/config.h
  include/mbedtls/ssl.h
  include/mbedtls/ssl_internal.h
  library/ssl_msg.c
  library/ssl_tls.c
  library/version_features.c
  programs/ssl/ssl_server2.c
  programs/test/query_config.c
  tests/scripts/all.sh
  tests/ssl-opt.sh
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: component: TLS, enhancement, ready for merge

#3093 Backport baremetal: Add zlib tests and fix runtime bug
  ChangeLog
  library/ssl_tls.c
  tests/scripts/all.sh
  tests/ssl-opt.sh
Labels: branch: baremetal, component: TLS, ready for merge

#2262 Fix compilation failure when MBEDTLS_SSL_HW_RECORD_ACCEL is enabled
  ChangeLog
  library/ssl_msg.c
  library/ssl_tls.c
  tests/scripts/all.sh
Labels: bug, component: TLS, mbed TLS team, ready for merge

#2439 Backport 2.16: Fix compilation failure when MBEDTLS_SSL_HW_RECORD_ACCEL is enabled
  ChangeLog
  library/ssl_tls.c
  tests/scripts/all.sh
Labels: bug, component: TLS, mbed TLS team, ready for merge

#2440 Backport 2.7: Fix compilation failure when MBEDTLS_SSL_HW_RECORD_ACCEL is enabled
  ChangeLog
  library/ssl_tls.c
  tests/scripts/all.sh
Labels: bug, component: TLS, mbed TLS team, ready for merge

#3100 Change the use of pylint to optionally use pylint3
  scripts/output_env.sh
  tests/scripts/all.sh
  tests/scripts/check-python-files.sh
Labels: ready for merge

#3101 Backport 2.16: Change the use of pylint to optionally use pylint3
  scripts/output_env.sh
  tests/scripts/all.sh
  tests/scripts/check-python-files.sh
Labels: ready for merge

#3105 ssl_srv.c: initialize flags on each iteration of the loop
  library/ssl_srv.c
Labels: component: TLS, enhancement, mbed TLS team, ready for merge

#3103 ssl - improve documentation on mbedtls_ssl_read and PEER_CLOSE_NOTIFY
  include/mbedtls/ssl.h
Labels: component: TLS, mbed TLS team, ready for merge

#3094 Merge documentation from Mbed Crypto
  README.md
Labels: good first issue, mbed TLS team

#3113 Improve some test names in ssl-opt.sh
  tests/ssl-opt.sh
Labels: component: TLS, good first issue, mbed TLS team

#3114 [Backport 2.16] Improve some test names in ssl-opt.sh
  tests/ssl-opt.sh
Labels: component: TLS, good first issue, mbed TLS team

#3115 [Backport 2.7] Improve some test names in ssl-opt.sh
  tests/ssl-opt.sh
Labels: component: TLS, good first issue, mbed TLS team

#3117 Increase test coverage by adding AES and CAMELLIA empty buffer tests
  tests/suites/test_suite_cipher.aes.data
  tests/suites/test_suite_cipher.camellia.data
  tests/suites/test_suite_cipher.gcm.data
Labels: component: Crypto, enhancement, mbed TLS team, ready for merge

#3126 Merge mbed-crypto stragglers 2020-03-25
  ChangeLog.d/README
  scripts/assemble_changelog.py
  tests/suites/test_suite_psa_crypto.function
Labels: component: Crypto, mbed TLS team, ready for merge

#3128 Sort changelog entries by their merge date
  scripts/assemble_changelog.py
Labels: component: Platform, enhancement, mbed TLS team

#3133 assemble_changelog.py: Reformatting to pacify pylint
  scripts/assemble_changelog.py
Labels: mbed TLS team

#3131 makefile: remove unneeded priority dependency from library makefile
  library/Makefile
Labels: component: Crypto, enhancement, mbed TLS team, ready for merge

#3013 Fix debug message by using the correct function name called
  programs/pkey/ecdsa.c
Labels: bug, ready for merge

#3106 [backport 2.16] Fix function name in error message
  programs/pkey/ecdsa.c
Labels: bug, good first issue, ready for merge

#3107 [backport 2.7] Fix function name in error message
  programs/pkey/ecdsa.c
Labels: bug, good first issue

#3140 Fix intermittent crash in test suites with outcome file enabled
  tests/suites/host_test.function
Labels: bug, component: Platform, mbed TLS team, needs: backports

#3143 [2.16 only] Since unmet_dependencies stores integers, represent them as int
  tests/suites/host_test.function
Labels: component: Platform, mbed TLS team, ready for merge

#3134 Add an include path to the doxyfile to fix preprocessing for docs
  doxygen/mbedtls.doxyfile
Labels: good first issue, mbed TLS team, ready for merge
