Repository Mbed-TLS/mbedtls, pull requests merged in 2021-08, with the labels that each got.

#4806 Store TLS version in SSL session structure
  include/mbedtls/ssl.h
  library/ssl_cli.c
  library/ssl_srv.c
  library/ssl_tls.c
  tests/suites/test_suite_ssl.function
Labels: MPS / TLS 1.3, component: TLS, enhancement

#4830 2.16 Backport of #4659
  include/mbedtls/check_config.h
Labels: Community, bug, single-reviewer

#4829 Backport of #4659
  include/mbedtls/check_config.h
Labels: Community, bug, single-reviewer

#4659 Remove duplicated check in `check_config.h`
  include/mbedtls/check_config.h
Labels: Community, bug

#4815 Move MBEDTLS_ERR_xxx Doxygen comments before the definition
  include/mbedtls/aes.h
  include/mbedtls/aria.h
  include/mbedtls/asn1.h
  include/mbedtls/base64.h
  include/mbedtls/bignum.h
  include/mbedtls/camellia.h
  include/mbedtls/ccm.h
  include/mbedtls/chacha20.h
  include/mbedtls/chachapoly.h
  include/mbedtls/cipher.h
  include/mbedtls/ctr_drbg.h
  include/mbedtls/des.h
  include/mbedtls/dhm.h
  include/mbedtls/ecp.h
  include/mbedtls/entropy.h
  include/mbedtls/error.h
  include/mbedtls/gcm.h
  include/mbedtls/hkdf.h
  include/mbedtls/hmac_drbg.h
  include/mbedtls/md.h
  include/mbedtls/net_sockets.h
  include/mbedtls/oid.h
  include/mbedtls/pem.h
  include/mbedtls/pk.h
  include/mbedtls/pkcs12.h
  include/mbedtls/pkcs5.h
  include/mbedtls/poly1305.h
  include/mbedtls/rsa.h
  include/mbedtls/sha1.h
  include/mbedtls/sha256.h
  include/mbedtls/sha512.h
  include/mbedtls/ssl.h
  include/mbedtls/threading.h
  include/mbedtls/x509.h
  scripts/generate_errors.pl
Labels: component: Platform, enhancement, needs: backports, needs: review

#4827 Backport 2.2x: Move MBEDTLS_ERR_xxx Doxygen comments before the definition
  include/mbedtls/aes.h
  include/mbedtls/arc4.h
  include/mbedtls/aria.h
  include/mbedtls/asn1.h
  include/mbedtls/base64.h
  include/mbedtls/bignum.h
  include/mbedtls/blowfish.h
  include/mbedtls/camellia.h
  include/mbedtls/ccm.h
  include/mbedtls/chacha20.h
  include/mbedtls/chachapoly.h
  include/mbedtls/cipher.h
  include/mbedtls/cmac.h
  include/mbedtls/ctr_drbg.h
  include/mbedtls/des.h
  include/mbedtls/dhm.h
  include/mbedtls/ecp.h
  include/mbedtls/entropy.h
  include/mbedtls/error.h
  include/mbedtls/gcm.h
  include/mbedtls/hkdf.h
  include/mbedtls/hmac_drbg.h
  include/mbedtls/md.h
  include/mbedtls/md2.h
  include/mbedtls/md4.h
  include/mbedtls/md5.h
  include/mbedtls/net_sockets.h
  include/mbedtls/oid.h
  include/mbedtls/padlock.h
  include/mbedtls/pem.h
  include/mbedtls/pk.h
  include/mbedtls/pkcs12.h
  include/mbedtls/pkcs5.h
  include/mbedtls/platform.h
  include/mbedtls/poly1305.h
  include/mbedtls/ripemd160.h
  include/mbedtls/rsa.h
  include/mbedtls/sha1.h
  include/mbedtls/sha256.h
  include/mbedtls/sha512.h
  include/mbedtls/ssl.h
  include/mbedtls/threading.h
  include/mbedtls/x509.h
  include/mbedtls/xtea.h
  scripts/generate_errors.pl
Labels: component: Platform, enhancement, needs: review

#4828 Backport 2.16: Move MBEDTLS_ERR_xxx Doxygen comments before the definition
  include/mbedtls/aes.h
  include/mbedtls/arc4.h
  include/mbedtls/aria.h
  include/mbedtls/asn1.h
  include/mbedtls/base64.h
  include/mbedtls/bignum.h
  include/mbedtls/blowfish.h
  include/mbedtls/camellia.h
  include/mbedtls/ccm.h
  include/mbedtls/chacha20.h
  include/mbedtls/chachapoly.h
  include/mbedtls/cipher.h
  include/mbedtls/cmac.h
  include/mbedtls/ctr_drbg.h
  include/mbedtls/des.h
  include/mbedtls/dhm.h
  include/mbedtls/ecp.h
  include/mbedtls/entropy.h
  include/mbedtls/gcm.h
  include/mbedtls/hkdf.h
  include/mbedtls/hmac_drbg.h
  include/mbedtls/md.h
  include/mbedtls/md2.h
  include/mbedtls/md4.h
  include/mbedtls/md5.h
  include/mbedtls/net_sockets.h
  include/mbedtls/oid.h
  include/mbedtls/padlock.h
  include/mbedtls/pem.h
  include/mbedtls/pk.h
  include/mbedtls/pkcs12.h
  include/mbedtls/pkcs5.h
  include/mbedtls/platform.h
  include/mbedtls/poly1305.h
  include/mbedtls/ripemd160.h
  include/mbedtls/rsa.h
  include/mbedtls/sha1.h
  include/mbedtls/sha256.h
  include/mbedtls/sha512.h
  include/mbedtls/ssl.h
  include/mbedtls/threading.h
  include/mbedtls/x509.h
  include/mbedtls/xtea.h
  scripts/generate_errors.pl
Labels: component: Platform, single-reviewer

#4695 ssl-opt.sh: Skip tests instead of conditional hard abort
  tests/ssl-opt.sh
Labels: Arm Contribution, bug, component: test, needs: backports, size:S

#4697 Backport 2.16: ssl-opt.sh: Skip tests instead of conditional hard abort
  tests/ssl-opt.sh
Labels: Arm Contribution, bug, component: test, size:S

#4696 Backport 2.x: ssl-opt.sh: Skip tests instead of conditional hard abort
  tests/ssl-opt.sh
Labels: Arm Contribution, bug, component: test, size:S

#4746 Fix release scripts for 3.0
  scripts/bump_version.sh
  tests/scripts/check-generated-files.sh
Labels: bug, ready for merge, component: Platform

#4853 TLS1_3:add tls13 config check and dummy handshake
  library/CMakeLists.txt
  library/Makefile
  library/ssl_misc.h
  library/ssl_tls.c
  library/ssl_tls13_client.c
  library/ssl_tls13_server.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  tests/ssl-opt.sh
  tests/suites/test_suite_debug.function
Labels: needs: review, component: TLS, needs: ci, MPS / TLS 1.3, size:S

#4851 Add handshake message writing variant that doesn't update checksum
  library/ssl_misc.h
  library/ssl_msg.c
Labels: ready for merge, component: TLS, MPS / TLS 1.3, size:S

#4834 Move messaging related session reset into separate helper function
  library/ssl_tls.c
Labels: enhancement, ready for merge, mbed TLS team, component: TLS

#4858 Upstream TLS 1.3 record transformations structure fields
  include/mbedtls/ssl.h
  library/ssl_misc.h
  library/ssl_tls.c
Labels: ready for merge, component: TLS, MPS / TLS 1.3

#3572 Add arm-linux-gnueabi-gcc build
  .travis.yml
  tests/scripts/all.sh
Labels: enhancement, ready for merge, mbed TLS team, component: Platform, Product Backlog, size:S

#4855 Backport 2.x: Add arm-linux-gnueabi-gcc build
  .travis.yml
  tests/scripts/all.sh
Labels: enhancement, ready for merge

#4856 Backport 2.16: Add arm-linux-gnueabi-gcc build
  .travis.yml
  tests/scripts/all.sh
Labels: enhancement, ready for merge

#4861 Add openssl/gnutls tls1.3 feature tests.
  tests/ssl-opt.sh
Labels: ready for merge, component: TLS, MPS / TLS 1.3

#4413 Allow configuring MBEDTLS_TLS_EXT_CID at compile time
  ChangeLog.d/tls_ext_cid-config.txt
  include/mbedtls/mbedtls_config.h
  include/mbedtls/ssl.h
Labels: ready for merge, mbed TLS team, component: TLS

#4427 Backport 2.x: Allow configuring MBEDTLS_TLS_EXT_CID at compile time
  ChangeLog.d/tls_ext_cid-config.txt
  include/mbedtls/config.h
  include/mbedtls/ssl.h
  programs/test/query_config.c
Labels: ready for merge, mbed TLS team, component: TLS, single-reviewer

#4807 Document that returning 0 from the recv callback means EOF
  include/mbedtls/ssl.h
Labels: enhancement, ready for merge, component: TLS

#4873 Backport 2.x: Document that returning 0 from the recv callback means EOF
  include/mbedtls/ssl.h
Labels: enhancement, ready for merge, single-reviewer

#4874 Backport 2.16: Document that returning 0 from the recv callback means EOF
  include/mbedtls/ssl.h
Labels: enhancement, ready for merge, single-reviewer

#4872 Update CMake version for CMP0090
  CMakeLists.txt
Labels: needs: review, Community, size:S, single-reviewer

#4864 TLS 1.3 MVP: Upstream TLS 1.3 SignatureAlgorithm identifiers and configuration API
  include/mbedtls/ssl.h
  library/ssl_tls.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
Labels: ready for merge, component: TLS, MPS / TLS 1.3

#4890 Misprint was fixed
  include/mbedtls/ssl.h
Labels: bug, fix available, size:S, single-reviewer

#4841 Backport 2.x: Byte reading macros
  library/aes.c
  library/aria.c
  library/asn1write.c
  library/base64.c
  library/blowfish.c
  library/camellia.c
  library/ccm.c
  library/chacha20.c
  library/chachapoly.c
  library/common.h
  library/ctr_drbg.c
  library/des.c
  library/dhm.c
  library/ecjpake.c
  library/ecp.c
  library/gcm.c
  library/md4.c
  library/md5.c
  library/nist_kw.c
  library/pkcs12.c
  library/poly1305.c
  library/psa_crypto.c
  library/psa_crypto_storage.c
  library/psa_its_file.c
  library/ripemd160.c
  library/sha1.c
  library/sha256.c
  library/sha512.c
  library/ssl_cli.c
  library/ssl_cookie.c
  library/ssl_msg.c
  library/ssl_srv.c
  library/ssl_ticket.c
  library/ssl_tls.c
  library/ssl_tls13_keys.c
  library/x509write_crt.c
  library/xtea.c
Labels: enhancement, size:S

#4716 Byte Reading Macros
  library/aes.c
  library/aria.c
  library/asn1write.c
  library/base64.c
  library/camellia.c
  library/ccm.c
  library/chacha20.c
  library/chachapoly.c
  library/common.h
  library/ctr_drbg.c
  library/des.c
  library/dhm.c
  library/ecjpake.c
  library/ecp.c
  library/gcm.c
  library/md5.c
  library/nist_kw.c
  library/pkcs12.c
  library/poly1305.c
  library/psa_crypto.c
  library/psa_crypto_storage.c
  library/psa_its_file.c
  library/ripemd160.c
  library/sha1.c
  library/sha256.c
  library/sha512.c
  library/ssl_cli.c
  library/ssl_cookie.c
  library/ssl_msg.c
  library/ssl_srv.c
  library/ssl_ticket.c
  library/ssl_tls.c
  library/ssl_tls13_keys.c
  library/x509write_crt.c
Labels: enhancement, Arm Contribution, needs: backports, size:S

#4811 Add TLS 1.3 ciphersuite and key exchange identifiers and API
  include/mbedtls/ssl.h
  include/mbedtls/ssl_ciphersuites.h
  library/ssl_ciphersuites.c
  library/ssl_tls.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  tests/scripts/all.sh
  tests/ssl-opt.sh
Labels: enhancement, ready for merge, MPS / TLS 1.3
