Repository Mbed-TLS/mbedtls, pull requests merged in 2021-04, with the labels that each got.

#4198 PSA Update return code for non-existing key in various key operations
  ChangeLog.d/fix_return_type_for_invalid_crypto_key.txt
  library/psa_crypto_slot_management.c
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_slot_management.data
  tests/suites/test_suite_psa_crypto_slot_management.function
Labels: PSA compliance, bug, needs: work, size:S

#3512 Reduce the number of allocations in ECP operations
  library/bignum.c
  library/ecp_curves.c
  programs/test/benchmark.c
Labels: component: Crypto, enhancement, ready for merge

#3615 Speed up ssl-opt.sh when running a small number of test cases
  tests/ssl-opt.sh
Labels: component: TLS, enhancement, ready for merge

#3905 Backport 2.16: Speed up ssl-opt.sh when running a small number of test cases
  tests/ssl-opt.sh
Labels: component: TLS, ready for merge

#4281 Remove missing reference
  docs/architecture/testing/invasive-testing.md
Labels: mbedtls-3, ready for merge

#4279 Fix error code when creating/registering a key with invalid id
  ChangeLog.d/fix-invalid-id-error-code.txt
  include/psa/crypto_extra.h
  library/psa_crypto.c
  library/psa_crypto_slot_management.c
  library/psa_crypto_slot_management.h
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_persistent_key.data
  tests/suites/test_suite_psa_crypto_se_driver_hal.data
  tests/suites/test_suite_psa_crypto_slot_management.data
Labels: PSA compliance, component: PSA, enhancement, ready for merge

#3183 RSA PSS signature generation with the option to specify the salt length (proposed solution for issue #3152)
  ChangeLog.d/pkcs1_v21_sign_ext.txt
  include/mbedtls/rsa.h
  library/rsa.c
  tests/suites/test_suite_pkcs1_v21.data
  tests/suites/test_suite_pkcs1_v21.function
  tests/suites/test_suite_rsa.function
Labels: Community, component: Crypto, enhancement, needs: review

#4174 PSA Encodings for EdDSA
  include/psa/crypto.h
  include/psa/crypto_extra.h
  include/psa/crypto_values.h
  programs/Makefile
  programs/psa/psa_constant_names_generated.c
  scripts/mbedtls_dev/asymmetric_key_data.py
  scripts/mbedtls_dev/crypto_knowledge.py
  tests/suites/test_suite_psa_crypto_metadata.data
  tests/suites/test_suite_psa_crypto_metadata.function
  tests/suites/test_suite_psa_crypto_not_supported.generated.data
  tests/suites/test_suite_psa_crypto_storage_format.current.data
  tests/suites/test_suite_psa_crypto_storage_format.v0.data
Labels: component: Crypto, component: PSA, enhancement, mbed TLS team, needs: review

#4309 Make check-names.sh accept any grep
  tests/scripts/check-names.sh
Labels: enhancement, needs: backports, needs: review, needs: reviewer, size:S

#4308 Forwardport 3.0: Make check-names.sh accept FreeBSD grep
  tests/scripts/check-names.sh
Labels: enhancement, needs: review

#4310 Backport 2.16: Make check-names.sh accept any grep
  tests/scripts/check-names.sh
Labels: enhancement, needs: review, size:S

#4306 Capitalise MPS trace macros
  library/mps_common.h
  library/mps_reader.c
  library/mps_trace.c
  library/mps_trace.h
  tests/scripts/list-enum-consts.pl
Labels: MPS / TLS 1.3, bug, component: TLS, needs: ci

#4290 Hash dispatch follow up
  include/psa/crypto_builtin.h
  include/psa/crypto_builtin_cipher.h
  include/psa/crypto_driver_contexts.h
  include/psa/crypto_struct.h
  library/psa_crypto_hash.c
  library/psa_crypto_hash.h
  visualc/VS2010/mbedTLS.vcxproj
Labels: component: PSA, enhancement, needs: review, needs: reviewer

#4318 Fix reference to deprecated macro in documentation
  include/psa/crypto.h
Labels: needs: ci

#4311 [3.0] Remove obsolete reference to internal headers under include/
  doxygen/mbedtls.doxyfile
Labels: component: Platform, enhancement, ready for merge

#4297 Fix ECP arithmetic bug and read of zero-padded negative number
  library/bignum.c
  library/ecp.c
  library/ecp_curves.c
  library/ecp_invasive.h
  tests/suites/test_suite_ecp.data
  tests/suites/test_suite_ecp.function
  tests/suites/test_suite_mpi.data
  visualc/VS2010/mbedTLS.vcxproj
Labels: bug, component: Crypto, mbed TLS team, needs: ci

#4337 Backport 2.16: Make assemble changelog script enforce line length
  scripts/assemble_changelog.py
Labels: enhancement, mbed TLS team, needs: review

#4323 Changelog entry for mbedtls_mpi_read_string("-0")
  ChangeLog.d/mpi_read_negative_zero.txt
Labels: bug, component: Crypto, mbed TLS team, ready for merge

#4324 Remove MBEDTLS_SSL_DEFAULT_TICKET_LIFETIME
  configs/config-psa-crypto.h
  include/mbedtls/config.h
  include/mbedtls/ssl.h
  programs/test/query_config.c
Labels: component: TLS, enhancement, mbedtls-3, needs: review, needs: reviewer

#4257 Add PSA crypto driver delegation for AEAD single shot PSA APIs - 1
  library/CMakeLists.txt
  library/Makefile
  library/psa_crypto.c
  library/psa_crypto_aead.c
  library/psa_crypto_aead.h
  library/psa_crypto_core.h
  library/psa_crypto_driver_wrappers.c
  library/psa_crypto_driver_wrappers.h
  tests/include/test/drivers/aead.h
  tests/include/test/drivers/test_driver.h
  tests/src/drivers/aead.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
  visualc/VS2010/mbedTLS.vcxproj
Labels: HwDrivers, mbed TLS team, ready for merge

#4334 Remove deprecated things from hashing modules
  ChangeLog.d/issue4280.txt
  include/mbedtls/md.h
  include/mbedtls/md2.h
  include/mbedtls/md4.h
  include/mbedtls/md5.h
  include/mbedtls/ripemd160.h
  include/mbedtls/sha1.h
  include/mbedtls/sha256.h
  include/mbedtls/sha512.h
  library/error.c
  library/md.c
  library/md2.c
  library/md4.c
  library/md5.c
  library/psa_crypto.c
  library/ripemd160.c
  library/sha1.c
  library/sha256.c
  library/sha512.c
Labels: mbedtls-3, ready for merge

#4253 Allow changelog entries to have URLs exceeding 80 char limit.
  scripts/assemble_changelog.py
Labels: enhancement, needs: backports

#4346 Backport 2.16: Allow changelog entries to have URLs exceeding 80 char limit.
  scripts/assemble_changelog.py
Labels: enhancement, needs: review, needs: reviewer

#4322 Backport 2.16: Test read of zero-padded negative number
  ChangeLog.d/mpi_read_negative_zero.txt
  library/bignum.c
  library/ecp_curves.c
  tests/suites/test_suite_ecp.data
  tests/suites/test_suite_ecp.function
  tests/suites/test_suite_mpi.data
Labels: bug, component: Crypto, enhancement, mbed TLS team, ready for merge

#4348 Revert 4334 from development
  ChangeLog.d/issue4280.txt
  include/mbedtls/md.h
  include/mbedtls/md2.h
  include/mbedtls/md4.h
  include/mbedtls/md5.h
  include/mbedtls/ripemd160.h
  include/mbedtls/sha1.h
  include/mbedtls/sha256.h
  include/mbedtls/sha512.h
  library/error.c
  library/md.c
  library/md2.c
  library/md4.c
  library/md5.c
  library/psa_crypto.c
  library/ripemd160.c
  library/sha1.c
  library/sha256.c
  library/sha512.c
Labels: bug, ready for merge

#4156 Drop support for obsolete SSL/TLS features
  CMakeLists.txt
  ChangeLog.d/remove_obsolete_tls_features.txt
  configs/config-no-entropy.h
  configs/config-psa-crypto.h
  doxygen/input/doc_mainpage.h
  include/mbedtls/check_config.h
  include/mbedtls/config.h
  include/mbedtls/ssl.h
  include/mbedtls/ssl_ciphersuites.h
  library/CMakeLists.txt
  library/error.c
  library/ssl_ciphersuites.c
  library/ssl_cli.c
  library/ssl_misc.h
  library/ssl_msg.c
  library/ssl_srv.c
  library/ssl_tls.c
  library/version_features.c
  programs/Makefile
  programs/fuzz/CMakeLists.txt
  programs/fuzz/Makefile
  programs/ssl/CMakeLists.txt
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  programs/test/CMakeLists.txt
  programs/test/query_config.c
  programs/x509/CMakeLists.txt
  scripts/config.py
  tests/CMakeLists.txt
  tests/Makefile
  tests/compat.sh
  tests/scripts/all.sh
  tests/scripts/basic-build-test.sh
  tests/ssl-opt.sh
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: mbedtls-3, ready for merge

#4266 Remove optional SHA-1 in the default TLS configuration.
  ChangeLog.d/remove_allow_sha1_in_certificates
  configs/config-psa-crypto.h
  include/mbedtls/config.h
  library/x509_crt.c
  programs/test/query_config.c
  tests/scripts/all.sh
  tests/ssl-opt.sh
  tests/suites/test_suite_x509parse.data
Labels: mbedtls-3, ready for merge

#4199 Fix ECDSA failing when the hash is all-bits-zero
  ChangeLog.d/issue1792.txt
  library/ecjpake.c
  library/ecp.c
  tests/suites/test_suite_ecdsa.data
  tests/suites/test_suite_ecdsa.function
  tests/suites/test_suite_ecjpake.data
Labels: Community, bug, ready for merge

#4344 Remove deprecated things from crypto_compat.h and dependent tests.
  ChangeLog.d/issue4284.txt
  docs/proposed/psa-driver-interface.md
  include/psa/crypto_compat.h
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
  tests/suites/test_suite_psa_crypto_entropy.function
Labels: mbedtls-3, ready for merge, size:S

#4366 Merge development 2.x into 3.0 (Apr 19)
  ChangeLog.d/issue1792.txt
  ChangeLog.d/mpi_read_negative_zero.txt
  include/psa/crypto.h
  include/psa/crypto_builtin.h
  include/psa/crypto_builtin_cipher.h
  include/psa/crypto_driver_contexts.h
  include/psa/crypto_struct.h
  library/CMakeLists.txt
  library/Makefile
  library/bignum.c
  library/ecjpake.c
  library/ecp.c
  library/ecp_curves.c
  library/ecp_invasive.h
  library/psa_crypto.c
  library/psa_crypto_aead.c
  library/psa_crypto_aead.h
  library/psa_crypto_core.h
  library/psa_crypto_driver_wrappers.c
  library/psa_crypto_driver_wrappers.h
  library/psa_crypto_hash.c
  library/psa_crypto_hash.h
  scripts/assemble_changelog.py
  tests/include/test/drivers/aead.h
  tests/include/test/drivers/test_driver.h
  tests/src/drivers/aead.c
  tests/suites/test_suite_ecdsa.data
  tests/suites/test_suite_ecdsa.function
  tests/suites/test_suite_ecjpake.data
  tests/suites/test_suite_ecp.data
  tests/suites/test_suite_ecp.function
  tests/suites/test_suite_mpi.data
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
  visualc/VS2010/mbedTLS.vcxproj
Labels: mbedtls-3, needs: review, needs: reviewer

#4391 Error on removed options
  include/mbedtls/check_config.h
  tests/scripts/check-names.sh
Labels: component: Platform, mbed TLS team, mbedtls-3, ready for merge

#4254 Remove PKCS#11 library wrapper.
  CMakeLists.txt
  ChangeLog.d/remove_pkcs11.txt
  configs/config-psa-crypto.h
  include/mbedtls/check_config.h
  include/mbedtls/config.h
  include/mbedtls/pkcs11.h
  library/CMakeLists.txt
  library/Makefile
  library/pkcs11.c
  library/version_features.c
  programs/Makefile
  programs/fuzz/CMakeLists.txt
  programs/ssl/CMakeLists.txt
  programs/test/CMakeLists.txt
  programs/test/cpp_dummy_build.cpp
  programs/test/query_config.c
  programs/x509/CMakeLists.txt
  scripts/config.py
  scripts/data_files/query_config.fmt
  tests/CMakeLists.txt
  tests/Makefile
  visualc/VS2010/mbedTLS.vcxproj
Labels: mbedtls-3, ready for merge

#4349 Apply 4334 to development-3.0
  ChangeLog.d/issue4280.txt
  include/mbedtls/md.h
  include/mbedtls/md2.h
  include/mbedtls/md4.h
  include/mbedtls/md5.h
  include/mbedtls/ripemd160.h
  include/mbedtls/sha1.h
  include/mbedtls/sha256.h
  include/mbedtls/sha512.h
  library/error.c
  library/md.c
  library/md2.c
  library/md4.c
  library/md5.c
  library/psa_crypto.c
  library/ripemd160.c
  library/sha1.c
  library/sha256.c
  library/sha512.c
Labels: mbedtls-3, ready for merge

#4380 Fix unchecked return value in bignum
  library/bignum.c
Labels: component: Crypto, mbed TLS team, needs: reviewer, size:S

#4339 Remove deprecated error codes.
  ChangeLog.d/issue4283.txt
  include/mbedtls/aes.h
  include/mbedtls/arc4.h
  include/mbedtls/aria.h
  include/mbedtls/blowfish.h
  include/mbedtls/camellia.h
  include/mbedtls/ccm.h
  include/mbedtls/chacha20.h
  include/mbedtls/cipher.h
  include/mbedtls/cmac.h
  include/mbedtls/des.h
  include/mbedtls/dhm.h
  include/mbedtls/ecp.h
  include/mbedtls/error.h
  include/mbedtls/gcm.h
  include/mbedtls/md.h
  include/mbedtls/pk.h
  include/mbedtls/platform.h
  include/mbedtls/poly1305.h
  include/mbedtls/psa_util.h
  include/mbedtls/rsa.h
  include/mbedtls/threading.h
  include/mbedtls/xtea.h
  library/cipher.c
  library/error.c
  library/pk.c
  library/pk_wrap.c
  library/pkwrite.c
  library/psa_crypto.c
  library/ssl_tls.c
  tests/suites/test_suite_rsa.function
Labels: mbedtls-3, ready for merge, size:S

#4160 Add implementation for MBEDTLS_PSA_CRYPTO_BUILTIN_KEYS
  ChangeLog.d/psa-builtin-keys-implementation.txt
  docs/proposed/psa-driver-interface.md
  include/mbedtls/config.h
  include/psa/crypto_extra.h
  library/psa_crypto.c
  library/psa_crypto_core.h
  library/psa_crypto_driver_wrappers.c
  library/psa_crypto_driver_wrappers.h
  library/psa_crypto_slot_management.c
  library/version_features.c
  programs/test/query_config.c
  scripts/generate_visualc_files.pl
  tests/include/test/drivers/key_management.h
  tests/include/test/drivers/test_driver.h
  tests/scripts/all.sh
  tests/src/drivers/key_management.c
  tests/src/drivers/platform_builtin_keys.c
  tests/src/drivers/test_driver_aead.c
  tests/src/drivers/test_driver_cipher.c
  tests/src/drivers/test_driver_key_management.c
  tests/src/drivers/test_driver_signature.c
  tests/src/drivers/test_driver_size.c
  tests/suites/test_suite_psa_crypto_driver_wrappers.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
  visualc/VS2010/mbedTLS.vcxproj
Labels: Community, HwDrivers, component: Crypto, enhancement, ready for merge

#4359 Backport 2.16: Disable debugging features in baremetal
  scripts/config.pl
Labels: component: Platform, enhancement, mbed TLS team

#4432 [backport 2.x] Add missing parenthesis when MBEDTLS_ECP_NORMALIZE_MXZ_ALT is declared
  ChangeLog.d/add-missing-parenthesis.txt
  library/ecp.c
Labels: Community, bug, size:S

#4219 Add missing parenthesis when MBEDTLS_ECP_NORMALIZE_MXZ_ALT is declared
  ChangeLog.d/add-missing-parenthesis.txt
  library/ecp.c
Labels: Community, bug, needs: backports, needs: review, size:S

#4243 PSA: Update AEAD output buffer macros to PSA API version 1.0
  ChangeLog.d/psa-aead-output-size-macros-1.0.txt
  include/psa/crypto.h
  include/psa/crypto_compat.h
  include/psa/crypto_sizes.h
  include/psa/crypto_values.h
  library/psa_crypto_aead.c
  programs/psa/key_ladder_demo.c
  programs/psa/psa_constant_names_generated.c
  scripts/generate_psa_constants.py
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
  tests/suites/test_suite_psa_crypto_metadata.data
  tests/suites/test_suite_psa_crypto_metadata.function
Labels: PSA compliance, needs: backports, ready for merge

#4241 [backport 2.16] Add missing parenthesis when MBEDTLS_ECP_NORMALIZE_MXZ_ALT is declared
  ChangeLog.d/add-missing-parenthesis.txt
  library/ecp.c
Labels: Community, bug, needs: review, size:S

#4433 [development] PSA: Update AEAD output buffer macros to PSA API version 1.0
  ChangeLog.d/psa-aead-output-size-macros-1.0.txt
  include/psa/crypto.h
  include/psa/crypto_sizes.h
  include/psa/crypto_values.h
  library/psa_crypto_aead.c
  programs/psa/key_ladder_demo.c
  programs/psa/psa_constant_names_generated.c
  scripts/generate_psa_constants.py
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
  tests/suites/test_suite_psa_crypto_metadata.data
  tests/suites/test_suite_psa_crypto_metadata.function
Labels: PSA compliance, ready for merge

#4436 Backport 2.16: Add macro to check error code additions/combinations
  ChangeLog.d/fix-pk-parse-key-error-code.txt
  library/pkparse.c
Labels: bug, component: Crypto, mbed TLS team, needs: review

#4434 Backport 2.x: Add macro to check error code additions/combinations
  ChangeLog.d/fix-pk-parse-key-error-code.txt
  include/mbedtls/error.h
  library/dhm.c
  library/ecdsa.c
  library/error.c
  library/pem.c
  library/pkcs12.c
  library/pkcs5.c
  library/pkparse.c
  library/rsa.c
  library/ssl_cookie.c
  library/x509.c
  library/x509_crl.c
  library/x509_crt.c
  library/x509_csr.c
  scripts/data_files/error.fmt
  tests/include/test/helpers.h
  tests/src/helpers.c
  tests/suites/main_test.function
  tests/suites/test_suite_x509parse.function
Labels: component: Platform, ready for merge

#3777 Reduce ROM usage due to X.509 info
  ChangeLog.d/x509_remove_info.txt
  include/mbedtls/config.h
  include/mbedtls/debug.h
  include/mbedtls/oid.h
  include/mbedtls/x509.h
  include/mbedtls/x509_crl.h
  include/mbedtls/x509_crt.h
  include/mbedtls/x509_csr.h
  library/debug.c
  library/oid.c
  library/version_features.c
  library/x509.c
  library/x509_crl.c
  library/x509_crt.c
  library/x509_csr.c
  programs/fuzz/fuzz_x509crl.c
  programs/fuzz/fuzz_x509crt.c
  programs/fuzz/fuzz_x509csr.c
  programs/ssl/dtls_client.c
  programs/ssl/ssl_client1.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_context_info.c
  programs/ssl/ssl_mail_client.c
  programs/ssl/ssl_server2.c
  programs/ssl/ssl_test_common_source.c
  programs/test/query_config.c
  programs/x509/cert_app.c
  programs/x509/crl_app.c
  programs/x509/req_app.c
  scripts/config.py
  tests/scripts/all.sh
  tests/ssl-opt.sh
  tests/suites/test_suite_debug.data
  tests/suites/test_suite_debug.function
  tests/suites/test_suite_oid.function
  tests/suites/test_suite_x509parse.data
  tests/suites/test_suite_x509parse.function
Labels: Community, component: X.509, enhancement, ready for merge

#3950 Enforce dhm_min_bitlen exactly
  ChangeLog.d/dhm_min_bitlen.txt
  library/ssl_cli.c
  tests/data_files/Makefile
  tests/data_files/dh.998.pem
  tests/data_files/dh.999.pem
  tests/ssl-opt.sh
Labels: bug, component: TLS, mbed TLS team

#4430 Backport 2.x: Enforce dhm_min_bitlen exactly
  ChangeLog.d/dhm_min_bitlen.txt
  library/ssl_cli.c
  tests/data_files/Makefile
  tests/data_files/dh.998.pem
  tests/data_files/dh.999.pem
  tests/ssl-opt.sh
Labels: bug, component: TLS, mbed TLS team

#4325 Backport 2.16: Enforce dhm_min_bitlen exactly
  ChangeLog.d/dhm_min_bitlen.txt
  library/ssl_cli.c
  tests/data_files/Makefile
  tests/data_files/dh.998.pem
  tests/data_files/dh.999.pem
  tests/ssl-opt.sh
Labels: bug, component: TLS, mbed TLS team

#4146 Allow CMAC self-test to skip tests for unsupported primitives (2)
  ChangeLog.d/allow_alt_cmac_without_des.txt
  include/mbedtls/cmac.h
  include/mbedtls/config.h
  library/cmac.c
Labels: Community, HwDrivers, component: Crypto, needs: review

#4437 Remove the sample program aescrypt2
  ChangeLog.d/aescrypt2.txt
  programs/.gitignore
  programs/Makefile
  programs/README.md
  programs/aes/CMakeLists.txt
  programs/aes/aescrypt2.c
  visualc/VS2010/aescrypt2.vcxproj
  visualc/VS2010/mbedTLS.sln
Labels: bug, component: Crypto, ready for merge

#4438 Backport 2.x: Remove the sample program aescrypt2
  ChangeLog.d/aescrypt2.txt
  programs/.gitignore
  programs/Makefile
  programs/README.md
  programs/aes/CMakeLists.txt
  programs/aes/aescrypt2.c
  visualc/VS2010/aescrypt2.vcxproj
  visualc/VS2010/mbedTLS.sln
Labels: bug, component: Crypto, ready for merge

#4439 Backport 2.16: Remove the sample program aescrypt2
  ChangeLog.d/aescrypt2.txt
  programs/.gitignore
  programs/Makefile
  programs/README.md
  programs/aes/CMakeLists.txt
  programs/aes/aescrypt2.c
  visualc/VS2010/aescrypt2.vcxproj
  visualc/VS2010/mbedTLS.sln
Labels: bug, component: Crypto, ready for merge

#4448 [Backport 2.x] Allow CMAC_ALT implementations to not support 3DES
  ChangeLog.d/allow_alt_cmac_without_des.txt
  include/mbedtls/cmac.h
  include/mbedtls/config.h
  library/cmac.c
Labels: ready for merge
