Repository Mbed-TLS/mbedtls, pull requests merged in 2022-02, with the labels that each got.

#5469 Don't inline mbedtls_mpi_safe_cond_assign on MSVC/ARM64 to avoid a compiler bug
  library/constant_time.c
Labels: bug, approved, Community

#5468 Backport 2.28: Don't inline mbedtls_mpi_safe_cond_assign on MSVC/ARM64 to avoid a compiler bug
  library/constant_time.c
Labels: bug, approved, Community, single-reviewer

#5385 Resolve problems with reduced configs using USE_PSA_CRYPTO
  ChangeLog.d/psa_crypto_reduced_configs.txt
  ChangeLog.d/psa_crypto_reduced_configs_bugs.txt
  configs/config-ccm-psk-tls1_2.h
  configs/config-suite-b.h
  configs/config-thread.h
  include/mbedtls/build_info.h
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  tests/scripts/test-ref-configs.pl
  tests/src/psa_exercise_key.c
  tests/suites/test_suite_cipher.gcm.data
  tests/suites/test_suite_psa_crypto.function
Labels: bug, approved, mbed TLS team, component: test

#5444 Backport 2.28: Resolve problems with reduced configs using USE_PSA_CRYPTO
  ChangeLog.d/psa_crypto_reduced_configs_bugs.txt
  configs/config-ccm-psk-tls1_2.h
  configs/config-mini-tls1_1.h
  configs/config-suite-b.h
  configs/config-thread.h
  include/mbedtls/check_config.h
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  tests/scripts/test-ref-configs.pl
  tests/src/psa_exercise_key.c
  tests/suites/test_suite_cipher.gcm.data
  tests/suites/test_suite_psa_crypto.function
Labels: approved, mbed TLS team, component: test

#5255 Backport 2.28: Return an error from `mbedtls_cipher_set_iv` for an invalid IV length with ChaCha20 and ChaCha20+Poly
  ChangeLog.d/chacha20_invalid_iv_len_fix.txt
  library/cipher.c
  tests/suites/test_suite_cipher.chacha20.data
  tests/suites/test_suite_cipher.chachapoly.data
  tests/suites/test_suite_cipher.function
Labels: approved, mbed TLS team, component: Crypto

#5462 Clarify key types message from ssl_client2 and ssl_server2
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  tests/ssl-opt.sh
Labels: enhancement, approved, component: TLS, size:S

#5461 Backport 2.28: Add positive test case with self-signed certificates
  tests/ssl-opt.sh
Labels: enhancement, approved, component: TLS

#5463 CMake: generate the list of test suites automatically
  tests/CMakeLists.txt
  tests/scripts/all.sh
Labels: bug, enhancement, approved, component: Platform, size:S

#5465 Backport 2.28: CMake: generate the list of test suites automatically
  tests/CMakeLists.txt
  tests/scripts/all.sh
Labels: bug, enhancement, approved, component: Platform, size:S

#5502 Backport 2.28 - Add tests for an opaque import in the driver wrappers
  tests/include/test/drivers/key_management.h
  tests/src/drivers/test_driver_key_management.c
  tests/suites/test_suite_psa_crypto_driver_wrappers.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
Labels: approved, mbed TLS team, component: PSA

#5282 Add tests for an opaque import in the driver wrappers
  tests/include/test/drivers/key_management.h
  tests/src/drivers/test_driver_key_management.c
  tests/suites/test_suite_psa_crypto_driver_wrappers.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
Labels: mbed TLS team, needs: backports, component: PSA

#5434 TLS Cipher: use PSA crypto
  library/ssl_misc.h
  library/ssl_msg.c
  library/ssl_srv.c
  library/ssl_tls.c
  library/ssl_tls13_keys.c
  tests/ssl-opt.sh
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: approved, mbed TLS team, component: Crypto, component: PSA

#5080 add tls1_3 read certificate request
  library/ssl_misc.h
  library/ssl_tls.c
  library/ssl_tls13_client.c
  library/ssl_tls13_generic.c
  tests/ssl-opt.sh
Labels: needs: work, MPS / TLS 1.3

#5472 Move client_auth to handshake
  include/mbedtls/ssl.h
  library/ssl_cli.c
  library/ssl_misc.h
  library/ssl_tls.c
Labels: enhancement, approved

#5004 Document PSA migration strategy
  docs/architecture/psa-migration/psa-limitations.md
  docs/architecture/psa-migration/strategy.md
  docs/architecture/psa-migration/syms.sh
  docs/architecture/psa-migration/tasks-g2.md
  docs/architecture/psa-migration/testing.md
  docs/use-psa-crypto.md
Labels: approved, size:S

#5501 Add mbedtls_ssl_ticket_rotate() for ticket rotation
  ChangeLog.d/mbedtls_ssl_ticket_rotate.txt
  include/mbedtls/ssl_ticket.h
  library/ssl_ticket.c
  programs/ssl/ssl_server2.c
  tests/ssl-opt.sh
Labels: approved, Community, size:S

#5522 Fixup psa migration documentation
  docs/architecture/psa-migration/psa-limitations.md
Labels: approved, single-reviewer

#5456 Cleanup PSA-based ECDHE in TLS 1.2
  ChangeLog.d/use-psa-ecdhe-curve.txt
  include/mbedtls/psa_util.h
  library/ssl_cli.c
  library/ssl_misc.h
  library/ssl_tls.c
Labels: bug, enhancement, approved

#5536 [Backport 2.28] Fix PSA-based ECDH in TLS 1.2
  ChangeLog.d/use-psa-ecdhe-curve.txt
  include/mbedtls/ssl_internal.h
  library/ssl_cli.c
  library/ssl_tls.c
Labels: bug, approved

#5449 2.28 only: Any package used in a script must be listed in ci.requirements.txt
  scripts/ci.requirements.txt
  scripts/maintainer.requirements.txt
Labels: enhancement, approved, component: Platform, size:S

#5459 Backport 2.28: check_test_cases.py --list
  tests/scripts/analyze_outcomes.py
  tests/scripts/check_test_cases.py
Labels: enhancement, needs: review, size:S, component: test

#5393 Fix test suite name reporting of opt-testcases/tls13-compat.sh
  tests/scripts/analyze_outcomes.py
  tests/scripts/check_test_cases.py
  tests/ssl-opt.sh
Labels: approved, needs: backports, size:S

#5533 Fix null context when using dummy_rand with mbedtls_pk_parse_key()
  programs/fuzz/common.c
  programs/fuzz/fuzz_dtlsserver.c
  programs/fuzz/fuzz_privkey.c
Labels: bug, approved, size:S, component: test

#5532 Make TLS 1.3 compatible with MBEDTLS_USE_PSA_CRYPTO
  ChangeLog.d/tls13_and_use_psa_crypto.txt
  docs/architecture/tls13-support.md
  library/ssl_tls.c
  tests/opt-testcases/tls13-compat.sh
  tests/scripts/generate_tls13_compat_tests.py
  tests/ssl-opt.sh
Labels: approved, component: TLS, MPS / TLS 1.3

#5377 Minor improvements to ECC arithmetic subroutines
  library/ecp.c
Labels: enhancement, approved, component: Crypto, needs: preceding PR

#5511 feat: Update test_suite_psa_its to NOT use UID=0
  ChangeLog.d/PSA-test-suites-NOT-using-UID-0.txt
  library/psa_its_file.c
  tests/suites/test_suite_psa_its.data
  tests/suites/test_suite_psa_its.function
Labels: bug, approved, component: PSA

#5546 Backport 2.28: feat: Update test_suite_psa_its to NOT use UID=0
  ChangeLog.d/PSA-test-suites-NOT-using-UID-0.txt
  library/psa_its_file.c
  tests/suites/test_suite_psa_its.data
  tests/suites/test_suite_psa_its.function
Labels: bug, approved, component: PSA, single-reviewer

#5551 Require an older version of markupsafe for the sake of older Jinja2
  scripts/driver.requirements.txt
Labels: bug, needs: review, needs: ci, needs: reviewer, regression, component: test

#5520 HKDF 1b: Implement Expand in TLS 1.3 based on PSA HMAC
  library/ssl_tls13_invasive.h
  library/ssl_tls13_keys.c
  tests/suites/test_suite_hkdf.function
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: enhancement, approved, component: TLS

#5521 Make RSA-PSS verification use PSA with MBEDTLS_USE_PSA_CRYPTO
  library/pk.c
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
Labels: enhancement, approved, mbed TLS team

#5426 Add accessors to mbedtls_ssl_context: user data, version
  ChangeLog.d/ssl_context-user_data.txt
  ChangeLog.d/ssl_context-version_number.txt
  ChangeLog.d/ssl_get_version_1_3.txt
  include/mbedtls/ssl.h
  library/ssl_debug_helpers.h
  library/ssl_tls.c
  tests/ssl-opt.sh
  tests/suites/test_suite_ssl.function
Labels: bug, enhancement, component: TLS, needs: ci

#5577 Backport 2.28: Add missing key destruction calls in ssl_write_client_key_exchange
  ChangeLog.d/raw-agreement-destroy-missing.txt
  library/ssl_cli.c
Labels: approved, mbed TLS team, component: TLS, single-reviewer

#5576 Add missing key destruction calls in ssl_write_client_key_exchange
  ChangeLog.d/raw-agreement-destroy-missing.txt
  library/ssl_cli.c
Labels: approved, mbed TLS team, component: TLS

#5540 Backport 2.28: Add check_config checks for AEAD
  include/mbedtls/check_config.h
Labels: enhancement, approved, single-reviewer

#5503 Backport 2.28: doxygen: merge multiple descriptions of the same return codes
  include/psa/crypto.h
  include/psa/crypto_extra.h
Labels: approved, mbed TLS team

#5543 Backport 2.28: Remove default values and comments from mbedtls.doxyfile
  doxygen/mbedtls.doxyfile
Labels: enhancement, approved

#5372 Remove default values and comments from mbedtls.doxyfile
  doxygen/mbedtls.doxyfile
Labels: approved, mbed TLS team, needs: backports, component: Platform
