Repository Mbed-TLS/mbedtls, pull requests merged in 2022-08, with the labels that each got.

#6159 Fix typographical errors in .md files found by cspell
  SECURITY.md
  docs/3.0-migration-guide.md
  docs/architecture/psa-crypto-implementation-structure.md
  docs/architecture/psa-migration/psa-limitations.md
  docs/architecture/psa-migration/strategy.md
  docs/proposed/psa-driver-interface.md
  docs/proposed/psa-driver-wrappers-codegen-migration-guide.md
  tests/git-scripts/README.md
Labels: approved, needs-review, needs-reviewer, size-s, single-reviewer, priority-medium

#6160 Backport 2.28: Fix typographical errors in .md files found by cspell
  SECURITY.md
  docs/architecture/psa-crypto-implementation-structure.md
  docs/proposed/psa-driver-interface.md
  tests/git-scripts/README.md
Labels: approved, needs-review, needs-reviewer, size-s, single-reviewer, priority-medium

#6114 Use double quotes to include private header file psa_crypto_cipher.h
  ChangeLog.d/fix_psa_crypto_cipher_h_include.txt
  library/psa_crypto_cipher.c
Labels: bug, approved, priority-medium

#6168 Backport 2.28: Use double quotes to include private header file psa_crypto_cipher.h
  ChangeLog.d/fix_psa_crypto_cipher_h_include.txt
  library/psa_crypto_cipher.c
Labels: bug, approved, priority-medium

#6088 Validation remove and change in files related to curve in library
  library/ecdh.c
  library/ecdsa.c
  library/ecjpake.c
  library/ecp.c
  tests/suites/test_suite_ecdh.function
  tests/suites/test_suite_ecjpake.function
  tests/suites/test_suite_ecp.function
Labels: approved, size-s

#2602 x509_crt: handle properly broken links when looking for certificates
  ChangeLog.d/x509-broken-symlink-handling.txt
  library/x509_crt.c
Labels: bug, approved, component-x509, size-s, historical-reviewed, priority-medium

#6161 Backport 2.28: x509_crt: handle properly broken links when looking for certificates
  ChangeLog.d/x509-broken-symlink-handling.txt
  library/x509_crt.c
Labels: bug, approved, needs-backports, component-x509, needs-ci, size-s, priority-medium

#6165 Avoid use of MD in X.509 write test suite
  tests/suites/test_suite_x509write.function
Labels: approved, priority-high

#6070 Remove radix argument from bignum test functions
  tests/data_files/mpi_10
  tests/data_files/mpi_16
  tests/include/test/helpers.h
  tests/src/helpers.c
  tests/suites/test_suite_asn1parse.function
  tests/suites/test_suite_debug.data
  tests/suites/test_suite_debug.function
  tests/suites/test_suite_dhm.data
  tests/suites/test_suite_dhm.function
  tests/suites/test_suite_ecdh.function
  tests/suites/test_suite_ecdsa.function
  tests/suites/test_suite_ecp.function
  tests/suites/test_suite_mpi.data
  tests/suites/test_suite_mpi.function
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_pkcs1_v15.data
  tests/suites/test_suite_pkcs1_v15.function
  tests/suites/test_suite_rsa.data
  tests/suites/test_suite_rsa.function
  tests/suites/test_suite_x509write.function
Labels: enhancement, approved, needs-backports, component-crypto, component-test, priority-high

#6071 [Backport 2.28] Remove radix argument from bignum test functions
  tests/data_files/mpi_10
  tests/data_files/mpi_16
  tests/include/test/helpers.h
  tests/src/helpers.c
  tests/suites/test_suite_asn1parse.function
  tests/suites/test_suite_debug.data
  tests/suites/test_suite_debug.function
  tests/suites/test_suite_dhm.data
  tests/suites/test_suite_dhm.function
  tests/suites/test_suite_ecdh.function
  tests/suites/test_suite_ecdsa.function
  tests/suites/test_suite_ecp.function
  tests/suites/test_suite_mpi.data
  tests/suites/test_suite_mpi.function
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_pkcs1_v15.data
  tests/suites/test_suite_pkcs1_v15.function
  tests/suites/test_suite_rsa.data
  tests/suites/test_suite_rsa.function
  tests/suites/test_suite_x509write.function
Labels: enhancement, approved, component-crypto, component-test, priority-high

#6164 Avoid use of MD in SSL test suite
  tests/suites/test_suite_ssl.function
Labels: approved, priority-high

#5949 MBEDTLS_POLY1305_C and MBEDTLS_CHACHA20_C are needed when PSA_WANT_ALG_CHACHA20_POLY1305 is defined
  include/mbedtls/config_psa.h
Labels: bug, approved, needs-backports, component-psa, priority-high

#6157 backport 2.28: MBEDTLS_POLY1305_C and MBEDTLS_CHACHA20_C are needed when PSA_WANT_ALG_CHACHA20_POLY1305 is defined
  include/mbedtls/config_psa.h
Labels: bug, component-psa, size-s, priority-high

#5971 Add rsa pss rsae for tls12
  ChangeLog.d/add-rsa-pss-rsae-support-for-tls12.txt
  library/ssl_misc.h
  library/ssl_tls.c
  library/ssl_tls12_client.c
  library/ssl_tls13_generic.c
  tests/ssl-opt.sh
Labels: bug, approved, component-tls13, priority-high

#5950 cmake: IAR support option( MBEDTLS_FATAL_WARNINGS)
  CMakeLists.txt
  ChangeLog.d/fix_cmake_using_iar_toolchain.txt
Labels: bug, approved, size-s, priority-medium

#6139 Fix build error due to missing prototype warning when `MBEDTLS_DEPRECATED_REMOVED` is enabled
  ChangeLog.d/fix_build_error_for_mbedtls_deprecated_removed.txt
  library/ssl_tls.c
Labels: bug, needs-review, needs-reviewer, priority-medium

#6187 Backport 2.28: cmake: IAR support option( MBEDTLS_FATAL_WARNINGS)
  CMakeLists.txt
  ChangeLog.d/fix_cmake_using_iar_toolchain.txt
Labels: bug, approved, component-platform, size-s, single-reviewer, priority-medium

#6155 Add ability to check if any/all configs are enabled/disabled for ssl-opt
  programs/test/query_compile_time_config.c
  tests/ssl-opt.sh
Labels: approved, needs-review, component-test, priority-high

#6186 ssl_tls: avoid the appearance of a potential NULL dereferencing
  library/ssl_tls.c
Labels: enhancement, approved, component-tls, size-s, priority-low

#6182 [Backport 2.28] Add tests for mbedtls_ecp_set_zero
  tests/suites/test_suite_ecp.data
  tests/suites/test_suite_ecp.function
Labels: approved, component-crypto, priority-high

#6181 Add tests for mbedtls_ecp_set_zero
  tests/suites/test_suite_ecp.data
  tests/suites/test_suite_ecp.function
Labels: approved, needs-backports, component-crypto, priority-high

#5993 Allow non-versioned library soname.
  ChangeLog.d/nonversioned-library-soname.txt
  library/Makefile
  scripts/bump_version.sh
Labels: enhancement, approved, needs-review, component-platform, size-s, priority-medium

#6141 Driver hashes rsa v21
  include/mbedtls/check_config.h
  include/mbedtls/config_psa.h
  include/mbedtls/mbedtls_config.h
  library/hash_info.c
  library/hash_info.h
  library/legacy_or_psa.h
  library/rsa.c
  tests/include/test/drivers/config_test_driver.h
  tests/scripts/all.sh
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pkcs1_v21.data
  tests/suites/test_suite_pkcs1_v21.function
Labels: approved, priority-high

#6177 Adjust hash dependencies in `test_suite_ecdsa`
  tests/suites/test_suite_ecdsa.function
Labels: approved, component-test

#5990 Backport 2.28: Re-enable 5 tests disabled because of an old OpenSSL bug
  tests/ssl-opt.sh
Labels: bug, approved, needs-review, size-s, component-test, priority-low

#5985 Re-enable four tests disabled because of an old OpenSSL bug
  tests/ssl-opt.sh
Labels: bug, approved, needs-backports, size-s, component-test, priority-low

#6090 Remove encoding width suffix from Arm bignum assembly
  library/bn_mul.h
  tests/scripts/all.sh
Labels: bug, approved, component-crypto, priority-high

#6123 TLS 1.3:finalize tls13 serialize session save and load
  library/ssl_tls.c
  tests/suites/test_suite_ssl.function
Labels: needs-review, component-tls13

#6215 Backprort: ssl_tls12_server: fix potential NULL-dereferencing
  library/ssl_srv.c
Labels: approved, component-tls, size-s, single-reviewer, priority-medium

#6185 ssl_tls12_server: fix potential NULL-dereferencing if local certifica…
  library/ssl_tls12_server.c
Labels: enhancement, approved, needs-backports, component-tls, size-s, priority-low

#6171 Driver-only hashes: X.509
  include/mbedtls/check_config.h
  include/mbedtls/mbedtls_config.h
  include/mbedtls/oid.h
  include/mbedtls/x509_crt.h
  library/legacy_or_psa.h
  library/oid.c
  library/pem.c
  library/x509.c
  library/x509write_crt.c
  tests/scripts/all.sh
  tests/suites/test_suite_oid.data
  tests/suites/test_suite_oid.function
  tests/suites/test_suite_pem.data
  tests/suites/test_suite_pem.function
  tests/suites/test_suite_pkparse.data
  tests/suites/test_suite_pkparse.function
  tests/suites/test_suite_x509parse.data
  tests/suites/test_suite_x509parse.function
  tests/suites/test_suite_x509write.data
  tests/suites/test_suite_x509write.function
Labels: approved, priority-high

#6211 Be explicit about constant time bignum functions that must take a 0 or 1 condition value
  include/mbedtls/bignum.h
  library/constant_time.c
Labels: approved, size-s, single-reviewer, priority-medium

#6212 Backport 2.28: Be explicit about constant time bignum functions that must take a 0 or 1 condition value
  include/mbedtls/bignum.h
  library/constant_time.c
Labels: approved, size-s, single-reviewer, priority-medium

#6169 Fix incorrect use of mbedtls_ecp_group_id in test_suite_ssl.function
  tests/suites/test_suite_ssl.function
Labels: approved, size-s, single-reviewer, priority-medium

#6195 Driver-only hashes: EC J-PAKE
  include/mbedtls/check_config.h
  include/mbedtls/ecjpake.h
  include/mbedtls/mbedtls_config.h
  library/ecjpake.c
  tests/scripts/all.sh
  tests/suites/test_suite_ecjpake.function
Labels: approved, component-test, priority-high

#6219 Fix minor typos
  include/mbedtls/ecp.h
  include/mbedtls/mbedtls_config.h
  include/mbedtls/ssl.h
Labels: enhancement, approved, single-reviewer

#6095 Add the new modulus and the residue structures with low level I/O operations
  include/mbedtls/mbedtls_config.h
  library/CMakeLists.txt
  library/Makefile
  library/bignum.c
  library/bignum_core.c
  library/bignum_core.h
  library/bignum_mod.c
  library/bignum_mod.h
  library/bignum_mod_raw.c
  library/bignum_mod_raw.h
  library/constant_time.c
  library/constant_time_internal.h
  tests/scripts/check_names.py
  tests/suites/test_suite_mpi.data
  tests/suites/test_suite_mpi.function
Labels: enhancement, approved, component-crypto, priority-high

#6189 ctr_drbg: fix free uninitialized aes context
  ChangeLog.d/fix-ctr-drbg-may-free-invalid-aes-context.txt
  library/ctr_drbg.c
Labels: bug, approved, component-crypto, needs-ci, size-s, priority-low

#6207 Fix type used for capturing TLS ticket generation time
  include/mbedtls/ssl_ticket.h
  library/ssl_ticket.c
Labels: bug, needs-review, component-tls, needs-reviewer, size-s, single-reviewer, priority-medium

#6249 Add a missing guard in an example program
  programs/ssl/ssl_context_info.c
Labels: bug, approved, component-tls, component-test, priority-high

#6135 TLS 1.3: SRV: Finalize external PSK negotiation
  library/ssl_tls.c
  library/ssl_tls13_keys.c
  library/ssl_tls13_keys.h
  library/ssl_tls13_server.c
  programs/ssl/ssl_server2.c
  tests/opt-testcases/tls13-kex-modes.sh
  tests/ssl-opt.sh
Labels: approved, component-tls13
