Repository Mbed-TLS/mbedtls, pull requests merged in 2022-04, with the labels that each got.

#5647 Remove md_info in ssl_tls12_populate_transform() when USE_PSA_CRYPTO is defined
  library/ssl_tls.c
Labels: enhancement, approved, component: TLS, Community

#5682 Update references to old Github organisation
  .travis.yml
  BRANCHES.md
  BUGS.md
  CONTRIBUTING.md
  README.md
  include/mbedtls/config_psa.h
  include/psa/crypto_config.h
  scripts/ci.requirements.txt
  tests/compat.sh
  tests/scripts/all.sh
  tests/ssl-opt.sh
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
Labels: size:S, single-reviewer

#5681 Update references to old Github organisation
  .travis.yml
  BRANCHES.md
  BUGS.md
  CONTRIBUTING.md
  README.md
  docs/3.0-migration-guide.md
  docs/architecture/psa-migration/psa-limitations.md
  docs/architecture/psa-migration/strategy.md
  docs/architecture/tls13-support.md
  docs/proposed/psa-driver-wrappers-codegen-migration-guide.md
  include/mbedtls/check_config.h
  include/mbedtls/config_psa.h
  include/psa/crypto_config.h
  programs/psa/hmac_demo.c
  scripts/ci.requirements.txt
  scripts/driver.requirements.txt
  tests/compat.sh
  tests/scripts/all.sh
  tests/ssl-opt.sh
  tests/suites/test_suite_pk.function
Labels: size:S, single-reviewer

#5648 HKDF 2: use internal implementations in TLS 1.3
  library/ssl_misc.h
  library/ssl_tls13_invasive.h
  library/ssl_tls13_keys.c
  library/ssl_tls13_keys.h
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: enhancement, approved

#5638 Accessors to own CID within mbedtls_ssl_context
  ChangeLog.d/add_own_cid_accessors
  include/mbedtls/mbedtls_config.h
  include/mbedtls/ssl.h
  library/ssl_tls.c
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: enhancement, approved, component: TLS, size:S

#5568 PK: RSA verification
  library/pk_wrap.c
  tests/suites/test_suite_pk.function
Labels: approved, component: Crypto, Community

#4907 Disable debugging features in the primary code size measurement job
  scripts/config.py
  tests/scripts/all.sh
Labels: enhancement, approved, component: Platform

#5542 Backport 2.28: Disable debugging features in the primary code size measurement job
  scripts/config.py
  tests/scripts/all.sh
Labels: enhancement, approved, component: Platform

#5683 Prevent free of uninitialised MPI variables
  tests/suites/test_suite_pk.function
Labels: bug, approved, size:S, single-reviewer, component: test

#5689 Fix LTS version in contributing guidelines
  CONTRIBUTING.md
Labels: approved

#5695 ssl_tls13_generate_and_write_ecdh_key_exchange(): remove redundant check
  library/ssl_misc.h
  library/ssl_tls13_client.c
Labels: bug, approved, needs: ci

#5624 TLS ECDH 3b: server-side static ECDH (1.2)
  include/mbedtls/pk.h
  library/pk.c
  library/ssl_misc.h
  library/ssl_tls.c
  library/ssl_tls12_client.c
  library/ssl_tls12_server.c
  library/ssl_tls13_client.c
  tests/ssl-opt.sh
Labels: approved, component: TLS, Community, component: PSA

#5705 Backport 2.28 - Fix an off-by-one error in ssl-opt.sh
  tests/ssl-opt.sh
Labels: bug, approved, mbed TLS team, single-reviewer, component: test

#5623 Introduce mbedtls_ssl_hs_cb_t typedef
  ChangeLog.d/mbedtls_ssl_hs_cb_t.txt
  include/mbedtls/ssl.h
  library/ssl_tls.c
Labels: approved, Community, size:S

#5718 Backport 2.28: Remove the dependency on MBEDTLS_TIME_H from the timing module
  include/mbedtls/config.h
  library/timing.c
  programs/test/udp_proxy.c
  tests/suites/test_suite_timing.data
Labels: enhancement, approved, mbed TLS team, component: Platform

#5708 Remove the dependency on MBEDTLS_TIME_H from the timing module
  include/mbedtls/mbedtls_config.h
  library/timing.c
  programs/test/udp_proxy.c
  tests/suites/test_suite_timing.data
Labels: enhancement, approved, mbed TLS team, needs: backports, component: Platform

#5721 Backport 2.28: Fix Shared Library compilation issue with Cmake
  ChangeLog.d/fix-windows-cmake-build-with-shared-libraries.txt
  library/CMakeLists.txt
Labels: approved

#1133 Fix Shared Library compilation issue with Cmake
  ChangeLog.d/fix-windows-cmake-build-with-shared-libraries.txt
  library/CMakeLists.txt
Labels: bug, approved, mbed TLS team, component: Platform, historical-reviewing

#5719 Fix spelling of 'reasonable' in comments
  include/mbedtls/mbedtls_config.h
  include/mbedtls/ssl.h
Labels: approved, needs: backports, single-reviewer

#5720 Backport 2.28: Fix spelling of 'reasonable' in comments
  include/mbedtls/config.h
  include/mbedtls/ssl.h
  include/mbedtls/ssl_ticket.h
Labels: approved, single-reviewer

#2479 Fix typo in config-no-entropy.h
  configs/config-no-entropy.h
Labels: bug, CLA valid, component: Platform, single-reviewer, historical-reviewing

#5713 Backport 2.28: Fix spelling of 'features' in comment
  configs/config-no-entropy.h
Labels: approved, needs: ci, single-reviewer

#5717 Backport 2.28 - make mbedtls_ssl_send_alert_message() reentrant
  ChangeLog.d/alert_reentrant.txt
  library/ssl_msg.c
Labels: bug, needs: backports, size:S, single-reviewer

#5611 TLS ECDH 3a: ECDHE-PSK (both sides, 1.2)
  library/ssl_tls12_client.c
  library/ssl_tls12_server.c
Labels: approved, component: TLS, Community

#5634 PK Opaque RSA sign
  include/mbedtls/pk.h
  library/pk.c
  library/pk_wrap.c
  library/pk_wrap.h
  library/pkwrite.c
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
Labels: approved, component: Crypto, Community, component: PSA, component: test

#5006 clean up compat.sh
  tests/compat.sh
  tests/scripts/all.sh
  tests/scripts/basic-build-test.sh
Labels: enhancement, approved, size:S, historical-reviewed

#5737 [backport 2.28] clean up compat.sh
  tests/compat.sh
  tests/scripts/basic-build-test.sh
Labels: approved

#5701 Make size of output in mpi_mul_hlp() explicit
  library/bignum.c
  library/bignum_internal.h
  library/bn_mul.h
  library/ecp_curves.c
Labels: approved, component: Crypto

#5635 PSA: systematically test operation failure
  ChangeLog.d/ccm_star_no_tag.txt
  include/mbedtls/config_psa.h
  library/psa_crypto.c
  library/psa_crypto_cipher.c
  scripts/mbedtls_dev/crypto_knowledge.py
  tests/CMakeLists.txt
  tests/Makefile
  tests/scripts/check-generated-files.sh
  tests/scripts/generate_psa_tests.py
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto_op_fail.function
  tests/suites/test_suite_psa_crypto_op_fail.misc.data
Labels: approved, component: PSA, size:M, component: test

#5697 Backport 2.28: PSA: systematically test operation failure
  include/mbedtls/config_psa.h
  library/psa_crypto.c
  library/psa_crypto_cipher.c
  library/psa_crypto_driver_wrappers.c
  scripts/mbedtls_dev/crypto_knowledge.py
  tests/include/test/drivers/crypto_config_test_driver_extension.h
  tests/scripts/all.sh
  tests/scripts/check-generated-files.sh
  tests/scripts/generate_psa_tests.py
  tests/suites/test_suite_psa_crypto_op_fail.function
  tests/suites/test_suite_psa_crypto_op_fail.generated.data
  tests/suites/test_suite_psa_crypto_op_fail.misc.data
  tests/suites/test_suite_psa_crypto_storage_format.current.data
  tests/suites/test_suite_psa_crypto_storage_format.v0.data
Labels: approved, component: PSA, component: test

#5706 Simplify structure of bignum inline assembly
  library/bignum.c
  library/bn_mul.h
Labels: approved, component: Crypto

#5747 Backport 2.28: Add a test for a raw key agreement failure
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: enhancement, approved, mbed TLS team, single-reviewer

#5608 Add a test for a raw key agreement failure
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: enhancement, approved, mbed TLS team, needs: backports

#5631 Unify internal/external TLS protocol version enums
  ChangeLog.d/mbedtls_tlsver_enum.txt
  include/mbedtls/ssl.h
  include/mbedtls/ssl_ciphersuites.h
  library/ssl_ciphersuites.c
  library/ssl_client.c
  library/ssl_client.h
  library/ssl_misc.h
  library/ssl_msg.c
  library/ssl_tls.c
  library/ssl_tls12_client.c
  library/ssl_tls12_server.c
  library/ssl_tls13_client.c
  library/ssl_tls13_keys.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: enhancement, needs: review, component: TLS, needs: ci, Community, needs: reviewer, size:M

#5743 Fix Windows build host detection
  CMakeLists.txt
Labels: bug, needs: review, component: Platform, Community, needs: reviewer, size:S

#5698 TLS 1.3 - miscellaneous
  include/mbedtls/ssl.h
  library/ecdh.c
  library/ecdh_misc.h
  library/ssl_client.c
  library/ssl_misc.h
  library/ssl_tls13_client.c
  tests/opt-testcases/tls13-compat.sh
  tests/scripts/generate_tls13_compat_tests.py
  tests/ssl-opt.sh
Labels: enhancement, approved, component: TLS, MPS / TLS 1.3

#5739 Don't test with all-but-one elliptic curves
  tests/scripts/curves.pl
Labels: approved, component: test

#5741 Backport 2.28: Don't test with all-but-one elliptic curves
  tests/scripts/curves.pl
Labels: single-reviewer, component: test

#5726 Mixed PSK 1: Extend PSK-to-MS algorithm in PSA (v.2)
  include/psa/crypto_struct.h
  include/psa/crypto_values.h
  library/psa_crypto.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: approved, approved for design, component: PSA

#5709 RSA sign 3b: TLS 1.2 integration testing
  programs/ssl/ssl_server2.c
  tests/ssl-opt.sh
Labels: approved, component: TLS, Community

#5539 Add client hello into server side
  include/mbedtls/ssl.h
  library/ssl_client.c
  library/ssl_client.h
  library/ssl_misc.h
  library/ssl_tls.c
  library/ssl_tls13_client.c
  library/ssl_tls13_generic.c
  library/ssl_tls13_server.c
  programs/ssl/ssl_server2.c
  tests/ssl-opt.sh
  tests/suites/test_suite_ssl.data
Labels: needs: work, needs: ci, MPS / TLS 1.3

#5703 TLS ECDH 4: remove legacy context
  library/ssl_misc.h
  library/ssl_tls.c
  library/ssl_tls12_client.c
  library/ssl_tls12_server.c
Labels: enhancement, approved, component: TLS, Community

#5710 RSA sign 3a: X.509 integration testing
  tests/suites/test_suite_x509write.data
  tests/suites/test_suite_x509write.function
Labels: approved, component: TLS, Community

#5744 [backport 2.28] Improve benchmarking of ECC heap usage
  programs/test/benchmark.c
  scripts/ecc-heap.sh
Labels: approved, single-reviewer

#5381 Improve benchmarking of ECC heap usage
  include/mbedtls/memory_buffer_alloc.h
  library/memory_buffer_alloc.c
  programs/test/benchmark.c
  scripts/ecc-heap.sh
Labels: approved, needs: backports

#5769 [Backport 2.28] Expand negative coverage of ECDSA verification
  tests/suites/test_suite_ecdsa.function
Labels: approved, single-reviewer

#5755 Expand negative coverage of ECDSA verification
  tests/suites/test_suite_ecdsa.function
Labels: approved, needs: backports, size:S

#5753 Hide unnecessarily public functions in SHA-256 and SHA-512 A64 acceleration
  library/sha256.c
  library/sha512.c
Labels: approved, mbed TLS team

#5684 M aead decrypt driver dispatch test
  tests/suites/test_suite_psa_crypto_driver_wrappers.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
Labels: needs: review, component: test

#5679 TLS1.3: Add server-side ServerHello handler
  library/ssl_misc.h
  library/ssl_tls13_client.c
  library/ssl_tls13_generic.c
  library/ssl_tls13_server.c
  tests/ssl-opt.sh
Labels: approved, needs: review, MPS / TLS 1.3

#5742 Fixup or re-enable tests with Use PSA
  tests/scripts/all.sh
  tests/ssl-opt.sh
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_ssl.function
Labels: approved, Community, component: test

#5674 Cipher cleanup: abstract TLS mode
  library/ssl_misc.h
  library/ssl_msg.c
  library/ssl_ticket.c
  library/ssl_tls.c
  library/ssl_tls12_server.c
Labels: enhancement, component: TLS, Community

#5778 [Backport 2.28] Fix documentation of allowed_pks field in mbedtls_x509_crt_profile
  ChangeLog.d/doc-x509-profile-pk.txt
  include/mbedtls/x509_crt.h
Labels: bug, approved, single-reviewer

#2082 Fix documentation of allowed_pks field in mbedtls_x509_crt_profile
  ChangeLog.d/doc-x509-profile-pk.txt
  include/mbedtls/x509_crt.h
Labels: bug, approved, mbed TLS team, component: X.509, historical-reviewed

#5776 Add change log entry for mixed-psk
  ChangeLog.d/psk_to_ms_mixed_psk.txt
Labels: approved, single-reviewer

#5745 RSA-PSS sign 2: TLS 1.3 integration testing
  tests/ssl-opt.sh
Labels: approved, component: TLS, Community, component: test

#5740 Backport 2.28: Support alternative MBEDTLS_PSA_CRYPTO_CONFIG_FILE
  ChangeLog.d/psa_crypto_config_file.txt
  include/mbedtls/config.h
  include/mbedtls/config_psa.h
  programs/test/query_config.c
  scripts/config.py
  tests/scripts/all.sh
Labels: approved, needs: ci, component: test

#5654 Support alternative MBEDTLS_PSA_CRYPTO_CONFIG_FILE
  ChangeLog.d/psa_crypto_config_file.txt
  include/mbedtls/config_psa.h
  include/mbedtls/mbedtls_config.h
  scripts/config.py
  tests/scripts/all.sh
Labels: enhancement, approved, needs: backports, component: Platform, needs: ci, size:S

#5644 PSA storage format: exercise key
  include/mbedtls/config_psa.h
  include/psa/crypto_builtin_primitives.h
  include/psa/crypto_config.h
  scripts/mbedtls_dev/crypto_knowledge.py
  scripts/mbedtls_dev/macro_collector.py
  tests/scripts/generate_psa_tests.py
  tests/scripts/test_psa_constant_names.py
  tests/src/psa_exercise_key.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_storage_format.function
Labels: enhancement, approved, needs: backports, component: PSA, size:M, component: test

#5754 Backport 2.28: PSA storage format: exercise key
  ChangeLog.d/psa-rc4.txt
  include/mbedtls/config_psa.h
  include/psa/crypto_builtin_primitives.h
  include/psa/crypto_config.h
  include/psa/crypto_values.h
  library/psa_crypto.c
  scripts/mbedtls_dev/crypto_knowledge.py
  scripts/mbedtls_dev/macro_collector.py
  tests/scripts/all.sh
  tests/scripts/generate_psa_tests.py
  tests/scripts/test_psa_constant_names.py
  tests/src/psa_exercise_key.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_op_fail.generated.data
  tests/suites/test_suite_psa_crypto_op_fail.misc.data
  tests/suites/test_suite_psa_crypto_storage_format.current.data
  tests/suites/test_suite_psa_crypto_storage_format.function
  tests/suites/test_suite_psa_crypto_storage_format.v0.data
Labels: enhancement, approved, component: PSA, component: test

#5759 Set flag to proper value in x509 parse tests
  tests/suites/test_suite_x509parse.function
Labels: bug, needs: backports, needs: ci, single-reviewer, component: test

#5760 [Backport 2.28] Set flag to proper value in x509 parse tests
  tests/suites/test_suite_x509parse.function
Labels: bug, single-reviewer, component: test

#5704 Mixed PSK 2a, 2b, 2c: enable client/server support opaque RSA-PSK, ECDHE-PSK, DHE-PSK
  library/ssl_tls.c
  library/ssl_tls12_client.c
  library/ssl_tls12_server.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  tests/ssl-opt.sh
Labels: approved, component: TLS
