Repository Mbed-TLS/mbedtls, pull requests merged in 2022-01, with the labels that each got.

#5337 bump_version: Fix spurious replacement in build_info.h
  scripts/bump_version.sh
Labels: bug, approved, component: Platform, size:S

#5193 Driver Wrappers Codegen 1.0
  ChangeLog.d/Driver_wrapper_codegen_1.0.txt
  docs/proposed/psa-driver-wrappers-codegen-migration-guide.md
  library/.gitignore
  library/CMakeLists.txt
  library/Makefile
  library/psa_crypto_driver_wrappers.h
  scripts/data_files/driver_templates/psa_crypto_driver_wrappers.c.jinja
  scripts/generate_driver_wrappers.py
  scripts/make_generated_files.bat
  tests/docker/bionic/Dockerfile
  tests/scripts/check-generated-files.sh
Labels: component: PSA, component: test

#5386 Update information in BRANCHES.md
  BRANCHES.md
Labels: bug, approved, single-reviewer

#5388 Fix the multipart AEAD compliance tests
  tests/scripts/test_psa_compliance.py
Labels: single-reviewer, component: test

#5422 Update mailing list links [Backport]
  CONTRIBUTING.md
  SUPPORT.md
Labels: approved, needs: ci, single-reviewer

#5272 PSA: Return the same error in multipart and single shot AEAD operations
  ChangeLog.d/psa_aead_singleshot_error.txt
  library/psa_crypto.c
  tests/scripts/test_psa_compliance.py
  tests/suites/test_suite_psa_crypto.data
Labels: bug, approved, needs: ci, PSA compliance, component: PSA

#5353 Reset dhm_P and dhm_G if config call repeated; avoid memory leak
  ChangeLog.d/mbedtls_ssl_comfig_defaults-memleak.txt
  library/ssl_tls.c
Labels: bug, approved, Community, size:S

#5416 Backport 2.28: Reset dhm_P and dhm_G if config call repeated
  ChangeLog.d/mbedtls_ssl_config_defaults-memleak.txt
  library/ssl_tls.c
Labels: bug, approved, Community, single-reviewer

#5351 Remove duplicate function for writing supported_groups extension
  library/ssl_cli.c
  library/ssl_misc.h
  library/ssl_srv.c
  library/ssl_tls.c
  library/ssl_tls13_client.c
  library/ssl_tls13_generic.c
  tests/ssl-opt.sh
Labels: needs: review, MPS / TLS 1.3

#5344 PSA AEAD: test more combinations of generate_nonce and set_lengths
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: enhancement, approved, mbed TLS team, component: PSA

#5380 Make KEY_ID_ENCODES_OWNER compatible with USE_PSA_CRYPTO
  include/mbedtls/check_config.h
  include/mbedtls/pk.h
  include/mbedtls/ssl.h
  library/cipher_wrap.h
  library/pk.c
  library/pk_wrap.c
  library/pkwrite.c
  library/ssl_misc.h
  library/ssl_tls.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  programs/ssl/ssl_test_lib.h
  tests/scripts/all.sh
  tests/suites/test_suite_ssl.function
Labels: approved, mbed TLS team, component: PSA, component: test

#5253 Return an error from `mbedtls_cipher_set_iv` for an invalid IV length with ChaCha20 and ChaCha20+Poly
  ChangeLog.d/chacha20_invalid_iv_len_fix.txt
  library/cipher.c
  tests/suites/test_suite_cipher.chacha20.data
  tests/suites/test_suite_cipher.chachapoly.data
  tests/suites/test_suite_cipher.function
Labels: approved, mbed TLS team, component: Crypto

#5267 Extend driver dispatch tests for MAC multipart
  tests/suites/test_suite_psa_crypto_driver_wrappers.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
Labels: approved, component: PSA

#5350 Detect invalid tag lengths in psa_aead_setup
  library/psa_crypto.c
  library/psa_crypto_driver_wrappers.h
  scripts/data_files/driver_templates/psa_crypto_driver_wrappers.c.jinja
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: approved, mbed TLS team, component: PSA

#5438 Add missing config check for PKCS5.
  include/mbedtls/check_config.h
Labels: bug, approved, component: Crypto, size:S, single-reviewer

#5439 Backport 2.28: Add missing config check for PKCS5.
  include/mbedtls/check_config.h
Labels: bug, approved, component: Crypto, needs: ci, single-reviewer

#5425 TLS Cipher 1a: extend testing of tickets
  programs/ssl/ssl_server2.c
  tests/ssl-opt.sh
Labels: enhancement, approved

#5309 mbedtls_pk_parse_key: don't allocate if not needed
  ChangeLog.d/pkparse-pkcs8-unencrypted-no-alloc.txt
  library/pkparse.c
Labels: enhancement, component: Crypto, size:S

#5428 Add accessors for ciphersuite info
  ChangeLog.d/mbedtls_ssl_get_ciphersuite_id.txt
  include/mbedtls/ssl.h
  include/mbedtls/ssl_ciphersuites.h
  library/ssl_ciphersuites.c
  library/ssl_tls.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  programs/ssl/ssl_test_lib.h
  tests/ssl-opt.sh
Labels: approved, Community, size:S, regression

#5367 doxygen: add missing asterisk to group closures
  include/mbedtls/asn1.h
  include/mbedtls/ctr_drbg.h
  include/mbedtls/ecp.h
  include/mbedtls/entropy.h
  include/mbedtls/hkdf.h
  include/mbedtls/hmac_drbg.h
  include/mbedtls/mbedtls_config.h
  include/mbedtls/memory_buffer_alloc.h
  include/mbedtls/pem.h
  include/mbedtls/platform.h
  include/mbedtls/platform_time.h
  include/mbedtls/ssl.h
  include/mbedtls/ssl_cache.h
  include/mbedtls/ssl_cookie.h
  include/mbedtls/x509.h
  include/mbedtls/x509_crl.h
  include/mbedtls/x509_crt.h
  include/mbedtls/x509_csr.h
Labels: mbed TLS team, needs: review, needs: backports

#5452 Backport 2.28: doxygen: add missing asterisk to group closures
  include/mbedtls/asn1.h
  include/mbedtls/config.h
  include/mbedtls/ctr_drbg.h
  include/mbedtls/ecp.h
  include/mbedtls/entropy.h
  include/mbedtls/hkdf.h
  include/mbedtls/hmac_drbg.h
  include/mbedtls/memory_buffer_alloc.h
  include/mbedtls/pem.h
  include/mbedtls/platform.h
  include/mbedtls/platform_time.h
  include/mbedtls/ssl.h
  include/mbedtls/ssl_cache.h
  include/mbedtls/ssl_cookie.h
  include/mbedtls/x509.h
  include/mbedtls/x509_crl.h
  include/mbedtls/x509_crt.h
  include/mbedtls/x509_csr.h
Labels: mbed TLS team, needs: review, needs: ci, needs: reviewer

#5395 Add positive test case with self-signed certificates
  tests/ssl-opt.sh
Labels: enhancement, needs: review, needs: backports, component: TLS, needs: reviewer, size:S

#5359 Remove redundant write operation in Montgomery multiplication
  library/bignum.c
Labels: enhancement, approved, mbed TLS team, component: Crypto

#5363 PSA AEAD: extend testing of set_nonce + set_lengths
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: approved, mbed TLS team, component: PSA

#5457 Remove incorrect incompatibility information about `MBEDTLS_PSA_CRYPTO_KEY_ID_ENCODES_OWNER` from mbedtls_config.h
  include/mbedtls/mbedtls_config.h
Labels: bug, approved, mbed TLS team

#5458 Backport 2.28: Add eclipse-specific project files to gitignore
  .gitignore
Labels: enhancement, approved, mbed TLS team, single-reviewer

#5355 Remove duplicate write signature algorithms extension
  include/mbedtls/ssl.h
  library/ssl_cli.c
  library/ssl_misc.h
  library/ssl_srv.c
  library/ssl_tls.c
  library/ssl_tls13_client.c
  library/ssl_tls13_generic.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  programs/ssl/ssl_test_common_source.c
Labels: needs: review, MPS / TLS 1.3

#5276 Add hello retry request in client side
  include/mbedtls/ssl.h
  library/ssl_misc.h
  library/ssl_tls.c
  library/ssl_tls13_client.c
  library/ssl_tls13_generic.c
  tests/ssl-opt.sh
Labels: needs: review, MPS / TLS 1.3

#5473 Avoid dead code in some configurations
  library/ssl_misc.h
Labels: bug, approved

#5382 Swap the client and server random for TLS 1.3 f_export_keys
  ChangeLog.d/tls13_f_export_keys.txt
  library/ssl_tls13_keys.c
Labels: bug, fix available, needs: review, Community
