Repository Mbed-TLS/mbedtls, pull requests merged in 2022-12, with the labels that each got.

#6426 Add driver dispatch layer for raw key agreement, along with test call for transparent drivers.
  ChangeLog.d/psa_driver_wrapper_for_raw_key_agreement.txt
  library/psa_crypto.c
  library/psa_crypto_core.h
  library/psa_crypto_driver_wrappers.h
  library/psa_crypto_ecp.c
  library/psa_crypto_ecp.h
  scripts/data_files/driver_templates/psa_crypto_driver_wrappers.c.jinja
  tests/include/test/drivers/crypto_config_test_driver_extension.h
  tests/include/test/drivers/key_agreement.h
  tests/include/test/drivers/test_driver.h
  tests/scripts/all.sh
  tests/src/drivers/test_driver_key_agreement.c
  tests/suites/test_suite_psa_crypto_driver_wrappers.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
  tests/suites/test_suite_ssl.data
Labels: needs-review, component-psa

#6698 Bignum: Enable test generation from bignum_mod.py
  scripts/mbedtls_dev/bignum_mod.py
  tests/CMakeLists.txt
  tests/Makefile
  tests/scripts/generate_bignum_tests.py
Labels: approved, priority-high

#6722 Fix broken link
  .github/pull_request_template.md
Labels: bug, approved, needs-ci, component-docs, size-s, single-reviewer, priority-medium

#6709 Add warnings & disable PKCS #7 by default
  ChangeLog.d/pkcs7-parser.txt
  include/mbedtls/mbedtls_config.h
  include/mbedtls/pkcs7.h
Labels: approved, needs-ci, priority-high

#6704 Implement mbedtls_mpi_mod_sub()
  library/bignum_mod.c
  library/bignum_mod.h
  scripts/mbedtls_dev/bignum_mod.py
  tests/suites/test_suite_bignum_mod.data
  tests/suites/test_suite_bignum_mod.function
Labels: approved, component-crypto, priority-high

#6689 Changelog improvements for 3.3
  ChangeLog.d/LMS.txt
  ChangeLog.d/add-rsa-pss-rsae-support-for-tls12.txt
  ChangeLog.d/dtls-connection-id.txt
  ChangeLog.d/extend-query_compile_time_config-to-psa_want.txt
  ChangeLog.d/fix-tls12server-sent-sigalgs.txt
  ChangeLog.d/fix_build_error_for_mbedtls_deprecated_removed.txt
  ChangeLog.d/fix_build_tls1_2_with_single_encryption_type.txt
  ChangeLog.d/fix_cmake_gen_files
  ChangeLog.d/fix_cmake_gen_files.txt
  ChangeLog.d/fix_cmake_using_iar_toolchain.txt
  ChangeLog.d/fix_hard_link_across_drives
  ChangeLog.d/fix_hard_link_across_drives.txt
  ChangeLog.d/fix_tls13_session_resumption_fail_when_hostname_is_not_localhost.txt
  ChangeLog.d/fix_zeroization.txt
  ChangeLog.d/mbedtls_asn1_type_free.txt
  ChangeLog.d/psa_crypto_code_gen_1_1.txt
  ChangeLog.d/remove_ssl_session_compression.txt
  ChangeLog.d/tls13-misc.txt
Labels: approved, needs-backports, size-s, priority-high

#6730 Backport 2.28: Changelog improvements for 3.3
  ChangeLog.d/fix_build_tls1_2_with_single_encryption_type.txt
  ChangeLog.d/fix_cmake_using_iar_toolchain.txt
  ChangeLog.d/fix_zeroization.txt
Labels: enhancement, approved, size-s, priority-high

#6717 Fix typos prior to release
  doxygen/input/doc_encdec.h
  include/mbedtls/asn1write.h
  include/mbedtls/check_config.h
  include/mbedtls/config_psa.h
  include/mbedtls/lms.h
  include/mbedtls/mbedtls_config.h
  include/mbedtls/pkcs12.h
  include/mbedtls/pkcs7.h
  include/mbedtls/rsa.h
  include/mbedtls/ssl.h
  include/psa/crypto.h
  include/psa/crypto_se_driver.h
  include/psa/crypto_sizes.h
  include/psa/crypto_types.h
  include/psa/crypto_values.h
  library/aes.c
  library/ccm.c
  library/debug.c
  library/lmots.h
  library/mps_reader.c
  library/pkcs7.c
  library/psa_crypto.c
  library/psa_crypto_se.h
  library/ssl_client.c
  library/ssl_misc.h
  library/ssl_msg.c
  library/ssl_tls12_client.c
  library/ssl_tls13_server.c
  library/x509.c
  library/x509_crl.c
  programs/pkey/dh_genprime.c
  programs/psa/aead_demo.c
  programs/psa/hmac_demo.c
  programs/ssl/dtls_client.c
  programs/ssl/ssl_server2.c
  programs/test/benchmark.c
  programs/test/udp_proxy.c
  programs/x509/cert_req.c
  programs/x509/cert_write.c
  scripts/mbedtls_dev/bignum_data.py
  tests/include/test/psa_crypto_helpers.h
  tests/scripts/check_names.py
  tests/scripts/generate_psa_tests.py
  tests/scripts/test_psa_compliance.py
  tests/suites/test_suite_mps.function
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
  tests/suites/test_suite_psa_crypto_generate_key.function
  tests/suites/test_suite_psa_crypto_persistent_key.function
  tests/suites/test_suite_ssl.function
Labels: approved, needs-backports, size-s, single-reviewer, priority-high

#6736 [backport 2.28] Tell cmake to get SKIP_TEST_SUITES from ENV
  tests/CMakeLists.txt
Labels: approved, needs-ci, size-s, single-reviewer, component-test, priority-medium

#6739 Backport 2.28: Update documenation of PSA_ALG_RSA_PSS
  include/psa/crypto_values.h
Labels: bug, approved, needs-ci, component-psa, size-s, single-reviewer, priority-high

#6731 Require input to mbedtls_mpi_core_exp_mod() to already be in Montgomery form
  library/bignum_core.c
  library/bignum_core.h
  scripts/mbedtls_dev/bignum_common.py
  scripts/mbedtls_dev/bignum_core.py
  scripts/mbedtls_dev/bignum_mod_raw.py
Labels: approved, component-crypto, priority-high

#6734 Fix spelling of test dependency
  library/ssl_tls.c
  tests/suites/test_suite_psa_crypto.data
Labels: bug, approved, needs-backports, needs-ci, size-s, single-reviewer, component-test, priority-medium

#6735 Backport 2.28: Fix spelling of test dependency
  library/ssl_tls.c
  tests/include/test/psa_exercise_key.h
  tests/suites/test_suite_psa_crypto.data
Labels: bug, approved, needs-ci, size-s, single-reviewer, component-test, priority-medium

#6752 Add Changelog for Arm compile fix
  ChangeLog.d/fix_arm_compile_erorr.txt
Labels: bug, approved, component-platform, size-s, single-reviewer, priority-high

#6705 Add code style correction script
  .uncrustify.cfg
  include/mbedtls/check_config.h
  programs/psa/key_ladder_demo.c
  scripts/code_style.py
  tests/scripts/all.sh
Labels: approved, size-s, priority-high

#6706 [Backport 2.28] Add code style correction script
  .uncrustify.cfg
  include/mbedtls/check_config.h
  library/ssl_srv.c
  programs/psa/key_ladder_demo.c
  scripts/code_style.py
  tests/scripts/all.sh
Labels: approved, size-s, priority-high

#6750 Bignum: Implement mbedtls_mpi_mod_raw_inv_prime()
  library/bignum_core.h
  library/bignum_mod_raw.c
  library/bignum_mod_raw.h
  scripts/mbedtls_dev/bignum_common.py
  scripts/mbedtls_dev/bignum_data.py
  scripts/mbedtls_dev/bignum_mod_raw.py
  tests/suites/test_suite_bignum_core.function
  tests/suites/test_suite_bignum_mod_raw.function
Labels: approved, component-crypto, priority-high

#6693 [backport 2.28] Optimize with asan
  tests/scripts/all.sh
Labels: enhancement, approved, size-s, component-test, priority-medium

#6683 Optimize with asan
  tests/scripts/all.sh
Labels: enhancement, approved, size-s, component-test, priority-medium

#6744 Backport 2.28: Copy files instead of hard-linking on Windows
  CMakeLists.txt
  ChangeLog.d/fix_hard_link_across_drives
Labels: bug, approved, component-platform, size-s, priority-medium

#6301 Fix missing file name in changelog
  ChangeLog
Labels: bug, approved, size-s, priority-medium

#6666 Fast unaligned memory access macros
  ChangeLog.d/alignment-perf.txt
  README.md
  library/aes.c
  library/alignment.h
  library/aria.c
  library/bignum_core.c
  library/camellia.c
  library/ccm.c
  library/chacha20.c
  library/cmac.c
  library/common.h
  library/ctr_drbg.c
  library/des.c
  library/gcm.c
  library/md.c
  library/pkcs5.c
  library/platform_util.c
  library/ssl_msg.c
  tests/suites/test_suite_alignment.data
  tests/suites/test_suite_alignment.function
  tests/suites/test_suite_common.data
  tests/suites/test_suite_common.function
Labels: enhancement, approved, component-platform, size-s, historical-reviewed, priority-medium

#6751 Fix typo in `library/entropy.c`
  library/entropy.c
Labels: approved, needs-backports, needs-ci, single-reviewer, priority-medium

#6762 Backport 2.28: Fix typo in `library/entropy.c`
  library/entropy.c
Labels: approved, needs-ci, single-reviewer, priority-medium

#6204 [Backport 2.28] Add test for ECP group metadata
  tests/suites/test_suite_ecp.data
  tests/suites/test_suite_ecp.function
Labels: enhancement, approved, component-crypto, priority-high

#6743 Bignum: Implement fixed width modular negation
  library/bignum_mod_raw.c
  library/bignum_mod_raw.h
  scripts/mbedtls_dev/bignum_mod_raw.py
  tests/suites/test_suite_bignum_mod_raw.function
Labels: approved, component-crypto, component-test, priority-high

#6558 check_names: extend typo check to PSA macro/enum names
  include/mbedtls/check_config.h
  include/mbedtls/legacy_or_psa.h
  include/psa/crypto_values.h
  library/psa_crypto_aead.h
  library/psa_crypto_its.h
  library/psa_crypto_rsa.h
  scripts/data_files/driver_templates/psa_crypto_driver_wrappers.c.jinja
  tests/scripts/check_names.py
Labels: enhancement, approved, size-s, component-test, priority-medium

#6783 2.28 only: Move `MBEDTLS_DEPRECATED` annotation to prefix
  include/mbedtls/cipher.h
Labels: approved, size-s

#6629 Install CMake files in MbedTLS dir
  CMakeLists.txt
  ChangeLog.d/cmake-install.txt
  programs/test/cmake_package_install/CMakeLists.txt
Labels: enhancement, approved, component-platform, size-s, priority-medium

#6548 Reword documentation on function deprecation
  CONTRIBUTING.md
Labels: approved, size-s

#6680 Allow isolation of EC J-PAKE password when used in TLS
  include/mbedtls/ssl.h
  library/ssl_tls.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  tests/scripts/all.sh
  tests/ssl-opt.sh
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: approved, size-s

#6732 Bignum: Implement mbedtls_mpi_mod_add()
  library/bignum_mod.c
  library/bignum_mod.h
  scripts/mbedtls_dev/bignum_mod.py
  tests/suites/test_suite_bignum_mod.function
  tests/suites/test_suite_bignum_mod.misc.data
Labels: approved, component-crypto, size-s, priority-high

#6699 lcov script
  CMakeLists.txt
  Makefile
  scripts/lcov.sh
  tests/CMakeLists.txt
Labels: approved, component-platform, size-s, priority-medium

#6782 Backport 2.28: lcov script
  CMakeLists.txt
  Makefile
  scripts/lcov.sh
  tests/CMakeLists.txt
Labels: approved, component-platform, size-s, single-reviewer, priority-medium

#6688 Backport 2.28: Allow comments in test function prototypes
  tests/Makefile
  tests/scripts/generate_test_code.py
  tests/scripts/test_generate_test_code.py
  tests/suites/test_suite_psa_crypto.function
Labels: approved, size-s, component-test, priority-medium

#6594 Allow comments in test function prototypes
  tests/Makefile
  tests/scripts/generate_test_code.py
  tests/scripts/test_generate_test_code.py
  tests/suites/test_suite_psa_crypto.function
Labels: approved, size-s, component-test, priority-medium

#6772 Bignum: Refactor mpi_core_sub tests to use arch_split
  scripts/mbedtls_dev/bignum_core.py
  tests/suites/test_suite_bignum_core.function
Labels: enhancement, approved, component-crypto

#6793 Update mbedtls_mpi_mod_sub() tests to incorporate mod_add test feedback
  tests/suites/test_suite_bignum_mod.function
Labels: enhancement, approved, component-crypto, needs-ci

#6687 programs/fuzz: set sensible default CFLAGS
  programs/fuzz/Makefile
Labels: approved, needs-backports, component-platform, size-s, priority-medium

#6696 Backport 2.28: programs/fuzz: set sensible default CFLAGS
  programs/fuzz/Makefile
Labels: approved, component-platform, size-s, single-reviewer, priority-medium

#6723 Document ECP_RESTARTABLE and make it compatible with USE_PSA
  ChangeLog.d/pk-sign-restartable.txt
  docs/architecture/psa-migration/psa-limitations.md
  docs/use-psa-crypto.md
  include/mbedtls/check_config.h
  include/mbedtls/mbedtls_config.h
  library/pk_wrap.c
  scripts/config.py
  tests/scripts/all.sh
  tests/scripts/depends.py
  tests/ssl-opt.sh
  tests/suites/test_suite_ecp.function
  tests/suites/test_suite_x509parse.function
Labels: bug, enhancement, approved, needs-backports, size-s, priority-medium

#6753 [Backport 2.28] Document ECP_RESTARTABLE
  include/mbedtls/check_config.h
  include/mbedtls/config.h
  tests/scripts/depends.py
  tests/ssl-opt.sh
  tests/suites/test_suite_ecp.function
Labels: bug, approved, size-s, priority-medium

#6303 Bignum: Implement mbedtls_mpi_core_random
  library/bignum.c
  library/bignum_core.c
  library/bignum_core.h
  tests/suites/test_suite_bignum.function
  tests/suites/test_suite_bignum.misc.data
  tests/suites/test_suite_bignum_core.function
  tests/suites/test_suite_bignum_core.misc.data
  tests/suites/test_suite_bignum_random.data
  tests/suites/test_suite_bignum_random.function
Labels: enhancement, approved, component-crypto, priority-high

#6766 Bignum: document conventions for bignum mod and mod_raw
  library/bignum_mod.h
  library/bignum_mod_raw.h
Labels: enhancement, approved, component-crypto, size-s, priority-high

#6794 TLS 1.3: Fix some test dependencies
  tests/opt-testcases/tls13-misc.sh
Labels: enhancement, needs-review, component-tls13, priority-high

#6811 [Backport 2.28] Fix an incorrect regex in check_names.py
  tests/scripts/check_names.py
Labels: approved, size-s, component-test

#6810 Fix an incorrect regex in check_names.py
  tests/scripts/check_names.py
Labels: approved, needs-backports, size-s, component-test

#6789 Point to docker images used in the CI
  README.md
  tests/compat-in-docker.sh
  tests/docker/bionic/Dockerfile
  tests/make-in-docker.sh
  tests/scripts/all-in-docker.sh
  tests/scripts/basic-in-docker.sh
  tests/scripts/docker_env.sh
  tests/ssl-opt-in-docker.sh
Labels: enhancement, approved, needs-backports

#6807 [Backport 2.28] Point to docker images used in the CI
  README.md
  tests/compat-in-docker.sh
  tests/docker/bionic/Dockerfile
  tests/make-in-docker.sh
  tests/scripts/all-in-docker.sh
  tests/scripts/basic-in-docker.sh
  tests/scripts/docker_env.sh
  tests/ssl-opt-in-docker.sh
Labels: enhancement, approved, single-reviewer

#6742 Bignum: Implement fixed width raw modular multiplication
  library/bignum_mod_raw.c
  library/bignum_mod_raw.h
  scripts/mbedtls_dev/bignum_mod_raw.py
  tests/suites/test_suite_bignum_mod_raw.function
Labels: enhancement, approved, component-crypto, priority-high

#6777 Bignum: Implement high level fixed width modular inversion
  library/bignum_core.c
  library/bignum_core.h
  library/bignum_mod.c
  library/bignum_mod.h
  library/bignum_mod_raw.c
  library/bignum_mod_raw.h
  scripts/mbedtls_dev/bignum_common.py
  scripts/mbedtls_dev/bignum_core.py
  scripts/mbedtls_dev/bignum_data.py
  scripts/mbedtls_dev/bignum_mod.py
  scripts/mbedtls_dev/bignum_mod_raw.py
  tests/suites/test_suite_bignum_core.function
  tests/suites/test_suite_bignum_mod.function
  tests/suites/test_suite_bignum_mod.misc.data
  tests/suites/test_suite_bignum_mod_raw.function
Labels: enhancement, approved, component-crypto, priority-high

#6808 Fix code_coverage broken by extra echo in make lcov
  tests/scripts/basic-build-test.sh
Labels: bug, approved, component-test, priority-high

#6822 [Backport 2.28] Fix code_coverage broken by extra echo in make lcov
  tests/scripts/basic-build-test.sh
Labels: bug, approved, single-reviewer, component-test, priority-high

#6827 Backport 2.28 - fix gettimeofday overflow
  ChangeLog.d/fix-gettimeofday-overflow.txt
  library/timing.c
Labels: bug, approved, component-platform, needs-ci, size-s, priority-medium

#6826 Fix gettimeofday overflow
  ChangeLog.d/fix-gettimeofday-overflow.txt
  programs/test/benchmark.c
Labels: bug, approved, component-platform, needs-ci, size-s, priority-medium

#6825 pylint: Set a minimum duplicate match to 10 lines.
  .pylintrc
Labels: approved, size-s, component-test, priority-high

#6795 Hide check_test_cases warnings on the CI
  tests/scripts/all.sh
Labels: approved, size-s, component-test, priority-medium

#6798 Hide check_test_cases warnings on the CI
  tests/scripts/all.sh
Labels: approved, size-s, single-reviewer, component-test, priority-medium

#6282 mbedtls_ecp_point_read_binary from compressed fmt
  ChangeLog.d/mbedtls_ecp_point_read_binary-compressed-fmt.txt
  library/ecp.c
  tests/suites/test_suite_ecjpake.data
  tests/suites/test_suite_ecp.data
  tests/suites/test_suite_ecp.function
Labels: enhancement, approved, component-crypto, size-s, priority-medium

#6747 Bignum mod random
  library/bignum_mod.c
  library/bignum_mod.h
  library/bignum_mod_raw.c
  library/bignum_mod_raw.h
  scripts/mbedtls_dev/bignum_common.py
  scripts/mbedtls_dev/bignum_mod_raw.py
  tests/include/test/bignum_helpers.h
  tests/include/test/helpers.h
  tests/scripts/generate_bignum_tests.py
  tests/src/bignum_helpers.c
  tests/src/helpers.c
  tests/suites/helpers.function
  tests/suites/test_suite_bignum_mod_raw.function
  tests/suites/test_suite_bignum_random.data
  tests/suites/test_suite_bignum_random.function
Labels: approved, component-crypto, size-s, priority-high

#6776 Bignum: Implement fixed width modular multiplication
  library/bignum_mod.c
  library/bignum_mod.h
  scripts/mbedtls_dev/bignum_mod.py
  tests/suites/test_suite_bignum_mod.function
  tests/suites/test_suite_bignum_mod.misc.data
Labels: enhancement, approved, component-crypto, priority-high

#6837 Backport 2.28: Tweak code style to be more like K&R
  .uncrustify.cfg
Labels: approved, size-s, component-test, priority-high

#6836 Tweak code style to be more like K&R
  .uncrustify.cfg
Labels: approved, size-s, component-test, priority-high

#6595 lms: Move merkle tree generation to heap allocation
  library/lms.c
Labels: enhancement, approved, size-s, priority-medium

#5907 Use PSA more often in `pk_verify_ext()`
  docs/use-psa-crypto.md
  include/mbedtls/pk.h
  library/pk.c
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_x509parse.data
  tests/suites/test_suite_x509parse.function
Labels: enhancement, needs-work, needs-ci, priority-medium
