Repository Mbed-TLS/mbedtls, pull requests merged in 2023-11, with the labels that each got.

#8457 Fix broken link to psa-driver-example-and-guide in psa-driver-wrappers-codegen-migration-guide.md
  docs/proposed/psa-driver-wrappers-codegen-migration-guide.md
Labels: bug, approved, component-docs, priority-medium, size-xs

#8196 Backport 2.28: Make check_test_cases.py recognize test case name templates in ssl-opt.sh
  tests/compat.sh
  tests/scripts/check_test_cases.py
  tests/ssl-opt.sh
Labels: bug, approved, size-s, single-reviewer, component-test

#8088 Make check_test_cases.py recognize test case name templates in ssl-opt.sh
  tests/compat.sh
  tests/scripts/check_test_cases.py
  tests/ssl-opt.sh
Labels: bug, approved, size-s, component-test

#8395 Modify lcov.sh to work in tf-psa-crypto as well
  scripts/lcov.sh
Labels: enhancement, approved, component-platform, priority-high

#8443 Clean up curves handling in libtestdriver1 config
  tests/include/test/drivers/crypto_config_test_driver_extension.h
  tests/scripts/all.sh
Labels: approved, needs-review, size-s, priority-high

#8467 Typo fixes in Changelog
  ChangeLog
Labels: bug, approved, component-docs, single-reviewer, size-xs

#8435 Remove cipher/aead legacy dependencies from PSA test suites
  tests/suites/test_suite_psa_crypto_metadata.data
Labels: approved, needs-review, size-s, priority-high

#8434 [G2] Make TLS work without Cipher
  include/mbedtls/check_config.h
  library/ssl_misc.h
  programs/ssl/ssl_context_info.c
  programs/ssl/ssl_server2.c
  tests/scripts/all.sh
  tests/src/test_helpers/ssl_helpers.c
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl_decrypt.misc.data
Labels: approved, size-s, priority-high

#8442 X.509: Support driver-only cipher+aead
  tests/data_files/Makefile
  tests/data_files/test-ca_unenc.key
  tests/scripts/all.sh
  tests/suites/test_suite_x509write.data
Labels: enhancement, approved, component-x509, size-s, priority-high

#8477 [Backport 2.28] Add build preset full_no_platform
  scripts/config.py
  tests/scripts/all.sh
Labels: enhancement, approved, component-platform, priority-high, size-xs

#8391 Add full_no_platform config preset
  scripts/config.py
  tests/scripts/all.sh
Labels: enhancement, approved, component-platform, priority-high, size-xs

#8444 code size for mbedtls_cipher_validate_values
  library/common.h
  library/psa_crypto_cipher.c
Labels: needs-review, component-psa, priority-medium, size-xs

#8485 Backport 2.28: Check copyright statements and SPDX license statements
  tests/scripts/check_files.py
Labels: approved, single-reviewer, priority-very-high, size-xs

#8470 Check copyright statements and SPDX license statements
  tests/scripts/check_files.py
Labels: approved, priority-very-high, size-xs

#6945 TLS 1.3: SRV: Check ticket_flags on kex mode determination when resumption
  library/ssl_misc.h
  library/ssl_tls13_server.c
  tests/opt-testcases/tls13-kex-modes.sh
  tests/opt-testcases/tls13-misc.sh
Labels: bug, needs-review, component-tls13, size-m, priority-high

#8429 Fix test suite never executed due to an undefined symbol
  tests/suites/test_suite_constant_time_hmac.function
Labels: bug, needs-review, needs-ci, priority-high, size-xs

#8469 Mbedtls 2.28.6
  BRANCHES.md
  ChangeLog
  doxygen/input/doc_mainpage.h
  doxygen/mbedtls.doxyfile
  include/mbedtls/config.h
  include/mbedtls/version.h
  library/CMakeLists.txt
  tests/suites/test_suite_version.data
Labels: needs-review, needs-ci, needs-reviewer, priority-very-high

#8468 Mbed TLS 3.5.1
  BRANCHES.md
  CMakeLists.txt
  ChangeLog
  ChangeLog.d/fix-3rdparty-target-prefix.txt
  ChangeLog.d/license.txt
  doxygen/input/doc_mainpage.h
  doxygen/mbedtls.doxyfile
  include/mbedtls/build_info.h
  include/mbedtls/mbedtls_config.h
  library/CMakeLists.txt
  tests/suites/test_suite_version.data
Labels: needs-ci, priority-very-high

#8480 Backports for #7649 : add command for server9-bad-saltlen
  scripts/ci.requirements.txt
  tests/data_files/Makefile
  tests/data_files/opensslcnf/server9.crt.v3_ext
  tests/scripts/generate_server9_bad_saltlen.py
Labels: approved, needs-review, needs-reviewer, size-m, single-reviewer, component-test

#8496 Remove unused *.cocci files
  scripts/find-mem-leak.cocci
  scripts/rm-calloc-cast.cocci
Labels: enhancement, approved, needs-ci, component-test

#8439 Add test-suite parameter to filter tests
  tests/ssl-opt.sh
Labels: approved, needs-ci, component-test, size-xs

#8503 2.28 only: Update license of a newly added file
  tests/scripts/generate_server9_bad_saltlen.py
Labels: approved, needs-ci, priority-very-high

#8378 Fixes "CSR parsing with critical fields fails"
  ChangeLog.d/fix-csr-parsing-with-critical-fields-fails.txt
  include/mbedtls/x509_csr.h
  library/x509_csr.c
  tests/suites/test_suite_x509parse.data
  tests/suites/test_suite_x509parse.function
Labels: approved, needs-review, component-x509, needs-ci, priority-medium

#8495 [G3] Driver-only cipher+aead: TLS: main test suite
  library/ssl_ciphersuites.c
  library/ssl_misc.h
  tests/include/test/ssl_helpers.h
  tests/scripts/all.sh
  tests/src/test_helpers/ssl_helpers.c
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
  tests/suites/test_suite_ssl_decrypt.function
  tests/suites/test_suite_ssl_decrypt.misc.data
Labels: enhancement, approved, component-tls, size-m, priority-high

#8502 [G3] Disable cipher.c in the accel component
  tests/scripts/all.sh
Labels: approved, size-s, priority-high

#8487 TLS 1.3: Rename early_data and max_early_data_size configuration function
  ChangeLog.d/rename-conf-early-data-API.txt
  include/mbedtls/mbedtls_config.h
  include/mbedtls/ssl.h
  library/ssl_tls.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  tests/ssl-opt.sh
Labels: enhancement, approved, component-tls13, priority-high, size-xs

#8498 Remove legacy dependencies from PSA tests
  tests/scripts/all.sh
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.data
  tests/suites/test_suite_psa_crypto_persistent_key.data
  tests/suites/test_suite_psa_crypto_storage_format.function
Labels: approved, component-crypto, size-s, component-test

#8508 [G3] Driver-only cipher+aead: TLS: ssl-opt.sh
  include/mbedtls/ssl.h
  library/ssl_misc.h
  programs/ssl/ssl_server2.c
  tests/scripts/all.sh
  tests/ssl-opt.sh
Labels: approved, size-s, priority-high

#8499 Clean up libtestdriver1 config: unconditonal removals
  tests/include/test/drivers/crypto_config_test_driver_extension.h
Labels: approved, size-s, priority-high

#8164 Adjust how we handle TF-M config files
  configs/config-tfm.h
  configs/ext/crypto_config_profile_medium.h
  configs/ext/tfm_mbedcrypto_config_profile_medium.h
  include/mbedtls/check_config.h
  scripts/code_size_compare.py
  tests/scripts/all.sh
  tests/scripts/analyze_outcomes.py
  tests/scripts/test-ref-configs.pl
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_psa_crypto_slot_management.function
Labels: enhancement, approved, size-s, priority-high

#8519 [G2] Add internal module block_cipher
  include/mbedtls/block_cipher.h
  include/mbedtls/config_adjust_legacy_crypto.h
  library/CMakeLists.txt
  library/Makefile
  library/block_cipher.c
  library/block_cipher_internal.h
  tests/scripts/all.sh
  tests/suites/test_suite_block_cipher.data
  tests/suites/test_suite_block_cipher.function
Labels: enhancement, needs-review, needs-reviewer

#7071 TLS 1.3 EarlyData: add `max_early_data_size` field for ticket
  include/mbedtls/ssl.h
  library/ssl_tls.c
  library/ssl_tls13_server.c
  tests/src/test_helpers/ssl_helpers.c
  tests/suites/test_suite_ssl.function
Labels: approved, component-tls13, priority-high

#8527 [G3] Driver-only cipher+aead: TLS: compat.sh
  tests/scripts/all.sh
Labels: enhancement, approved, component-test, priority-high, size-xs

#8497 [Backport 2.28] Remove unused *.cocci files
  scripts/find-mem-leak.cocci
  scripts/rm-calloc-cast.cocci
Labels: approved

#8491 Backport 2.28: "CSR parsing with critical fields fails" #8377
  tests/suites/test_suite_x509parse.data
Labels: approved, component-x509

#8463 Create a metatest program
  programs/.gitignore
  programs/Makefile
  programs/test/CMakeLists.txt
  programs/test/metatest.c
  scripts/generate_visualc_files.pl
  tests/scripts/all.sh
  tests/scripts/run-metatests.sh
Labels: approved, needs-backports, size-s, component-test, priority-high

#8489 Make CCM* and CCM independent
  ChangeLog.d/8482.txt
  include/mbedtls/config_adjust_legacy_from_psa.h
  include/psa/crypto_adjust_config_synonyms.h
  library/ssl_misc.h
  tests/include/test/drivers/crypto_config_test_driver_extension.h
  tests/include/test/psa_exercise_key.h
  tests/scripts/all.sh
Labels: approved, size-s, priority-high

#7649 Add command for server9-bad-saltlen
  scripts/ci.requirements.txt
  tests/data_files/Makefile
  tests/data_files/opensslcnf/server9.crt.v3_ext
  tests/scripts/generate_server9_bad_saltlen.py
Labels: approved, size-s, component-test, priority-medium

#8438 Disable stdout in require_*_configs_* functions
  tests/ssl-opt.sh
Labels: approved, component-test, size-xs

#6788 TLS 1.3: Fix anti replay fail from GnuTLS
  ChangeLog.d/gnutls_anti_replay_fail.txt
  include/mbedtls/debug.h
  include/mbedtls/mbedtls_config.h
  include/mbedtls/ssl.h
  library/ssl_client.c
  library/ssl_misc.h
  library/ssl_ticket.c
  library/ssl_tls.c
  library/ssl_tls13_client.c
  library/ssl_tls13_server.c
  programs/ssl/ssl_server2.c
  tests/opt-testcases/tls13-misc.sh
  tests/src/test_helpers/ssl_helpers.c
  tests/suites/test_suite_ssl.function
Labels: bug, approved, component-tls13, priority-high

#8222 Backport 2.28: Start testing the PSA built-in drivers: hashes
  scripts/mbedtls_dev/crypto_data_tests.py
  scripts/mbedtls_dev/psa_information.py
  tests/scripts/generate_psa_tests.py
  tests/suites/test_suite_psa_crypto_low_hash.function
  tests/suites/test_suite_psa_crypto_low_hash.generated.data
Labels: approved, component-crypto, size-s, component-test, priority-high

#8541 ssl_tls: add missing macro guard
  include/mbedtls/config_adjust_legacy_crypto.h
  include/mbedtls/ssl.h
  library/ssl_tls.c
Labels: enhancement, approved, component-tls, priority-medium, size-xs

#8440 Fix missing pre shared key ext sent mask
  library/ssl_client.c
Labels: bug, approved, component-tls13, priority-high, size-xs

#8546 [cipher.h] Arithmetic overflow in binary left shift operation
  include/mbedtls/cipher.h
Labels: approved, needs-ci, priority-low, size-xs

#8557 Backport 2.28: Fix metatest.c with gcc-12 -Wuse-after-free
  programs/test/metatest.c
Labels: approved, component-test, priority-very-high, size-xs

#8549 Fix metatest.c with gcc-12 -Wuse-after-free
  programs/test/metatest.c
Labels: bug, approved, needs-backports, component-test, priority-very-high, size-xs

#8558 Backport 2.28: Fix test_suite_platform failure with Asan on modern Clang
  tests/include/test/helpers.h
Labels: approved, component-test, size-xs

#7905 misc improvements
  library/aesni.h
  tests/suites/test_suite_ssl.function
Labels: enhancement, approved, priority-medium, size-xs

#8556 prepare_release: sed querry change to strip whitespace
  scripts/prepare_release.sh
Labels: approved, needs-review, component-platform, priority-medium, size-xs

#8124 Support the negative option MBEDTLS_BLOCK_CIPHER_NO_DECRYPT
  ChangeLog.d/add-block-cipher-no-decrypt.txt
  include/mbedtls/aes.h
  include/mbedtls/aria.h
  include/mbedtls/camellia.h
  include/mbedtls/check_config.h
  include/mbedtls/mbedtls_config.h
  library/aes.c
  library/aesce.c
  library/aesce.h
  library/aesni.c
  library/aesni.h
  library/aria.c
  library/camellia.c
  library/cipher.c
  library/cipher_wrap.c
  library/cipher_wrap.h
  library/padlock.c
  programs/pkey/dh_client.c
  scripts/config.py
  scripts/mbedtls_dev/psa_information.py
  tests/scripts/all.sh
  tests/scripts/generate_psa_tests.py
  tests/suites/test_suite_aes.function
  tests/suites/test_suite_aria.function
  tests/suites/test_suite_camellia.function
  tests/suites/test_suite_cipher.aes.data
  tests/suites/test_suite_psa_crypto.data
Labels: approved, component-crypto, needs-ci, size-m, priority-high, size-optimisation

#8500 Make empty key slots explicit
  library/psa_crypto.c
  library/psa_crypto_core.h
  library/psa_crypto_slot_management.c
Labels: enhancement, needs-review, component-crypto, size-s

#8551 Sign conversion part 1
  library/aesce.c
  library/base64.c
  library/bignum.c
  library/debug.c
  library/dhm.c
  library/ecdh.c
  library/ecjpake.c
  library/entropy_poll.c
  library/lmots.c
  library/lmots.h
  library/lms.c
  library/oid.c
  library/pem.c
  library/pkcs7.c
  library/pkparse.c
  library/psa_crypto.c
  library/psa_its_file.c
  library/rsa.c
  library/ssl_client.c
  library/ssl_misc.h
  library/ssl_msg.c
  library/ssl_ticket.c
  library/ssl_tls.c
  library/ssl_tls12_client.c
  library/ssl_tls12_server.c
  library/x509_create.c
  library/x509_crl.c
  library/x509_crt.c
  library/x509_csr.c
  library/x509write_crt.c
  library/x509write_csr.c
Labels: bug, approved, component-platform, size-s, priority-medium

#8326 Support hw-accelerated AES on Thumb and Arm
  ChangeLog.d/armv8-aesce.txt
  include/mbedtls/mbedtls_config.h
  library/aes.c
  library/aesce.c
  library/aesce.h
  tests/scripts/all.sh
Labels: approved, component-crypto, size-s, priority-medium

#8515 Fix compiler error on gcc 4.5.2.
  library/constant_time_impl.h
Labels: approved, priority-medium, size-xs

#8540 [G2] Make CCM and GCM work with the new block_cipher module
  ChangeLog.d/8060.txt
  include/mbedtls/ccm.h
  include/mbedtls/check_config.h
  include/mbedtls/config_adjust_legacy_crypto.h
  include/mbedtls/gcm.h
  library/ccm.c
  library/gcm.c
  tests/scripts/all.sh
Labels: approved, size-s, priority-high

#8568 Driver-only: G1: clean up for BLOCK_CIPHER_NO_DECRYPT
  configs/ext/tfm_mbedcrypto_config_profile_medium.h
  include/mbedtls/mbedtls_config.h
Labels: enhancement, approved, priority-high, size-xs

#8029 Update old dependency to MBEDTLS_MD_CAN
  tests/scripts/analyze_outcomes.py
  tests/suites/test_suite_pkparse.data
  tests/suites/test_suite_pkparse.function
Labels: bug, approved, component-crypto, priority-high, size-xs

#8286 Fix test_suite_platform failure with Asan on modern Clang
  tests/include/test/helpers.h
  tests/scripts/analyze_outcomes.py
  tests/suites/test_suite_platform.data
Labels: bug, needs-review, needs-backports, component-platform, size-xs

#8547 [G2] Make PSA-AEAD work with cipher-light
  include/mbedtls/check_config.h
  include/mbedtls/config_adjust_psa_from_legacy.h
  tests/scripts/all.sh
Labels: approved, size-s, priority-high

#8570 Backport 2.28: ssl-opt.sh: Fix getting the list of supported ciphersuites.
  tests/ssl-opt.sh
Labels: bug, approved, component-test, priority-very-high, size-xs

#8561 ssl-opt.sh: Fix getting the list of supported ciphersuites.
  tests/ssl-opt.sh
Labels: bug, approved, needs-backports, component-tls, needs-ci, component-test, priority-very-high

#8560 Optimize analyze_outcomes.py
  tests/scripts/analyze_outcomes.py
Labels: enhancement, approved, size-s, component-test, priority-high

#8535 Adjust to match current TF-M config
  configs/config-tfm.h
  configs/ext/crypto_config_profile_medium.h
  configs/ext/tfm_mbedcrypto_config_profile_medium.h
  tests/scripts/all.sh
Labels: approved, priority-medium, size-optimisation, size-xs
