Repository Mbed-TLS/mbedtls, pull requests merged in 2023-04, with the labels that each got.

#7103 Some MAX_SIZE macros are too small when PSA ECC is accelerated
  ChangeLog.d/some-max-size-macro-are-too-small-when-psa-ecc-is-accelerated.txt
  include/mbedtls/check_config.h
  include/psa/crypto_sizes.h
  tests/scripts/all.sh
  tests/suites/test_suite_ecp.function
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.data
Labels: bug, approved, component-crypto, size-s, priority-high

#7059 PSA cryptography miscellaneous
  docs/architecture/mbed-crypto-storage-specification.md
  docs/proposed/psa-driver-developer-guide.md
  docs/proposed/psa-driver-integration-guide.md
  include/mbedtls/build_info.h
  include/mbedtls/mbedtls_config.h
  include/psa/build_info.h
  include/psa/crypto_builtin_composites.h
  include/psa/crypto_builtin_key_derivation.h
  include/psa/crypto_builtin_primitives.h
  include/psa/crypto_driver_contexts_composites.h
  include/psa/crypto_driver_contexts_key_derivation.h
  include/psa/crypto_driver_contexts_primitives.h
  include/psa/crypto_extra.h
  include/psa/crypto_platform.h
  include/psa/crypto_sizes.h
  include/psa/crypto_struct.h
  library/alignment.h
  library/psa_crypto.c
  library/psa_crypto_core_common.h
  library/psa_crypto_slot_management.c
  scripts/data_files/driver_templates/psa_crypto_driver_wrappers.c.jinja
  tests/scripts/all.sh
  tests/src/drivers/hash.c
  tests/src/drivers/test_driver_aead.c
  tests/src/drivers/test_driver_asymmetric_encryption.c
  tests/src/drivers/test_driver_cipher.c
  tests/src/drivers/test_driver_key_agreement.c
  tests/src/drivers/test_driver_key_management.c
  tests/src/drivers/test_driver_mac.c
  tests/src/drivers/test_driver_pake.c
  tests/src/drivers/test_driver_signature.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
Labels: needs-review, needs-ci, component-psa, priority-high

#6233 Bignum: extract core_mul from the prototype
  library/bignum.c
  library/bignum_core.c
  library/bignum_core.h
  scripts/mbedtls_dev/bignum_common.py
  scripts/mbedtls_dev/bignum_core.py
  tests/suites/test_suite_bignum_core.function
Labels: needs-review, component-crypto, size-s, priority-high

#7394 Fix memory allocations in pkcs7_verify test
  tests/suites/test_suite_pkcs7.function
Labels: bug, approved, priority-medium, size-xs

#7324 bignum: Removed merge scaffolding
  library/bignum_core.c
  library/bignum_core.h
  library/bignum_mod.c
  library/bignum_mod.h
  library/bignum_mod_raw.c
  library/bignum_mod_raw.h
  scripts/mbedtls_dev/bignum_common.py
  scripts/mbedtls_dev/bignum_core.py
  scripts/mbedtls_dev/bignum_mod.py
  scripts/mbedtls_dev/bignum_mod_raw.py
  tests/suites/test_suite_bignum_core.function
  tests/suites/test_suite_bignum_core.misc.data
  tests/suites/test_suite_bignum_mod.function
  tests/suites/test_suite_bignum_mod.misc.data
  tests/suites/test_suite_bignum_mod_raw.data
  tests/suites/test_suite_bignum_mod_raw.function
Labels: component-crypto, single-reviewer, priority-medium, size-xs

#7351 Test unlikely cases of ECC modular reduction
  library/ecp_curves.c
  scripts/mbedtls_dev/ecp.py
Labels: enhancement, approved, component-crypto

#7288 TLS: TLS 1.2 / 1.3 version negotiation on server side
  ChangeLog.d/tls13-server-version-negotiation.txt
  docs/architecture/tls13-support.md
  include/mbedtls/ssl.h
  library/ssl_client.c
  library/ssl_misc.h
  library/ssl_tls.c
  library/ssl_tls12_server.c
  library/ssl_tls13_client.c
  library/ssl_tls13_generic.c
  library/ssl_tls13_server.c
  tests/include/test/ssl_helpers.h
  tests/opt-testcases/tls13-compat.sh
  tests/opt-testcases/tls13-kex-modes.sh
  tests/opt-testcases/tls13-misc.sh
  tests/scripts/generate_tls13_compat_tests.py
  tests/src/test_helpers/ssl_helpers.c
  tests/ssl-opt.sh
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: enhancement, approved, component-tls, priority-high

#7391 PK: don't use mbedtls_ecp_check_pub_priv() when USE_PSA is enabled
  library/pk_wrap.c
  tests/suites/test_suite_pk.function
Labels: enhancement, approved, size-s, priority-high

#7392 PK: use PSA to complete public key when USE_PSA is enabled
  library/pk_wrap.c
  library/pkparse.c
  tests/suites/test_suite_pkparse.function
Labels: enhancement, approved, size-s, priority-high

#7287 6500 follow-up: enhancements to the new ssl_helpers test module
  tests/include/test/ssl_helpers.h
  tests/src/test_helpers/ssl_helpers.c
  tests/suites/test_suite_ssl.function
Labels: enhancement, approved, component-tls, needs-ci, size-s, priority-high

#7332 Backport 2.28: 6500 follow-up: enhancements to the new ssl_helpers test module #7287
  tests/include/test/ssl_helpers.h
  tests/src/test_helpers/ssl_helpers.c
  tests/suites/test_suite_ssl.function
Labels: enhancement, approved, size-s, component-test, priority-high

#7401 Add missing md.h includes
  ChangeLog.d/add-missing-md-includes.txt
  include/mbedtls/ssl.h
  programs/pkey/dh_client.c
  programs/pkey/dh_server.c
  programs/pkey/pk_sign.c
  programs/pkey/pk_verify.c
  programs/pkey/rsa_sign.c
  programs/pkey/rsa_sign_pss.c
  programs/pkey/rsa_verify.c
  programs/pkey/rsa_verify_pss.c
  programs/x509/cert_req.c
  programs/x509/cert_write.c
Labels: approved, size-s

#7418 Update SEC1 link in ecp.c
  library/ecp.c
Labels: approved, needs-ci, component-docs, priority-medium

#7393 PK tests: use PSA to generate keypairs when USE_PSA is enabled
  tests/suites/test_suite_pk.function
Labels: enhancement, approved, size-s, priority-high

#7329 ecp: Unify test cases
  scripts/mbedtls_dev/bignum_common.py
  scripts/mbedtls_dev/ecp.py
  tests/suites/test_suite_ecp.function
Labels: enhancement, needs-review, needs-ci, size-s, component-test, priority-low

#7440 Test fixes for big-endian
  tests/suites/test_suite_alignment.function
Labels: bug, approved, needs-ci, size-s, component-test

#7410 Define (private) "light" subset of ECP
  include/mbedtls/build_info.h
  include/mbedtls/check_config.h
  include/mbedtls/ecp.h
  include/mbedtls/oid.h
  include/mbedtls/pk.h
  include/mbedtls/ssl.h
  include/psa/crypto_extra.h
  library/debug.c
  library/ecp.c
  library/ecp_curves.c
  library/ecp_invasive.h
  library/oid.c
  library/pk.c
  library/pk_wrap.c
  library/pk_wrap.h
  library/pkparse.c
  library/pkwrite.c
  library/psa_crypto.c
  library/ssl_client.c
  library/ssl_misc.h
  library/ssl_tls.c
  library/x509_crt.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  tests/scripts/all.sh
  tests/scripts/analyze_outcomes.py
  tests/src/psa_exercise_key.c
  tests/ssl-opt.sh
  tests/suites/test_suite_debug.data
  tests/suites/test_suite_ecp.function
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_pkparse.data
  tests/suites/test_suite_pkparse.function
  tests/suites/test_suite_pkwrite.data
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
  tests/suites/test_suite_x509parse.data
Labels: enhancement, approved, size-s, priority-high

#7331 PSA PAKE: Check input_length against PSA_PAKE_INPUT_SIZE() in psa_pake_input
  docs/proposed/psa-driver-interface.md
  include/psa/crypto_extra.h
  library/psa_crypto.c
  tests/suites/test_suite_psa_crypto_pake.data
  tests/suites/test_suite_psa_crypto_pake.function
Labels: enhancement, approved, needs-ci, component-psa

#7409 [Backport 2.28] Clarify LTS lifetime
  BRANCHES.md
Labels: enhancement, approved, needs-ci, component-docs, single-reviewer, priority-medium, size-xs

#7383 Clarify LTS lifetime
  BRANCHES.md
Labels: enhancement, approved, needs-backports, component-docs, single-reviewer, priority-medium, size-xs

#7431 driver-only: ECP.PSA starter
  tests/scripts/all.sh
  tests/scripts/analyze_outcomes.py
  tests/src/psa_exercise_key.c
Labels: enhancement, component-crypto, size-s, priority-high

#7424 Add unit tests for ecp_mod_p192k1()
  library/ecp_curves.c
  library/ecp_invasive.h
  scripts/mbedtls_dev/ecp.py
  tests/suites/test_suite_ecp.function
Labels: enhancement, needs-review, component-crypto, needs-reviewer, size-s, priority-high

#7425 ECP: Add Unit Tests for secp224k1
  library/ecp_curves.c
  library/ecp_invasive.h
  scripts/mbedtls_dev/ecp.py
  tests/suites/test_suite_ecp.function
Labels: needs-review, needs-reviewer, size-s, component-test, priority-high

#7436 x509 SAN IP parsing
  ChangeLog.d/verify-ip-sans-properly.txt
  include/mbedtls/x509_crt.h
  library/x509_crt.c
  library/x509_invasive.h
  tests/scripts/all.sh
  tests/suites/test_suite_x509parse.data
  tests/suites/test_suite_x509parse.function
Labels: enhancement, approved, component-x509, priority-high

#7449 Clean up & improve PK write test functions
  tests/data_files/Makefile
  tests/data_files/ec_256_long_prv.der
  tests/data_files/ec_521_prv.der
  tests/data_files/ec_521_pub.der
  tests/data_files/ec_521_short_prv.der
  tests/data_files/ec_bp512_prv.der
  tests/data_files/ec_bp512_pub.der
  tests/data_files/rsa4096_prv.der
  tests/data_files/rsa4096_pub.der
  tests/data_files/server1.key.der
  tests/data_files/server1.pubkey.der
  tests/suites/test_suite_pkwrite.data
  tests/suites/test_suite_pkwrite.function
Labels: enhancement, approved, needs-ci, size-s, priority-medium

#7456 Backport: Clean up & improve PK write test functions
  tests/data_files/Makefile
  tests/data_files/ec_256_long_prv.der
  tests/data_files/ec_521_prv.der
  tests/data_files/ec_521_pub.der
  tests/data_files/ec_521_short_prv.der
  tests/data_files/ec_bp512_prv.der
  tests/data_files/ec_bp512_pub.der
  tests/data_files/rsa4096_prv.der
  tests/data_files/rsa4096_pub.der
  tests/data_files/server1.key.der
  tests/data_files/server1.pubkey.der
  tests/suites/test_suite_pkwrite.data
  tests/suites/test_suite_pkwrite.function
Labels: approved, needs-ci, priority-medium

#7465 Check remaning dependencies on ECP in PK module
  docs/architecture/psa-migration/syms.sh
  tests/scripts/all.sh
Labels: approved, needs-ci, size-s, single-reviewer, priority-high

#7450 Update gen_prvkey_mx paras to align with comments and c code
  library/ecp_invasive.h
Labels: needs-backports, component-crypto, priority-medium, size-xs

#7463 Pass pk_context pointer to PK wrappers instead of void pointer
  library/pk.c
  library/pk_wrap.c
  library/pk_wrap.h
Labels: approved, size-s, priority-high

#7448 Roll up the loop in ecp_mod_koblitz()
  library/ecp_curves.c
Labels: enhancement, needs-review, component-crypto, needs-preceding-pr, needs-reviewer, size-s, priority-high

#7462 clz size/perf optimisation
  library/bignum_core.c
  library/bignum_core.h
  tests/suites/test_suite_bignum_core.function
  tests/suites/test_suite_bignum_core.misc.data
Labels: approved, component-crypto, priority-high, size-optimisation, size-xs

#7427 ECP: Add Unit Tests for secp256k1
  library/ecp_curves.c
  library/ecp_invasive.h
  scripts/mbedtls_dev/ecp.py
  tests/suites/test_suite_ecp.function
Labels: enhancement, approved, needs-review, size-s, component-test, priority-high

#7429 Update links to references in bignum
  library/ecdh.c
  library/ecdsa.c
  library/ecp.c
Labels: approved, needs-backports, needs-ci, component-docs, size-s, single-reviewer, priority-medium

#7469 Backport 2.28: Update links of references in bignum code
  library/ecdh.c
  library/ecdsa.c
  library/ecp.c
Labels: approved, needs-ci, component-docs, single-reviewer, priority-medium

#7316 Add msvc support for AESCE
  include/mbedtls/check_config.h
  include/mbedtls/mbedtls_config.h
  library/aesce.c
  library/aesce.h
Labels: approved, component-crypto, needs-ci, priority-high

#7468 Add link to review guideline fro contributors
  CONTRIBUTING.md
Labels: enhancement, approved, single-reviewer, priority-medium, size-xs

#7433 Fix PSA AEAD ChaCha20 test dependency.
  tests/suites/test_suite_psa_crypto.data
Labels: bug, approved, needs-backports, single-reviewer, component-test, size-xs

#7510 Fix psa aead chacha20 test dependency - backport 2.28
  tests/suites/test_suite_psa_crypto.data
Labels: bug, approved, needs-ci, component-psa, single-reviewer, priority-medium, size-xs

#7499 Bug Fix: mbedtls_ecdsa_verify_restartable fails with ECDSA_SIGN_ALT
  ChangeLog.d/mbedtls_ecdsa_can_do-unconditional-define.txt
  library/ecdsa.c
Labels: bug, approved, component-crypto, priority-medium, size-xs

#7488 Backport 2.28: Init PSA in ssl and x509 programs
  ChangeLog.d/programs_psa_fix.txt
  programs/fuzz/fuzz_client.c
  programs/fuzz/fuzz_dtlsclient.c
  programs/fuzz/fuzz_dtlsserver.c
  programs/fuzz/fuzz_privkey.c
  programs/fuzz/fuzz_pubkey.c
  programs/fuzz/fuzz_server.c
  programs/fuzz/fuzz_x509crl.c
  programs/fuzz/fuzz_x509crt.c
  programs/fuzz/fuzz_x509csr.c
  programs/pkey/gen_key.c
  programs/pkey/key_app.c
  programs/pkey/key_app_writer.c
  programs/pkey/pk_decrypt.c
  programs/pkey/pk_encrypt.c
  programs/pkey/pk_sign.c
  programs/pkey/pk_verify.c
  programs/pkey/rsa_sign_pss.c
  programs/pkey/rsa_verify_pss.c
  programs/ssl/dtls_client.c
  programs/ssl/dtls_server.c
  programs/ssl/mini_client.c
  programs/ssl/ssl_client1.c
  programs/ssl/ssl_context_info.c
  programs/ssl/ssl_fork_server.c
  programs/ssl/ssl_mail_client.c
  programs/ssl/ssl_pthread_server.c
  programs/ssl/ssl_server.c
  programs/x509/cert_app.c
  programs/x509/cert_req.c
  programs/x509/cert_write.c
  programs/x509/crl_app.c
  programs/x509/load_roots.c
  programs/x509/req_app.c
Labels: approved, size-s

#7443 Init PSA in ssl and x509 programs
  ChangeLog.d/programs_psa_fix.txt
  programs/fuzz/fuzz_client.c
  programs/fuzz/fuzz_dtlsclient.c
  programs/fuzz/fuzz_dtlsserver.c
  programs/fuzz/fuzz_privkey.c
  programs/fuzz/fuzz_pubkey.c
  programs/fuzz/fuzz_server.c
  programs/fuzz/fuzz_x509crl.c
  programs/fuzz/fuzz_x509crt.c
  programs/fuzz/fuzz_x509csr.c
  programs/pkey/gen_key.c
  programs/pkey/key_app.c
  programs/pkey/key_app_writer.c
  programs/pkey/pk_decrypt.c
  programs/pkey/pk_encrypt.c
  programs/pkey/pk_sign.c
  programs/pkey/pk_verify.c
  programs/pkey/rsa_sign_pss.c
  programs/pkey/rsa_verify_pss.c
  programs/ssl/dtls_client.c
  programs/ssl/dtls_server.c
  programs/ssl/mini_client.c
  programs/ssl/ssl_client1.c
  programs/ssl/ssl_context_info.c
  programs/ssl/ssl_fork_server.c
  programs/ssl/ssl_mail_client.c
  programs/ssl/ssl_pthread_server.c
  programs/ssl/ssl_server.c
  programs/x509/cert_app.c
  programs/x509/cert_req.c
  programs/x509/cert_write.c
  programs/x509/crl_app.c
  programs/x509/load_roots.c
  programs/x509/req_app.c
Labels: bug, approved, needs-backports, size-s

#7502 Fix VS2022 build error
  library/bignum_core.c
Labels: bug, needs-review, needs-reviewer, priority-very-high

#7419 Workaround random `test_suite_platform` fail in time test
  tests/suites/test_suite_platform.data
  tests/suites/test_suite_platform.function
Labels: bug, component-test, priority-high
