Repository Mbed-TLS/mbedtls, pull requests merged in 2023-07, with the labels that each got.

#7627 Make use of FFDH keys in TLS 1.3 v.2
  ChangeLog.d/ffdh-tls-1-3.txt
  include/mbedtls/build_info.h
  include/mbedtls/check_config.h
  include/mbedtls/mbedtls_config.h
  include/mbedtls/psa_util.h
  library/psa_crypto.c
  library/psa_crypto_ffdh.c
  library/psa_crypto_ffdh.h
  library/ssl_client.c
  library/ssl_misc.h
  library/ssl_tls.c
  library/ssl_tls12_client.c
  library/ssl_tls12_server.c
  library/ssl_tls13_client.c
  library/ssl_tls13_generic.c
  library/ssl_tls13_keys.c
  library/ssl_tls13_server.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  programs/ssl/ssl_test_lib.c
  programs/ssl/ssl_test_lib.h
  tests/include/test/ssl_helpers.h
  tests/opt-testcases/tls13-compat.sh
  tests/opt-testcases/tls13-kex-modes.sh
  tests/scripts/all.sh
  tests/scripts/generate_tls13_compat_tests.py
  tests/src/drivers/test_driver_key_agreement.c
  tests/src/drivers/test_driver_key_management.c
  tests/ssl-opt.sh
  tests/suites/test_suite_ssl.function
Labels: approved, priority-high

#7626 Support compilation using CLang on Windows
  ChangeLog.d/fix-win32-llvm-build.txt
  library/aesni.c
Labels: bug, component-platform, single-reviewer, size-xs

#7823 Support compilation using CLang on Windows
  ChangeLog.d/fix-win32-llvm-build.txt
  library/aesni.c
Labels: component-platform

#7702 PBKDF2: Out of range input cost
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: approved, component-crypto, size-s, component-test, priority-high

#7853 7831 follow-up: fix wrong dependency name and wrong commands
  tests/data_files/Makefile
  tests/data_files/test-ca.opensslconf
Labels: bug, needs-review, component-test, priority-high, size-xs

#7854 Fix AES dependencies - build TF-M config cleanly - backport 2.28
  ChangeLog.d/fix-tfm-build.txt
  library/aes.c
  library/ctr_drbg.c
  library/entropy.c
  library/pkparse.c
  library/pkwrite.c
  tests/scripts/all.sh
Labels: bug, approved, component-crypto, size-s, priority-high

#7851 Fix AES dependencies - build TF-M config cleanly
  ChangeLog.d/fix-tfm-build.txt
  library/aes.c
  library/x509.c
  tests/scripts/all.sh
Labels: bug, approved, needs-backports, component-crypto, size-s, priority-high

#7840 AES: use uint8_t for array of pow and log to save RAM usage
  library/aes.c
Labels: approved, priority-high, size-optimisation, size-xs

#7834 aesce: do not specify an arch version when enabling crypto instructions
  library/aesce.c
Labels: approved

#7829 De-duplicate TLS hashing functions
  library/ssl_tls.c
Labels: approved, needs-ci, size-s, priority-high, size-optimisation

#7874 code_size_compare.py: run make clean before build libraries
  scripts/code_size_compare.py
Labels: enhancement, needs-ci, priority-high, size-optimisation, size-xs

#7784 Further AES perf
  ChangeLog.d/aes-perf.txt
  library/aes.c
  library/aesce.c
  library/aesce.h
  library/bn_mul.h
  library/cmac.c
  library/common.h
Labels: approved, component-crypto, size-s, priority-high

#7862 Improve write supported group ext
  library/ssl_client.c
Labels: enhancement, approved, component-tls13, priority-high

#7876 Backport 2.28: code_style.py --since
  scripts/code_style.py
Labels: approved, priority-low, size-xs

#7825 Cipher wrap size improvement
  include/mbedtls/cipher.h
  library/ccm.c
  library/cipher.c
  library/cipher_wrap.c
  library/cipher_wrap.h
  library/cmac.c
  library/gcm.c
  library/nist_kw.c
  library/pkcs12.c
  library/pkcs5.c
  library/psa_crypto_cipher.c
  library/ssl_tls.c
  library/ssl_tls13_keys.c
  tests/src/test_helpers/ssl_helpers.c
  tests/suites/test_suite_cipher.function
Labels: approved, component-crypto, size-s, priority-high, size-optimisation

#6003 mbedtls_x509_time performance and reduce memory use
  ChangeLog.d/mbedtls_x509_time.txt
  include/mbedtls/x509.h
  library/x509.c
  library/x509_crt.c
Labels: enhancement, approved, component-x509, needs-ci, priority-medium, size-optimisation

#7890 AES: fix mismatch comment in #endif
  library/aes.c
Labels: enhancement, approved, single-reviewer, priority-medium, size-xs

#7492 README: add section about drivers
  README.md
Labels: approved, component-psa, single-reviewer, priority-high, size-xs

#7810 Define PSA_WANT_xxx_KEY_PAIR_yyy step 2/ECC
  configs/crypto_config_profile_medium.h
  include/mbedtls/check_config.h
  include/mbedtls/config_psa.h
  include/mbedtls/pk.h
  include/psa/crypto_legacy.h
  library/check_crypto_config.h
  library/psa_crypto.c
  library/psa_crypto_ecp.c
  tests/scripts/all.sh
  tests/scripts/generate_psa_tests.py
  tests/src/drivers/test_driver_key_management.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
  tests/suites/test_suite_psa_crypto_entropy.data
  tests/suites/test_suite_psa_crypto_pake.data
  tests/suites/test_suite_psa_crypto_slot_management.data
Labels: approved, size-m, priority-high

#7867 Officially require Python 3.8
  ChangeLog.d/python3.8.txt
  README.md
Labels: single-reviewer, priority-high, size-xs

#7868 Backport 2.28: officially require Python 3.6
  README.md
Labels: approved, single-reviewer, priority-high, size-xs

#7585 Backport 2.28: Fuzz programs: print an error if loading the reproducer fails
  programs/fuzz/onefile.c
Labels: needs-review, needs-reviewer, single-reviewer, component-test, priority-medium, size-xs

#7584 Fuzz programs: print an error if loading the reproducer fails
  programs/fuzz/onefile.c
Labels: enhancement, approved, needs-backports, component-test, priority-medium, size-xs

#7858 Make use of FFDH keys in TLS 1.3 - follow-up
  library/ssl_client.c
  library/ssl_misc.h
  library/ssl_tls.c
  library/ssl_tls12_client.c
  library/ssl_tls12_server.c
  library/ssl_tls13_client.c
  library/ssl_tls13_generic.c
  library/ssl_tls13_keys.c
  library/ssl_tls13_server.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  programs/ssl/ssl_test_lib.c
  programs/ssl/ssl_test_lib.h
  tests/opt-testcases/tls13-compat.sh
  tests/opt-testcases/tls13-kex-modes.sh
  tests/scripts/generate_tls13_compat_tests.py
  tests/ssl-opt.sh
  tests/suites/test_suite_ssl.function
Labels: approved, needs-ci, priority-high

#7464 Replace CLOCK_MONOTONIC with CLOCK_BOOTTIME for `mbedtls_ms_time` on linux
  library/platform_util.c
Labels: approved, needs-review, component-platform, priority-low, size-xs

#7212 Fix error: comparison of integers of different signs: 'SOCKET' and 'int'
  library/net_sockets.c
Labels: approved, needs-backports, historical-reviewed, size-xs

#7213 mbedtls-2.28: Fix error: comparison of integers of different signs: 'SOCKET' and 'int'
  library/net_sockets.c
Labels: approved, size-xs

#6974 [Backport 2.28] Pass `MBEDTLS_CONFIG_FILE` defines through cmake
  CMakeLists.txt
  ChangeLog.d/cmake-pass-through-config-defines.txt
  library/CMakeLists.txt
  tests/scripts/all.sh
Labels: approved, size-s

#6914 Pass `MBEDTLS_CONFIG_FILE` defines through cmake
  CMakeLists.txt
  ChangeLog.d/cmake-pass-through-config-defines.txt
  library/CMakeLists.txt
  tests/scripts/all.sh
Labels: enhancement, approved, component-platform, needs-ci, historical-reviewing, priority-medium

#7441 More mbedtls_x509_crt_parse_path() tests, and note qemu-user bug when 32-bit code run on 64-bit host
  tests/suites/test_suite_x509parse.data
  tests/suites/test_suite_x509parse.function
Labels: approved, needs-backports, component-x509, priority-medium, size-xs

#7483 Backport 2.28: More mbedtls_x509_crt_parse_path() tests, and note qemu-user bug when 32-bit code run on 64-bit host
  tests/suites/test_suite_x509parse.data
  tests/suites/test_suite_x509parse.function
Labels: approved, component-x509, priority-medium, size-xs

#7887 tls13: server: Fix spurious HRR
  ChangeLog.d/fix-hrr-in-psk-kem.txt
  library/ssl_tls13_server.c
  tests/ssl-opt.sh
Labels: enhancement, approved, component-tls13, priority-high

#7136 Record the outcome of each test case in compat.sh
  docs/architecture/testing/test-framework.md
  tests/compat.sh
  tests/ssl-opt.sh
Labels: enhancement, approved, needs-backports, component-tls, size-s, historical-reviewed, priority-medium

#7897 Backport 2.28: Record the outcome of each test case in compat.sh
  docs/architecture/testing/test-framework.md
  tests/compat.sh
  tests/ssl-opt.sh
Labels: needs-review, priority-medium, size-xs

#7656 FFDH 4: driver-only parity testing - with TLS 1.3
  tests/scripts/all.sh
  tests/scripts/analyze_outcomes.py
  tests/suites/test_suite_psa_crypto_metadata.function
Labels: approved, priority-high

#7216 Add getters for some fields
  ChangeLog.d/add-getters-for-some-fields.txt
  include/mbedtls/ssl.h
  include/mbedtls/ssl_cache.h
  tests/src/test_helpers/ssl_helpers.c
  tests/suites/test_suite_ssl.function
Labels: enhancement, approved, component-tls, size-s, historical-reviewed, priority-medium

#7879 tests/test_suite_pem: Augment DES test cases with AES: PEM
  tests/suites/test_suite_pem.data
Labels: enhancement, approved, needs-backports, component-crypto, priority-medium, size-xs

#7908 Fix failure of ssl-opt "TLS 1.3: no HRR in case of PSK key exchange mode"
  tests/ssl-opt.sh
Labels: approved, needs-ci, single-reviewer, priority-very-high, size-xs

#7500 Fix MBEDTLS_BSWAP32 on armcc 5
  library/alignment.h
Labels: bug, approved, needs-ci, historical-reviewing, priority-medium, size-xs

#7863 PK: parse: fix disparity with private Montgomery keys
  library/ecp.c
  library/pkparse.c
  tests/scripts/analyze_outcomes.py
  tests/suites/test_suite_pkparse.data
  tests/suites/test_suite_pkparse.function
Labels: bug, approved, size-s, priority-high

#7907 2.28 only: tests/test_suite_ecp: Fix ECP group compare test
  tests/suites/test_suite_ecp.function
Labels: approved, priority-medium, size-xs

#7507 Fix armclang without cmd target flags fail
  include/mbedtls/mbedtls_config.h
  library/aesce.c
  library/sha256.c
  library/sha512.c
Labels: bug, approved, component-crypto, needs-ci, size-s, priority-high

#7920 Reduce size of static data in gcm
  library/gcm.c
Labels: approved, component-crypto, needs-ci, single-reviewer, priority-high, size-optimisation, size-xs

#7792 Don't force _WIN32_WINNT values
  library/entropy_poll.c
  library/net_sockets.c
  library/x509_crt.c
Labels: bug, approved, component-platform, priority-medium

#7925 Fix order of steps in DTLS server example program
  programs/ssl/dtls_server.c
Labels: approved, component-tls, single-reviewer, priority-medium, size-xs

#7432 Fix derive_ecjpake_to_pms dependency in PSA crypto test
  tests/suites/test_suite_psa_crypto.function
Labels: approved, component-test, historical-reviewed, priority-medium, size-xs

#7478 Add script for generating cert macros
  tests/data_files/Makefile
  tests/data_files/test_certs.h.jinja2
  tests/scripts/generate_test_cert_macros.py
  tests/src/certs.c
  tests/src/test_certs.h
Labels: enhancement, approved, component-test, priority-high

#7923 [Bignum] Fixes for the ecp module cloning
  library/ecp.c
  tests/suites/test_suite_ecp.function
Labels: approved, component-crypto, priority-high

#7848 driver-only ECC: EPCf.TLS testing
  include/mbedtls/ssl.h
  library/ssl_misc.h
  library/ssl_tls.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  programs/ssl/ssl_test_lib.c
  tests/scripts/all.sh
  tests/suites/test_suite_debug.data
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: approved, size-s, priority-high

#7859 Reduce the size of mbedtls_mpi
  include/mbedtls/bignum.h
  library/bignum.c
  library/ecp.c
  library/ecp_curves.c
  tests/suites/test_suite_bignum_random.function
Labels: approved, component-crypto, priority-high, size-optimisation, size-xs

#7950 Fix IAR trying to use memset_s in platform_util
  library/platform_util.c
Labels: approved, single-reviewer, size-xs

#7949 Use correct asm keyword for IAR compilers
  library/common.h
Labels: needs-review, needs-reviewer, size-s

#7932 Use compile-time determination of which __builtin_clz() to use, with new MBEDTLS_MPI_UINT_SIZE macro
  include/mbedtls/bignum.h
  library/bignum_core.c
Labels: approved, needs-ci, size-s

#7960 Robustness fix to MBEDTLS_LIKELY
  library/common.h
Labels: bug, approved, needs-ci, single-reviewer, priority-medium, size-xs

#7546 Align psa md identifiers
  include/mbedtls/md.h
  library/md.c
  library/md_psa.h
  library/psa_crypto_rsa.c
  library/ssl_tls.c
  tests/scripts/all.sh
  tests/suites/test_suite_md.data
  tests/suites/test_suite_md.function
Labels: approved, size-s, priority-high, size-optimisation

#5549 Fix wrong doxygen parameter names and misused `\p` commands
  include/mbedtls/aria.h
  include/mbedtls/asn1.h
  include/mbedtls/bignum.h
  include/mbedtls/camellia.h
  include/mbedtls/cipher.h
  include/mbedtls/dhm.h
  include/mbedtls/ecdsa.h
  include/mbedtls/ecp.h
  include/mbedtls/hmac_drbg.h
  include/mbedtls/mbedtls_config.h
  include/mbedtls/pk.h
  include/mbedtls/rsa.h
  include/mbedtls/ssl.h
  include/mbedtls/ssl_cache.h
  include/mbedtls/x509.h
  include/psa/crypto.h
  include/psa/crypto_extra.h
Labels: bug, approved, needs-backports, historical-reviewing, priority-medium

#7922 [Backport 2.28] Fix wrong doxygen parameter names and misused \p commands
  include/mbedtls/aria.h
  include/mbedtls/asn1.h
  include/mbedtls/bignum.h
  include/mbedtls/camellia.h
  include/mbedtls/cipher.h
  include/mbedtls/config.h
  include/mbedtls/ecdsa.h
  include/mbedtls/ecp.h
  include/mbedtls/hmac_drbg.h
  include/mbedtls/pk.h
  include/mbedtls/rsa.h
  include/mbedtls/ssl.h
  include/mbedtls/x509_crt.h
Labels: bug, needs-review, priority-medium

#7893 Miscellaneous fixes resulting from the work on PSA-Crypto
  ChangeLog.d/misc-from-psa-crypto.txt
  configs/crypto-config-ccm-aes-sha256.h
  include/mbedtls/check_config.h
  include/psa/crypto_builtin_primitives.h
  tests/scripts/all.sh
  tests/src/random.c
  tests/suites/test_suite_alignment.function
Labels: enhancement, needs-review, component-crypto, component-psa, priority-high

#7518 Fix and test MBEDTLS_PSA_INJECT_ENTROPY
  .gitignore
  ChangeLog.d/inject-entropy.txt
  library/psa_crypto.c
  scripts/config.py
  tests/configs/user-config-for-test.h
  tests/include/test/psa_crypto_helpers.h
  tests/scripts/all.sh
  tests/src/helpers.c
  tests/src/psa_crypto_helpers.c
  tests/suites/test_suite_entropy.function
  tests/suites/test_suite_psa_crypto_entropy.function
  tests/suites/test_suite_psa_crypto_init.data
  tests/suites/test_suite_random.function
Labels: bug, enhancement, approved, component-psa, size-s, priority-medium

#7965 Backport 2.28: Fix and test MBEDTLS_PSA_INJECT_ENTROPY
  .gitignore
  ChangeLog.d/inject-entropy.txt
  library/psa_crypto.c
  scripts/config.py
  tests/configs/user-config-for-test.h
  tests/include/test/psa_crypto_helpers.h
  tests/scripts/all.sh
  tests/src/helpers.c
  tests/src/psa_crypto_helpers.c
  tests/suites/test_suite_entropy.function
  tests/suites/test_suite_psa_crypto_entropy.function
  tests/suites/test_suite_psa_crypto_init.data
  tests/suites/test_suite_random.function
  tests/suites/test_suite_ssl.function
Labels: bug, enhancement, approved, component-psa, size-s, priority-medium

#7906 PSA: add guards for PAKE getter functions
  library/psa_crypto.c
Labels: needs-review, needs-ci, priority-high, size-optimisation, size-xs

#7900 ECPf wrap-up
  ChangeLog.d/driver-only-ecc.txt
  ChangeLog.d/extend-pk-opaque-ecc.txt
  docs/driver-only-builds.md
Labels: enhancement, approved, priority-high

#7935 Add type casts for integer and enum types
  library/lmots.c
  library/lms.c
  library/psa_crypto.c
  library/rsa.c
  library/ssl_ciphersuites.c
  library/ssl_msg.c
  library/ssl_tls.c
  library/ssl_tls12_client.c
  library/ssl_tls12_server.c
  tests/include/test/macros.h
  tests/src/test_helpers/ssl_helpers.c
Labels: approved, single-reviewer, size-xs

#7909 Enable DH in generate_psa_tests.py
  scripts/mbedtls_dev/crypto_knowledge.py
  tests/scripts/generate_psa_tests.py
Labels: enhancement, approved, size-s, priority-high

#7835 Fix empty union when TLS is disabled
  ChangeLog.d/ssl_premaster_secret-empty.txt
  include/mbedtls/ssl.h
Labels: bug, approved, needs-backports, component-tls, single-reviewer, priority-medium, size-xs

#7988 Add 32bit test component for ecp with new bignum interface
  tests/scripts/all.sh
Labels: enhancement, approved, component-test, priority-high

#8003 Make code_style.py --since more precise
  scripts/code_style.py
Labels: enhancement, approved, needs-review, needs-backports, component-platform, needs-ci, single-reviewer, priority-medium, size-xs

#8004 backport 2.28 - Make code_style.py --since more precise
  scripts/code_style.py
Labels: enhancement, approved, needs-review, component-platform, needs-ci, single-reviewer, priority-medium, size-xs

#7811 Optimize strings in MD
  include/mbedtls/md.h
  library/md.c
  library/md_wrap.h
  library/psa_crypto.c
  library/psa_crypto_hash.h
Labels: approved, priority-high, size-optimisation

#7777 [Bignum] Bignum cleanup ecp curves
  library/ecp.c
  library/ecp_curves.c
  tests/suites/test_suite_ecp.function
Labels: approved, component-crypto, priority-high
