Repository Mbed-TLS/mbedtls, pull requests merged in 2023-09, with the labels that each got.

#8116 Announce that #7420 is fixed
  ChangeLog.d/config_psa-include-order.txt
Labels: needs-review, priority-very-high, size-xs

#8068 Fix TLS pad buffer zeroization
  ChangeLog.d/fix-tls-padbuf-zeroization
  library/ssl_tls.c
Labels: approved, component-tls, needs-ci, priority-high, size-xs

#8144 Add more protection to mbedtls_platform_zeroize
  library/platform_util.c
Labels: enhancement, approved, component-platform, needs-ci, priority-medium, size-xs

#8082 Misc code size improvements
  include/mbedtls/ccm.h
  include/mbedtls/entropy.h
  include/mbedtls/sha256.h
  library/ccm.c
  library/ecp.c
  library/psa_crypto.c
  library/psa_crypto_core.h
  library/psa_crypto_mac.c
  library/psa_crypto_slot_management.c
  scripts/data_files/driver_templates/psa_crypto_driver_wrappers.c.jinja
  tests/src/drivers/test_driver_aead.c
Labels: approved, size-s, priority-high, size-optimisation

#8145 Backport 2.28: Check mbedtls_platform_zeroize() calls
  include/mbedtls/platform_util.h
  tests/configs/user-config-zeroize-memset.h
  tests/scripts/all.sh
  tests/suites/test_suite_pkwrite.function
Labels: approved, component-platform, priority-medium, size-xs

#8143 Check mbedtls_platform_zeroize() calls
  include/mbedtls/platform_util.h
  tests/configs/user-config-zeroize-memset.h
  tests/scripts/all.sh
  tests/suites/test_suite_pkwrite.function
Labels: approved, needs-backports, component-platform, needs-ci, priority-medium, size-xs

#8146 Backport 2.28: Define all PSA_xxx macros to 1 rather than have them empty, for consistency
  include/mbedtls/config_psa.h
  library/psa_crypto_storage.h
Labels: approved, single-reviewer, priority-medium, size-xs

#8141 Define all PSA_xxx macros to 1 rather than have them empty, for consistency
  include/mbedtls/config_psa.h
  library/psa_crypto_storage.h
Labels: approved, needs-backports, priority-medium, size-xs

#8158 Backport 2.28: Rename test macros ASSERT_COMPARE(), ASSERT_ALLOC() and ASSERT_ALLOC_WEAK()
  tests/include/test/macros.h
  tests/src/psa_exercise_key.c
  tests/src/test_helpers/ssl_helpers.c
  tests/suites/test_suite_aes.function
  tests/suites/test_suite_aria.function
  tests/suites/test_suite_asn1parse.function
  tests/suites/test_suite_asn1write.function
  tests/suites/test_suite_bignum.function
  tests/suites/test_suite_ccm.function
  tests/suites/test_suite_chacha20.function
  tests/suites/test_suite_cipher.function
  tests/suites/test_suite_constant_time.function
  tests/suites/test_suite_constant_time_hmac.function
  tests/suites/test_suite_ecp.function
  tests/suites/test_suite_hkdf.function
  tests/suites/test_suite_md.function
  tests/suites/test_suite_mps.function
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_pkcs12.function
  tests/suites/test_suite_pkcs1_v21.function
  tests/suites/test_suite_pkwrite.function
  tests/suites/test_suite_platform_printf.function
  tests/suites/test_suite_poly1305.function
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
  tests/suites/test_suite_psa_crypto_entropy.function
  tests/suites/test_suite_psa_crypto_hash.function
  tests/suites/test_suite_psa_crypto_init.function
  tests/suites/test_suite_psa_crypto_persistent_key.function
  tests/suites/test_suite_psa_crypto_se_driver_hal.function
  tests/suites/test_suite_psa_crypto_slot_management.function
  tests/suites/test_suite_psa_crypto_storage_format.function
  tests/suites/test_suite_psa_its.function
  tests/suites/test_suite_random.function
  tests/suites/test_suite_ssl.function
Labels: needs-review, needs-ci, needs-reviewer, component-test, priority-very-high

#8159 Split out configuration adjustments from build_info.h and config_psa.h
  include/mbedtls/build_info.h
  include/mbedtls/config_adjust_legacy_crypto.h
  include/mbedtls/config_adjust_legacy_from_psa.h
  include/mbedtls/config_adjust_psa_from_legacy.h
  include/mbedtls/config_adjust_psa_superset_legacy.h
  include/mbedtls/config_adjust_ssl.h
  include/mbedtls/config_adjust_x509.h
  include/mbedtls/config_psa.h
  include/psa/crypto_adjust_auto_enabled.h
  include/psa/crypto_adjust_config_synonyms.h
  programs/test/generate_cpp_dummy_build.sh
Labels: approved, priority-high, size-xs

#8160 Fix clang warnings about unreachable code
  include/mbedtls/bignum.h
  library/bignum_core.c
  library/x509_crt.c
Labels: enhancement, approved, component-platform, needs-ci, priority-medium, size-xs

#8174 Fix incorrect dependencies in pkwrite tests
  tests/suites/test_suite_pkwrite.data
Labels: approved, component-test, size-xs

#8178 Remove always-false null pointer check in sha3.c that Coverity complains about
  library/sha3.c
Labels: needs-review, component-crypto, needs-ci, priority-medium, size-xs

#8180 Ensure all md_<hash>_finish functions perform zeroization
  library/md5.c
  library/ripemd160.c
  library/sha1.c
  library/sha256.c
  library/sha512.c
Labels: enhancement, approved, component-crypto, needs-ci, single-reviewer, priority-medium, size-xs

#8161 Fix module configuration options in mbedtls_config.h
  ChangeLog.d/tls13-custom-config.txt
  include/mbedtls/mbedtls_config.h
  include/mbedtls/ssl.h
  library/ssl_tls13_generic.c
  scripts/config.py
Labels: bug, approved, needs-backports, component-crypto, component-tls13, single-reviewer, priority-high, size-xs

#8171 One minor fix
  include/mbedtls/config_adjust_legacy_from_psa.h
  library/pkwrite.c
Labels: enhancement, approved, needs-ci, component-psa

#8175 Fix query_config.c generation with CMake build system
  programs/test/CMakeLists.txt
  scripts/generate_query_config.pl
Labels: enhancement, approved, component-test, priority-high

#7590 Constant time asm for x86 and x86-64
  library/bignum.c
  library/constant_time_impl.h
  library/constant_time_internal.h
Labels: approved, component-crypto, size-s, priority-high, size-optimisation

#8188 Prevent potential use of uninitialised data in pkcs7 tests
  tests/suites/test_suite_pkcs7.function
Labels: bug, approved, needs-ci, single-reviewer, size-xs

#8189 Use the correct variable when tracking padding length
  library/ssl_msg.c
Labels: bug, approved, component-tls, needs-ci, priority-very-high, size-xs

#8166 p256-m: Use the zeroize function from Mbed TLS
  3rdparty/p256-m/p256-m/p256-m.c
Labels: approved, priority-very-high, size-xs

#8190 Update CMake minimum version(s) to match main CMakeLists.txt
  programs/test/cmake_package/CMakeLists.txt
  programs/test/cmake_package_install/CMakeLists.txt
  programs/test/cmake_subproject/CMakeLists.txt
Labels: approved, component-platform, needs-ci, single-reviewer, priority-high, size-xs

#8034 Update capitalization of "Mbed" and fix bump_version.sh
  3rdparty/everest/include/everest/vs2013/inttypes.h
  3rdparty/everest/include/everest/vs2013/stdbool.h
  3rdparty/everest/include/everest/x25519.h
  3rdparty/everest/library/Hacl_Curve25519_joined.c
  3rdparty/everest/library/x25519.c
  3rdparty/p256-m/p256-m_driver_entrypoints.h
  CMakeLists.txt
  DartConfiguration.tcl
  configs/README.txt
  configs/config-no-entropy.h
  configs/config-suite-b.h
  configs/config-thread.h
  doxygen/mbedtls.doxyfile
  include/CMakeLists.txt
  include/mbedtls/build_info.h
  include/mbedtls/check_config.h
  include/mbedtls/ecp.h
  include/mbedtls/error.h
  include/mbedtls/mbedtls_config.h
  include/mbedtls/platform_time.h
  include/mbedtls/ssl_ciphersuites.h
  include/mbedtls/threading.h
  include/mbedtls/version.h
  include/mbedtls/x509_crt.h
  include/mbedtls/x509_csr.h
  library/CMakeLists.txt
  library/cipher.c
  library/cipher_wrap.c
  library/ecjpake.c
  library/entropy_poll.h
  library/md.c
  library/mps_common.h
  library/mps_error.h
  library/mps_reader.h
  library/mps_trace.h
  library/psa_crypto_core.h
  library/ssl_ciphersuites.c
  library/ssl_client.c
  library/ssl_tls13_client.c
  programs/ssl/ssl_fork_server.c
  programs/ssl/ssl_mail_client.c
  programs/ssl/ssl_pthread_server.c
  programs/ssl/ssl_server.c
  programs/ssl/ssl_server2.c
  scripts/bump_version.sh
  scripts/footprint.sh
  scripts/generate_features.pl
  scripts/lcov.sh
  tests/compat.sh
  tests/data_files/Makefile
  tests/scripts/basic-build-test.sh
  tests/scripts/check-doxy-blocks.pl
  tests/scripts/check-generated-files.sh
  tests/scripts/doxygen.sh
  tests/scripts/generate-afl-tests.sh
  tests/suites/test_suite_ecp.function
  tests/suites/test_suite_version.function
  tests/suites/test_suite_x509parse.function
Labels: approved, priority-medium, size-xs

#8194 Backport 2.28: Update capitalization of "Mbed" and fix bump_version.sh
  .github/issue_template.md
  3rdparty/everest/include/everest/vs2010/inttypes.h
  3rdparty/everest/include/everest/vs2010/stdbool.h
  3rdparty/everest/include/everest/x25519.h
  3rdparty/everest/library/Hacl_Curve25519_joined.c
  3rdparty/everest/library/x25519.c
  CMakeLists.txt
  DartConfiguration.tcl
  configs/README.txt
  configs/config-mini-tls1_1.h
  configs/config-no-entropy.h
  configs/config-suite-b.h
  configs/config-thread.h
  doxygen/mbedtls.doxyfile
  include/CMakeLists.txt
  include/mbedtls/check_config.h
  include/mbedtls/compat-1.3.h
  include/mbedtls/config.h
  include/mbedtls/ecp.h
  include/mbedtls/entropy_poll.h
  include/mbedtls/error.h
  include/mbedtls/pkcs11.h
  include/mbedtls/platform_time.h
  include/mbedtls/ssl_ciphersuites.h
  include/mbedtls/threading.h
  include/mbedtls/version.h
  include/mbedtls/x509_crt.h
  include/mbedtls/x509_csr.h
  library/CMakeLists.txt
  library/cipher.c
  library/cipher_wrap.c
  library/ecjpake.c
  library/md.c
  library/mps_common.h
  library/mps_error.h
  library/mps_reader.h
  library/mps_trace.h
  library/psa_crypto_core.h
  library/ssl_ciphersuites.c
  programs/ssl/ssl_fork_server.c
  programs/ssl/ssl_mail_client.c
  programs/ssl/ssl_pthread_server.c
  programs/ssl/ssl_server.c
  programs/ssl/ssl_server2.c
  scripts/bump_version.sh
  scripts/footprint.sh
  scripts/generate_features.pl
  scripts/lcov.sh
  scripts/rename.pl
  tests/compat.sh
  tests/data_files/Makefile
  tests/scripts/all.sh
  tests/scripts/basic-build-test.sh
  tests/scripts/check-doxy-blocks.pl
  tests/scripts/check-generated-files.sh
  tests/scripts/doxygen.sh
  tests/scripts/generate-afl-tests.sh
  tests/suites/test_suite_ecp.function
  tests/suites/test_suite_version.function
  tests/suites/test_suite_x509parse.function
Labels: approved, priority-medium, size-xs

#8093 Add architecture detection macros
  include/mbedtls/build_info.h
  library/aes.c
  library/aesce.c
  library/aesce.h
  library/aesni.h
  library/gcm.c
  library/padlock.c
  library/padlock.h
Labels: approved, component-crypto, component-platform

#8025 Accept numericoid hexstring x509
  ChangeLog.d/extend-distinguished-names.txt
  include/mbedtls/asn1.h
  include/mbedtls/asn1write.h
  library/asn1parse.c
  library/asn1write.c
  library/x509.c
  library/x509_create.c
  tests/data_files/Makefile
  tests/data_files/server1.asciichars.crt
  tests/data_files/server1.hashsymbol.crt
  tests/data_files/server1.spaces.crt
  tests/suites/test_suite_x509parse.data
  tests/suites/test_suite_x509write.data
Labels: approved, component-x509, size-m, priority-high

#8172 Backport 2.28: Add comment about HKDF in config_psa.h
  include/mbedtls/config_psa.h
Labels: enhancement, approved, needs-ci, component-psa, single-reviewer

#8195 Improve use of ct interface in mbedtls_ssl_decrypt_buf
  library/ssl_msg.c
Labels: enhancement, approved, component-tls, needs-ci, priority-medium, size-xs

#7210 Fix llvm error: variable 'default_iv_length' and other may be used uninitialized
  library/psa_crypto.c
  library/ssl_cache.c
  tests/suites/test_suite_psa_crypto.function
Labels: approved, needs-ci, size-s

#7211 mbedtls-2.28: Fix llvm error: variable 'default_iv_length' may be used uninitialized
  library/psa_crypto.c
Labels: approved, size-s

#8076 Test with ECC and FFDH accelerated and no bignum
  docs/driver-only-builds.md
  tests/scripts/all.sh
  tests/scripts/analyze_outcomes.py
Labels: approved, size-s, priority-very-high

#8214 Fix some clang-18 warnings
  library/ssl_client.c
  library/ssl_tls.c
Labels: bug, approved, component-tls, needs-ci, single-reviewer, priority-medium, size-xs

#8212 MBEDTLS_SSL_MAX_EARLY_DATA_SIZE: default value should be commented out in config
  include/mbedtls/check_config.h
  include/mbedtls/mbedtls_config.h
  include/mbedtls/ssl.h
Labels: approved, component-tls13, size-xs

#8220 Fix issue #8215 : add missing requires documentation in mbedtls_config.h
  include/mbedtls/mbedtls_config.h
Labels: approved, component-tls, single-reviewer

#8217 Remove unneeded setting of ret from ssl programs
  programs/ssl/dtls_client.c
  programs/ssl/dtls_server.c
  programs/ssl/ssl_server2.c
Labels: enhancement, approved, single-reviewer, priority-high, size-xs

#8218 Backport 2.28: Remove unneeded setting of ret from ssl programs
  programs/ssl/dtls_client.c
  programs/ssl/dtls_server.c
  programs/ssl/ssl_server2.c
Labels: enhancement, approved, needs-ci, single-reviewer, priority-high, size-xs

#7961 Enable MBEDTLS_PSA_CRYPTO_CONFIG in the full config
  include/psa/crypto_sizes.h
  library/psa_crypto.c
  scripts/config.py
  tests/configs/user-config-for-test.h
  tests/configs/user-config-malloc-0-null.h
  tests/scripts/all.sh
  tests/scripts/depends.py
  tests/suites/test_suite_entropy.function
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: approved, needs-review, size-s, component-test, priority-high

#8103 Backport 2.28: parts of #7961
  tests/configs/user-config-for-test.h
  tests/configs/user-config-malloc-0-null.h
  tests/scripts/all.sh
  tests/suites/test_suite_ssl.function
Labels: approved, size-s, component-test, priority-high

#8177 Generated files off in release
  CMakeLists.txt
  Makefile
  library/Makefile
  programs/Makefile
  scripts/prepare_release.sh
  tests/Makefile
Labels: approved, component-platform, size-s, priority-high

#8203 Declare p256-m as ready for production
  ChangeLog.d/p256-m.txt
  docs/psa-driver-example-and-guide.md
  include/mbedtls/mbedtls_config.h
Labels: component-crypto, priority-very-high, size-xs

#7921 TLS: Clean up ECDSA dependencies
  include/mbedtls/ssl_ciphersuites.h
  library/ssl_ciphersuites.c
  library/ssl_client.c
  library/ssl_misc.h
  library/ssl_tls.c
  library/ssl_tls12_client.c
  library/ssl_tls12_server.c
  tests/scripts/all.sh
  tests/ssl-opt.sh
Labels: approved, size-s, priority-very-high

#8230 Work around a race condition in parallel builds
  tests/scripts/all.sh
Labels: approved, component-platform, priority-medium, size-xs

#8041 Test TF-M config with p256-m driver
  3rdparty/p256-m/p256-m/p256-m.c
  3rdparty/p256-m/p256-m/p256-m.h
  3rdparty/p256-m/p256-m_driver_entrypoints.c
  3rdparty/p256-m/p256-m_driver_entrypoints.h
  include/mbedtls/pk.h
  scripts/data_files/driver_jsons/driverlist.json
  scripts/data_files/driver_jsons/p256_transparent_driver.json
  tests/scripts/all.sh
  tests/scripts/analyze_outcomes.py
  tests/suites/test_suite_psa_crypto.function
Labels: approved, size-m, priority-very-high

#8232 Rename p256m configuration option
  3rdparty/CMakeLists.txt
  3rdparty/p256-m/p256-m/p256-m.c
  3rdparty/p256-m/p256-m_driver_entrypoints.c
  3rdparty/p256-m/p256-m_driver_entrypoints.h
  ChangeLog.d/p256-m.txt
  docs/psa-driver-example-and-guide.md
  include/mbedtls/mbedtls_config.h
  include/psa/crypto_config.h
  library/psa_crypto_driver_wrappers.h
  scripts/config.py
  scripts/data_files/driver_jsons/p256_transparent_driver.json
  scripts/data_files/driver_templates/psa_crypto_driver_wrappers.c.jinja
  tests/scripts/all.sh
Labels: approved, component-crypto, priority-very-high, size-xs

#8237 Remove unused variable and unreachable return from mbedtls_pk_write_key_der()
  library/pkwrite.c
Labels: approved, component-crypto, single-reviewer, priority-medium, size-xs

#8241 fix cast warning
  library/pkparse.c
Labels: bug, approved, component-crypto, needs-ci, single-reviewer, size-xs

#8092 PBKDF2: test output_key
  tests/include/test/psa_crypto_helpers.h
  tests/include/test/psa_exercise_key.h
  tests/src/psa_crypto_helpers.c
  tests/src/psa_exercise_key.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: approved, component-psa, size-s, priority-high

#8210 AES 128bit only: add guards in cipher_wrap.c
  library/cipher_wrap.c
Labels: approved, priority-high, size-optimisation, size-xs

#8243 Update TF-M config
  configs/tfm_mbedcrypto_config_profile_medium.h
Labels: bug, approved, component-platform, needs-ci, priority-very-high, size-xs

#8244 Remove all travis builds except for coverity_scan
  .travis.yml
Labels: approved, single-reviewer, component-test, priority-very-high, size-xs

#8240 Document driver only hashes (overdue)
  ChangeLog.d/driver-only-hashes.txt
  docs/driver-only-builds.md
  tests/include/test/drivers/crypto_config_test_driver_extension.h
  tests/scripts/all.sh
  tests/suites/test_suite_md.psa.data
Labels: bug, enhancement, approved, priority-very-high, size-xs

#8245 [Backport 2.28] Remove all travis builds except for coverity_scan
  .travis.yml
Labels: approved, single-reviewer, component-test, priority-very-high, size-xs

#8234 Fix MSVC error C4703 about possibly uninitialized variable in pkwrite.c
  library/pkwrite.c
Labels: needs-review, needs-reviewer, single-reviewer, priority-medium, size-xs

#8247 Fix SHA-3 dependencies in test_suite_md
  tests/suites/test_suite_md.data
Labels: approved, priority-very-high, size-xs

#8249 Set explicit version for the typing packages
  scripts/driver.requirements.txt
Labels: bug, approved, needs-ci, priority-very-high

#8047 Bugfix/update win crypto apis
  ChangeLog.d/updated_windows_apis.txt
  library/CMakeLists.txt
  library/Makefile
  library/entropy_poll.c
  library/x509_crt.c
  programs/Makefile
  programs/fuzz/Makefile
  scripts/data_files/vs2013-app-template.vcxproj
  scripts/data_files/vs2013-main-template.vcxproj
  scripts/data_files/vs6-app-template.dsp
  scripts/data_files/vs6-main-template.dsp
  scripts/data_files/vs6-workspace-template.dsw
  tests/Makefile
Labels: approved, component-crypto, component-platform, needs-ci, size-s, priority-very-high

#7980 Codesize exclude psa wrappers
  3rdparty/p256-m/p256-m_driver_entrypoints.c
  docs/architecture/psa-crypto-implementation-structure.md
  docs/proposed/psa-driver-wrappers-codegen-migration-guide.md
  docs/psa-driver-example-and-guide.md
  include/psa/crypto_driver_contexts_composites.h
  include/psa/crypto_driver_contexts_primitives.h
  library/.gitignore
  library/CMakeLists.txt
  library/Makefile
  library/psa_crypto.c
  library/psa_crypto_driver_wrappers.h
  library/psa_crypto_driver_wrappers_no_static.h
  library/psa_crypto_slot_management.c
  scripts/data_files/driver_templates/psa_crypto_driver_wrappers.h.jinja
  scripts/data_files/driver_templates/psa_crypto_driver_wrappers_no_static.c.jinja
  scripts/generate_driver_wrappers.py
  scripts/make_generated_files.bat
  tests/scripts/check-generated-files.sh
  tests/scripts/check_names.py
Labels: enhancement, approved, component-crypto, priority-very-high

#8209 2.28: Fix AESNI selection
  include/mbedtls/aesni.h
  include/mbedtls/padlock.h
  library/aes.c
  library/padlock.c
Labels: bug, approved, component-crypto, priority-very-high, size-xs

#8254 [Backport 2.28] Re-add python install of requirements to Travis CI.
  .travis.yml
Labels: bug, approved, single-reviewer, component-test, priority-high, size-xs

#8253 Re-add python install of requirements to Travis CI
  .travis.yml
Labels: bug, approved, needs-backports, single-reviewer, component-test, priority-high, size-xs

#8075 driver-only ECC: curve acceleration macros
  ChangeLog.d/driver-only-ecc.txt
  docs/driver-only-builds.md
  include/mbedtls/check_config.h
  include/mbedtls/config_adjust_legacy_crypto.h
  include/mbedtls/config_adjust_legacy_from_psa.h
  include/mbedtls/config_adjust_psa_superset_legacy.h
  include/mbedtls/config_psa.h
  include/psa/crypto_adjust_config_key_pair_types.h
  library/oid.c
  library/pk_internal.h
  library/pkwrite.c
  library/psa_crypto.c
  library/ssl_misc.h
  library/ssl_tls.c
  tests/scripts/all.sh
  tests/scripts/analyze_outcomes.py
  tests/ssl-opt.sh
  tests/suites/test_suite_debug.data
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pkparse.data
  tests/suites/test_suite_pkwrite.data
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
  tests/suites/test_suite_x509parse.data
  tests/suites/test_suite_x509write.data
Labels: approved, size-s, priority-very-high

#8260 Fix include path to psa/crypto_spe.h
  include/mbedtls/mbedtls_config.h
  include/psa/crypto_platform.h
  tests/scripts/all.sh
Labels: bug, approved, priority-very-high, size-xs

#8242 Driver-only ECC: wrap-up
  ChangeLog.d/driver-only-ecc.txt
  docs/driver-only-builds.md
  docs/psa-driver-example-and-guide.md
  include/mbedtls/config_adjust_legacy_from_psa.h
  include/mbedtls/mbedtls_config.h
  include/mbedtls/ssl.h
  library/ssl_tls.c
  tests/scripts/all.sh
  tests/scripts/analyze_outcomes.py
  tests/suites/test_suite_ssl.function
Labels: approved, size-s, priority-very-high

#8261 Add CMake include path for generated header
  library/CMakeLists.txt
  programs/test/cmake_package/CMakeLists.txt
  programs/test/cmake_package_install/CMakeLists.txt
  tests/scripts/all.sh
Labels: approved, needs-ci, priority-very-high, size-xs

#8264 Follow up to 8075
  include/mbedtls/check_config.h
  include/mbedtls/config_adjust_legacy_from_psa.h
  tests/configs/user-config-for-test.h
  tests/scripts/all.sh
Labels: approved, needs-ci, size-s, priority-very-high

#8271 Fix error handling in psa_driver_wrapper_xxx_hash_get_num_ops
  scripts/data_files/driver_templates/psa_crypto_driver_wrappers.h.jinja
Labels: bug, needs-review, component-crypto, priority-high, size-xs

#8279 Backport 2.28: Bug Fix: mbedtls_ecdsa_verify_restartable fails with ECDSA_SIGN_ALT
  ChangeLog.d/mbedtls_ecdsa_can_do-unconditional-define.txt
  library/ecdsa.c
Labels: approved, priority-very-high, size-xs

#8272 Fix IAR warnings
  library/bignum.c
  library/pk.c
  library/pk_wrap.c
  library/psa_crypto_rsa.c
  library/sha256.c
  library/sha512.c
  scripts/data_files/driver_templates/psa_crypto_driver_wrappers.h.jinja
Labels: enhancement, approved, needs-ci, single-reviewer, priority-high, size-xs

#8277 Fix ChangeLog entry for FFDH in PSA
  ChangeLog.d/driver-ffdh.txt
Labels: approved, priority-very-high, size-xs

#8278 Changelog entry for 7298
  ChangeLog.d/MBEDTLS_ERR_SSL_CACHE_ENTRY_NOT_FOUND.txt
Labels: approved, single-reviewer, priority-very-high

#8280 Backport 2.28: ssl_cache: misc improvements
  ChangeLog.d/MBEDTLS_ERR_SSL_CACHE_ENTRY_NOT_FOUND.txt
  include/mbedtls/ssl.h
  include/mbedtls/ssl_cache.h
  library/error.c
  library/ssl_cache.c
Labels: bug, approved, needs-design-approval, needs-review, component-tls, needs-reviewer, priority-very-high, size-xs
