Repository Mbed-TLS/mbedtls, pull requests merged in 2023-06, with the labels that each got.

#7438 Avoid parse/unparse private ECC keys in PK with USE_PSA when !ECP_C
  include/mbedtls/pk.h
  library/pk.c
  library/pk_internal.h
  library/pk_wrap.c
  library/pkparse.c
  library/pkwrite.c
  library/ssl_tls.c
  library/ssl_tls12_client.c
  library/ssl_tls12_server.c
  library/x509_crt.c
  tests/scripts/analyze_outcomes.py
  tests/suites/test_suite_ecp.function
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_pkparse.data
  tests/suites/test_suite_pkparse.function
Labels: approved, size-m, priority-high

#7629 [Bignum] Bignum/test read write named modulu
  tests/suites/test_suite_ecp.data
  tests/suites/test_suite_ecp.function
Labels: approved, component-crypto, priority-high

#7591 [Bignum] Implement fast reduction curve25519
  library/ecp_curves.c
  library/ecp_invasive.h
  scripts/mbedtls_dev/ecp.py
  tests/suites/test_suite_ecp.function
Labels: needs-review, component-crypto, size-s, priority-high

#7650 code size measurement support for tfm-medium
  configs/crypto_config_profile_medium.h
  configs/tfm_mbedcrypto_config_profile_medium.h
  include/psa/crypto_platform.h
  scripts/code_size_compare.py
Labels: approved, size-s, priority-high, size-optimisation

#7400 Add a possibility to generate certificates with a Subject Alternative Name
  ChangeLog.d/add-subjectAltName-certs.txt
  include/mbedtls/x509.h
  include/mbedtls/x509_crt.h
  include/mbedtls/x509_csr.h
  library/x509write_crt.c
  programs/x509/cert_req.c
  programs/x509/cert_write.c
  tests/data_files/Makefile
  tests/data_files/server1.allSubjectAltNames.crt
  tests/suites/test_suite_x509write.data
  tests/suites/test_suite_x509write.function
Labels: enhancement, approved, needs-review, component-x509, priority-high

#7639 Fix: correct calling to time function in tls13 client&server
  library/ssl_tls13_client.c
  library/ssl_tls13_server.c
Labels: approved, component-tls, size-s

#7676 PK: add support for check_pair() with "opaque" EC keys
  library/pk.c
  library/pk_internal.h
  library/pk_wrap.c
  tests/suites/test_suite_pk.function
Labels: enhancement, approved, size-s, priority-high

#6257 Change macros in mps_common.h
  library/mps_common.h
Labels: bug, approved, component-crypto, single-reviewer, historical-reviewing, priority-medium, size-xs

#7575 Add partial support for URI SubjectAltNames verification
  ChangeLog.d/basic-uri-verification.txt
  include/mbedtls/x509_crt.h
  library/x509_crt.c
  tests/suites/test_suite_x509parse.data
Labels: enhancement, approved, component-x509

#7699 Fix file missing fail on development
  tests/data_files/rsa_single_san_uri.crt.der
Labels: bug, approved, component-test, priority-very-high

#5451 PSA drivers: specification for key derivation
  docs/proposed/psa-driver-interface.md
Labels: enhancement, approved, component-psa, size-s, historical-reviewed, priority-medium

#7670 Fix invalid commands for ec_x{25519,448}_{prv,pub}.{der,pem}
  tests/data_files/Makefile
Labels: bug, approved, priority-high, size-xs

#7106 Parse an OID from a string
  ChangeLog.d/oid-parse-from-numeric-string.txt
  include/mbedtls/oid.h
  library/oid.c
  tests/suites/test_suite_oid.data
  tests/suites/test_suite_oid.function
Labels: approved

#7349 Remove `hash_info` module
  include/mbedtls/build_info.h
  include/mbedtls/md.h
  include/mbedtls/psa_util.h
  include/psa/crypto_sizes.h
  library/CMakeLists.txt
  library/Makefile
  library/ecjpake.c
  library/hash_info.c
  library/hash_info.h
  library/md.c
  library/md_psa.h
  library/pem.c
  library/pk.c
  library/pk_wrap.c
  library/pkcs12.c
  library/pkcs5.c
  library/psa_crypto.c
  library/psa_crypto_ecp.c
  library/psa_crypto_rsa.c
  library/psa_util.c
  library/rsa.c
  library/ssl_ciphersuites.c
  library/ssl_cookie.c
  library/ssl_misc.h
  library/ssl_tls.c
  library/ssl_tls12_client.c
  library/ssl_tls12_server.c
  library/ssl_tls13_client.c
  library/ssl_tls13_generic.c
  library/ssl_tls13_keys.c
  library/ssl_tls13_server.c
  library/x509_crt.c
  library/x509write_crt.c
  library/x509write_csr.c
  tests/include/test/ssl_helpers.h
  tests/scripts/all.sh
  tests/src/test_helpers/ssl_helpers.c
  tests/suites/test_suite_constant_time_hmac.function
  tests/suites/test_suite_ecdsa.function
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_ssl.function
  tests/suites/test_suite_x509write.function
Labels: approved, priority-high, size-optimisation

#7708 SHA-3 support (+ minor fixes & perf)
  ChangeLog.d/sha3.txt
  include/mbedtls/error.h
  include/mbedtls/mbedtls_config.h
  include/mbedtls/md.h
  include/mbedtls/sha3.h
  library/CMakeLists.txt
  library/Makefile
  library/md.c
  library/md_wrap.h
  library/sha3.c
  programs/test/benchmark.c
  programs/test/selftest.c
  scripts/generate_errors.pl
  tests/scripts/depends.py
  tests/suites/test_suite_hmac_drbg.misc.data
  tests/suites/test_suite_md.data
  tests/suites/test_suite_shax.data
  tests/suites/test_suite_shax.function
Labels: enhancement, needs-review, component-crypto, needs-ci, size-s, single-reviewer, historical-reviewed

#7651 Fix armclang compile fail
  ChangeLog.d/armclang-compile-fix.txt
  library/bn_mul.h
  tests/scripts/all.sh
Labels: bug, approved, needs-backports, component-platform, size-s

#7706 Add clangd compilation databases to gitignore
  .gitignore
Labels: approved, single-reviewer, size-xs

#7666 OPC UA: parsing IP's in SubjectAltNames & printing info
  library/x509.c
  tests/data_files/Makefile
  tests/data_files/server5-tricky-ip-san-malformed-len.crt.der
  tests/data_files/server5-tricky-ip-san.crt
  tests/data_files/server5-tricky-ip-san.crt.der
  tests/suites/test_suite_x509parse.data
Labels: approved, component-x509, priority-high

#7723 Fix "unterminated '#pragma clang attribute push'" in sha256/sha512.c
  ChangeLog.d/fix-unterminated-pragma-clang-attribute-push.txt
  library/sha256.c
  library/sha512.c
  tests/scripts/all.sh
Labels: bug, approved, component-crypto, component-platform, needs-ci, single-reviewer, priority-medium, size-xs

#7751 [Backport 2.28] Build the docs in realfull config
  .readthedocs.yaml
Labels: approved, needs-ci, component-docs, single-reviewer, size-xs

#7411 Improve tests for parsing x509 SubjectKeyId and AuthorityKeyId
  tests/data_files/Makefile
  tests/data_files/authorityKeyId_no_authorityKeyId.crt.der
  tests/data_files/authorityKeyId_no_issuer.crt.der
  tests/data_files/authorityKeyId_no_keyid.crt.der
  tests/data_files/authorityKeyId_subjectKeyId.conf
  tests/data_files/authorityKeyId_subjectKeyId.crt.der
  tests/data_files/authorityKeyId_subjectKeyId_issuer_tag1_malformed.crt.der
  tests/data_files/authorityKeyId_subjectKeyId_issuer_tag2_malformed.crt.der
  tests/data_files/authorityKeyId_subjectKeyId_keyid_tag_len_malformed.crt.der
  tests/data_files/authorityKeyId_subjectKeyId_keyid_tag_malformed.crt.der
  tests/data_files/authorityKeyId_subjectKeyId_length_malformed.crt.der
  tests/data_files/authorityKeyId_subjectKeyId_sequence_tag_malformed.crt.der
  tests/data_files/authorityKeyId_subjectKeyId_sn_len_malformed.crt.der
  tests/data_files/authorityKeyId_subjectKeyId_sn_tag_malformed.crt.der
  tests/data_files/authorityKeyId_subjectKeyId_tag_len_malformed.crt.der
  tests/data_files/authorityKeyId_subjectKeyId_tag_malformed.crt.der
  tests/data_files/clusterfuzz-testcase-minimized-fuzz_x509crt-6666050834661376.crt.der
  tests/suites/test_suite_x509parse.data
  tests/suites/test_suite_x509parse.function
Labels: enhancement, approved, component-x509, priority-high

#7770 gcc 11.3 fails when compiling ecjpake drivers
  tests/src/drivers/test_driver_pake.c
Labels: bug, approved, size-s

#7451 Introduce config option of 128-bit key only in AES calculation
  ChangeLog.d/add-aes-128bit-only.txt
  include/mbedtls/aes.h
  include/mbedtls/build_info.h
  include/mbedtls/mbedtls_config.h
  library/aes.c
  library/aesce.c
  library/aesni.c
  library/cmac.c
  library/gcm.c
  library/nist_kw.c
  scripts/config.py
  tests/scripts/all.sh
  tests/scripts/generate_psa_tests.py
  tests/suites/test_suite_aes.cbc.data
  tests/suites/test_suite_aes.cfb.data
  tests/suites/test_suite_aes.ecb.data
  tests/suites/test_suite_aes.ofb.data
  tests/suites/test_suite_aes.rest.data
  tests/suites/test_suite_aes.xts.data
  tests/suites/test_suite_ccm.data
  tests/suites/test_suite_cipher.aes.data
  tests/suites/test_suite_cipher.ccm.data
  tests/suites/test_suite_cipher.gcm.data
  tests/suites/test_suite_cipher.nist_kw.data
  tests/suites/test_suite_cmac.data
  tests/suites/test_suite_ctr_drbg.data
  tests/suites/test_suite_gcm.aes192_de.data
  tests/suites/test_suite_gcm.aes192_en.data
  tests/suites/test_suite_gcm.aes256_de.data
  tests/suites/test_suite_gcm.aes256_en.data
  tests/suites/test_suite_nist_kw.data
  tests/suites/test_suite_pkparse.data
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto_metadata.data
  tests/suites/test_suite_psa_crypto_se_driver_hal.data
  tests/suites/test_suite_ssl.data
Labels: approved, size-m, priority-high, size-optimisation

#7624 AES perf improvements
  ChangeLog.d/aes-perf.txt
  library/aes.c
  library/common.h
  tests/suites/test_suite_common.data
Labels: enhancement, approved, component-crypto, priority-medium, size-xs

#7775 Shorten encoding of version features
  scripts/data_files/version_features.fmt
  scripts/generate_features.pl
Labels: enhancement, approved, component-crypto, size-optimisation, size-xs

#7637 [Bignum] Fixed width for ecp mod p448
  library/ecp_curves.c
  library/ecp_invasive.h
  scripts/mbedtls_dev/ecp.py
Labels: enhancement, needs-review, component-crypto, needs-ci, size-m, priority-high

#7739 [Backport 2.28] Fix typo in CMakeList.txt in IAR compiler flags
  CMakeLists.txt
  ChangeLog.d/bugfix_iar_typo.txt
Labels: approved, component-platform, single-reviewer, size-xs

#7738 Fix typo in CMakeList.txt in IAR compiler flags
  CMakeLists.txt
  ChangeLog.d/bugfix_iar_typo.txt
Labels: bug, approved, component-platform, single-reviewer, size-xs

#7700 PBKDF2: Output bytes
  ChangeLog.d/add-pbkdf2-hmac.txt
  include/psa/crypto_builtin_key_derivation.h
  library/psa_crypto.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: enhancement, approved, component-crypto, size-s, priority-high

#7672 Libtestdriver1 helpers
  tests/scripts/all.sh
Labels: approved, size-s, priority-high

#7782 Move mbedtls_ecp_modulus_type out of the public headers
  include/mbedtls/ecp.h
  library/ecp_invasive.h
Labels: bug, needs-review, component-crypto, size-xs

#7680 [Bignum] Split out raw ECP mod p448
  library/ecp_curves.c
  library/ecp_invasive.h
  scripts/mbedtls_dev/ecp.py
  tests/suites/test_suite_ecp.function
Labels: enhancement, component-crypto, needs-ci, size-s, priority-high

#7774 Update `PSA_WANT` spec for new `KEY_PAIR` scheme
  docs/proposed/psa-conditional-inclusion-c.md
Labels: approved, size-s, priority-high

#7717 Driver-only ECC: auto-enable ECP_LIGHT when needed
  include/mbedtls/build_info.h
  include/mbedtls/mbedtls_config.h
  library/pkparse.c
  tests/scripts/all.sh
  tests/scripts/analyze_outcomes.py
  tests/scripts/depends.py
  tests/suites/test_suite_pkparse.data
Labels: approved, size-s, priority-high

#7638 Use better IP parsing in x509 apps
  include/mbedtls/x509.h
  library/x509_crt.c
  library/x509_invasive.h
  programs/x509/cert_req.c
  programs/x509/cert_write.c
  tests/suites/test_suite_x509parse.function
Labels: enhancement, approved, component-x509, component-test, priority-high

#7805 Pacify clang15 warnings about empty \retval
  library/psa_crypto_ffdh.h
  library/psa_crypto_pake.h
Labels: bug, approved, needs-ci, single-reviewer, size-xs

#7806 [Bignum] Fix 32 bit unreachable code build failure
  library/ecp_curves.c
Labels: bug, approved, single-reviewer, priority-high, size-xs

#7691 x509parse tests: Replace TEST_ASSERT with TEST_EQUAL
  tests/suites/test_suite_x509parse.function
Labels: enhancement, approved, component-x509, single-reviewer, component-test, priority-medium, size-xs

#7712 Backport 2.28: x509parse tests: Replace TEST_ASSERT with TEST_EQUAL
  tests/suites/test_suite_x509parse.function
Labels: enhancement, approved, component-x509, single-reviewer, size-xs

#7686 Add a do-while loop around macros.
  library/x509.c
Labels: enhancement, approved, component-x509, single-reviewer, priority-medium, size-xs

#7753 Backport 2.28: Updating crt/crl files due to expiry before 2024-01-01
  library/certs.c
  tests/data_files/Makefile
  tests/data_files/crl-ec-sha1.pem
  tests/data_files/crl-ec-sha256.pem
  tests/data_files/crl.pem
  tests/data_files/crl_cat_ec-rsa.pem
  tests/data_files/crl_cat_rsa-ec.pem
  tests/data_files/server10-badsign.crt
  tests/data_files/server10-bs_int3.pem
  tests/data_files/server10.crt
  tests/data_files/server10_int3-bs.pem
  tests/data_files/server10_int3_int-ca2.crt
  tests/data_files/server10_int3_int-ca2_ca.crt
  tests/data_files/server10_int3_spurious_int-ca2.crt
  tests/data_files/server3.crt
  tests/data_files/server4.crt
  tests/data_files/server5-badsign.crt
  tests/data_files/server5-der0.crt
  tests/data_files/server5-der1a.crt
  tests/data_files/server5-der1b.crt
  tests/data_files/server5-der2.crt
  tests/data_files/server5-der4.crt
  tests/data_files/server5-der8.crt
  tests/data_files/server5-der9.crt
  tests/data_files/server5-sha1.crt
  tests/data_files/server5-sha224.crt
  tests/data_files/server5-sha384.crt
  tests/data_files/server5-sha512.crt
  tests/data_files/server5.crt
  tests/data_files/server5.crt.der
  tests/data_files/server5.crt.openssl.v3_ext
  tests/data_files/server6.crt
  tests/data_files/server7-badsign.crt
  tests/data_files/server7-expired.crt
  tests/data_files/server7-future.crt
  tests/data_files/server7.crt
  tests/data_files/server7_int-ca-exp.crt
  tests/data_files/server7_int-ca.crt
  tests/data_files/server7_int-ca_ca2.crt
  tests/data_files/server7_spurious_int-ca.crt
  tests/data_files/server8.crt
  tests/data_files/server8_int-ca2.crt
  tests/data_files/test-ca.crt
  tests/data_files/test-ca.opensslconf
  tests/data_files/test-ca.req.sha256
  tests/data_files/test-ca.req_ec.sha256
  tests/data_files/test-ca2.req.sha256
  tests/data_files/test-ca2_cat-future-invalid.crt
  tests/data_files/test-ca2_cat-future-present.crt
  tests/data_files/test-ca2_cat-past-invalid.crt
  tests/data_files/test-ca2_cat-past-present.crt
  tests/data_files/test-ca2_cat-present-future.crt
  tests/data_files/test-ca2_cat-present-past.crt
  tests/data_files/test-ca_cat12.crt
  tests/data_files/test-ca_cat21.crt
  tests/data_files/test-int-ca-exp.crt
  tests/data_files/test-int-ca.crt
  tests/data_files/test-int-ca2.crt
  tests/data_files/test-int-ca3-badsign.crt
  tests/data_files/test-int-ca3.crt
Labels: enhancement, needs-review, component-x509, needs-reviewer, size-m, priority-high

#7682 driver-only ECC: ECPf.PK testing
  include/mbedtls/build_info.h
  include/mbedtls/oid.h
  include/mbedtls/pk.h
  include/psa/crypto_extra.h
  library/oid.c
  library/pk.c
  library/pk_internal.h
  library/pk_wrap.c
  library/pk_wrap.h
  library/pkparse.c
  library/pkwrite.c
  library/pkwrite.h
  library/psa_crypto.c
  tests/scripts/all.sh
  tests/scripts/analyze_outcomes.py
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_pkparse.data
  tests/suites/test_suite_pkparse.function
  tests/suites/test_suite_pkwrite.data
Labels: approved, size-s, priority-high

#7807 Fix very high stack usage in SSL debug code
  ChangeLog.d/ssl_debug_helpers-stack_usage.txt
  scripts/generate_ssl_debug_helpers.py
Labels: approved, component-tls, priority-medium, size-xs

#7847 Aarch64 asm docs improvement
  library/common.h
Labels: needs-review, component-platform, single-reviewer, priority-medium, size-xs

#7665 Optimize error translation code size
  library/common.h
  library/constant_time.c
  library/lmots.c
  library/lms.c
  library/psa_crypto.c
  library/psa_crypto_slot_management.c
  library/sha512.c
  library/ssl_cookie.c
  library/ssl_msg.c
  library/ssl_ticket.c
  library/ssl_tls.c
  library/ssl_tls12_client.c
  library/ssl_tls12_server.c
  library/ssl_tls13_client.c
  library/ssl_tls13_generic.c
  library/ssl_tls13_keys.c
  tests/include/test/macros.h
Labels: approved, priority-high, size-optimisation

#7719 Change J-PAKE internal state machine
  include/psa/crypto_extra.h
  library/psa_crypto.c
  library/psa_crypto_pake.c
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
  tests/suites/test_suite_psa_crypto_pake.data
  tests/suites/test_suite_psa_crypto_pake.function
Labels: approved, component-psa, priority-high

#7793 [Bignum] Fast reduction dispatch
  library/bignum_mod_raw.c
  library/ecp_curves.c
  scripts/mbedtls_dev/bignum_common.py
  scripts/mbedtls_dev/ecp.py
  tests/suites/test_suite_ecp.data
  tests/suites/test_suite_ecp.function
Labels: needs-review, component-crypto, size-s, priority-high

#7646 Storage resilience with stateful secure elements: design document
  docs/architecture/psa-storage-resilience.md
Labels: approved, component-psa, size-m, priority-high

#7802 Use DER format for x509 SAN tests
  tests/data_files/Makefile
  tests/data_files/parse_input/server5-fan.crt
  tests/data_files/parse_input/server5-fan.crt.der
  tests/data_files/parse_input/server5-nonprintable_othername.crt
  tests/data_files/parse_input/server5-nonprintable_othername.crt.der
  tests/data_files/parse_input/server5-othername.crt
  tests/data_files/parse_input/server5-othername.crt.der
  tests/data_files/parse_input/server5-unsupported_othername.crt
  tests/data_files/parse_input/server5-unsupported_othername.crt.der
  tests/suites/test_suite_x509parse.data
Labels: approved, component-x509

#7822 code_style.py --since
  scripts/code_style.py
Labels: priority-low, size-xs

#7821 Simplify directory name comparison in AuthorityKeyIdentifier tests
  tests/suites/test_suite_x509parse.data
  tests/suites/test_suite_x509parse.function
Labels: approved, component-x509, size-s

#7630 Prefer intrinsics over asm for AES-NI
  library/aes.c
  library/aesni.h
  tests/scripts/all.sh
Labels: approved, component-crypto, priority-high, size-xs

#7761 Backport 2.28: Fix crypt_and_hash decrypt issue when used with stream cipher
  ChangeLog.d/fix-crypt_and_hash-decrypt-issue.txt
  programs/aes/crypt_and_hash.c
Labels: approved, size-xs

#7728 Fix crypt_and_hash decrypt issue when used with stream cipher
  ChangeLog.d/fix-crypt_and_hash-decrypt-issue.txt
  programs/aes/crypt_and_hash.c
Labels: approved, size-xs

#7849 Fix false success return code in `mbedtls_x509_string_to_names()`
  ChangeLog.d/fix-string-to-names-retcode.txt
  library/x509_create.c
  tests/suites/test_suite_x509write.data
Labels: approved, needs-backports, component-x509, size-s

#7850 [Backport 2.28] Fix false success return code in `mbedtls_x509_string_to_names()`
  ChangeLog.d/fix-string-to-names-retcode.txt
  library/x509_create.c
  tests/suites/test_suite_x509write.data
Labels: approved, component-x509, size-s
