Repository Mbed-TLS/mbedtls, pull requests merged in 2023-03, with the labels that each got.

#7147 Remove driver entry points for psa_{get|set}_max_ops()
  include/psa/crypto.h
  library/psa_crypto.c
  library/psa_crypto_driver_wrappers.h
  scripts/data_files/driver_templates/psa_crypto_driver_wrappers.c.jinja
Labels: enhancement, approved, size-s, priority-very-high

#6949 Replace fuzzer-generated PKCS #7 memory management tests
  tests/data_files/Makefile
  tests/data_files/pkcs7_get_signers_info_set-leak-fuzz_pkcs7-4541044530479104.der
  tests/data_files/pkcs7_get_signers_info_set-missing_free-fuzz_pkcs7-6213931373035520.der
  tests/data_files/pkcs7_signerInfo_1_serial_invalid_tag_after_long_name.der
  tests/data_files/pkcs7_signerInfo_2_invalid_tag.der
  tests/suites/test_suite_pkcs7.data
Labels: approved, component-x509, component-test, priority-very-high

#7189 Fix macro redefinition warning from armclang
  library/alignment.h
Labels: bug, needs-review, component-platform, needs-reviewer, size-s, priority-high

#7177 Interruptible sign hash improve num ops testing
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: approved, needs-preceding-pr, component-psa, size-s, component-test, priority-very-high

#7176 Interruptible {sign|verify} hash verification test improvements
  tests/suites/test_suite_psa_crypto.function
Labels: enhancement, approved, needs-work, needs-ci, component-psa, size-s, component-test, priority-very-high

#7188 Interruptible {sign|verify} hash - Call complete() after start() failure.
  tests/suites/test_suite_psa_crypto.function
Labels: enhancement, approved, component-psa, size-s, component-test, priority-very-high

#6932 Replace CPU modifier check with file scope target cpu modifiers
  include/mbedtls/check_config.h
  include/mbedtls/mbedtls_config.h
  library/sha256.c
  library/sha512.c
Labels: bug, approved, component-crypto, size-s, priority-high

#7104 [Backport 2.28] Use config.py as a module in depends.py
  tests/scripts/depends.py
Labels: approved, component-test

#6493 Use `config.py` as a module in `depends.py`
  tests/scripts/depends.py
Labels: approved, component-test

#7197 Enable -Werror in all.sh for armclang
  tests/scripts/all.sh
Labels: bug, approved, needs-backports, component-platform, needs-ci, size-s, priority-medium

#7199 Backport 2.28: enable -Werror for armclang
  tests/scripts/all.sh
Labels: approved, component-platform, needs-ci, size-s, single-reviewer, priority-medium

#6201 Disable MBEDTLS_SSL_RENEGOTIATION in TLS-1.3-only builds
  ChangeLog.d/tls13-only-renegotiation.txt
  include/mbedtls/check_config.h
  tests/configs/tls13-only.h
Labels: approved, component-tls13, priority-high

#7200 Enable all keys for interruptible op fail tests
  tests/suites/test_suite_psa_crypto_op_fail.function
Labels: enhancement, approved, size-s, single-reviewer, priority-very-high

#7151 Allow alternative names for overridable PSA headers
  ChangeLog.d/psa-alt-headers.txt
  include/mbedtls/build_info.h
  include/mbedtls/mbedtls_config.h
  include/psa/crypto.h
  include/psa/crypto_types.h
  programs/.gitignore
  programs/Makefile
  programs/test/CMakeLists.txt
  programs/test/query_included_headers.c
  tests/.gitignore
  tests/Makefile
  tests/include/alt-extra/psa/crypto.h
  tests/scripts/all.sh
Labels: approved, needs-review, component-psa, size-s, priority-very-high

#7173 Use platform-provided secure zeroization
  ChangeLog.d/platform-zeroization.txt
  library/platform_util.c
  tests/suites/test_suite_platform_util.data
  tests/suites/test_suite_platform_util.function
Labels: enhancement, needs-review, component-platform, size-s, priority-medium

#7120 Define "MD light" subset of MD
  include/mbedtls/build_info.h
  include/mbedtls/mbedtls_config.h
  include/mbedtls/md.h
  library/md.c
  tests/scripts/all.sh
  tests/suites/test_suite_md.data
  tests/suites/test_suite_md.function
Labels: enhancement, approved, size-s, priority-high

#7142 Driver-only ECDH starter
  tests/scripts/all.sh
  tests/scripts/analyze_outcomes.py
  tests/suites/test_suite_psa_crypto.data
Labels: enhancement, approved, component-crypto, size-s

#7184 Extract Secp224r1 fast reduction from the prototype
  library/ecp_curves.c
  library/ecp_invasive.h
  scripts/mbedtls_dev/bignum_common.py
  scripts/mbedtls_dev/ecp.py
  tests/suites/test_suite_ecp.function
Labels: enhancement, needs-work, component-crypto, priority-high

#7220 Enable explicit_bzero() on OpenBSD
  library/platform_util.c
Labels: enhancement, approved, component-platform, size-s, single-reviewer, priority-medium

#7164 Fix expected export length for Edwards curves in test suite.
  tests/src/psa_exercise_key.c
Labels: approved, size-s

#7168 Use MD (not low-level hash interface) in X.509 and TLS
  library/ssl_misc.h
  library/ssl_tls.c
  library/x509write_crt.c
Labels: enhancement, approved, size-s, priority-high

#6172 Document the need to call psa_crypto_init for TLS 1.3
  include/mbedtls/mbedtls_config.h
  include/mbedtls/pk.h
  include/mbedtls/ssl.h
  include/mbedtls/x509_crl.h
  include/mbedtls/x509_crt.h
  include/mbedtls/x509_csr.h
Labels: enhancement, approved, component-tls13, size-s, priority-high

#7162 Legacy MBEDTLS_PK_PARSE_C and MBEDTLS_PK_WRITE_C dependencies in test_suite_psa_crypto
  library/psa_crypto_rsa.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.data
  tests/suites/test_suite_psa_crypto_persistent_key.data
Labels: bug, approved, size-s, component-test, priority-high

#7218 Fix typos in development prior to release
  include/mbedtls/mbedtls_config.h
  library/aesce.c
  library/bignum_core.h
  library/ecp_curves.c
  library/pkcs7.c
  library/sha256.c
  library/ssl_tls13_client.c
  programs/ssl/ssl_client2.c
Labels: approved, needs-backports, size-s, single-reviewer, priority-medium

#7219 Fix typos in LTS prior to release
  include/mbedtls/config.h
Labels: approved, size-s, single-reviewer, priority-medium

#7232 Backport 2.28: Update ChangeLog to make "fix" explicit
  ChangeLog
Labels: approved, size-s, single-reviewer, priority-medium

#7231 Update ChangeLog to make "fix" explicit
  ChangeLog
Labels: approved, needs-backports, size-s, single-reviewer, priority-medium

#6567 EC J-PAKE driver dispatch implementation v.2
  docs/proposed/psa-driver-interface.md
  include/mbedtls/config_psa.h
  include/psa/crypto_builtin_composites.h
  include/psa/crypto_driver_contexts_composites.h
  include/psa/crypto_extra.h
  library/psa_crypto.c
  library/psa_crypto_core.h
  library/psa_crypto_driver_wrappers.h
  library/psa_crypto_pake.c
  library/psa_crypto_pake.h
  scripts/data_files/driver_templates/psa_crypto_driver_wrappers.c.jinja
  tests/include/test/drivers/crypto_config_test_driver_extension.h
  tests/include/test/drivers/pake.h
  tests/include/test/drivers/test_driver.h
  tests/scripts/all.sh
  tests/src/drivers/test_driver_pake.c
  tests/suites/test_suite_psa_crypto_driver_wrappers.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
  tests/suites/test_suite_psa_crypto_pake.data
  tests/suites/test_suite_psa_crypto_pake.function
Labels: approved, component-psa, size-m, priority-high

#7208 Interruptible_{sign|verify}_hash: Add public key verification tests
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: enhancement, approved, component-psa, size-s, component-test, priority-very-high

#7117 driver-only ECDSA: enable ECDSA-based TLS 1.2 key exchanges
  include/mbedtls/check_config.h
  include/mbedtls/config_psa.h
  library/ssl_tls.c
  tests/scripts/all.sh
  tests/ssl-opt.sh
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: enhancement, approved, size-m

#7237 Move docs/getting_started.md to docs repo
  docs/getting_started.md
Labels: approved, component-docs, size-s, single-reviewer

#7238 [Backport 2.28] Move docs/getting_started.md to docs repo
  docs/getting_started.md
Labels: needs-review, component-docs, needs-reviewer, size-s, single-reviewer

#7206 Test memory management in pkcs7
  tests/data_files/Makefile
  tests/data_files/pkcs7_data_signed_badsigner1_badsize.der
  tests/data_files/pkcs7_data_signed_badsigner1_badtag.der
  tests/data_files/pkcs7_data_signed_badsigner1_fuzzbad.der
  tests/data_files/pkcs7_data_signed_badsigner2_badsize.der
  tests/data_files/pkcs7_data_signed_badsigner2_badtag.der
  tests/data_files/pkcs7_data_signed_badsigner2_fuzzbad.der
  tests/suites/test_suite_pkcs7.data
Labels: approved, component-x509, priority-high

#7245 Driver-only ecdsa wrapup
  ChangeLog.d/driver-only-ecdsa.txt
  docs/use-psa-crypto.md
  include/mbedtls/check_config.h
  include/mbedtls/config_psa.h
Labels: approved, size-s

#7247 Add test case for PKCS7 file with zero signers
  tests/data_files/pkcs7_data_no_signers.der
  tests/suites/test_suite_pkcs7.data
Labels: approved, component-x509, needs-ci, size-s, single-reviewer, priority-high

#7269 Test fixes for PKCS 7 when MBEDTLS_HAVE_TIME_DATE not set
  tests/data_files/Makefile
  tests/data_files/pkcs7-rsa-expired.der
  tests/data_files/pkcs7_data_rsa_expired.der
  tests/suites/test_suite_pkcs7.data
Labels: bug, approved, component-x509, size-s, single-reviewer, priority-high

#7172 Backport 2.28: Fix undefined behavior in ssl_read if buf parameter is NULL
  ChangeLog.d/mbedtls_ssl_read_undefined_behavior.txt
  library/ssl_msg.c
  tests/suites/test_suite_ssl.function
Labels: bug, component-tls, size-s, priority-high

#7171 Fix undefined behavior in ssl_read if buf parameter is NULL
  ChangeLog.d/mbedtls_ssl_read_undefined_behavior.txt
  library/ssl_msg.c
  tests/suites/test_suite_ssl.function
Labels: bug, approved, needs-backports, component-tls, size-s, priority-high

#7260 Remove duplicate test macros
  tests/include/test/macros.h
  tests/src/random.c
Labels: approved, size-s, single-reviewer, component-test, priority-medium

#7207 Handle output consistently in analyze_outcomes.py
  tests/scripts/analyze_outcomes.py
Labels: enhancement, needs-review, needs-reviewer, size-s, component-test

#7163 all.sh: Do not list unsupported cases
  tests/scripts/all.sh
Labels: bug, approved, size-s, component-test, priority-high

#7204 Backport 2.28: all.sh: Do not list unsupported cases
  tests/scripts/all.sh
Labels: bug, approved, needs-backports, size-s, single-reviewer, component-test, priority-high

#7243 driver-only ECDH: enable ssl-opt.sh with parity
  tests/scripts/all.sh
  tests/ssl-opt.sh
Labels: enhancement, approved, size-s

#7203 Add CPU modifier for AESCE
  .travis.yml
  include/mbedtls/mbedtls_config.h
  library/aesce.c
  library/sha256.c
  library/sha512.c
Labels: bug, approved, component-crypto, component-test, priority-very-high

#7229 Implement and use MBEDTLS_STATIC_ASSERT()
  library/common.h
  library/psa_crypto.c
  library/psa_crypto_se.c
  library/ssl_tls.c
  library/ssl_tls12_server.c
Labels: approved, component-platform, size-s, priority-medium

#7278 Improve macro naming
  library/aesce.c
  library/sha256.c
  library/sha512.c
Labels: approved, component-platform, needs-ci, single-reviewer, priority-medium, size-xs

#7196 EC J-PAKE: partial fix for role vs user+peer
  ChangeLog.d/ec_jpake_driver_dispatch.txt
  ChangeLog.d/fix-jpake-user-peer.txt
  docs/proposed/psa-driver-interface.md
  include/psa/crypto_extra.h
  library/psa_crypto.c
  library/ssl_tls.c
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
  tests/suites/test_suite_psa_crypto_pake.data
  tests/suites/test_suite_psa_crypto_pake.function
Labels: approved, component-psa, priority-very-high

#7240 Don't insist on MBEDTLS_HAVE_ASM for MBEDTLS_AESCE_C on non-Arm64 systems
  include/mbedtls/check_config.h
Labels: approved, component-crypto, needs-ci, priority-very-high

#7282 Add changelog entry for a bug in non-PAKE code fixed during PAKE work
  ChangeLog.d/changelog-6567-psa_key_derivation_abort-no-other_secret.txt
Labels: bug, approved, single-reviewer, priority-very-high, size-xs

#6500 Move TLS connection helper code from test_suite_ssl.function to ssl_helpers.c
  CMakeLists.txt
  tests/CMakeLists.txt
  tests/Makefile
  tests/include/test/psa_crypto_helpers.h
  tests/include/test/ssl_helpers.h
  tests/src/psa_crypto_helpers.c
  tests/src/test_helpers/ssl_helpers.c
  tests/suites/helpers.function
  tests/suites/test_suite_ssl.function
Labels: enhancement, approved, size-m, component-test, priority-high

#7217 ssl_cache: Add cache entry removal api
  ChangeLog.d/add-cache-remove-api.txt
  include/mbedtls/ssl_cache.h
  library/ssl_cache.c
  programs/ssl/ssl_server2.c
  tests/ssl-opt.sh
Labels: enhancement, approved, component-tls, size-s, priority-high

#7295 [Backport 2.28] Fix segfault in mbedtls_oid_get_numeric_string
  ChangeLog.d/fix-oid-to-string-bugs.txt
  library/oid.c
  tests/suites/test_suite_oid.data
  tests/suites/test_suite_oid.function
Labels: bug, approved, needs-preceding-pr, single-reviewer, priority-very-high

#7270 Fix segfault in mbedtls_oid_get_numeric_string
  ChangeLog.d/fix-oid-to-string-bugs.txt
  library/oid.c
  tests/suites/test_suite_oid.data
  tests/suites/test_suite_oid.function
Labels: bug, approved, size-s, priority-very-high

#7301 Fix Msan failure with explicit_bzero
  library/platform_util.c
Labels: approved, component-platform, priority-very-high, size-xs

#7303 Add tests that cover msan explicit_bzero issue
  tests/suites/test_suite_platform_util.data
  tests/suites/test_suite_platform_util.function
Labels: bug, approved, component-platform, needs-ci, single-reviewer, priority-medium, size-xs

#7230 Extract Secp256r1 fast reduction from the prototype
  library/ecp_curves.c
  library/ecp_invasive.h
  scripts/mbedtls_dev/ecp.py
  tests/suites/test_suite_ecp.function
Labels: enhancement, needs-review, component-crypto, needs-reviewer

#7242 Implement MD dispatch to PSA
  docs/architecture/psa-migration/md-cipher-dispatch.md
  include/mbedtls/md.h
  library/md.c
  library/psa_crypto.c
  library/psa_crypto_core.h
  tests/include/test/psa_crypto_helpers.h
  tests/scripts/all.sh
  tests/suites/test_suite_md.data
  tests/suites/test_suite_md.function
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: approved, priority-high

#7275 Driver-only EC JPAKE: starter
  tests/include/test/drivers/crypto_config_test_driver_extension.h
  tests/scripts/all.sh
  tests/scripts/analyze_outcomes.py
Labels: enhancement, approved, size-s

#7009 Added ability to include the SubjectAltName extension to a CSR - v.2
  ChangeLog.d/san_csr.txt
  include/mbedtls/asn1write.h
  include/mbedtls/x509_csr.h
  library/x509write_csr.c
  programs/x509/cert_req.c
  tests/data_files/Makefile
  tests/data_files/server1.req.sha256.ext
  tests/suites/test_suite_x509write.function
Labels: enhancement, approved, component-x509

#7083 Add parsing for Record Size Limit extension in TLS 1.3
  include/mbedtls/check_config.h
  include/mbedtls/mbedtls_config.h
  include/mbedtls/ssl.h
  library/ssl_misc.h
  library/ssl_tls.c
  library/ssl_tls13_client.c
  library/ssl_tls13_generic.c
  library/ssl_tls13_server.c
  scripts/config.py
  tests/scripts/all.sh
  tests/ssl-opt.sh
Labels: enhancement, approved, component-tls13, size-s, priority-high

#7313 Changelog and terminology tidy-up for AESCE
  ChangeLog.d/armv8-aes.txt
  include/mbedtls/mbedtls_config.h
  library/aesce.c
  library/aesce.h
Labels: approved, component-crypto, single-reviewer, priority-very-high, size-xs

#7192 psa_crypto: Fix psa_key_derivation_output_key ECC without builtin keys
  library/psa_crypto.c
  tests/scripts/all.sh
Labels: enhancement, approved, component-psa, size-s, priority-high

#7300 Driver only EC JPAKE: re-enable the EC J-PAKE key exchange and get test parity
  include/mbedtls/check_config.h
  include/mbedtls/config_psa.h
  tests/scripts/all.sh
Labels: enhancement, approved, size-s

#6918 Add GCM with armv8 crypto extension
  library/aesce.c
  library/aesce.h
  library/gcm.c
Labels: enhancement, approved, component-crypto, size-m, priority-very-high

#7190 RSA: provide interface to retrieve padding mode and hash_id
  ChangeLog.d/rsa-padding-accessor.txt
  include/mbedtls/rsa.h
  library/rsa.c
  tests/suites/test_suite_pkcs1_v15.function
  tests/suites/test_suite_pkcs1_v21.function
Labels: enhancement, component-tls, size-s, priority-high

#7320 Backport 2.28: Implement and use MBEDTLS_STATIC_ASSERT()
  library/common.h
  library/psa_crypto.c
  library/psa_crypto_se.c
Labels: enhancement, approved, component-platform, needs-ci, single-reviewer, priority-very-high, size-xs

#7296 driver-only ECDH: enable ECDH-based TLS 1.2 key exchanges -- part 1
  include/mbedtls/check_config.h
  include/mbedtls/config_psa.h
  include/mbedtls/pk.h
  library/ssl_tls.c
  tests/scripts/all.sh
  tests/ssl-opt.sh
  tests/suites/test_suite_ssl.data
Labels: enhancement, needs-review, size-s

#7321 Driver-only ECC: all three top-level modules
  include/mbedtls/pk.h
  include/mbedtls/ssl.h
  library/psa_crypto.c
  library/ssl_misc.h
  library/ssl_tls12_client.c
  library/ssl_tls12_server.c
  tests/scripts/all.sh
  tests/scripts/analyze_outcomes.py
Labels: enhancement, approved, size-s, priority-high

#7310 [Backport 2.28] Generate API documentation with Sphinx and Breathe
  .readthedocs.yaml
  docs/.gitignore
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/requirements.in
  docs/requirements.txt
  doxygen/mbedtls.doxyfile
  include/mbedtls/bignum.h
Labels: approved, component-docs, size-s, priority-high

#7334 Improve analyze_outcomes.py script
  tests/scripts/analyze_outcomes.py
Labels: enhancement, approved, component-test

#7336 fix: ignore *.o under tests/src/test_helpers
  tests/.gitignore
Labels: enhancement, approved, component-tls, priority-high, size-xs

#7354 Ecc doc update
  docs/architecture/psa-migration/psa-limitations.md
  docs/use-psa-crypto.md
  include/mbedtls/check_config.h
  include/mbedtls/mbedtls_config.h
Labels: approved, priority-high

#7352 Remove obsolete ecp_fix_negative function
  library/ecp_curves.c
  library/ecp_invasive.h
  tests/suites/test_suite_ecp.data
  tests/suites/test_suite_ecp.function
Labels: enhancement, component-crypto, single-reviewer

#6900 Add support for directoryName subjectAltName
  ChangeLog.d/add-directoryname-san.txt
  include/mbedtls/x509.h
  include/mbedtls/x509_crt.h
  library/x509.c
  tests/data_files/Makefile
  tests/data_files/server5-directoryname-seq-malformed.crt.der
  tests/data_files/server5-directoryname.crt.der
  tests/data_files/server5-second-directoryname-oid-malformed.crt.der
  tests/data_files/server5-two-directorynames.crt.der
  tests/data_files/test-ca.opensslconf
  tests/suites/test_suite_x509parse.data
  tests/suites/test_suite_x509parse.function
Labels: approved, component-tls, component-x509, needs-ci, priority-high

#7338 Backport 2.28: fix: ignore *.o under tests/src/test_helpers
  tests/.gitignore
Labels: enhancement, approved, component-tls, needs-ci, single-reviewer, priority-high, size-xs

#7386 Backport 2.28 - Timing alignment
  library/timing.c
  tests/suites/test_suite_timing.function
Labels: bug, approved, component-platform, single-reviewer, priority-medium, size-xs

#7385 Fix cast alignment warning in timing.c
  include/mbedtls/timing.h
  tests/suites/test_suite_timing.function
Labels: bug, approved, needs-backports, component-platform, single-reviewer, priority-medium, size-xs
