Repository Mbed-TLS/mbedtls, pull requests merged in 2024-06, with the labels that each got.

#9222 [Backport 2.28] fix documentation of psa_hash_compare()
  include/psa/crypto.h
Labels: approved, priority-high

#9221 [Backport 3.6] fix documentation of psa_hash_compare()
  include/psa/crypto.h
Labels: approved, priority-high, size-xs

#9219 [Backport 3.6] adjust_legacy_crypto: enable CIPHER_C when PSA CMAC is builtin
  ChangeLog.d/fix-psa-cmac.txt
  include/mbedtls/config_adjust_legacy_crypto.h
Labels: approved, priority-high, size-xs

#9234 [Backport 3.6] Allow `code_style.py` to work from a git hook
  scripts/code_style.py
Labels: approved, size-s

#9233 Allow `code_style.py` to work from a git hook
  scripts/code_style.py
Labels: approved, size-s, priority-medium

#9228 [Backport 3.6] Extend python checks to framework scripts
  tests/scripts/check-python-files.sh
Labels: approved, priority-high, size-xs

#9227 Extend python checks to framework scripts
  tests/scripts/check-python-files.sh
Labels: approved, priority-high, size-xs

#9062 Make TLS 1.2 components work with PSA_CRYPTO_CONFIG set
  tests/scripts/all.sh
Labels: approved, size-s, component-test, priority-high

#9231 Backport 3.6: Fix uint32_t printed as unsigned int
  library/ssl_tls13_generic.c
  library/ssl_tls13_server.c
Labels: enhancement, approved, needs-ci, priority-medium, size-xs

#9225 Fix uint32_t printed as unsigned int
  library/ssl_tls13_generic.c
  library/ssl_tls13_server.c
Labels: enhancement, approved, priority-medium, size-xs

#9149 ssl-opt.sh, compat.sh: Error out if not executing any tests
  tests/compat.sh
  tests/ssl-opt.sh
Labels: approved, needs-backports, component-tls, size-s, priority-high

#9199 Make everest component work with PSA_CRYPTO_CONFIG set
  tests/scripts/all.sh
Labels: approved, component-test, priority-high

#9204 Backport 2.28: ssl-opt.sh, compat.sh: Error out if not executing any tests
  tests/compat.sh
  tests/scripts/test-ref-configs.pl
  tests/ssl-opt.sh
Labels: approved, component-tls, size-s, priority-high

#9203 Backport 3.6: ssl-opt.sh, compat.sh: Error out if not executing any tests
  tests/compat.sh
  tests/ssl-opt.sh
Labels: approved, component-tls, size-s, priority-high

#9246 Backport 2.28: Set psk to NULL in ssl_psk_remove
  library/ssl_tls.c
Labels: approved, component-tls

#9241 Set psk to NULL in ssl_psk_remove
  library/ssl_tls.c
Labels: approved, needs-backports, component-tls, size-s, priority-medium

#9242 Fix incorrect array length in function prototype
  include/mbedtls/ssl.h
  library/ssl_tls.c
Labels: approved, component-tls, size-xs

#9248 [Backport 3.6] Fix incorrect array length in function prototype
  include/mbedtls/ssl.h
  library/ssl_tls.c
Labels: approved, component-tls, needs-ci, size-xs

#9025 Backport 2.28: Fix the detection of not-supported mechanisms in systematically generated PSA tests
  library/psa_crypto.c
  scripts/mbedtls_dev/psa_information.py
  scripts/mbedtls_dev/test_case.py
  tests/scripts/generate_psa_tests.py
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto_generate_key.generated.data
  tests/suites/test_suite_psa_crypto_not_supported.function
  tests/suites/test_suite_psa_crypto_not_supported.generated.data
  tests/suites/test_suite_psa_crypto_op_fail.function
  tests/suites/test_suite_psa_crypto_op_fail.generated.data
  tests/suites/test_suite_psa_crypto_op_fail.misc.data
  tests/suites/test_suite_psa_crypto_se_driver_hal_mocks.function
  tests/suites/test_suite_psa_crypto_storage_format.current.data
  tests/suites/test_suite_psa_crypto_storage_format.v0.data
Labels: bug, approved, needs-backports, size-s, component-test, priority-high

#9279 psa_sim: make server ping time much faster
  tests/psa-client-server/psasim/src/psa_ff_server.c
Labels: needs-review, priority-high, size-xs

#9277 [Backport 2.28] Partial backport of #9247
  .gitignore
  pkgconfig/.gitignore
  tests/scripts/all.sh
Labels: enhancement, approved, priority-very-high

#9278 psa_sim: improve log prints
  tests/psa-client-server/psasim/include/util.h
  tests/psa-client-server/psasim/src/client.c
  tests/psa-client-server/psasim/src/psa_ff_client.c
  tests/psa-client-server/psasim/src/psa_sim_crypto_client.c
  tests/psa-client-server/psasim/src/psa_sim_generate.pl
  tests/psa-client-server/psasim/src/psa_sim_serialise.c
  tests/psa-client-server/psasim/src/psa_sim_serialise.pl
Labels: approved, priority-high, size-xs

#9280 psasim-server: add function to reset operations slots
  tests/psa-client-server/psasim/src/psa_sim_crypto_server.c
  tests/psa-client-server/psasim/src/psa_sim_generate.pl
  tests/psa-client-server/psasim/src/psa_sim_serialise.c
  tests/psa-client-server/psasim/src/psa_sim_serialise.h
  tests/psa-client-server/psasim/src/psa_sim_serialise.pl
  tests/psa-client-server/psasim/src/server.c
Labels: approved, priority-high, size-xs

#9251 Resolve to run the legacy only test cases with `PSA_WANT` macros
  configs/config-no-entropy.h
  tests/scripts/test-ref-configs.pl
Labels: enhancement, approved, component-test, priority-very-high, size-xs

#9138 Do not perform adjustments on legacy crypto from PSA, when MBEDTLS_PSA_CRYPTO_CLIENT && !MBEDTLS_PSA_CRYPTO_C
  ChangeLog.d/9126.txt
  include/mbedtls/config_psa.h
Labels: approved, priority-high, size-xs

#9305 [Backport 3.6] Do not perform adjustments on legacy crypto from PSA, when MBEDTLS_PSA_CRYPTO_CLIENT && !MBEDTLS_PSA_CRYPTO_C
  ChangeLog.d/9126.txt
  include/mbedtls/config_psa.h
Labels: approved, priority-high, size-xs

#9274 [Backport 3.6] Fix compiler warnings in test_suite_pk.function
  ChangeLog.d/fix-test-suite-pk-warnings.txt
  tests/suites/test_suite_pk.function
Labels: bug, approved, component-crypto, size-xs

#9250 Fix compiler warnings in test_suite_pk.function
  ChangeLog.d/fix-test-suite-pk-warnings.txt
  tests/suites/test_suite_pk.function
Labels: bug, approved, component-crypto, size-xs

#9273 [Backport 3.6] Use CMAKE_C_SIMULATE_ID when available to determine compiler
  CMakeLists.txt
Labels: enhancement, approved, component-platform, size-s, priority-medium

#8389 Use CMAKE_C_SIMULATE_ID when available to determine compiler
  CMakeLists.txt
Labels: enhancement, approved, component-platform, size-s, priority-medium

#9258 Drop support for VIA Padlock
  ChangeLog.d/remove-via-padlock-support.txt
  SECURITY.md
  configs/ext/tfm_mbedcrypto_config_profile_medium.h
  docs/architecture/alternative-implementations.md
  include/mbedtls/aes.h
  include/mbedtls/error.h
  include/mbedtls/mbedtls_config.h
  library/CMakeLists.txt
  library/Makefile
  library/aes.c
  library/padlock.c
  library/padlock.h
  scripts/generate_errors.pl
  tests/scripts/all.sh
Labels: needs-review, component-psa, api-break

#9310 psasim: complete support of PSA functions in `psasim` and add basic "smoke test" applications
  tests/psa-client-server/psasim/Makefile
  tests/psa-client-server/psasim/src/aut_main.c
  tests/psa-client-server/psasim/src/aut_psa_aead_encrypt.c
  tests/psa-client-server/psasim/src/aut_psa_aead_encrypt_decrypt.c
  tests/psa-client-server/psasim/src/aut_psa_asymmetric_encrypt_decrypt.c
  tests/psa-client-server/psasim/src/aut_psa_cipher_encrypt_decrypt.c
  tests/psa-client-server/psasim/src/aut_psa_hash.c
  tests/psa-client-server/psasim/src/aut_psa_hash_compute.c
  tests/psa-client-server/psasim/src/aut_psa_hkdf.c
  tests/psa-client-server/psasim/src/aut_psa_key_agreement.c
  tests/psa-client-server/psasim/src/aut_psa_mac.c
  tests/psa-client-server/psasim/src/aut_psa_random.c
  tests/psa-client-server/psasim/src/aut_psa_sign_verify.c
  tests/psa-client-server/psasim/src/psa_functions_codes.h
  tests/psa-client-server/psasim/src/psa_sim_crypto_client.c
  tests/psa-client-server/psasim/src/psa_sim_crypto_server.c
  tests/psa-client-server/psasim/src/psa_sim_generate.pl
  tests/psa-client-server/psasim/src/psa_sim_serialise.c
  tests/psa-client-server/psasim/src/psa_sim_serialise.h
  tests/psa-client-server/psasim/src/psa_sim_serialise.pl
  tests/psa-client-server/psasim/test/run_test.sh
  tests/scripts/all.sh
Labels: approved, size-s, priority-high
