Repository Mbed-TLS/mbedtls, pull requests merged in 2024-10, with the labels that each got.

#9655 Backport 3.6: dtls_server: allow unexpected message on second handshake
  programs/ssl/dtls_server.c
  tests/opt-testcases/sample.sh
Labels: approved, component-tls, priority-very-high, size-xs

#9594 analyze_outcomes.py refactoring: change stringly typed data to classes
  .mypy.ini
  .pylintrc
  tests/scripts/analyze_outcomes.py
Labels: approved, needs-backports, component-test, priority-high, size-xs

#9236 Configuration file split proposal
  docs/proposed/Makefile
  docs/proposed/config-split.md
Labels: enhancement, needs-review, component-crypto, component-docs, priority-high

#9653 Revert move of version.h to tf-psa-crypto library
  include/mbedtls/version.h
  library/CMakeLists.txt
  library/Makefile
  library/version.c
  scripts/config.py
  scripts/generate_features.pl
  tests/psa-client-server/psasim/src/server.c
  tests/scripts/check-generated-files.sh
  tests/suites/test_suite_version.data
  tests/suites/test_suite_version.function
  tf-psa-crypto/drivers/builtin/CMakeLists.txt
  tf-psa-crypto/drivers/builtin/src/.gitignore
Labels: enhancement, needs-review, size-s, priority-high

#9161 [3.6 only] Document transitional feature macros / guards
  docs/architecture/psa-migration/psa-limitations.md
  docs/architecture/psa-migration/strategy.md
  docs/architecture/psa-migration/transition-guards.md
  docs/driver-only-builds.md
  library/ssl_tls12_client.c
  tests/scripts/components-configuration-crypto.sh
Labels: approved, size-s, priority-medium

#9674 Fix driver schema json default type requirements
  ChangeLog.d/fix-driver-schema-check.txt
  scripts/data_files/driver_jsons/driver_opaque_schema.json
  scripts/data_files/driver_jsons/driver_transparent_schema.json
Labels: bug, approved, needs-backports, component-psa, priority-high, size-xs

#9679 Backport 3.6: Fix driver schema json default type requirements
  ChangeLog.d/fix-driver-schema-check.txt
  scripts/data_files/driver_jsons/driver_opaque_schema.json
  scripts/data_files/driver_jsons/driver_transparent_schema.json
Labels: bug, approved, component-psa, priority-high, size-xs

#9597 Improve support for submodules in code_style.py
  scripts/code_style.py
Labels: approved, component-test, priority-medium

#9696 [Backport 3.6] Improve support for submodules in code_style.py
  scripts/code_style.py
Labels: approved, component-test, priority-medium

#9700 Enable PSA_CRYPTO_CONFIG in test_psa_crypto_drivers
  tests/configs/user-config-for-test.h
  tests/scripts/components-configuration-crypto.sh
  tf-psa-crypto/drivers/builtin/include/mbedtls/config_adjust_test_accelerators.h
  tf-psa-crypto/drivers/builtin/include/mbedtls/config_psa.h
Labels: enhancement, needs-review, needs-reviewer, priority-high

#9690 pkwrite: fix buffer overrun
  CMakeLists.txt
  ChangeLog.d/9690.txt
  docs/architecture/psa-keystore-design.md
  tf-psa-crypto/drivers/builtin/src/pkwrite.c
  tf-psa-crypto/tests/suites/test_suite_pkwrite.data
  tf-psa-crypto/tests/suites/test_suite_pkwrite.function
Labels: bug, approved, component-crypto, size-s, priority-high

#9566 Error codes: enforce add macro
  library/x509_crt.c
  tests/scripts/check_files.py
  tests/suites/test_suite_x509parse.data
  tf-psa-crypto/tests/suites/test_suite_dhm.data
  tf-psa-crypto/tests/suites/test_suite_dhm.function
  tf-psa-crypto/tests/suites/test_suite_pkcs5.data
  tf-psa-crypto/tests/suites/test_suite_pkcs5.function
  tf-psa-crypto/tests/suites/test_suite_pkparse.data
  tf-psa-crypto/tests/suites/test_suite_pkparse.function
  tf-psa-crypto/tests/suites/test_suite_rsa.data
  tf-psa-crypto/tests/suites/test_suite_rsa.function
Labels: approved, component-test, priority-high, size-xs

#9657 Refactor all.sh
  tests/scripts/all-core.sh
  tests/scripts/all-helpers.sh
  tests/scripts/all.sh
  tests/scripts/components-compiler.sh
  tests/scripts/components-configuration-crypto.sh
  tests/scripts/components-platform.sh
Labels: approved, component-platform, size-s

#9702 [Backport 3.6] Refactor all.sh
  tests/scripts/all-core.sh
  tests/scripts/all-helpers.sh
  tests/scripts/all.sh
  tests/scripts/components-compiler.sh
  tests/scripts/components-configuration-crypto.sh
  tests/scripts/components-platform.sh
Labels: approved, component-platform, size-s

#9715 [Backport 2.28] net/mbedtls_net_connect: Preventing double close problem
  ChangeLog.d/replace-close-with-mbedtls_net_close.txt
  library/net_sockets.c
Labels: approved, component-platform, size-xs

#9714 [Backport 3.6] net/mbedtls_net_connect: Preventing double close problem
  ChangeLog.d/replace-close-with-mbedtls_net_close.txt
  library/net_sockets.c
Labels: approved, component-platform, size-xs

#9706 tf-psa-crypto: cmake: Add support for pkg install, doc, lcov
  CMakeLists.txt
  library/CMakeLists.txt
  scripts/lcov.sh
  tests/CMakeLists.txt
  tests/scripts/components-build-system.sh
  tests/scripts/pkgconfig.sh
  tf-psa-crypto/CMakeLists.txt
  tf-psa-crypto/TF-PSA-Crypto.cmake
  tf-psa-crypto/cmake/.gitignore
  tf-psa-crypto/cmake/TF-PSA-CryptoConfig.cmake.in
  tf-psa-crypto/doxygen/.gitignore
  tf-psa-crypto/doxygen/input/.gitignore
  tf-psa-crypto/doxygen/input/doc_mainpage.h.in
  tf-psa-crypto/doxygen/tfpsacrypto.doxyfile.in
  tf-psa-crypto/drivers/p256-m/CMakeLists.txt
  tf-psa-crypto/pkgconfig/.gitignore
  tf-psa-crypto/pkgconfig/CMakeLists.txt
  tf-psa-crypto/pkgconfig/JoinPaths.cmake
  tf-psa-crypto/pkgconfig/tfpsacrypto.pc.in
  tf-psa-crypto/programs/test/cmake_package/.gitignore
  tf-psa-crypto/programs/test/cmake_package/CMakeLists.txt
  tf-psa-crypto/programs/test/cmake_package/cmake_package.c
  tf-psa-crypto/tests/CMakeLists.txt
  tf-psa-crypto/tests/Descriptions.txt
Labels: enhancement, needs-review, component-platform, priority-high

#9448 [Backport 3.6] PSA: use static key slots to store keys
  ChangeLog.d/9302.txt
  include/mbedtls/check_config.h
  include/mbedtls/entropy.h
  include/mbedtls/mbedtls_config.h
  include/psa/crypto_extra.h
  include/psa/crypto_sizes.h
  library/pk.c
  library/psa_crypto.c
  library/psa_crypto_core.h
  library/psa_crypto_storage.h
  scripts/config.py
  tests/include/test/psa_crypto_helpers.h
  tests/scripts/components-basic-checks.sh
  tests/scripts/components-configuration-crypto.sh
  tests/suites/test_suite_pkparse.data
  tests/suites/test_suite_pkwrite.data
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
  tests/suites/test_suite_psa_crypto_storage_format.function
  tests/suites/test_suite_psa_crypto_storage_format.misc.data
Labels: approved, size-s, priority-high

#9302 PSA: use static key slots to store keys
  ChangeLog.d/9302.txt
  include/mbedtls/check_config.h
  include/mbedtls/mbedtls_config.h
  scripts/config.py
  tests/include/test/psa_crypto_helpers.h
  tests/scripts/analyze_outcomes.py
  tests/scripts/components-basic-checks.sh
  tests/scripts/components-configuration-crypto.sh
  tf-psa-crypto/core/psa_crypto.c
  tf-psa-crypto/core/psa_crypto_core.h
  tf-psa-crypto/core/psa_crypto_storage.h
  tf-psa-crypto/drivers/builtin/src/pk.c
  tf-psa-crypto/include/psa/crypto_extra.h
  tf-psa-crypto/include/psa/crypto_sizes.h
  tf-psa-crypto/tests/suites/test_suite_pkparse.data
  tf-psa-crypto/tests/suites/test_suite_pkwrite.data
  tf-psa-crypto/tests/suites/test_suite_psa_crypto.data
  tf-psa-crypto/tests/suites/test_suite_psa_crypto.function
  tf-psa-crypto/tests/suites/test_suite_psa_crypto_driver_wrappers.function
  tf-psa-crypto/tests/suites/test_suite_psa_crypto_storage_format.function
  tf-psa-crypto/tests/suites/test_suite_psa_crypto_storage_format.misc.data
Labels: approved, needs-backports, component-psa, size-s, priority-high

#9608 Backport 3.6: Fix some all.sh components with sub-components
  .gitignore
  library/Makefile
  tests/scripts/components-compiler.sh
  tests/scripts/components-configuration-crypto.sh
  tests/scripts/components-platform.sh
Labels: approved, component-test, priority-high, size-xs

#9703 Revert & fix #9690 workarounds
  CMakeLists.txt
  tf-psa-crypto/tests/suites/test_suite_pkwrite.data
Labels: approved, needs-backports, size-s, priority-high

#9609 Backport 2.28: Fix some all.sh components with sub-components
  tests/scripts/all.sh
Labels: approved, component-test, priority-high, size-xs

#9293 Fix some all.sh components with sub-components
  .gitignore
  library/Makefile
  tests/scripts/components-compiler.sh
  tests/scripts/components-configuration-crypto.sh
  tests/scripts/components-platform.sh
Labels: approved, needs-backports, component-test, priority-high, size-xs

#9728 [Backport 3.6] Revert & fix #9690 workarounds
  CMakeLists.txt
  tests/suites/test_suite_pkwrite.data
Labels: approved, size-s, priority-high

#9723 [Backport 3.6] Fix new coverity issues
  tests/src/bignum_codepath_check.c
  tests/suites/test_suite_ctr_drbg.function
  tests/suites/test_suite_psa_crypto_memory.function
  tests/suites/test_suite_x509write.function
Labels: bug, approved, component-test, priority-high, size-xs

#9721 Fix new coverity issues
  tests/src/bignum_codepath_check.c
  tests/suites/test_suite_x509write.function
  tf-psa-crypto/tests/suites/test_suite_ctr_drbg.function
  tf-psa-crypto/tests/suites/test_suite_psa_crypto_memory.function
Labels: approved, component-test, priority-high, size-xs

#9389 Add default config tests for the A64, A32, Thumb 1 and Thumb 2 instruction sets
  tests/scripts/all-core.sh
  tests/scripts/all-helpers.sh
  tests/scripts/components-platform.sh
Labels: approved, component-test, priority-very-high

#9734 [Backport 2.28] Add default config tests for the A64, A32, Thumb 1 and Thumb 2 instruction sets
  tests/scripts/all.sh
Labels: approved, needs-ci, priority-very-high

#9733 [Backport 3.6] Add default config tests for the A64, A32, Thumb 1 and Thumb 2 instruction sets
  tests/scripts/all-core.sh
  tests/scripts/all-helpers.sh
  tests/scripts/components-platform.sh
Labels: approved, needs-ci, priority-very-high

#9729 [Backport 2.28] Fix new coverity issues
  tests/suites/test_suite_psa_crypto_memory.function
  tests/suites/test_suite_x509write.function
Labels: bug, approved, component-test, priority-high, size-xs

#9614 Always enable MBEDTLS_USE_PSA_CRYPTO in all.sh
  ChangeLog.d/psa-always-on.txt
  include/mbedtls/mbedtls_config.h
  tests/scripts/analyze_outcomes.py
  tests/scripts/components-configuration-crypto.sh
  tests/scripts/components-sanitizers.sh
  tests/suites/test_suite_x509parse.data
  tf-psa-crypto/tests/suites/test_suite_pk.data
Labels: approved, priority-high, size-xs

#9708 cmake: Define compile and link options target by target
  CMakeLists.txt
  library/CMakeLists.txt
  programs/aes/CMakeLists.txt
  programs/cipher/CMakeLists.txt
  programs/fuzz/CMakeLists.txt
  programs/hash/CMakeLists.txt
  programs/pkey/CMakeLists.txt
  programs/psa/CMakeLists.txt
  programs/psa/key_ladder_demo.c
  programs/random/CMakeLists.txt
  programs/ssl/CMakeLists.txt
  programs/test/CMakeLists.txt
  programs/util/CMakeLists.txt
  programs/x509/CMakeLists.txt
  tests/CMakeLists.txt
  tf-psa-crypto/TF-PSA-Crypto.cmake
  tf-psa-crypto/core/CMakeLists.txt
  tf-psa-crypto/drivers/builtin/CMakeLists.txt
  tf-psa-crypto/drivers/everest/CMakeLists.txt
  tf-psa-crypto/drivers/p256-m/CMakeLists.txt
  tf-psa-crypto/tests/CMakeLists.txt
Labels: enhancement, approved, component-platform, priority-high

#9547 Align 3.6 test helpers with development
  tests/include/test/drivers/crypto_config_test_driver_extension.h
  tests/include/test/psa_crypto_helpers.h
  tests/src/drivers/hash.c
  tests/src/drivers/test_driver_aead.c
  tests/src/drivers/test_driver_asymmetric_encryption.c
  tests/src/drivers/test_driver_cipher.c
  tests/src/drivers/test_driver_key_agreement.c
  tests/src/drivers/test_driver_key_management.c
  tests/src/drivers/test_driver_mac.c
  tests/src/drivers/test_driver_pake.c
  tests/src/drivers/test_driver_signature.c
  tests/src/psa_exercise_key.c
Labels: approved, priority-high

#9736 [2.28] Drop armcc5 support in all.sh
  scripts/output_env.sh
  tests/scripts/all.sh
Labels: approved, component-test, priority-very-high, size-xs

#9738 [dev] Drop building with armcc5 in all.sh
  scripts/output_env.sh
  tests/scripts/all-core.sh
  tests/scripts/components-platform.sh
Labels: approved, priority-very-high
