Repository Mbed-TLS/mbedtls, pull requests merged in 2024-02, with the labels that each got.

#8771 [backport 2.28] fix build for midipix
  library/entropy_poll.c
  library/platform_util.c
Labels: bug, approved, component-platform, size-xs

#8754 fix build for midipix
  library/entropy_poll.c
  library/platform_util.c
Labels: enhancement, needs-review, needs-backports, component-platform, needs-reviewer, size-xs

#8692 TLS 1.3: SRV: Implement mbedtls_ssl_read_early_data()
  include/mbedtls/ssl.h
  library/ssl_misc.h
  library/ssl_msg.c
  library/ssl_tls.c
  library/ssl_tls13_server.c
  programs/ssl/ssl_server2.c
  tests/data_files/tls13_early_data.txt
  tests/opt-testcases/tls13-misc.sh
  tests/suites/test_suite_ssl.function
Labels: enhancement, approved, component-tls13, priority-high

#8733 Add back restriction on AD length of GCM
  library/gcm.c
  tests/suites/test_suite_gcm.function
  tests/suites/test_suite_gcm.misc.data
Labels: bug, needs-review, component-crypto, priority-medium, size-xs

#8715 Remove all internal functions from public headers
  include/mbedtls/debug.h
  include/mbedtls/pk.h
  include/mbedtls/pkcs7.h
  include/mbedtls/ssl_ciphersuites.h
  include/mbedtls/x509.h
  library/debug.c
  library/debug_internal.h
  library/pk_internal.h
  library/pkcs7.c
  library/ssl_ciphersuites_internal.h
  library/ssl_client.c
  library/ssl_misc.h
  library/ssl_msg.c
  library/ssl_tls.c
  library/ssl_tls12_client.c
  library/ssl_tls12_server.c
  library/ssl_tls13_client.c
  library/ssl_tls13_generic.c
  library/ssl_tls13_keys.c
  library/ssl_tls13_server.c
  library/x509.c
  library/x509_create.c
  library/x509_crl.c
  library/x509_crt.c
  library/x509_csr.c
  library/x509_internal.h
  library/x509write.c
  library/x509write_crt.c
  library/x509write_csr.c
  tests/suites/test_suite_debug.function
  tests/suites/test_suite_pkcs7.function
  tests/suites/test_suite_pkwrite.function
  tests/suites/test_suite_x509parse.function
  tests/suites/test_suite_x509write.function
Labels: approved, size-s, priority-high

#8727 TLS 1.3: SRV: Ignore early data when rejected
  include/mbedtls/ssl.h
  library/ssl_msg.c
  library/ssl_tls.c
  library/ssl_tls13_client.c
  library/ssl_tls13_server.c
  tests/opt-testcases/tls13-misc.sh
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: enhancement, approved, component-tls13, priority-high

#8745 Put the id field at the end of the psa_key_attributes_s structure
  include/psa/crypto_struct.h
Labels: approved, component-psa, priority-high, size-xs

#8738 Implement mbedtls_pk_get_psa_attributes
  doxygen/mbedtls.doxyfile
  include/mbedtls/pk.h
  library/pk.c
  library/ssl_tls12_client.c
  tests/scripts/all.sh
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_pkparse.function
Labels: enhancement, approved, component-crypto, size-s, priority-high

#8781 Backport 2.28: Fix KDF Incorrect Initial Capacity
  ChangeLog.d/fix_kdf_incorrect_initial_capacity.txt
  library/psa_crypto.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: approved, component-crypto, size-s, priority-high

#8788 Change unaligned access method for old gcc
  library/alignment.h
Labels: bug, approved, needs-review, component-platform, priority-high, size-xs

#8717 PSA FFDH: feature macros for parameters
  ChangeLog.d/8030.txt
  include/mbedtls/config_adjust_legacy_from_psa.h
  include/mbedtls/config_adjust_psa_from_legacy.h
  include/psa/crypto_config.h
  include/psa/crypto_sizes.h
  library/psa_crypto.c
  library/psa_crypto_ffdh.c
  library/psa_crypto_ffdh.h
  library/ssl_tls13_generic.c
  programs/ssl/ssl_test_lib.c
  scripts/mbedtls_dev/psa_information.py
  tests/include/test/drivers/crypto_config_test_driver_extension.h
  tests/opt-testcases/tls13-compat.sh
  tests/scripts/all.sh
  tests/scripts/generate_tls13_compat_tests.py
  tests/ssl-opt.sh
  tests/suites/test_suite_psa_crypto.data
Labels: approved, size-s, priority-high

#8789 Stop platform test failures with GCC and TSAN
  tests/include/test/helpers.h
Labels: bug, approved, component-platform, needs-ci, priority-very-high, size-xs

#8791 Update ECDSA signature conversion specification
  docs/architecture/psa-migration/psa-legacy-bridges.md
Labels: approved, component-crypto, priority-high, size-xs

#8794 Remind contributors not to force-push
  .github/pull_request_template.md
Labels: enhancement, approved, component-docs, priority-medium, size-xs

#8798 Backport 2.28: Reduce many unnecessary static memory consumption
  library/ecp_curves.c
  library/ssl_tls.c
Labels: enhancement, approved, needs-ci, size-s, priority-medium

#8665 Reduce many unnecessary static memory consumption
  library/ecp_curves.c
  library/sha3.c
  library/ssl_tls.c
Labels: enhancement, approved, needs-backports, needs-ci, size-s, priority-medium

#8740 Move RSA basic key parsing/writing to rsa.c
  ChangeLog.d/8647.txt
  include/mbedtls/config_adjust_legacy_crypto.h
  include/mbedtls/config_adjust_legacy_from_psa.h
  library/pk_wrap.c
  library/pkparse.c
  library/pkwrite.c
  library/psa_crypto_rsa.c
  library/rsa.c
  library/rsa_internal.h
  tests/scripts/all.sh
  tests/scripts/test_psa_compliance.py
  tests/suites/test_suite_pkparse.data
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_rsa.data
  tests/suites/test_suite_rsa.function
  tests/suites/test_suite_x509parse.data
Labels: approved, size-s, priority-high

#8703 Conversion function between raw and DER ECDSA signatures (guards in ASN1)
  ChangeLog.d/7765.txt
  include/mbedtls/asn1.h
  include/mbedtls/asn1write.h
  include/mbedtls/config_adjust_legacy_crypto.h
  include/mbedtls/psa_util.h
  library/asn1parse.c
  library/asn1write.c
  library/pk_wrap.c
  library/psa_util.c
  tests/scripts/all.sh
  tests/suites/test_suite_psa_crypto_util.data
  tests/suites/test_suite_psa_crypto_util.function
Labels: approved, size-s, priority-high

#8636 New test thread interface
  3rdparty/everest/Makefile.inc
  3rdparty/p256-m/Makefile.inc
  CMakeLists.txt
  library/CMakeLists.txt
  programs/Makefile
  programs/aes/CMakeLists.txt
  programs/cipher/CMakeLists.txt
  programs/fuzz/CMakeLists.txt
  programs/fuzz/Makefile
  programs/hash/CMakeLists.txt
  programs/pkey/CMakeLists.txt
  programs/psa/CMakeLists.txt
  programs/random/CMakeLists.txt
  programs/ssl/CMakeLists.txt
  programs/ssl/ssl_test_lib.c
  programs/test/CMakeLists.txt
  programs/test/cmake_subproject/CMakeLists.txt
  programs/test/metatest.c
  programs/util/CMakeLists.txt
  programs/x509/CMakeLists.txt
  scripts/common.make
  tests/CMakeLists.txt
  tests/include/test/helpers.h
  tests/include/test/threading_helpers.h
  tests/src/threading_helpers.c
  tests/suites/helpers.function
  tests/suites/test_suite_ctr_drbg.function
Labels: enhancement, approved, size-s, component-test, priority-high

#8689 Make test data thread safe
  programs/ssl/ssl_test_lib.c
  programs/test/metatest.c
  tests/include/test/bignum_helpers.h
  tests/include/test/helpers.h
  tests/src/bignum_helpers.c
  tests/src/helpers.c
  tests/src/threading_helpers.c
  tests/suites/host_test.function
  tests/suites/test_suite_bignum.function
  tests/suites/test_suite_dhm.function
Labels: enhancement, approved, needs-ci, size-m, component-test, priority-very-high

#7604 Add AES encrypted keys support for PKCS5 PBES2
  ChangeLog.d/add-aes-cbc-to-pkcs5-pbes2.txt
  include/mbedtls/oid.h
  library/oid.c
  tests/data_files/Makefile
  tests/data_files/rsa_pkcs8_pbes2_pbkdf2_2048_aes128cbc_sha384.der
  tests/data_files/rsa_pkcs8_pbes2_pbkdf2_2048_aes128cbc_sha384.pem
  tests/data_files/rsa_pkcs8_pbes2_pbkdf2_2048_aes192cbc_sha384.der
  tests/data_files/rsa_pkcs8_pbes2_pbkdf2_2048_aes192cbc_sha384.pem
  tests/data_files/rsa_pkcs8_pbes2_pbkdf2_2048_aes256cbc_sha384.der
  tests/data_files/rsa_pkcs8_pbes2_pbkdf2_2048_aes256cbc_sha384.pem
  tests/scripts/analyze_outcomes.py
  tests/suites/test_suite_pkcs5.data
  tests/suites/test_suite_pkparse.data
Labels: enhancement, approved, size-s, priority-medium

#8702 [MBEDTLS_PRIVATE] Update dhm context in programs
  programs/pkey/dh_server.c
  programs/test/benchmark.c
Labels: approved, size-s, priority-high

#8764 Make key destruction thread safe
  include/psa/crypto_extra.h
  library/psa_crypto.c
  library/psa_crypto_slot_management.c
  library/psa_crypto_slot_management.h
Labels: approved, component-crypto, priority-very-high

#8802 Misc. clean-ups in `check_config.h`
  include/mbedtls/check_config.h
  include/mbedtls/config_adjust_legacy_crypto.h
Labels: approved, needs-review, component-crypto, size-s, priority-high

#8660 Fix a comment in ecp
  library/ecp.c
Labels: approved, component-crypto, size-xs

#8801 Inline the SHA3 parameters table into a switch
  library/sha3.c
Labels: enhancement, approved, component-crypto, priority-medium, size-optimisation, size-xs

#8817 Compiler warning fixes
  library/aesce.c
  library/lms.c
  library/pk.c
Labels: bug, approved, component-platform, needs-ci, priority-high, size-xs

#8816 Fix deadlock with test failures
  tests/src/helpers.c
Labels: bug, needs-review, needs-ci, component-test, priority-very-high, size-xs

#8755 TLS 1.3: Refine and test client early data status
  include/mbedtls/ssl.h
  library/ssl_misc.h
  library/ssl_tls.c
  library/ssl_tls13_client.c
  library/ssl_tls13_generic.c
  library/ssl_tls13_server.c
  tests/include/test/ssl_helpers.h
  tests/src/test_helpers/ssl_helpers.c
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: enhancement, needs-review, component-tls13, priority-high

#8820 SHA3: Pack the iota round constants
  library/sha3.c
Labels: enhancement, approved, component-crypto, priority-medium, size-xs

#8779 Fix mbedtls_pk_get_bitlen for a key size that is not a multiple of 8
  ChangeLog.d/rsa-bitlen.txt
  include/mbedtls/rsa.h
  library/pk_wrap.c
  library/rsa.c
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_pkparse.data
  tests/suites/test_suite_pkparse.function
  tests/suites/test_suite_rsa.data
  tests/suites/test_suite_rsa.function
Labels: bug, approved, needs-backports, component-crypto, priority-high, size-xs

#8818 Backport 2.28: move entropy init prior arguments number recognition
  ChangeLog.d/gen-key-segfault.txt
  programs/pkey/gen_key.c
Labels: bug, approved, component-crypto, priority-medium, size-xs

#8810 move entropy init prior arguments number recognition
  ChangeLog.d/gen-key-segfault.txt
  programs/pkey/gen_key.c
Labels: bug, approved, needs-backports, priority-medium, size-xs

#8734 Add test for driver-only HMAC
  docs/driver-only-builds.md
  programs/x509/cert_req.c
  programs/x509/cert_write.c
  tests/scripts/all.sh
  tests/scripts/analyze_outcomes.py
  tests/suites/test_suite_entropy.function
Labels: approved, size-s, priority-high

#8582 PK parse and PK write: add dependency check with OID
  include/mbedtls/check_config.h
  include/mbedtls/mbedtls_config.h
  include/mbedtls/pk.h
  tests/suites/test_suite_pk.function
Labels: bug, approved, component-crypto, priority-medium, size-xs

#8691 pkg-config: add initial pkg-config files
  CMakeLists.txt
  ChangeLog.d/pkg-config-files-addition.txt
  pkgconfig/CMakeLists.txt
  pkgconfig/JoinPaths.cmake
  pkgconfig/mbedcrypto.pc.in
  pkgconfig/mbedtls.pc.in
  pkgconfig/mbedx509.pc.in
Labels: enhancement, needs-review, component-platform, priority-high

#8797 Make check_config aware of MBEDTLS_PSA_CRYPTO_CLIENT
  include/mbedtls/build_info.h
  include/mbedtls/check_config.h
Labels: approved

#8841 use mbedtls_ssl_session_init() to init session variable
  programs/ssl/ssl_client2.c
Labels: approved, component-tls, size-xs

#8661 use mbedtls_ssl_session_init() to init session variable
  include/mbedtls/ssl.h
  programs/ssl/ssl_client2.c
Labels: approved, needs-backports, component-tls, size-xs

#8804 mbedtls_rsa_parse_key and mbedtls_rsa_parse_pubkey accept trailing garbage
  ChangeLog.d/8799.txt
  include/mbedtls/pem.h
  library/pem.c
  library/rsa.c
  tests/scripts/analyze_outcomes.py
  tests/suites/test_suite_pem.data
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_rsa.data
  tests/suites/test_suite_x509parse.data
Labels: approved, size-s, priority-high

#8826 RSA keys set to PSS/OAEP padding perform PKCS1v1.5 when MBEDTLS_USE_PSA_CRYPTO is enabled
  ChangeLog.d/8824.txt
  include/mbedtls/pk.h
  library/pk_wrap.c
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
Labels: approved, priority-high, size-xs

#8773 Make key locking and one-shot operations thread safe
  library/psa_crypto.c
  library/psa_crypto_core.h
  library/psa_crypto_slot_management.c
  library/psa_crypto_slot_management.h
Labels: approved, component-crypto, size-s, priority-very-high

#8811 Backport 2.28: bugs fixed in "Implement mbedtls_pk_import_into_psa"
  include/psa/crypto_values.h
  tests/scripts/depends.py
  tests/suites/test_suite_pk.function
Labels: approved, needs-backports, component-crypto, priority-high, size-xs

#8807 Implement mbedtls_pk_import_into_psa
  ChangeLog.d/mbedtls_pk_import_into_psa.txt
  include/mbedtls/pk.h
  include/psa/crypto_values.h
  library/pk.c
  library/pk_internal.h
  library/psa_util.c
  tests/include/test/psa_exercise_key.h
  tests/scripts/depends.py
  tests/src/psa_exercise_key.c
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_pkparse.function
Labels: enhancement, approved, needs-backports, component-crypto, needs-ci, size-s, priority-high

#8855 Remove most uses of MBEDTLS_ALLOW_PRIVATE_ACCESS in test programs
  ChangeLog.d/benchmark-ecdh.txt
  programs/fuzz/fuzz_client.c
  programs/fuzz/fuzz_dtlsclient.c
  programs/fuzz/fuzz_dtlsserver.c
  programs/fuzz/fuzz_privkey.c
  programs/fuzz/fuzz_pubkey.c
  programs/fuzz/fuzz_server.c
  programs/fuzz/fuzz_x509crl.c
  programs/fuzz/fuzz_x509crt.c
  programs/fuzz/fuzz_x509csr.c
  programs/ssl/ssl_context_info.c
  programs/ssl/ssl_test_lib.c
  programs/test/benchmark.c
  programs/test/metatest.c
  programs/test/selftest.c
  programs/test/udp_proxy.c
Labels: enhancement, approved, component-crypto, size-s, priority-medium

#8716 Use large GCM tables
  ChangeLog.d/gcm-large-tables.txt
  include/mbedtls/gcm.h
  include/mbedtls/mbedtls_config.h
  library/gcm.c
  tests/scripts/all.sh
Labels: enhancement, approved, component-crypto, size-s, priority-medium

#8833 Make multi-part operations thread-safe
  library/psa_crypto.c
Labels: approved, component-crypto, size-m, priority-very-high

#8856 Make psa_open_key threadsafe
  library/psa_crypto_slot_management.c
Labels: approved, component-crypto, priority-very-high, size-xs

#8815 Introduce psa_generate_key_ext
  ChangeLog.d/psa_generate_key_ext.txt
  include/psa/crypto.h
  include/psa/crypto_struct.h
  include/psa/crypto_types.h
  library/psa_crypto.c
  library/psa_crypto_core.h
  scripts/data_files/driver_templates/psa_crypto_driver_wrappers.h.jinja
  tests/scripts/analyze_outcomes.py
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: approved, component-psa, size-s, priority-high

#8838 Improve test info data accessors
  tests/src/helpers.c
  tests/src/threading_helpers.c
Labels: enhancement, approved, component-test, priority-very-high, size-xs

#8840 Remove domain parameters
  ChangeLog.d/domain_parameters.txt
  include/psa/crypto.h
  include/psa/crypto_compat.h
  include/psa/crypto_extra.h
  include/psa/crypto_struct.h
  library/psa_crypto.c
  library/psa_crypto_client.c
  library/psa_crypto_ecp.c
  library/psa_crypto_rsa.c
  library/psa_crypto_rsa.h
  tests/src/drivers/test_driver_key_management.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: enhancement, approved, component-psa, priority-high, size-optimisation, size-xs

#8844 Restore some X509 functions to public headers
  include/mbedtls/x509.h
  library/x509_internal.h
Labels: approved, size-s, priority-high

#8865 Add missing casts to fix IAR warnings
  library/pk_wrap.c
Labels: bug, approved, component-platform, needs-ci, priority-medium, size-xs

#8845 Document ECP write functions
  include/mbedtls/ecp.h
  library/ecp.c
  tests/suites/test_suite_ecp.data
  tests/suites/test_suite_ecp.function
Labels: enhancement, approved, component-crypto, priority-high, size-xs

#8860 Backport 2.28: Document ECP write functions
  include/mbedtls/ecp.h
  library/ecp.c
  tests/suites/test_suite_ecp.data
  tests/suites/test_suite_ecp.function
Labels: approved, component-crypto, priority-high, size-xs

#8760 TLS 1.3: Add mbedtls_ssl_write_early_data() API
  include/mbedtls/ssl.h
  library/ssl_debug_helpers.h
  library/ssl_misc.h
  library/ssl_msg.c
  library/ssl_tls13_client.c
  library/ssl_tls13_generic.c
  library/ssl_tls13_server.c
  programs/ssl/ssl_client2.c
  tests/include/test/ssl_helpers.h
  tests/opt-testcases/tls13-misc.sh
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: enhancement, needs-review, component-tls13, priority-high
