Repository Mbed-TLS/mbedtls, pull requests merged in 2024-03, with the labels that each got.

#8864 Deprecate or remove mbedtls_pk_wrap_as_opaque
  ChangeLog.d/8848.txt
  include/mbedtls/pk.h
  library/pk.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  programs/ssl/ssl_test_lib.c
  programs/ssl/ssl_test_lib.h
  tests/src/test_helpers/ssl_helpers.c
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_pkwrite.function
  tests/suites/test_suite_x509write.function
Labels: approved, size-s, priority-high

#8846 Introduce mbedtls_ecp_write_key_ext
  ChangeLog.d/ecp_write_key.txt
  docs/psa-transition.md
  include/mbedtls/ecp.h
  library/ecp.c
  library/pk.c
  library/pkwrite.c
  library/psa_crypto_ecp.c
  library/ssl_tls12_server.c
  tests/suites/test_suite_ecp.data
  tests/suites/test_suite_ecp.function
Labels: enhancement, needs-review, component-crypto, priority-high, size-xs

#8867 Merge psa_core_key_attributes_t back into psa_key_attributes_t
  docs/psa-driver-example-and-guide.md
  include/psa/crypto_extra.h
  include/psa/crypto_struct.h
  library/psa_crypto.c
  library/psa_crypto_aead.c
  library/psa_crypto_cipher.c
  library/psa_crypto_core.h
  library/psa_crypto_ecp.c
  library/psa_crypto_ffdh.c
  library/psa_crypto_rsa.c
  library/psa_crypto_slot_management.c
  library/psa_crypto_storage.c
  library/psa_crypto_storage.h
  scripts/data_files/driver_templates/psa_crypto_driver_wrappers.h.jinja
  scripts/data_files/driver_templates/psa_crypto_driver_wrappers_no_static.c.jinja
  tests/src/drivers/test_driver_signature.c
  tests/suites/test_suite_psa_crypto_persistent_key.function
  tests/suites/test_suite_psa_crypto_se_driver_hal.function
  tests/suites/test_suite_psa_crypto_se_driver_hal_mocks.function
  tests/suites/test_suite_psa_crypto_slot_management.function
Labels: approved, component-psa, priority-high, size-xs

#8821 Update `SSL_SERIALIZED_SESSION_CONFIG_BITFLAG` with new flags
  ChangeLog.d/fix-ssl-session-serialization-config.txt
  library/ssl_tls.c
Labels: approved, needs-backports, component-tls, component-tls13, size-s

#8823 [Backport 2.28] Update `SSL_SERIALIZED_SESSION_CONFIG_BITFLAG` with new flags
  ChangeLog.d/fix-ssl-session-serialization-config.txt
  library/ssl_tls.c
Labels: approved, component-tls, needs-ci, size-s

#8863 [MBEDTLS_PRIVATE] Add a getter for the ECDH context->grp.id member.
  ChangeLog.d/add_get_ecp_group_id.txt
  include/mbedtls/ecdh.h
  library/ecdh.c
  tests/suites/test_suite_ecdh.data
  tests/suites/test_suite_ecdh.function
Labels: approved, component-crypto, priority-high, size-xs

#8678 Make builds less verbose
  tests/scripts/all.sh
  tests/scripts/check_files.py
  tests/scripts/quiet/cmake
  tests/scripts/quiet/make
  tests/scripts/quiet/quiet.sh
Labels: approved, needs-backports, size-s, component-test, priority-medium

#8873 Make builds less verbose - 2.28 backport
  scripts/generate_visualc_files.pl
  tests/scripts/all.sh
  tests/scripts/check_files.py
  tests/scripts/quiet/cmake
  tests/scripts/quiet/make
  tests/scripts/quiet/quiet.sh
Labels: approved, size-s, component-test, priority-medium

#8892 Ensure drivers have threading enabled if required
  tests/include/test/drivers/config_test_driver.h
  tests/scripts/all.sh
Labels: enhancement, approved, needs-ci, component-test, size-xs

#8883 library: psa_crypto: Explicitly initialize shared_secret
  library/psa_crypto.c
Labels: needs-review, component-psa, priority-medium, size-xs

#8861 TLS 1.3: SRV: Improve key exchange mode selection
  library/ssl_tls13_server.c
  tests/opt-testcases/tls13-kex-modes.sh
  tests/opt-testcases/tls13-misc.sh
Labels: enhancement, needs-review, component-tls13, priority-high

#8854 TLS 1.3: Enforce max_early_data_size on server
  include/mbedtls/ssl.h
  library/ssl_misc.h
  library/ssl_msg.c
  library/ssl_tls.c
  library/ssl_tls13_generic.c
  library/ssl_tls13_server.c
  tests/include/test/ssl_helpers.h
  tests/src/test_helpers/ssl_helpers.c
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: enhancement, approved, component-tls13, priority-high

#8862 Improve support of mbedtls_psa_get_random in client-only builds
  ChangeLog.d/8825.txt
  include/mbedtls/psa_util.h
  library/psa_crypto.c
  library/psa_crypto_random_impl.h
  library/psa_util.c
  library/psa_util_internal.h
  tests/src/psa_crypto_stubs.c
Labels: approved, size-s, priority-high

#8912 Fix threading bug when multiple destroy_key calls run on the same key
  library/psa_crypto.c
Labels: needs-review, component-crypto, needs-reviewer, priority-very-high, size-xs

#8831 Use mpi_core_exp_mod in bignum
  ChangeLog.d/use_exp_mod_core.txt
  include/mbedtls/bignum.h
  library/bignum.c
  library/bignum_core.c
  library/bignum_core.h
  tests/suites/test_suite_bignum.function
  tests/suites/test_suite_bignum.misc.data
Labels: enhancement, approved, component-crypto, size-s, priority-very-high

#8882 Test multi-threaded key generation
  tests/scripts/all.sh
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: approved, component-crypto, size-s, priority-very-high

#8916 Fix IAR warning
  library/bignum.c
Labels: bug, approved, needs-review, needs-ci, needs-reviewer, priority-very-high, size-xs

#8917 mbedtls_pk_decrypt/encrypt actually check the padding mode
  ChangeLog.d/8824.txt
Labels: approved, component-crypto, priority-very-high, size-xs

#8887 Fix intended code blocks that were not suitably indented
  include/mbedtls/pk.h
Labels: bug, approved, component-crypto, priority-high, size-xs

#8850 project: set version
  CMakeLists.txt
Labels: bug, approved, needs-backports, component-platform, needs-ci, priority-high

#8822 SHA-3 performance & code size
  library/sha3.c
  tests/scripts/all.sh
Labels: enhancement, approved, component-crypto, priority-medium, size-optimisation, size-xs

#8908 CMAC size and perf
  library/cmac.c
Labels: approved, component-crypto, priority-medium, size-optimisation, size-xs

#8857 TLS 1.3: Enforce max_early_data_size on client
  library/ssl_msg.c
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: enhancement, approved, component-tls13, priority-very-high

#8774 Implement mbedtls_pk_copy_from_psa
  ChangeLog.d/8709.txt
  include/mbedtls/pk.h
  library/CMakeLists.txt
  library/Makefile
  library/pk.c
  library/pk_ecc.c
  library/pk_internal.h
  library/pk_wrap.c
  library/pkparse.c
  library/rsa.c
  tests/scripts/all.sh
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
Labels: approved, size-s, priority-very-high

#8895 Follow-up non-verbose logs 2.28
  tests/scripts/quiet/cmake
  tests/scripts/quiet/make
  tests/scripts/quiet/quiet.sh
Labels: bug, approved, component-platform, priority-medium, size-xs

#8894 Follow-up non-verbose logs
  tests/scripts/quiet/cmake
  tests/scripts/quiet/make
  tests/scripts/quiet/quiet.sh
Labels: bug, approved, component-platform, priority-medium, size-xs

#8899 New function mbedtls_pk_copy_public_from_psa
  ChangeLog.d/8709.txt
  include/mbedtls/pk.h
  library/pk.c
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
Labels: enhancement, approved, priority-high, size-xs

#8891 Officially document non thread-safety of MBEDTLS_PSA_CRYPTO_SE_C
  include/mbedtls/mbedtls_config.h
  library/psa_crypto_storage.h
  tests/scripts/all.sh
Labels: component-crypto, priority-very-high, size-xs

#8888 [MBEDTLS_PRIVATE] Add accessor for session and ciphersuite_id
  ChangeLog.d/add_ssl_session_accessors.txt
  include/mbedtls/ssl.h
  include/mbedtls/ssl_ciphersuites.h
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: approved, component-tls13, size-s, priority-very-high

#8922 Fix gcc -O3 warnings
  library/cmac.c
  library/gcm.c
Labels: approved, component-crypto, component-platform, priority-medium, size-xs

#8884 TLS 1.3: CLI: Split early data user status and internal state
  include/mbedtls/ssl.h
  library/ssl_debug_helpers.h
  library/ssl_misc.h
  library/ssl_msg.c
  library/ssl_tls.c
  library/ssl_tls13_client.c
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: enhancement, approved, component-tls13, priority-very-high

#8926 Work around a bug in ancient lcov
  scripts/lcov.sh
Labels: approved, component-test, priority-very-high, size-xs

#8920 Generalize some PK functions from MBEDTLS_PSA_CRYPTO_C to MBEDTLS_PSA_CRYPTO_CLIENT
  include/mbedtls/pk.h
  library/pk.c
  tests/scripts/all.sh
  tests/src/psa_crypto_stubs.c
Labels: approved, priority-very-high, size-xs

#8575 Fix wrong suite name in check_test_cases.py
  tests/compat.sh
  tests/scripts/check_test_cases.py
  tests/ssl-opt.sh
Labels: bug, approved, size-s, component-test, priority-high

#8697 Do not generate new random number while receiving HRR
  ChangeLog.d/fix-new-rn-on-hrr.txt
  library/ssl_client.c
  tests/suites/test_suite_ssl.function
Labels: bug, approved, component-tls13, priority-high, size-xs

#8829 Add metatests for failing TEST_EQUAL and TEST_LE_*
  programs/test/metatest.c
Labels: enhancement, approved, component-test, priority-high, size-xs

#8913 TLS 1.3: Enforce ticket maximum lifetime and discard tickets with 0 lifetime
  include/mbedtls/ssl_ticket.h
  library/ssl_ticket.c
  library/ssl_tls13_client.c
  library/ssl_tls13_server.c
  programs/ssl/ssl_client2.c
  tests/ssl-opt.sh
Labels: enhancement, approved, component-tls13, priority-very-high

#8830 [Backport 2.28] Add metatests for failing TEST_EQUAL and TEST_LE_*
  programs/test/metatest.c
Labels: enhancement, approved, component-test, priority-high, size-xs

#8858 Add ALPN information in session tickets
  include/mbedtls/ssl.h
  library/ssl_misc.h
  library/ssl_tls.c
  library/ssl_tls13_server.c
  tests/src/test_helpers/ssl_helpers.c
  tests/suites/test_suite_ssl.function
Labels: approved, component-tls13, priority-very-high

#8924 Add testing for concurrently loading/using/destroying the same key
  tests/include/test/psa_exercise_key.h
  tests/src/psa_exercise_key.c
  tests/suites/test_suite_pkparse.function
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_storage_format.function
Labels: needs-review, component-crypto, size-s, component-test

#8914 TLS 1.3: Resumption and early data compatibility tests
  programs/ssl/ssl_server2.c
  tests/opt-testcases/tls13-misc.sh
  tests/ssl-opt.sh
Labels: enhancement, approved, component-tls13, priority-very-high

#8923 Drop Support for MSVC 2013, 2015 and Arm Compiler 5
  ChangeLog.d/drop-msvc-2015-and-armcc-5.txt
  Makefile
  README.md
  include/mbedtls/mbedtls_config.h
  scripts/data_files/vs2017-app-template.vcxproj
  scripts/data_files/vs2017-main-template.vcxproj
  scripts/data_files/vs2017-sln-template.sln
  scripts/generate_visualc_files.pl
  scripts/windows_msbuild.bat
  tests/scripts/check-generated-files.sh
  visualc/VS2017/.gitignore
Labels: enhancement, approved, priority-very-high, deprecation

#8918 TLS: Improve server version negotiation testing
  tests/ssl-opt.sh
Labels: enhancement, approved, component-tls, component-tls13, priority-very-high

#8911 Check ALPN when receiving early data
  ChangeLog.d/fix-alpn-negotiating-bug.txt
  library/ssl_tls.c
  library/ssl_tls13_server.c
  tests/include/test/ssl_helpers.h
  tests/src/test_helpers/ssl_helpers.c
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: approved, component-tls, priority-very-high

#8931 Backport 2.28: Fix bug in ALPN loading from serialised session
  ChangeLog.d/fix-alpn-negotiating-bug.txt
  library/ssl_tls.c
Labels: approved, priority-very-high, size-xs

#8930 TLS 1.3: Documentation update for 3.6 release
  ChangeLog.d/early-data.txt
  docs/architecture/tls13-support.md
  docs/tls13-early-data.md
  include/mbedtls/mbedtls_config.h
  include/mbedtls/ssl.h
Labels: enhancement, approved, component-tls13, priority-very-high

#8901 Make PSA global_data thread safe
  include/mbedtls/threading.h
  library/psa_crypto.c
  library/psa_crypto_slot_management.c
  library/threading.c
  tests/suites/test_suite_psa_crypto_init.data
  tests/suites/test_suite_psa_crypto_init.function
Labels: enhancement, approved, needs-ci, component-psa, size-s, priority-very-high

#8921 pk_import_into_psa: test persistent keys
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
Labels: enhancement, approved, component-crypto, priority-high, size-xs

#8934 Add changelog entry for threading MVP
  ChangeLog.d/add_threading_changelog.txt
Labels: enhancement, approved, priority-very-high, size-xs

#8939 Codestyle autogen fix
  scripts/code_style.py
Labels: bug, approved, needs-review, needs-ci, component-test, priority-very-high, size-xs

#8940 Add issues fixed to threading MVP changelog entry
  ChangeLog.d/add_threading_changelog.txt
Labels: needs-ci, priority-very-high, size-xs

#8932 Enable TLS 1.3 by default
  ChangeLog.d/enable-tls13-by-default.txt
  include/mbedtls/mbedtls_config.h
  tests/scripts/all.sh
Labels: approved, component-tls, priority-very-high

#8942 [Bugfix] Fix null dereference in `mbedtls_pk_verify_ext()`
  ChangeLog.d/fix-null-dereference-verify-ext.txt
  library/pk.c
  tests/suites/test_suite_pk.function
Labels: bug, approved, priority-high, size-xs

#8951 mbedtls_pk_setup_opaque always uses PKCS#1v1.5 for RSA keys
  ChangeLog.d/8938.txt
  library/pk_wrap.c
  library/pkwrite.h
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
Labels: approved, size-s, priority-high

#8959 Update BRANCHES for 3.6 - 2.28 backport
  BRANCHES.md
  BUGS.md
  README.md
Labels: approved, component-docs, priority-very-high, size-xs

#8941 Update BRANCHES for 3.6
  BRANCHES.md
  BUGS.md
  README.md
Labels: approved, priority-very-high, size-xs

#8586 Fix fake cases listed of compat.sh
  tests/compat.sh
Labels: bug, approved, size-s, component-test, priority-high

#8956 [Backport 2.28] Fix fake cases listed of compat.sh
  tests/compat.sh
Labels: bug, approved, size-s, component-test, priority-high

#8967 ssl-opt.sh: Improve version selection test titles
  tests/ssl-opt.sh
Labels: enhancement, approved, component-tls, priority-high

#8957 Unify consistency tests for mbedtls_pk_import_into_psa and mbedtls_pk_copy_from_psa
  tests/suites/test_suite_pk.function
Labels: approved, priority-high, size-xs

#8875 [backport] Fix compilation on macOS without apple-clang
  library/CMakeLists.txt
Labels: approved, component-platform, priority-medium, size-xs

#8874 Fix compilation on macOS without apple-clang
  library/CMakeLists.txt
Labels: approved, component-platform, priority-medium
