Repository Mbed-TLS/mbedtls, pull requests merged in 2024-04, with the labels that each got.

#9007 Add 3.6 backport checkbox to the PR template
  .github/pull_request_template.md
Labels: approved, priority-very-high, size-xs

#8937 Clarify the documentation of mbedtls_pk_setup_opaque
  docs/use-psa-crypto.md
  include/mbedtls/pk.h
  library/pk.c
  tests/suites/test_suite_pk.function
Labels: approved, size-s, priority-high

#9005 [Backport 3.6] Clarify the documentation of mbedtls_pk_setup_opaque
  docs/use-psa-crypto.md
  include/mbedtls/pk.h
  library/pk.c
  tests/suites/test_suite_pk.function
Labels: approved, priority-high, size-xs

#9004 [Backport 3.6] Test gap: mbedtls_pk_check_pair with MBEDTLS_PK_OPAQUE
  tests/suites/test_suite_pk.function
Labels: approved, priority-high, size-xs

#8987 Test gap: mbedtls_pk_check_pair with MBEDTLS_PK_OPAQUE
  tests/suites/test_suite_pk.function
Labels: approved, priority-high, size-xs

#6955 Guard ticket specific TLS 1.3 function with macro
  ChangeLog.d/tls13-without-tickets.txt
  include/mbedtls/ssl.h
  library/ssl_msg.c
  library/ssl_tls.c
  library/ssl_tls13_client.c
  library/ssl_tls13_server.c
  tests/opt-testcases/tls13-misc.sh
  tests/scripts/all.sh
  tests/src/test_helpers/ssl_helpers.c
  tests/ssl-opt.sh
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: bug, approved, component-tls13, priority-high

#9014 [Backport 3.6] Guard ticket specific TLS 1.3 function with macro
  ChangeLog.d/tls13-without-tickets.txt
  include/mbedtls/ssl.h
  library/ssl_msg.c
  library/ssl_tls.c
  library/ssl_tls13_client.c
  library/ssl_tls13_server.c
  tests/opt-testcases/tls13-misc.sh
  tests/scripts/all.sh
  tests/src/test_helpers/ssl_helpers.c
  tests/ssl-opt.sh
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: bug, approved, component-tls13, priority-high

#8996 [Backport 2.28] Fix wrong dependencies in test cases
  tests/include/test/drivers/key_management.h
  tests/src/drivers/test_driver_key_management.c
  tests/suites/test_suite_psa_crypto_driver_wrappers.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
  tests/suites/test_suite_psa_crypto_se_driver_hal.function
  tests/suites/test_suite_x509parse.data
  tests/suites/test_suite_x509parse.function
Labels: approved, size-s, priority-high

#8997 Fix wrong dependencies in test cases
  tests/include/test/drivers/key_management.h
  tests/src/drivers/test_driver_key_management.c
  tests/suites/test_suite_psa_crypto_driver_wrappers.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
  tests/suites/test_suite_psa_crypto_pake.data
  tests/suites/test_suite_psa_crypto_se_driver_hal.function
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_x509parse.data
Labels: bug, approved, size-s, component-test, priority-high

#9009 [Backport 3.6] Fix wrong dependencies in test cases + follow-up
  tests/include/test/drivers/key_management.h
  tests/src/drivers/test_driver_key_management.c
  tests/suites/test_suite_psa_crypto_driver_wrappers.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
  tests/suites/test_suite_psa_crypto_pake.data
  tests/suites/test_suite_psa_crypto_se_driver_hal.function
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_x509parse.data
Labels: bug, approved, priority-high

#9000 Backport 3.6: Fix compilation when memcpy() is a function-like macro
  ChangeLog.d/fix-compilation-when-memcpy-is-function-like-macro.txt
  library/ssl_tls13_generic.c
Labels: approved, component-tls13, priority-high, size-xs

#8999 Fix compilation when memcpy() is a function-like macro
  ChangeLog.d/fix-compilation-when-memcpy-is-function-like-macro.txt
  library/ssl_tls13_generic.c
Labels: approved, needs-backports, component-tls13, priority-high, size-xs

#8998 Use latest installed OpenSSL 3 as OPENSSL_NEXT
  tests/data_files/Makefile
  tests/data_files/server2-sha256.ku-ds.crt
  tests/data_files/server2-sha256.ku-ds_ke.crt
  tests/data_files/server2-sha256.ku-ka.crt
  tests/data_files/server2-sha256.ku-ke.crt
  tests/opt-testcases/tls13-kex-modes.sh
  tests/scripts/all.sh
  tests/ssl-opt.sh
Labels: approved, component-tls, priority-high

#9028 Backport 3.6: Use latest installed OpenSSL 3 as OPENSSL_NEXT
  tests/data_files/Makefile
  tests/data_files/server2-sha256.ku-ds.crt
  tests/data_files/server2-sha256.ku-ds_ke.crt
  tests/data_files/server2-sha256.ku-ka.crt
  tests/data_files/server2-sha256.ku-ke.crt
  tests/opt-testcases/tls13-kex-modes.sh
  tests/scripts/all.sh
  tests/ssl-opt.sh
Labels: approved, component-tls, priority-high

#8566 Document driver testing status
  docs/architecture/testing/driver-interface-test-strategy.md
  tests/configs/user-config-for-test.h
  tests/include/test/drivers/crypto_config_test_driver_extension.h
  tests/scripts/all.sh
  tests/src/drivers/test_driver_pake.c
Labels: approved, size-s

#9042 [3.6 backport] Asn1 missing guard in rsa backport
  ChangeLog.d/asn1-missing-guard-in-rsa.txt
  include/mbedtls/config_adjust_legacy_crypto.h
Labels: bug, approved, size-s, priority-high

#9035 Auto-enable ASN1 when RSA is enabled
  ChangeLog.d/asn1-missing-guard-in-rsa.txt
  include/mbedtls/config_adjust_legacy_crypto.h
Labels: bug, approved, priority-high, size-xs

#9040 Make component_test_psa_crypto_rsa_no_genprime work with PSA_CRYPTO_CONFIG set
  tests/scripts/all.sh
Labels: needs-review, priority-high, size-xs

#9019 [2.28] Fix compat.sh tests (reported as) not executed
  tests/compat.sh
  tests/scripts/all.sh
  tests/scripts/analyze_outcomes.py
  tests/scripts/basic-build-test.sh
Labels: bug, approved, size-s, priority-high

#9021 [3.6] Small fixes to compat.sh (partial forward-port)
  tests/compat.sh
  tests/scripts/all.sh
  tests/scripts/basic-build-test.sh
Labels: approved, priority-high, size-xs

#9022 [dev] Small fixes to compat.sh (partial forward-port)
  tests/compat.sh
  tests/scripts/all.sh
  tests/scripts/basic-build-test.sh
Labels: approved, priority-high, size-xs

#9033 [3.6 backport] Improve test key generation in test_suite_pk
  library/pk.c
  scripts/mbedtls_dev/asymmetric_key_data.py
  tests/scripts/generate_test_keys.py
  tests/src/test_keys.h
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
Labels: approved, priority-high, size-xs

#8986 Improve test key generation in test_suite_pk
  library/pk.c
  scripts/mbedtls_dev/asymmetric_key_data.py
  tests/scripts/generate_test_keys.py
  tests/src/test_keys.h
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
Labels: approved, size-s, priority-high

#9065 Add early exit if zero length AEAD additional data passed in.
  ChangeLog.d/fix_ubsan_mp_aead_gcm.txt
  library/psa_crypto.c
Labels: approved, component-psa, priority-high, size-xs
