Repository Mbed-TLS/mbedtls, pull requests merged in 2024-12, with the labels that each got.

#9665 Add PSA interruptible key generation get num ops API
  ChangeLog.d/add-psa-iop-generate-key.txt
  tf-psa-crypto/core/psa_crypto.c
  tf-psa-crypto/drivers/builtin/src/psa_crypto_ecp.c
  tf-psa-crypto/drivers/builtin/src/psa_crypto_ecp.h
  tf-psa-crypto/tests/suites/test_suite_psa_crypto.function
Labels: needs-review, component-psa, size-s, priority-high

#9811 Mbedtls 2.28: Fix compilation on MS-DOS DJGPP
  ChangeLog.d/fix-compilation-with-djgpp.txt
  library/net_sockets.c
Labels: enhancement, needs-review, component-platform, needs-reviewer, priority-medium, size-xs

#9812 Mbedtls 3.6: Fix compilation on MS-DOS DJGPP
  ChangeLog.d/fix-compilation-with-djgpp.txt
  library/net_sockets.c
Labels: enhancement, needs-review, component-platform, needs-reviewer, priority-medium, size-xs

#9810 Fix compilation on MS-DOS DJGPP
  ChangeLog.d/fix-compilation-with-djgpp.txt
  library/net_sockets.c
Labels: enhancement, needs-review, needs-backports, component-platform, needs-reviewer, priority-medium, size-xs

#9781 Remove discussions of MBEDTLS_USE_PSA_CRYPTO in API documentation
  configs/ext/README.md
  configs/ext/tfm_mbedcrypto_config_profile_medium.h
  include/mbedtls/config_adjust_legacy_crypto.h
  include/mbedtls/mbedtls_config.h
  include/mbedtls/ssl.h
  include/mbedtls/ssl_ciphersuites.h
  include/mbedtls/x509_crl.h
  include/mbedtls/x509_crt.h
  include/mbedtls/x509_csr.h
  tf-psa-crypto/drivers/builtin/include/mbedtls/cipher.h
  tf-psa-crypto/drivers/builtin/include/mbedtls/pk.h
Labels: enhancement, approved, priority-high, size-xs

#9806 Finalize split preparation-1
  CMakeLists.txt
  docs/psa-driver-example-and-guide.md
  include/mbedtls/timing.h
  library/CMakeLists.txt
  library/Makefile
  library/ssl_tls.c
  library/ssl_tls13_keys.c
  library/timing.c
  programs/fuzz/CMakeLists.txt
  programs/pkey/gen_key.c
  programs/pkey/key_app.c
  programs/pkey/key_app_writer.c
  programs/pkey/pk_decrypt.c
  programs/pkey/pk_encrypt.c
  programs/pkey/pk_sign.c
  programs/pkey/pk_verify.c
  programs/ssl/CMakeLists.txt
  programs/test/CMakeLists.txt
  programs/test/benchmark.c
  programs/x509/CMakeLists.txt
  scripts/config.py
  scripts/make_generated_files.bat
  tests/Makefile
  tests/scripts/check-generated-files.sh
  tests/suites/test_suite_timing.data
  tests/suites/test_suite_timing.function
  tf-psa-crypto/CMakeLists.txt
  tf-psa-crypto/core/CMakeLists.txt
  tf-psa-crypto/drivers/builtin/include/mbedtls/config_adjust_legacy_crypto.h
  tf-psa-crypto/drivers/builtin/include/mbedtls/hkdf.h
  tf-psa-crypto/drivers/builtin/src/psa_util.c
  tf-psa-crypto/scripts/data_files/driver_jsons/driver_opaque_schema.json
  tf-psa-crypto/scripts/data_files/driver_jsons/driver_transparent_schema.json
  tf-psa-crypto/scripts/data_files/driver_jsons/driverlist.json
  tf-psa-crypto/scripts/data_files/driver_jsons/mbedtls_test_opaque_driver.json
  tf-psa-crypto/scripts/data_files/driver_jsons/mbedtls_test_transparent_driver.json
  tf-psa-crypto/scripts/data_files/driver_jsons/p256_transparent_driver.json
  tf-psa-crypto/scripts/data_files/driver_templates/OS-template-opaque.jinja
  tf-psa-crypto/scripts/data_files/driver_templates/OS-template-transparent.jinja
  tf-psa-crypto/scripts/data_files/driver_templates/psa_crypto_driver_wrappers.h.jinja
  tf-psa-crypto/scripts/data_files/driver_templates/psa_crypto_driver_wrappers_no_static.c.jinja
  tf-psa-crypto/scripts/framework_scripts_path.py
  tf-psa-crypto/scripts/generate_driver_wrappers.py
  tf-psa-crypto/tests/CMakeLists.txt
  tf-psa-crypto/tests/include/test/psa_test_wrappers.h
  tf-psa-crypto/tests/src/psa_test_wrappers.c
Labels: enhancement, approved, priority-high

#9824 Backport 3.6: Remove obsolete CI Scripts
  scripts/windows_msbuild.bat
  tests/docker/bionic/Dockerfile
  tests/scripts/all-in-docker.sh
  tests/scripts/basic-in-docker.sh
  tests/scripts/components-configuration-x509.sh
  tests/scripts/docker_env.sh
  tests/scripts/tcp_client.pl
  tests/scripts/travis-log-failure.sh
  tests/ssl-opt-in-docker.sh
  tests/ssl-opt.sh
Labels: approved

#9666 Remove obsolete CI Scripts
  scripts/config.pl
  scripts/windows_msbuild.bat
  tests/docker/bionic/Dockerfile
  tests/scripts/all-in-docker.sh
  tests/scripts/basic-in-docker.sh
  tests/scripts/components-configuration-x509.sh
  tests/scripts/docker_env.sh
  tests/scripts/tcp_client.pl
  tests/scripts/travis-log-failure.sh
  tests/ssl-opt-in-docker.sh
  tests/ssl-opt.sh
Labels: enhancement, approved, priority-high, size-xs

#9783 Make some edge cases of not-supported or invalid mechanisms more uniform
  tests/scripts/analyze_outcomes.py
  tf-psa-crypto/core/psa_crypto.c
  tf-psa-crypto/scripts/data_files/driver_templates/psa_crypto_driver_wrappers.h.jinja
  tf-psa-crypto/tests/suites/test_suite_psa_crypto.data
  tf-psa-crypto/tests/suites/test_suite_psa_crypto_not_supported.function
  tf-psa-crypto/tests/suites/test_suite_psa_crypto_op_fail.function
  tf-psa-crypto/tests/suites/test_suite_psa_crypto_op_fail.misc.data
  tf-psa-crypto/tests/suites/test_suite_psa_crypto_se_driver_hal_mocks.function
Labels: approved, component-crypto, priority-high, size-xs

#9782 Backport 3.6: Make some edge cases of not-supported or invalid mechanisms more uniform
  library/psa_crypto.c
  scripts/data_files/driver_templates/psa_crypto_driver_wrappers.h.jinja
  tests/scripts/analyze_outcomes.py
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto_not_supported.function
  tests/suites/test_suite_psa_crypto_op_fail.function
  tests/suites/test_suite_psa_crypto_op_fail.misc.data
  tests/suites/test_suite_psa_crypto_se_driver_hal_mocks.function
Labels: needs-review, component-crypto, priority-high, size-xs

#9808 Add PSA interruptible export public-key complete API
  tf-psa-crypto/core/psa_crypto.c
  tf-psa-crypto/drivers/builtin/src/psa_crypto_ecp.c
  tf-psa-crypto/drivers/builtin/src/psa_crypto_ecp.h
  tf-psa-crypto/include/psa/crypto_builtin_composites.h
  tf-psa-crypto/include/psa/crypto_struct.h
  tf-psa-crypto/tests/suites/test_suite_psa_crypto.data
  tf-psa-crypto/tests/suites/test_suite_psa_crypto.function
Labels: approved, needs-backports, component-psa, size-s, priority-high

#9821 Backport 2.28: Make some edge cases of not-supported or invalid mechanisms more uniform
  tests/suites/test_suite_psa_crypto.data
Labels: bug, approved, needs-backports, component-crypto, priority-high, size-xs

#9849 [Backport 2.28] Specify previously missed register clobbers in AES-NI asm blocks
  ChangeLog.d/fix-aesni-asm-clobbers.txt
  library/aesni.c
Labels: bug, approved, component-crypto, priority-high, size-xs

#9848 [Backport 3.6] Specify previously missed register clobbers in AES-NI asm blocks
  ChangeLog.d/fix-aesni-asm-clobbers.txt
  library/aesni.c
Labels: bug, approved, component-crypto, priority-high, size-xs

#9809 Specify previously missed register clobbers in AES-NI asm blocks
  ChangeLog.d/fix-aesni-asm-clobbers.txt
  tf-psa-crypto/drivers/builtin/src/aesni.c
Labels: bug, approved, needs-backports, component-crypto, priority-high, size-xs

#9847 Align mbedtls_config.h with design
  docs/proposed/config-split.md
  include/mbedtls/mbedtls_config.h
  scripts/generate_features.pl
Labels: needs-review, component-platform, size-s, priority-high

#9834 [Backport 3.6] Fix submodule error messages
  CMakeLists.txt
  Makefile
Labels: approved, size-xs

#9833 Fix submodule error messages
  CMakeLists.txt
  Makefile
Labels: approved, needs-backports, priority-medium, size-xs
