Repository Mbed-TLS/mbedtls, pull requests merged in 2025-05, with the labels that each got.

#10130 [development] Restrict MBEDTLS_X509_RSASSA_PSS_SUPPORT
  include/mbedtls/x509_crl.h
  include/mbedtls/x509_crt.h
  include/mbedtls/x509_csr.h
  library/ssl_tls12_client.c
  library/ssl_tls13_generic.c
  library/x509.c
  library/x509_crl.c
  library/x509_crt.c
  library/x509_csr.c
  library/x509_internal.h
  tests/suites/test_suite_x509parse.data
  tests/suites/test_suite_x509write.function
Labels: approved, size-s, priority-high

#10166 Restore the OID module for use in X.509
  library/x509_oid.c
  library/x509_oid.h
  tests/suites/test_suite_x509_oid.data
  tests/suites/test_suite_x509_oid.function
Labels: approved, priority-high, size-xs

#9654 Update the `pkalgs` domain to use PSA macros in `depends.py`
  tests/scripts/depends.py
Labels: enhancement, approved, size-s, component-test, priority-high

#8947 Mark ssl_tls12_preset_default_sig_algs const
  library/ssl_tls.c
Labels: enhancement, approved, size-xs

#10185 Mark TLS 1.2 algo suite definitons const
  library/ssl_tls.c
Labels: enhancement, approved, priority-medium, size-xs

#10186 Remove call to pk_decrypt() in ssl_server2
  programs/ssl/ssl_server2.c
Labels: approved, component-tls, size-xs

#10133 remove compat-2.x.h
  ChangeLog.d/remove-compat-2.x.txt
  include/mbedtls/compat-2.x.h
Labels: approved, priority-high, size-xs

#10183 Change hardcoded error values in ssl-opt to take in the PSA error alias
  tests/ssl-opt.sh
Labels: approved, priority-high, size-xs

#10196 [Backport 3.6] Move the inclusion of crypto_sizes.h and crypto_struct.h in crypto.h
  ChangeLog.d/move-crypto-struct-inclusion.txt
  include/psa/crypto.h
Labels: approved, priority-medium, size-xs
