Repository Mbed-TLS/mbedtls, pull requests merged in 2025-06, with the labels that each got.

#10201 Add temporary test component for SHA3 testing
  tests/scripts/components-configuration.sh
Labels: enhancement, approved, component-test, priority-high, size-xs

#10182 3.6 only: document f_rng callbacks
  include/mbedtls/bignum.h
  include/mbedtls/dhm.h
  include/mbedtls/ecdh.h
  include/mbedtls/ecdsa.h
  include/mbedtls/ecjpake.h
  include/mbedtls/ecp.h
  include/mbedtls/lms.h
  include/mbedtls/pk.h
  include/mbedtls/platform_util.h
  include/mbedtls/rsa.h
  include/mbedtls/ssl.h
  include/mbedtls/ssl_cookie.h
  include/mbedtls/ssl_ticket.h
  include/mbedtls/x509_crt.h
  include/mbedtls/x509_csr.h
Labels: approved, size-s, priority-medium

#10173 OID: make X.509 independent from crypto
  ChangeLog.d/oid.txt
  doxygen/mbedtls.doxyfile
  include/mbedtls/check_config.h
  include/mbedtls/mbedtls_config.h
  include/mbedtls/oid.h
  include/mbedtls/ssl.h
  include/mbedtls/x509.h
  library/CMakeLists.txt
  library/Makefile
  library/pkcs7.c
  library/ssl_tls.c
  library/ssl_tls13_generic.c
  library/x509.c
  library/x509_create.c
  library/x509_crt.c
  library/x509_csr.c
  library/x509_oid.c
  library/x509_oid.h
  library/x509write_crt.c
  library/x509write_csr.c
  tests/suites/test_suite_x509_oid.data
  tests/suites/test_suite_x509_oid.function
  tests/suites/test_suite_x509parse.data
  tests/suites/test_suite_x509parse.function
  tests/suites/test_suite_x509write.function
Labels: approved, component-x509, size-s, priority-high

#10192 [development] Some pre-requisites for psa#299
  include/mbedtls/debug.h
  library/debug.c
  library/debug_internal.h
  programs/ssl/ssl_client2.c
  tests/suites/test_suite_pkcs7.function
  tests/suites/test_suite_x509parse.function
Labels: approved, component-crypto, priority-high, size-xs

#9634 Update the `hashes` domain to use PSA macros in `depends.py`
  tests/scripts/components-configuration.sh
  tests/scripts/depends.py
Labels: enhancement, approved, size-s, component-test, priority-high

#10215 [3.6] Fix GCC 15 warning 'Wunterminated-string-initialization'
  ChangeLog.d/unterminated-string-initialization.txt
  library/common.h
  library/ssl_tls13_keys.c
  library/ssl_tls13_keys.h
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_slot_management.function
  tests/suites/test_suite_ssl_decrypt.function
Labels: approved, priority-high, size-xs

#10231 Preparatory work for the resolution of #10022
  programs/pkey/gen_key.c
  programs/pkey/pk_sign.c
  programs/pkey/pk_verify.c
  programs/pkey/rsa_sign_pss.c
  programs/pkey/rsa_verify_pss.c
  programs/test/CMakeLists.txt
  programs/test/cmake_package/CMakeLists.txt
  programs/test/cmake_package_install/CMakeLists.txt
  programs/test/cmake_subproject/CMakeLists.txt
  programs/util/CMakeLists.txt
Labels: enhancement, approved, priority-high

#10240 library: Makefile: use wildcard to select sources for crypto library
  library/Makefile
Labels: approved, priority-high, size-xs

#10241 [BACKPORT] Fixed some minor typos in comments.
  library/ssl_msg.c
  library/ssl_tls12_client.c
  tests/ssl-opt.sh
Labels: needs-review, priority-medium, size-xs

#10237 Remove temporary path fixes introduced in mbedtls#10225
  scripts/generate_visualc_files.pl
Labels: approved, priority-high, size-xs

#10245 [Dev] Turn Wunterminated-string-initialization back into an error
  tests/scripts/components-compiler.sh
Labels: approved, component-test, priority-high, size-xs

#10197 Break down mbedtls_test_ssl_perform_handshake
  ChangeLog.d/mbedtls_ssl_conf_alpn_protocols.txt
  include/mbedtls/ssl.h
  library/ssl_client.c
  library/ssl_tls.c
  library/ssl_tls12_client.c
  library/ssl_tls13_client.c
  tests/include/test/ssl_helpers.h
  tests/src/test_helpers/ssl_helpers.c
  tests/suites/test_suite_ssl.function
Labels: approved, component-tls, size-s, priority-high

#10255 Migration guide for API changes in 2025Q2 in mbedtls
  ChangeLog.d/9892.txt
  ChangeLog.d/9964.txt
  ChangeLog.d/error-unification.txt
  ChangeLog.d/removal-of-rng.txt
  ChangeLog.d/remove-crypto-alt-interface.txt
  ChangeLog.d/remove-via-padlock-support.txt
  docs/4.0-migration-guide/deprecated-removals.md
  docs/4.0-migration-guide/error-codes.md
  docs/4.0-migration-guide/feature-removals.md
  docs/4.0-migration-guide/function-prototype-changes.md
  docs/4.0-migration-guide/oid.md
  docs/4.0-migration-guide/private-decls.md
  docs/4.0-migration-guide/psa-only.md
  docs/psa-transition.md
  doxygen/input/doc_mainpage.h
Labels: approved, size-s, priority-high
