Repository Mbed-TLS/mbedtls, pull requests merged in 2025-01, with the labels that each got.

#9823 Backport 3.6: Fix discussions of MBEDTLS_USE_PSA_CRYPTO in standalone documentation
  docs/architecture/psa-migration/strategy.md
  docs/driver-only-builds.md
Labels: approved, priority-high, size-xs

#9777 Add a SBOM file in CycloneDX format
  scripts/sbom.cdx.json
Labels: enhancement, approved, component-platform, priority-medium, size-xs

#9830 Backport 3.6: Added debug print in tls13 ssl_tls13_write_key_share_ext
  library/ssl_tls13_client.c
Labels: needs-review, needs-reviewer, component-tls13, priority-medium, size-xs

#9796 Backport 3.6: Switch generate_psa_test.py to automatic dependencies for positive test cases
  Makefile
  include/mbedtls/config_adjust_legacy_from_psa.h
  include/mbedtls/config_adjust_psa_superset_legacy.h
  include/psa/crypto_config.h
  library/psa_crypto_cipher.c
  scripts/config.py
  tests/CMakeLists.txt
  tests/Makefile
  tests/configs/crypto_config_test_driver_extension.h
  tests/scripts/analyze_outcomes.py
Labels: approved, component-crypto, component-platform, priority-high, size-xs

#9890 PSA interruptible sign/verify: detect invalid curve family in start
  library/psa_crypto.c
Labels: approved, component-crypto, priority-high, size-xs

#9913 Remove deprecated function mbedtls_x509write_crt_set_serial()
  ChangeLog.d/9892.txt
  include/mbedtls/x509_crt.h
  library/x509write_crt.c
  tests/suites/test_suite_x509write.function
Labels: needs-review, priority-high, size-xs

#9918 Add X.509 formatting validation to SECURITY.md
  SECURITY.md
Labels: approved, needs-ci

#9495 [Backport 3.6] Refactored a minor check in ecp check privkey
  library/ecp.c
Labels: needs-review, single-reviewer, priority-low, size-xs

#9907 [3.6 backport]: mbedtls_conf_curves()
  docs/3.0-migration-guide.md
  tests/suites/test_suite_ssl.function
Labels: approved, priority-high, size-xs

#9906 [dev] Remove deprecated function mbedtls_ssl_conf_curves()
  ChangeLog.d/rm-ssl-conf-curves.txt
  docs/3.0-migration-guide.md
  include/mbedtls/ssl.h
  library/ssl_client.c
  library/ssl_misc.h
  library/ssl_tls.c
  library/ssl_tls12_server.c
  library/ssl_tls13_client.c
  tests/scripts/analyze_outcomes.py
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: approved, api-break, size-s, priority-high

#9633 Update the `curves` domain to use PSA macros in `depends.py`
  tests/scripts/depends.py
Labels: enhancement, approved, size-s, component-test, priority-high

#9937 [Backport 3.6] Migrate DHE test cases to ECDHE
  tests/scripts/analyze_outcomes.py
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: needs-review, priority-high, size-xs

#9916 Migrate DHE test cases to ECDHE
  tests/ssl-opt.sh
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: approved, needs-backports, size-s, priority-high

#9945 PR-Template: Updated the PR template with TF-PSA-Crypto checkbox
  .github/pull_request_template.md
Labels: priority-high, size-xs
