Repository Mbed-TLS/mbedtls, pull requests merged in 2025-03, with the labels that each got.

#9954 Migrate RSA-decryption test cases
  tests/include/test/ssl_helpers.h
  tests/scripts/components-configuration-tls.sh
  tests/ssl-opt.sh
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: needs-review, component-tls, priority-high

#10047 Fix defrag interleave dev
  library/ssl_msg.c
Labels: approved, priority-very-high, size-xs

#10046 Fix defrag interleave 3.6
  library/ssl_msg.c
Labels: approved, priority-very-high, size-xs

#10055 Backport 3.6: Document the limitations of TLS handshake message defragmentation
  ChangeLog.d/tls-hs-defrag-in.txt
  include/mbedtls/ssl.h
Labels: needs-review, component-tls, priority-very-high, size-xs

#10051 PSA core: Allow enabling one volatile/builtin key
  library/psa_crypto_slot_management.c
Labels: approved, component-crypto, priority-medium, size-xs

#10026 Backport 2.28: Fix psa_key_derivation_input_bytes() not detecting bad state
  ChangeLog.d/fix-key-derive-bad-state-error.txt
  library/psa_crypto.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: approved, size-xs

#10044 [Backport 2.28] Fix preprocessor guards for C99 format size specifiers
  3rdparty/everest/include/everest/kremlin/c_endianness.h
  3rdparty/everest/include/everest/kremlin/internal/callconv.h
  3rdparty/everest/include/everest/vs2010/inttypes.h
  3rdparty/everest/include/everest/vs2010/stdbool.h
  ChangeLog.d/fix-msvc-version-guard-format-zu.txt
  include/mbedtls/debug.h
  tests/suites/test_suite_debug.data
  tests/suites/test_suite_debug.function
Labels: bug, approved, component-tls, size-s, priority-high

#10043 [Backport 3.6] Fix preprocessor guards for C99 format size specifiers
  3rdparty/everest/include/everest/kremlin/c_endianness.h
  3rdparty/everest/include/everest/kremlin/internal/callconv.h
  3rdparty/everest/include/everest/vs2013/inttypes.h
  3rdparty/everest/include/everest/vs2013/stdbool.h
  ChangeLog.d/fix-msvc-version-guard-format-zu.txt
  include/mbedtls/debug.h
  tests/suites/test_suite_debug.data
  tests/suites/test_suite_debug.function
Labels: bug, approved, component-tls, size-s, priority-high

#10053 Backport 2.28: Document PSA's need for threading
  include/mbedtls/config.h
Labels: bug, approved, priority-high, size-xs

#9096 mbedtls_net_send API description typo fix
  include/mbedtls/net_sockets.h
Labels: approved, needs-backports, component-tls, priority-medium, size-xs

#10058 Backport 3.6: mbedtls_net_send API description typo fix
  include/mbedtls/net_sockets.h
Labels: approved, component-tls, priority-medium, size-xs

#10004 Backport 3.6: Document PSA's need for threading
  include/mbedtls/mbedtls_config.h
Labels: bug, approved, priority-high, size-xs

#10064 [Backport 3.6] Update the 3.0 migration guide
  docs/3.0-migration-guide.md
Labels: approved, priority-very-high

#10063 Update the 3.0 migration guide and fix broken README link
  README.md
  docs/3.0-migration-guide.md
Labels: approved, priority-very-high

#9976 Defragment ext test 3.6
  library/ssl_tls13_server.c
  tests/src/test_helpers/ssl_helpers.c
  tests/suites/test_suite_ssl.function
  tests/suites/test_suite_ssl.tls-defrag.data
Labels: approved, component-tls, size-s, priority-high

#10052 Defragment ext test dev
  library/ssl_tls13_server.c
  tests/src/test_helpers/ssl_helpers.c
  tests/suites/test_suite_ssl.function
  tests/suites/test_suite_ssl.tls-defrag.data
Labels: approved, component-tls, size-s, priority-high

#10065 [Backport 3.6] Extend ssl-opt testing for TLS HS defragmentation
  programs/ssl/ssl_client2.c
  tests/ssl-opt.sh
Labels: approved, size-s, priority-high

#10007 Extend ssl-opt testing for TLS HS defragmentation
  programs/ssl/ssl_client2.c
  tests/ssl-opt.sh
Labels: approved, needs-ci, size-s, priority-high

#10039 Remove RNG parameters from public SSL APIs
  include/mbedtls/ssl_cookie.h
  include/mbedtls/ssl_ticket.h
  library/ssl_cookie.c
  library/ssl_ticket.c
  programs/fuzz/fuzz_dtlsserver.c
  programs/fuzz/fuzz_server.c
  programs/ssl/dtls_server.c
  programs/ssl/ssl_server2.c
Labels: approved, api-break

#10092 [3.6] Add missing credit for `set_hostname` issue
  ChangeLog
Labels: approved, size-xs

#10093 The LTS branch 2.28 is now EOL
  .github/pull_request_template.md
  BRANCHES.md
Labels: approved

#10000 Delete some sample programs
  ChangeLog.d/9964.txt
  programs/.gitignore
  programs/CMakeLists.txt
  programs/Makefile
  programs/README.md
  programs/aes/CMakeLists.txt
  programs/aes/crypt_and_hash.c
  programs/cipher/CMakeLists.txt
  programs/cipher/cipher_aead_demo.c
  programs/hash/CMakeLists.txt
  programs/hash/generic_sum.c
  programs/hash/hello.c
  programs/hash/md_hmac_demo.c
  programs/pkey/CMakeLists.txt
  programs/pkey/dh_genprime.c
  programs/pkey/ecdh_curve25519.c
  programs/pkey/ecdsa.c
  programs/pkey/key_app.c
  programs/pkey/key_app_writer.c
  programs/pkey/mpi_demo.c
  programs/pkey/pk_decrypt.c
  programs/pkey/pk_encrypt.c
  programs/pkey/rsa_decrypt.c
  programs/pkey/rsa_encrypt.c
  programs/pkey/rsa_genkey.c
  programs/pkey/rsa_sign.c
  programs/pkey/rsa_verify.c
  programs/random/CMakeLists.txt
  programs/random/gen_entropy.c
  programs/random/gen_random_ctr_drbg.c
  programs/wince_main.c
Labels: approved

#10042 Remove mbedtls_ssl_conf_rng()
  include/mbedtls/ssl.h
  library/ssl_client.c
  library/ssl_misc.h
  library/ssl_msg.c
  library/ssl_tls.c
  library/ssl_tls12_server.c
  library/ssl_tls13_server.c
  programs/fuzz/fuzz_client.c
  programs/fuzz/fuzz_dtlsclient.c
  programs/fuzz/fuzz_dtlsserver.c
  programs/fuzz/fuzz_server.c
  programs/ssl/dtls_client.c
  programs/ssl/dtls_server.c
  programs/ssl/mini_client.c
  programs/ssl/ssl_client1.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_fork_server.c
  programs/ssl/ssl_mail_client.c
  programs/ssl/ssl_pthread_server.c
  programs/ssl/ssl_server.c
  programs/ssl/ssl_server2.c
  programs/x509/cert_app.c
  tests/src/test_helpers/ssl_helpers.c
  tests/suites/test_suite_debug.function
  tests/suites/test_suite_ssl.function
Labels: approved, api-break, priority-high

#10032 psasim: update README file
  tests/psa-client-server/psasim/README.md
Labels: approved, priority-high, size-xs

#10101 Remove all.sh wrapper
  tests/scripts/all.sh
  tests/scripts/mbedtls-all.sh
Labels: enhancement, approved, priority-high
