Repository Mbed-TLS/mbedtls, pull requests merged in 2025-04, with the labels that each got.

#10078 Pk rsa alt removal
  tests/suites/test_suite_x509write.function
Labels: approved

#10109 Merge from restricted
  ChangeLog.d/mbedtls_ssl_set_hostname.txt
  ChangeLog.d/tls12-check-finished-calc.txt
  include/mbedtls/ssl.h
  library/ssl_misc.h
  library/ssl_tls.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_test_common_source.c
  tests/src/test_helpers/ssl_helpers.c
  tests/ssl-opt.sh
Labels: approved, priority-high

#10118 Update bug report template for security issues
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved, size-xs

#10110 [Backport 3.6] Test coalesced or split handshake messages
  library/ssl_misc.h
  library/ssl_msg.c
  library/ssl_tls.c
  library/ssl_tls12_client.c
  library/ssl_tls12_server.c
  tests/include/test/ssl_helpers.h
  tests/suites/test_suite_ssl.function
  tests/suites/test_suite_ssl.records.data
Labels: needs-review, component-tls, priority-high

#10045 Test coalesced or split handshake messages
  library/ssl_misc.h
  library/ssl_msg.c
  library/ssl_tls.c
  library/ssl_tls12_client.c
  library/ssl_tls12_server.c
  tests/include/test/ssl_helpers.h
  tests/suites/test_suite_ssl.function
  tests/suites/test_suite_ssl.records.data
Labels: needs-review, needs-backports, component-tls, size-s, priority-high

#9421 Implement TLS-Exporter
  ChangeLog.d/add-tls-exporter.txt
  include/mbedtls/mbedtls_config.h
  include/mbedtls/ssl.h
  library/ssl_misc.h
  library/ssl_tls.c
  library/ssl_tls13_keys.c
  library/ssl_tls13_keys.h
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  tests/include/test/ssl_helpers.h
  tests/src/test_helpers/ssl_helpers.c
  tests/ssl-opt.sh
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
Labels: enhancement, approved, component-tls13, size-m, priority-medium

#10137 Backport 3.6: Fix uncaught failure conditions in test_suite_ssl
  tests/src/test_helpers/ssl_helpers.c
Labels: approved, priority-high, size-xs

#10120 Fix uncaught failure conditions in test_suite_ssl
  tests/src/test_helpers/ssl_helpers.c
Labels: approved, needs-backports, priority-high, size-xs

#10143 Removed use of mbedtls_cipher_info from ssl_context_info.c
  programs/ssl/ssl_context_info.c
Labels: approved, component-tls, size-s, priority-medium
